### ISSUE TITLE
[Android] Browser crash when rewards panel is opened on DDG

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10215]
## Description 
Browser crash when rewards panel is opened on DDG

## Steps to reproduce 

   1. Install nightly build
   2. Enable rewards (staging)
   3. Visit DDG and open rewards panel

## Actual result 
Browser crash

## Expected result
No crash

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.12.11

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by SergeyZhukovsky** [comment]
Attaching stack trace for the crash:
`2020-06-10 09:14:07.559 17648-17648/? W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference
2020-06-10 09:14:07.559 17648-17648/? W/System.err:     at org.chromium.chrome.browser.BraveRewardsPanelPopup.OnPublisherInfo(BraveRewardsPanelPopup.java:1256)
2020-06-10 09:14:07.559 17648-17648/? W/System.err:     at org.chromium.chrome.browser.BraveRewardsNativeWorker.OnPublisherInfo(BraveRewardsNativeWorker.java:514)
2020-06-10 09:14:07.559 17648-17648/? W/System.err:     at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
2020-06-10 09:14:07.559 17648-17648/? W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:336)
2020-06-10 09:14:07.559 17648-17648/? W/System.err:     at android.os.Looper.loop(Looper.java:197)
2020-06-10 09:14:07.559 17648-17648/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8016)
2020-06-10 09:14:07.559 17648-17648/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java)
2020-06-10 09:14:07.559 17648-17648/? W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2020-06-10 09:14:07.559 17648-17648/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
`

**Comment by btlechowski** [comment]
Verification passed on BraveModernarm v1.10.92 on Samsung Galaxy Tab S5e (Android 9.0)

Verified test plan from https://github.com/brave/brave-core/pull/5819
![Screenshot_20200617-045439_Brave](https://user-images.githubusercontent.com/34715963/84849992-d971a080-b056-11ea-96cc-7d6c3c6494ee.jpg)


-----
