### ISSUE TITLE
[Desktop] Issue loading BBCollaborate frame

### ISSUE THREAD

**Issue by cuppajoeman** [brave/brave-browser#11336]
## Description 
When I try to load a bbcollaborate window in brave it doesn't load: https://streamable.com/5ulnvn

## Steps to Reproduce

Open up a bbcollaborate link

## Version/Channel Information:
Version 1.12.107 Chromium: 84.0.4147.105 (Official Build) unknown (64-bit)

## Other Additional Information:
I installed it from the Arch user repository: https://aur.archlinux.org/packages/brave-bin/

## Miscellaneous Information:
In the video attached we can see it working in firefox

**Comment by rebron** [comment]
Hi @cuppajoeman Can you try turning shields down and letting us know if that workaround works. Also, can you paste what resource is being blocked.

**Comment by cuppajoeman** [comment]
Hi @rebron. Turning shields down fixes the issue. I'm not entirely sure what resource is being blocked (maybe you can elaborate on how I can show you this) but I will paste the error I was getting in the console:

```
Inst-FS ServiceWorker not necessary for this browser.
main.js:1 Blackboard Collaborate Scheduler UI - v21.2.9-localization.0.2 - Copyright (c) 2015-2020 Blackboard Inc, All rights reserved.
main.js:1 Starting scheduler app.
vendor.js:65 LaunchParams loaded parameters: {token: "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYkNvbGxhYkFwaSIsI…FhIn0.zkOVtB0wQecEN7HK1e3s6bBd4Jaevu6_hILkbOXq2bg"}
angular.js:46 Error: [angular-locker] The browser does not support the "local" driver
    at r (https://ca-lti.bbcollab.com/collab/js/angular/3a88f15f291d54cc7c58/angular.js:15:329)
    at u._removeItem (https://ca-lti.bbcollab.com/collab/js/angular/3a88f15f291d54cc7c58/angular.js:15:2538)
    at u.forget (https://ca-lti.bbcollab.com/collab/js/angular/3a88f15f291d54cc7c58/angular.js:15:3306)
    at e.logout (https://ca-lti.bbcollab.com/collab/ui/scheduler/21.2.9-localization.0/js/main/main.js:1:462708)
    at e.ltiAuthenticate (https://ca-lti.bbcollab.com/collab/ui/scheduler/21.2.9-localization.0/js/main/main.js:1:461957)
    at new e (https://ca-lti.bbcollab.com/collab/ui/scheduler/21.2.9-localization.0/js/main/main.js:1:616389)
    at Object.s [as instantiate] (https://ca-lti.bbcollab.com/collab/js/angular/3a88f15f291d54cc7c58/angular.js:46:18913)
    at https://ca-lti.bbcollab.com/collab/js/angular/3a88f15f291d54cc7c58/angular.js:46:45642
    at Object.<anonymous> (https://ca-lti.bbcollab.com/collab/js/angular/3a88f15f291d54cc7c58/angular.js:41:21847)
    at https://ca-lti.bbcollab.com/collab/js/angular/3a88f15f291d54cc7c58/angular.js:46:5636 <div ui-view="content" class="ng-scope">
(anonymous) @ angular.js:46
(anonymous) @ angular.js:46
we @ angular.js:46
h @ angular.js:46
a @ angular.js:46
(anonymous) @ angular.js:46
(anonymous) @ angular.js:46
l @ angular.js:41
(anonymous) @ angular.js:41
$broadcast @ angular.js:46
(anonymous) @ angular.js:41
s @ angular.js:46
(anonymous) @ angular.js:46
$eval @ angular.js:46
$digest @ angular.js:46
$apply @ angular.js:46
(anonymous) @ angular.js:46
a @ angular.js:46
o @ angular.js:46
ie @ angular.js:46
(anonymous) @ main.js:1
s @ main.js:1
(anonymous) @ main.js:1
a @ main.js:1
Promise.then (async)
l @ main.js:1
(anonymous) @ main.js:1
s @ main.js:1
(anonymous) @ main.js:1
u @ angular.js:69
fireWith @ angular.js:69
ready @ angular.js:69
l @ angular.js:59
angular.js:46 LocaleLoaderService checkLocale result:en
angular.js:46 LocaleLoaderService locale ready:  en
```

**Comment by rebron** [comment]
cc: @ryanbr

**Comment by ryanbr** [comment]
@cuppajoeman  rather than disable shields, lets try disabling sections of shields. (Disable uBO while doing this)

Does disabling trackers and ads in shields help? or `Allow all cookies` in shields?

**Comment by xavier2dc** [comment]
Having this issue as well, switching to `Allow all cookies` worked. Disabling trackers & ads doesn't help.

**Comment by antonok-edm** [comment]
@ryanbr is still relevant with ephemeral storage?

**Comment by ryanbr** [comment]
@xavier2dc   can you enable `ephemeral storage` via `brave://flags` and retest. Also screenshot the `padlock, cookies, blocked` (in the urlbar).

**Comment by ryanbr** [comment]
Safe to close @cuppajoeman ?     Just uploaded, and played fine. https://streamable.com/tszqjm
