### ISSUE TITLE
npm run sync error

### ISSUE THREAD

**Issue by bigfoxtail** [brave/brave-browser#11867]
```npm ERR! Maximum call stack size exceeded```

```
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2020-09-26T01_48_38_949Z-debug.log

Traceback (most recent call last):
  File "script/bootstrap.py", line 79, in <module>
    sys.exit(main())
  File "script/bootstrap.py", line 33, in main
    update_node_modules('.')
  File "script/bootstrap.py", line 69, in update_node_modules
    execute_stdout(args, env)
  File "G:\Other\brave\brave-browser_official\src\brave\script\lib\util.py", line 188, in execute_stdout
    execute(argv, env)
  File "G:\Other\brave\brave-browser_official\src\brave\script\lib\util.py", line 175, in execute
    raise e
subprocess.CalledProcessError: Command '['npm.cmd', 'install']' returned non-zero exit status 1
Error: Command 'vpython.bat script/bootstrap.py' returned non-zero exit status 1 in G:\Other\brave\brave-browser_official\src/brave
Hook 'vpython.bat script/bootstrap.py' took 37.07 secs
null
null
```

**Comment by bsclifton** [comment]
This issue hasn't had an update in a while - it's met the criteria for being stale. The issue is going to be closed for now. If this is still a problem, please leave a comment or re-open the issue. Thanks!
