### ISSUE TITLE
MediaTwitchTest.GetMediaIdFromParts crashes if ASAN is enabled

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#11893]
```
$ npm run test -- brave_unit_tests --filter=MediaTwitchTest.GetMediaIdFromParts
Using sharding settings from environment. This is shard 0/1
Using 4 parallel jobs.
[ RUN      ] MediaTwitchTest.GetMediaIdFromParts

=================================================================
==9740==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x00842c8fd2e7 at pc 0x7ffb1fa9375e bp 0x00842c8fc5d0 sp 0x00842c8fc618
READ of size 1 at 0x00842c8fd2e7 thread T0
==9740==*** WARNING: Failed to initialize DbgHelp!              ***
==9740==*** Most likely this means that the app is already      ***
==9740==*** using DbgHelp, possibly with incompatible flags.    ***
==9740==*** Due to technical reasons, symbolization might crash ***
==9740==*** or produce wrong results.                           ***
    #0 0x7ffb1fa9375d in std::__1::basic_string<char,std::__1::char_traits<char>,std::__1::allocator<char> >::size C:\bb\src\buildtools\third_party\libc++\trunk\include\string:947
    #1 0x7ff7b20ce73a in braveledger_media::Twitch::GetMediaIdFromParts C:\bb\src\brave\vendor\bat-native-ledger\src\bat\ledger\internal\legacy\media\twitch.cc:53
    #2 0x7ff7b42a5042 in braveledger_media::MediaTwitchTest_GetMediaIdFromParts_Test::TestBody C:\bb\src\brave\vendor\bat-native-ledger\src\bat\ledger\internal\legacy\media\twitch_unittest.cc:76
    #3 0x7ff7af69b275 in testing::Test::Run C:\bb\src\third_party\googletest\src\googletest\src\gtest.cc:2689
    #4 0x7ff7af69cb6b in testing::TestInfo::Run C:\bb\src\third_party\googletest\src\googletest\src\gtest.cc:2866
    #5 0x7ff7af69e423 in testing::TestSuite::Run C:\bb\src\third_party\googletest\src\googletest\src\gtest.cc:3020
    #6 0x7ff7af6b5f6c in testing::internal::UnitTestImpl::RunAllTests C:\bb\src\third_party\googletest\src\googletest\src\gtest.cc:5730
    #7 0x7ff7af6b544a in testing::UnitTest::Run C:\bb\src\third_party\googletest\src\googletest\src\gtest.cc:5313
    #8 0x7ff7b4438505 in base::TestSuite::Run C:\bb\src\base\test\test_suite.cc:480
    #9 0x7ff7baad6aa9 in content::UnitTestTestSuite::Run C:\bb\src\content\public\test\unittest_test_suite.cc:122
    #10 0x7ff7b08b13ea in base::OnceCallback<int ()>::Run C:\bb\src\base\callback.h:99
    #11 0x7ff7b4445ec7 in base::`anonymous namespace'::LaunchUnitTestsInternal C:\bb\src\base\test\launcher\unit_test_launcher.cc:165
    #12 0x7ff7b4445b1d in base::LaunchUnitTests C:\bb\src\base\test\launcher\unit_test_launcher.cc:235
    #13 0x7ff7baad5ef0 in main C:\bb\src\brave\test\base\run_all_unittests.cc:31
    #14 0x7ff7baadd8e3 in __scrt_common_main_seh d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #15 0x7ffb72e27973 in BaseThreadInitThunk+0x13 (C:\Windows\System32\KERNEL32.DLL+0x180017973)
    #16 0x7ffb730ca270 in RtlUserThreadStart+0x20 (C:\Windows\SYSTEM32\ntdll.dll+0x18006a270)

Address 0x00842c8fd2e7 is located in stack of thread T0 at offset 2023 in frame
    #0 0x7ff7b42a31b3 in braveledger_media::MediaTwitchTest_GetMediaIdFromParts_Test::TestBody C:\bb\src\brave\vendor\bat-native-ledger\src\bat\ledger\internal\legacy\media\twitch_unittest.cc:45

  This frame has 106 object(s):
    [32, 56) 'media_id' (line 46)
    [96, 120) 'user_id' (line 47)
    [160, 208) 'result' (line 49)
    [240, 264) 'ref.tmp' (line 50)
    [304, 320) 'gtest_ar_' (line 53)
    [336, 344) 'ref.tmp10' (line 53)
    [368, 376) 'ref.tmp12' (line 53)
    [400, 424) 'ref.tmp13' (line 53)
    [464, 480) 'gtest_ar_16' (line 54)
    [496, 504) 'ref.tmp24' (line 54)
    [528, 536) 'ref.tmp26' (line 54)
    [560, 584) 'ref.tmp27' (line 54)
    [624, 672) 'ref.tmp32' (line 57)
    [704, 728) 'ref.tmp33' (line 57)
    [768, 784) 'agg.tmp'
    [800, 896) 'ref.tmp34' (line 57)
    [928, 929) 'ref.tmp37' (line 57)
    [944, 960) 'gtest_ar_45' (line 63)
    [976, 984) 'ref.tmp53' (line 63)
    [1008, 1016) 'ref.tmp55' (line 63)
    [1040, 1064) 'ref.tmp56' (line 63)
    [1104, 1120) 'gtest_ar_60' (line 64)
    [1136, 1144) 'ref.tmp68' (line 64)
    [1168, 1176) 'ref.tmp70' (line 64)
    [1200, 1224) 'ref.tmp71' (line 64)
    [1264, 1312) 'ref.tmp79' (line 67)
    [1344, 1368) 'ref.tmp80' (line 67)
    [1408, 1424) 'agg.tmp81'
    [1440, 1488) 'ref.tmp82' (line 67)
    [1520, 1521) 'ref.tmp88' (line 67)
    [1536, 1552) 'gtest_ar_101' (line 72)
    [1568, 1576) 'ref.tmp109' (line 72)
    [1600, 1608) 'ref.tmp111' (line 72)
    [1632, 1656) 'ref.tmp112' (line 72)
    [1696, 1712) 'gtest_ar_116' (line 73)
    [1728, 1736) 'ref.tmp124' (line 73)
    [1760, 1768) 'ref.tmp126' (line 73)
    [1792, 1816) 'ref.tmp127' (line 73)
    [1856, 1904) 'ref.tmp135' (line 76)
    [1936, 1960) 'ref.tmp136' (line 76)
    [2000, 2016) 'agg.tmp137' <== Memory access at offset 2023 overflows this variable
    [2032, 2128) 'ref.tmp138' (line 76)
    [2160, 2161) 'ref.tmp146' (line 76)
    [2176, 2192) 'gtest_ar_159' (line 82)
    [2208, 2216) 'ref.tmp167' (line 82)
    [2240, 2248) 'ref.tmp169' (line 82)
    [2272, 2296) 'ref.tmp170' (line 82)
    [2336, 2352) 'gtest_ar_174' (line 83)
    [2368, 2376) 'ref.tmp182' (line 83)
    [2400, 2408) 'ref.tmp184' (line 83)
    [2432, 2456) 'ref.tmp185' (line 83)
    [2496, 2544) 'ref.tmp193' (line 86)
    [2576, 2600) 'ref.tmp194' (line 86)
    [2640, 2656) 'agg.tmp195'
    [2672, 2816) 'ref.tmp196' (line 86)
    [2880, 2881) 'ref.tmp206' (line 86)
    [2896, 2912) 'gtest_ar' (line 93)
    [2928, 2936) 'ref.tmp222' (line 93)
    [2960, 2968) 'ref.tmp224' (line 93)
    [2992, 3008) 'gtest_ar228' (line 94)
    [3024, 3032) 'ref.tmp232' (line 94)
    [3056, 3064) 'ref.tmp234' (line 94)
    [3088, 3136) 'ref.tmp242' (line 97)
    [3168, 3192) 'ref.tmp243' (line 97)
    [3232, 3248) 'agg.tmp244'
    [3264, 3456) 'ref.tmp245' (line 97)
    [3520, 3521) 'ref.tmp257' (line 97)
    [3536, 3552) 'gtest_ar270' (line 105)
    [3568, 3576) 'ref.tmp274' (line 105)
    [3600, 3608) 'ref.tmp276' (line 105)
    [3632, 3648) 'gtest_ar280' (line 106)
    [3664, 3672) 'ref.tmp284' (line 106)
    [3696, 3704) 'ref.tmp286' (line 106)
    [3728, 3776) 'ref.tmp294' (line 109)
    [3808, 3832) 'ref.tmp295' (line 109)
    [3872, 3888) 'agg.tmp296'
    [3904, 4096) 'ref.tmp297' (line 109)
    [4160, 4161) 'ref.tmp309' (line 109)
    [4176, 4192) 'gtest_ar322' (line 117)
    [4208, 4216) 'ref.tmp326' (line 117)
    [4240, 4248) 'ref.tmp328' (line 117)
    [4272, 4288) 'gtest_ar332' (line 118)
    [4304, 4312) 'ref.tmp336' (line 118)
    [4336, 4344) 'ref.tmp338' (line 118)
    [4368, 4416) 'ref.tmp346' (line 121)
    [4448, 4472) 'ref.tmp347' (line 121)
    [4512, 4528) 'agg.tmp348'
    [4544, 4688) 'ref.tmp349' (line 121)
    [4752, 4753) 'ref.tmp359' (line 121)
    [4768, 4784) 'gtest_ar372' (line 128)
    [4800, 4808) 'ref.tmp376' (line 128)
    [4832, 4840) 'ref.tmp378' (line 128)
    [4864, 4880) 'gtest_ar382' (line 129)
    [4896, 4904) 'ref.tmp386' (line 129)
    [4928, 4936) 'ref.tmp388' (line 129)
    [4960, 5008) 'ref.tmp396' (line 132)
    [5040, 5064) 'ref.tmp397' (line 132)
    [5104, 5120) 'agg.tmp398'
    [5136, 5328) 'ref.tmp399' (line 132)
    [5392, 5393) 'ref.tmp411' (line 132)
    [5408, 5424) 'gtest_ar424' (line 140)
    [5440, 5448) 'ref.tmp428' (line 140)
    [5472, 5480) 'ref.tmp430' (line 140)
    [5504, 5520) 'gtest_ar434' (line 141)
    [5536, 5544) 'ref.tmp438' (line 141)
    [5568, 5576) 'ref.tmp440' (line 141)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp, SEH and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow C:\bb\src\buildtools\third_party\libc++\trunk\include\string:947 in std::__1::basic_string<char,std::__1::char_traits<char>,std::__1::allocator<char> >::size
Shadow bytes around the buggy address:
  0x01f49f39fa00: f8 f8 f8 f8 f2 f2 f2 f2 f8 f8 f8 f2 f2 f2 f2 f2
  0x01f49f39fa10: 00 00 f2 f2 f8 f8 f8 f8 f8 f8 f2 f2 f2 f2 f8 f2
  0x01f49f39fa20: f8 f8 f2 f2 f8 f2 f2 f2 f8 f2 f2 f2 f8 f8 f8 f2
  0x01f49f39fa30: f2 f2 f2 f2 f8 f8 f2 f2 f8 f2 f2 f2 f8 f2 f2 f2
  0x01f49f39fa40: f8 f8 f8 f2 f2 f2 f2 f2 00 00 00 00 00 00 f2 f2
=>0x01f49f39fa50: f2 f2 00 00 00 f2 f2 f2 f2 f2 00 00[f2]f2 00 00
  0x01f49f39fa60: 00 00 00 00 00 00 00 00 00 00 f2 f2 f2 f2 01 f2
  0x01f49f39fa70: f8 f8 f2 f2 f8 f2 f2 f2 f8 f2 f2 f2 f8 f8 f8 f2
  0x01f49f39fa80: f2 f2 f2 f2 f8 f8 f2 f2 f8 f2 f2 f2 f8 f2 f2 f2
  0x01f49f39fa90: f8 f8 f8 f2 f2 f2 f2 f2 f8 f8 f8 f8 f8 f8 f2 f2
  0x01f49f39faa0: f2 f2 f8 f8 f8 f2 f2 f2 f2 f2 00 00 f2 f2 f8 f8
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==9740==ABORTING
[1/1] MediaTwitchTest.GetMediaIdFromParts (CRASHED)
1 test crashed:
    MediaTwitchTest.GetMediaIdFromParts (../../brave/vendor/bat-native-ledger/src/bat/ledger/internal/legacy/media/twitch_unittest.cc:45)
Tests took 1 seconds.
null
```

**Comment by iefremov** [comment]
Need to enable the whole test suite in corresponding BUILD.gn when fixed
