### ISSUE TITLE
GeminiAPIBrowserTest.GetOAuthClientURL crashes when ASAN is enabled

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#11898]
```
$ npm run build -- --is_asan
$ npm run test -- brave_browser_tests --filter=GeminiAPIBrowserTest.GetOAuthClientURL
=================================================================
==5464==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x0055547488a0 at pc 0x7ffb1fdf7e27 bp 0x005554747fa0 sp 0x005554747fe8
READ of size 37 at 0x0055547488a0 thread T0
==5464==*** WARNING: Failed to initialize DbgHelp!              ***
==5464==*** Most likely this means that the app is already      ***
==5464==*** using DbgHelp, possibly with incompatible flags.    ***
==5464==*** Due to technical reasons, symbolization might crash ***
==5464==*** or produce wrong results.                           ***
    #0 0x7ffb1fdf7e4f in _asan_wrap_strlen+0x1af (C:\bb\src\out\Component\clang_rt.asan_dynamic-x86_64.dll+0x180027e4f)
    #1 0x7ff695936d27 in ntp_widget_utils::GetCryptoRandomString C:\bb\src\brave\components\ntp_widget_utils\browser\ntp_widget_utils_oauth.cc:25
    #2 0x7ff695949090 in GeminiService::GetOAuthClientUrl C:\bb\src\brave\components\gemini\browser\gemini_service.cc:152
    #3 0x7ff69275db21 in GeminiAPIBrowserTest_GetOAuthClientURL_Test::RunTestOnMainThread C:\bb\src\brave\components\gemini\browser\gemini_service_browsertest.cc:325
    #4 0x7ff6976f4b6f in content::BrowserTestBase::ProxyRunTestOnMainThreadLoop C:\bb\src\content\public\test\browser_test_base.cc:707
    #5 0x7ff692914928 in base::OnceCallback<void ()>::Run C:\bb\src\base\callback.h:99
    #6 0x7ff69781bdf5 in ChromeBrowserMainParts::PreMainMessageLoopRunImpl C:\bb\src\chrome\browser\chrome_browser_main.cc:1657
    #7 0x7ff6978194bb in ChromeBrowserMainParts::PreMainMessageLoopRun C:\bb\src\chrome\browser\chrome_browser_main.cc:1032
    #8 0x7ffb2d3dd2b0 in content::BrowserMainLoop::PreMainMessageLoopRun C:\bb\src\content\browser\browser_main_loop.cc:985
    #9 0x7ffb2e69850c in base::OnceCallback<int ()>::Run C:\bb\src\base\callback.h:99
    #10 0x7ffb2e69835d in content::StartupTaskRunner::RunAllTasksNow C:\bb\src\content\browser\startup_task_runner.cc:41
    #11 0x7ffb2d3da32f in content::BrowserMainLoop::CreateStartupTasks C:\bb\src\content\browser\browser_main_loop.cc:895
    #12 0x7ffb2d3e3d98 in content::BrowserMainRunnerImpl::Initialize C:\bb\src\content\browser\browser_main_runner_impl.cc:130
    #13 0x7ffb2d3d5207 in content::BrowserMain C:\bb\src\content\browser\browser_main.cc:43
    #14 0x7ffb2f7c2528 in content::RunBrowserProcessMain C:\bb\src\content\app\content_main_runner_impl.cc:525
    #15 0x7ffb2f7c4eb6 in content::ContentMainRunnerImpl::RunServiceManager C:\bb\src\content\app\content_main_runner_impl.cc:997
    #16 0x7ffb2f7c3fa9 in content::ContentMainRunnerImpl::Run C:\bb\src\content\app\content_main_runner_impl.cc:881
    #17 0x7ffaf001261a in service_manager::Main C:\bb\src\services\service_manager\embedder\main.cc:453
    #18 0x7ffb2f7c227e in content::ContentMain C:\bb\src\content\app\content_main.cc:19
    #19 0x7ff6976f39fd in content::BrowserTestBase::SetUp C:\bb\src\content\public\test\browser_test_base.cc:544
    #20 0x7ff6976e1520 in InProcessBrowserTest::SetUp C:\bb\src\chrome\test\base\in_process_browser_test.cc:331
    #21 0x7ff6928de021 in testing::Test::Run C:\bb\src\third_party\googletest\src\googletest\src\gtest.cc:2684
    #22 0x7ff6928df9df in testing::TestInfo::Run C:\bb\src\third_party\googletest\src\googletest\src\gtest.cc:2866
    #23 0x7ff6928e1297 in testing::TestSuite::Run C:\bb\src\third_party\googletest\src\googletest\src\gtest.cc:3020
    #24 0x7ff6928f8de0 in testing::internal::UnitTestImpl::RunAllTests C:\bb\src\third_party\googletest\src\googletest\src\gtest.cc:5730
    #25 0x7ff6928f82be in testing::UnitTest::Run C:\bb\src\third_party\googletest\src\googletest\src\gtest.cc:5313
    #26 0x7ff6977a9c25 in base::TestSuite::Run C:\bb\src\base\test\test_suite.cc:480
    #27 0x7ff69d86ff0c in ChromeTestSuiteRunner::RunTestSuite C:\bb\src\chrome\test\base\chrome_test_launcher.cc:86
    #28 0x7ff699038f6b in content::LaunchTests C:\bb\src\content\public\test\test_launcher.cc:372
    #29 0x7ff69d870a6f in LaunchChromeTests C:\bb\src\chrome\test\base\chrome_test_launcher.cc:245
    #30 0x7ff69d86fcfd in main C:\bb\src\brave\test\base\browser_tests_main.cc:36
    #31 0x7ff69dbc43f3 in __scrt_common_main_seh d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #32 0x7ffb72e27973 in BaseThreadInitThunk+0x13 (C:\Windows\System32\KERNEL32.DLL+0x180017973)
    #33 0x7ffb730ca270 in RtlUserThreadStart+0x20 (C:\Windows\SYSTEM32\ntdll.dll+0x18006a270)

Address 0x0055547488a0 is located in stack of thread T0 at offset 64 in frame
    #0 0x7ff695936bf3 in ntp_widget_utils::GetCryptoRandomString C:\bb\src\brave\components\ntp_widget_utils\browser\ntp_widget_utils_oauth.cc:17

  This frame has 2 object(s):
    [32, 64) 'random_seed_bytes' (line 19)
    [96, 112) 'ref.tmp' (line 24) <== Memory access at offset 64 partially underflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp, SEH and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow (C:\bb\src\out\Component\clang_rt.asan_dynamic-x86_64.dll+0x180027e4f) in _asan_wrap_strlen+0x1af
Shadow bytes around the buggy address:
  0x0181e26690c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0181e26690d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0181e26690e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0181e26690f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0181e2669100: 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1
=>0x0181e2669110: 00 00 00 00[f2]f2 f2 f2 00 00 f3 f3 00 00 00 00
  0x0181e2669120: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0181e2669130: f1 f1 f1 f1 00 00 00 00 00 00 00 00 00 00 00 00
  0x0181e2669140: 00 00 00 f2 f2 f2 f2 f2 00 00 f2 f2 00 00 00 f2
  0x0181e2669150: f2 f2 f2 f2 f8 f8 f8 f2 f2 f2 f2 f2 f8 f8 f8 f8
  0x0181e2669160: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f2 f2 f2 f2 f2
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==5464==ABORTING
[1/1] GeminiAPIBrowserTest.GetOAuthClientURL (CRASHED)
1 test crashed:
    GeminiAPIBrowserTest.GetOAuthClientURL (../../brave/components/gemini/browser/gemini_service_browsertest.cc:320)
null
```

**Comment by jumde** [comment]
Likely dupe of https://github.com/brave/brave-browser/issues/11895
