### ISSUE TITLE
AddressSanitizer: use-after-poison blink::Bluetooth::~Bluetooth()+0x216

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#12964]
```
==69944==ERROR: AddressSanitizer: use-after-poison on address 0x7e97f4a511e0 at pc 0x0001693a4627 bp 0x7ffee5af2e30 sp 0x7ffee5af2e28
READ of size 8 at 0x7e97f4a511e0 thread T0
==69944==WARNING: failed to spawn external symbolizer (errno: 9)
==69944==WARNING: failed to spawn external symbolizer (errno: 9)
==69944==WARNING: failed to spawn external symbolizer (errno: 9)
==69944==WARNING: failed to spawn external symbolizer (errno: 9)
==69944==WARNING: failed to spawn external symbolizer (errno: 9)
==69944==WARNING: Failed to use and restart external symbolizer!
    #0 0x1693a4626 in blink::Bluetooth::~Bluetooth()+0x216 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libblink_modules.dylib:x86_64+0xc10626)
    #1 0x163f53ffc in blink::HeapObjectHeader::Finalize(unsigned char*, unsigned long)+0x16c (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libblink_platform.dylib:x86_64+0xb06ffc)
    #2 0x163f68437 in blink::NormalPage::FinalizeSweep(blink::SweepResult)+0x177 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libblink_platform.dylib:x86_64+0xb1b437)
    #3 0x163f642e2 in blink::NormalPageArena::LazySweepPages(unsigned long, unsigned long)+0x192 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libblink_platform.dylib:x86_64+0xb172e2)
    #4 0x163f58c79 in blink::BaseArena::LazySweep(unsigned long, unsigned long)+0x3d9 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libblink_platform.dylib:x86_64+0xb0bc79)
    #5 0x163f6499d in blink::NormalPageArena::OutOfLineAllocateImpl(unsigned long, unsigned long)+0x44d (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libblink_platform.dylib:x86_64+0xb1799d)
    #6 0x163f644db in blink::NormalPageArena::OutOfLineAllocate(unsigned long, unsigned long)+0x1b (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libblink_platform.dylib:x86_64+0xb174db)
    #7 0x15ae88f6a in blink::NormalPageArena::AllocateObject(unsigned long, unsigned long)+0x56a (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libblink_core.dylib:x86_64+0x15f6a)
    #8 0x15ae88185 in blink::ThreadHeap::AllocateOnArenaIndex(blink::ThreadState*, unsigned long, int, unsigned int, char const*)+0x355 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libblink_core.dylib:x86_64+0x15185)
    #9 0x15c19dbe2 in blink::SelectorQueryCache::Add(WTF::AtomicString const&, blink::Document const&, blink::ExceptionState&)+0x402 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libblink_core.dylib:x86_64+0x132abe2)
    #10 0x15c2d7f6c in blink::ContainerNode::QuerySelectorAll(WTF::AtomicString const&, blink::ExceptionState&)+0x3c (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libblink_core.dylib:x86_64+0x1464f6c)
    #11 0x168974a64 in blink::(anonymous namespace)::QuerySelectorAllOperationCallback(v8::FunctionCallbackInfo<v8::Value> const&)+0x394 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libblink_modules.dylib:x86_64+0x1e0a64)
    #12 0x12326c9de in v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo)+0x6ae (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libv8.dylib:x86_64+0xa4e9de)
    #13 0x12326827e in v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments)+0x94e (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libv8.dylib:x86_64+0xa4a27e)
    #14 0x1232646f1 in v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*)+0x4d1 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libv8.dylib:x86_64+0xa466f1)
    #15 0x123263972 in v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*)+0x1a2 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libv8.dylib:x86_64+0xa45972)
    #16 0x122ad9ede in Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit+0x3e (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libv8.dylib:x86_64+0x2bbede)
    #17 0x122842f77 in Builtins_InterpreterEntryTrampoline+0xd7 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libv8.dylib:x86_64+0x24f77)
    #18 0x122842f77 in Builtins_InterpreterEntryTrampoline+0xd7 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libv8.dylib:x86_64+0x24f77)
    #19 0x12281fe57 in Builtins_ArgumentsAdaptorTrampoline+0xb7 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libv8.dylib:x86_64+0x1e57)
    #20 0x122838dfa in Builtins_JSEntryTrampoline+0x5a (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libv8.dylib:x86_64+0x1adfa)
    #21 0x122838bd7 in Builtins_JSEntry+0x77 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libv8.dylib:x86_64+0x1abd7)
    #22 0x12366f4e8 in v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&)+0x2528 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libv8.dylib:x86_64+0xe514e8)
    #23 0x12366ceac in v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*)+0x23c (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libv8.dylib:x86_64+0xe4eeac)
    #24 0x123027c21 in v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*)+0x401 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libv8.dylib:x86_64+0x809c21)
    #25 0x15b01f428 in blink::V8ScriptRunner::CallFunction(v8::Local<v8::Function>, blink::ExecutionContext*, v8::Local<v8::Value>, int, v8::Local<v8::Value>*, v8::Isolate*)+0x698 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libblink_core.dylib:x86_64+0x1ac428)
    #26 0x16019b3fe in blink::V8IdleRequestCallback::Invoke(blink::bindings::V8ValueOrScriptWrappableAdapter, blink::IdleDeadline*)+0x72e (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libblink_core.dylib:x86_64+0x53283fe)
    #27 0x16019b84a in blink::V8IdleRequestCallback::InvokeAndReportException(blink::bindings::V8ValueOrScriptWrappableAdapter, blink::IdleDeadline*)+0x11a (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libblink_core.dylib:x86_64+0x532884a)
    #28 0x15c64f669 in blink::ScriptedIdleTaskController::RunCallback(int, base::TimeTicks, blink::IdleDeadline::CallbackType)+0x569 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libblink_core.dylib:x86_64+0x17dc669)
    #29 0x15c64de55 in blink::internal::IdleRequestCallbackWrapper::IdleTaskFired(scoped_refptr<blink::internal::IdleRequestCallbackWrapper>, base::TimeTicks)+0x455 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libblink_core.dylib:x86_64+0x17dae55)
    #30 0x15c6576cb in base::internal::Invoker<base::internal::BindState<void (*)(scoped_refptr<blink::internal::IdleRequestCallbackWrapper>, base::TimeTicks), scoped_refptr<blink::internal::IdleRequestCallbackWrapper> >, void (base::TimeTicks)>::RunOnce(base::internal::BindStateBase*, base::TimeTicks&&)+0x12b (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libblink_core.dylib:x86_64+0x17e46cb)
    #31 0x15b0107d1 in WTF::ThreadCheckingCallbackWrapper<base::OnceCallback<void (base::TimeTicks)>, void (base::TimeTicks)>::Run(base::TimeTicks)+0x1f1 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libblink_core.dylib:x86_64+0x19d7d1)
    #32 0x164296fa8 in blink::scheduler::MainThreadSchedulerImpl::RunIdleTask(base::OnceCallback<void (base::TimeTicks)>, base::TimeTicks)+0x188 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libblink_platform.dylib:x86_64+0xe49fa8)
    #33 0x1642ab823 in base::internal::Invoker<base::internal::BindState<void (*)(base::OnceCallback<void (base::TimeTicks)>, base::TimeTicks), base::OnceCallback<void (base::TimeTicks)> >, void (base::TimeTicks)>::RunOnce(base::internal::BindStateBase*, base::TimeTicks&&)+0x123 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libblink_platform.dylib:x86_64+0xe5e823)
    #34 0x1641f5153 in blink::scheduler::SingleThreadIdleTaskRunner::RunTask(base::OnceCallback<void (base::TimeTicks)>)+0x293 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libblink_platform.dylib:x86_64+0xda8153)
    #35 0x1641f6743 in void base::internal::Invoker<base::internal::BindState<void (blink::scheduler::SingleThreadIdleTaskRunner::*)(base::OnceCallback<void (base::TimeTicks)>), base::WeakPtr<blink::scheduler::SingleThreadIdleTaskRunner>, base::OnceCallback<void (base::TimeTicks)> >, void ()>::RunImpl<void (blink::scheduler::SingleThreadIdleTaskRunner::*)(base::OnceCallback<void (base::TimeTicks)>), std::__Cr::tuple<base::WeakPtr<blink::scheduler::SingleThreadIdleTaskRunner>, base::OnceCallback<void (base::TimeTicks)> >, 0ul, 1ul>(void (blink::scheduler::SingleThreadIdleTaskRunner::*&&)(base::OnceCallback<void (base::TimeTicks)>), std::__Cr::tuple<base::WeakPtr<blink::scheduler::SingleThreadIdleTaskRunner>, base::OnceCallback<void (base::TimeTicks)> >&&, std::__Cr::integer_sequence<unsigned long, 0ul, 1ul>)+0x223 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libblink_platform.dylib:x86_64+0xda9743)
    #36 0x127f14b57 in base::TaskAnnotator::RunTask(char const*, base::PendingTask*)+0x437 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libbase.dylib:x86_64+0x260b57)
    #37 0x127f73ad3 in base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::sequence_manager::LazyNow*)+0x4f3 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libbase.dylib:x86_64+0x2bfad3)
    #38 0x127f73217 in base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()+0x1d7 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libbase.dylib:x86_64+0x2bf217)
    #39 0x1280efdaa in base::MessagePumpCFRunLoopBase::RunWork()+0x18a (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libbase.dylib:x86_64+0x43bdaa)
    #40 0x1280c6fe9 in base::mac::CallWithEHFrame(void () block_pointer)+0x9 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libbase.dylib:x86_64+0x412fe9)
    #41 0x1280ee5a5 in base::MessagePumpCFRunLoopBase::RunWorkSource(void*)+0x175 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libbase.dylib:x86_64+0x43a5a5)
    #42 0x7fff370ddde1 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__+0x10 (/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation:x86_64h+0x83de1)
    #43 0x7fff370ddd80 in __CFRunLoopDoSource0+0x66 (/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation:x86_64h+0x83d80)
    #44 0x7fff370ddb9a in __CFRunLoopDoSources0+0xd0 (/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation:x86_64h+0x83b9a)
    #45 0x7fff370dc8c9 in __CFRunLoopRun+0x39e (/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation:x86_64h+0x828c9)
    #46 0x7fff370dbecd in CFRunLoopRunSpecific+0x1cd (/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation:x86_64h+0x81ecd)
    #47 0x7fff397741c7 in -[NSRunLoop(NSRunLoop) runMode:beforeDate:]+0xd3 (/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation:x86_64+0x601c7)
    #48 0x1280f1b10 in base::MessagePumpNSRunLoop::DoRun(base::MessagePump::Delegate*)+0xf0 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libbase.dylib:x86_64+0x43db10)
    #49 0x1280ed2ca in base::MessagePumpCFRunLoopBase::Run(base::MessagePump::Delegate*)+0x1ea (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libbase.dylib:x86_64+0x4392ca)
    #50 0x127f75258 in base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta)+0x368 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libbase.dylib:x86_64+0x2c1258)
    #51 0x127e89220 in base::RunLoop::Run()+0x890 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libbase.dylib:x86_64+0x1d5220)
    #52 0x1317e90c4 in content::RendererMain(content::MainFunctionParams const&)+0xaf4 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libcontent.dylib:x86_64+0x45450c4)
    #53 0x131c4f9f0 in content::ContentMainRunnerImpl::Run(bool)+0x4b0 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libcontent.dylib:x86_64+0x49ab9f0)
    #54 0x131c4b823 in content::RunContentProcess(content::ContentMainParams const&, content::ContentMainRunner*)+0x1473 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libcontent.dylib:x86_64+0x49a7823)
    #55 0x131c4bf17 in content::ContentMain(content::ContentMainParams const&)+0xd7 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libcontent.dylib:x86_64+0x49a7f17)
    #56 0x10e3da8dd in ChromeMain+0x1cd (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libchrome_dll.dylib:x86_64+0x88dd)
    #57 0x10a101509 in main+0x2e9 (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/Brave Browser Development.app/Contents/Frameworks/Brave Browser Development Framework.framework/Versions/87.1.19.41/Helpers/Brave Browser Development Helper (Renderer).app/Contents/MacOS/Brave Browser Development Helper (Renderer):x86_64+0x100001509)
    #58 0x7fff710d8cc8 in start+0x0 (/usr/lib/system/libdyld.dylib:x86_64+0x1acc8)

Address 0x7e97f4a511e0 is a wild pointer.
SUMMARY: AddressSanitizer: use-after-poison (/Users/terrym/Projects/Brave/brave-browser/src/out/Component/libblink_modules.dylib:x86_64+0xc10626) in blink::Bluetooth::~Bluetooth()+0x216
Shadow bytes around the buggy address:
  0x1fd2fe94a1e0: f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7
  0x1fd2fe94a1f0: f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7
  0x1fd2fe94a200: f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7
  0x1fd2fe94a210: f7 f7 f7 f7 f7 f7 f7 00 00 00 00 00 00 00 00 00
  0x1fd2fe94a220: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x1fd2fe94a230: f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7[f7]f7 f7 f7
  0x1fd2fe94a240: f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7
  0x1fd2fe94a250: f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7
  0x1fd2fe94a260: f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7
  0x1fd2fe94a270: f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7
  0x1fd2fe94a280: f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==69944==ABORTING
Received signal 6
0   libbase.dylib                       0x0000000128082b79 base::debug::CollectStackTrace(void**, unsigned long) + 9
1   libbase.dylib                       0x0000000127d11283 base::debug::StackTrace::StackTrace() + 19
2   libbase.dylib                       0x00000001280825c7 base::debug::(anonymous namespace)::StackDumpSignalHandler(int, __siginfo*, void*) + 4295
3   libsystem_platform.dylib            0x00007fff712d15fd _sigtramp + 29
4   ???                                 0x0000000000000000 0x0 + 0
5   libsystem_c.dylib                   0x00007fff711a7808 abort + 120
6   libclang_rt.asan_osx_dynamic.dylib  0x000000010a59c526 __sanitizer_sandbox_on_notify + 1030
7   libclang_rt.asan_osx_dynamic.dylib  0x000000010a59bc54 __sanitizer_on_print + 14580
8   libclang_rt.asan_osx_dynamic.dylib  0x000000010a583854 __asan_on_error + 788
9   libclang_rt.asan_osx_dynamic.dylib  0x000000010a58310e __asan_unpoison_intra_object_redzone + 9438
10  libclang_rt.asan_osx_dynamic.dylib  0x000000010a583d28 __asan_report_load8 + 40
11  libblink_modules.dylib              0x00000001693a4627 blink::Bluetooth::~Bluetooth() + 535
12  libblink_platform.dylib             0x0000000163f53ffd blink::HeapObjectHeader::Finalize(unsigned char*, unsigned long) + 365
13  libblink_platform.dylib             0x0000000163f68438 blink::NormalPage::FinalizeSweep(blink::SweepResult) + 376
14  libblink_platform.dylib             0x0000000163f642e3 blink::NormalPageArena::LazySweepPages(unsigned long, unsigned long) + 403
15  libblink_platform.dylib             0x0000000163f58c7a blink::BaseArena::LazySweep(unsigned long, unsigned long) + 986
16  libblink_platform.dylib             0x0000000163f6499e blink::NormalPageArena::OutOfLineAllocateImpl(unsigned long, unsigned long) + 1102
17  libblink_platform.dylib             0x0000000163f644dc blink::NormalPageArena::OutOfLineAllocate(unsigned long, unsigned long) + 28
18  libblink_core.dylib                 0x000000015ae88f6b blink::NormalPageArena::AllocateObject(unsigned long, unsigned long) + 1387
19  libblink_core.dylib                 0x000000015ae88186 blink::ThreadHeap::AllocateOnArenaIndex(blink::ThreadState*, unsigned long, int, unsigned int, char const*) + 854
20  libblink_core.dylib                 0x000000015c19dbe3 blink::SelectorQueryCache::Add(WTF::AtomicString const&, blink::Document const&, blink::ExceptionState&) + 1027
21  libblink_core.dylib                 0x000000015c2d7f6d blink::ContainerNode::QuerySelectorAll(WTF::AtomicString const&, blink::ExceptionState&) + 61
22  libblink_modules.dylib              0x0000000168974a65 blink::(anonymous namespace)::QuerySelectorAllOperationCallback(v8::FunctionCallbackInfo<v8::Value> const&) + 917
23  libv8.dylib                         0x000000012326c9df v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) + 1711
24  libv8.dylib                         0x000000012326827f v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) + 2383
25  libv8.dylib                         0x00000001232646f2 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) + 1234
26  libv8.dylib                         0x0000000123263973 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) + 419
27  libv8.dylib                         0x0000000122ad9edf Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit + 63
28  libv8.dylib                         0x0000000122842f78 Builtins_InterpreterEntryTrampoline + 216
```

**Comment by iefremov** [comment]
Most probably we will never be able to repro and fix after 1.5 years passed, so closing
