### ISSUE TITLE
iOS is intermittently failing to build in CI (jinja2.exceptions.TemplateNotFound: module.h.tmpl)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#13211]
## Description 
Latest master is failing CI for iOS
https://ci.brave.com/job/pr-brave-browser-bsc-show-qr-code-ios/3/execution/node/164/log/

```
15:56:51  FAILED: gen/brave/vendor/brave-ios/ads.mojom.objc.h gen/brave/vendor/brave-ios/ads.mojom.objc+private.h gen/brave/vendor/brave-ios/ads.mojom.objc.mm gen/brave/vendor/brave-ios/objc_templates_bytecode/ads_objc_templates.zip 
15:56:51  python ../../brave/vendor/brave-ios/scripts/mojo/gen_model_wrappers.py --mojom-module=/Users/jenkins/jenkins/workspace/pr-brave-browser-bsc-revert-kVideoPlaybackQuality-ios/src/out/ios_Release_arm64/gen/brave/vendor/bat-native-ads/include/bat/ads/public/interfaces/ads.mojom-module --module-include-path=bat/ads/public/interfaces --mojom-file=/Users/jenkins/jenkins/workspace/pr-brave-browser-bsc-revert-kVideoPlaybackQuality-ios/src/brave/vendor/bat-native-ads/include/bat/ads/public/interfaces/ads.mojom --output-dir=/Users/jenkins/jenkins/workspace/pr-brave-browser-bsc-revert-kVideoPlaybackQuality-ios/src/out/ios_Release_arm64/gen/brave/vendor/brave-ios
15:56:51  Traceback (most recent call last):
15:56:51    File "../../brave/vendor/brave-ios/scripts/mojo/gen_model_wrappers.py", line 47, in <module>
15:56:51      sys.exit(main())
15:56:51    File "../../brave/vendor/brave-ios/scripts/mojo/gen_model_wrappers.py", line 44, in main
15:56:51      generator.GenerateFiles(output_dir)
15:56:51    File "/Users/jenkins/jenkins/workspace/pr-brave-browser-bsc-revert-kVideoPlaybackQuality-ios/src/brave/vendor/brave-ios/scripts/mojo/mojom_objc_generator.py", line 357, in GenerateFiles
15:56:51      self.Write(self._GenerateModuleHeader(),
15:56:51    File "/Users/jenkins/jenkins/workspace/pr-brave-browser-bsc-revert-kVideoPlaybackQuality-ios/src/brave/vendor/brave-ios/scripts/mojo/../../../../../mojo/public/tools/mojom/mojom/generate/template_expander.py", line 35, in GeneratorInternal
15:56:51      return ApplyTemplate(args[0], path_to_template, parameters, **kwargs)
15:56:51    File "/Users/jenkins/jenkins/workspace/pr-brave-browser-bsc-revert-kVideoPlaybackQuality-ios/src/brave/vendor/brave-ios/scripts/mojo/../../../../../mojo/public/tools/mojom/mojom/generate/template_expander.py", line 27, in ApplyTemplate
15:56:51      template = jinja_env.get_template(path_to_template)
15:56:51    File "/Users/jenkins/jenkins/workspace/pr-brave-browser-bsc-revert-kVideoPlaybackQuality-ios/src/third_party/jinja2/environment.py", line 830, in get_template
15:56:51      return self._load_template(name, self.make_globals(globals))
15:56:51    File "/Users/jenkins/jenkins/workspace/pr-brave-browser-bsc-revert-kVideoPlaybackQuality-ios/src/third_party/jinja2/environment.py", line 804, in _load_template
15:56:51      template = self.loader.load(self, name, globals)
15:56:51    File "/Users/jenkins/jenkins/workspace/pr-brave-browser-bsc-revert-kVideoPlaybackQuality-ios/src/third_party/jinja2/loaders.py", line 474, in load
15:56:51      raise TemplateNotFound(name)
15:56:51  jinja2.exceptions.TemplateNotFound: module.h.tmpl
```

## Steps to Reproduce

   1. Create a branch from master
   2. Push branch to remote
   3. Create PR

## Actual result:
CI will fail on iOS

## Expected result:
CI should pass on iOS

## Reproduces how often: 
On issues I've found this, it seems to stay even when replayed

First reported here: 
https://bravesoftware.slack.com/archives/C06UXF3KJ/p1607632003345000

**Comment by iccub** [comment]
Let's close as stale(doing ios issues cleanup before the migration)
