### ISSUE TITLE
Errors/warnings seen when changing Shields settings from panel

### ISSUE THREAD

**Issue by mariospr** [brave/brave-browser#13216]
## Description 

As mentioned in https://github.com/brave/brave-browser/issues/6828#issuecomment-745485542, I'm seeing the following kind of errors on today's build off the `master` branch (Brave 1.20.28 - based on Chromium 88.0.4315.5), whenever I change any of the Shields's settings for the current website, from the Shields panel:
```
[2697829:2697829:1215/182658.592733:WARNING:render_widget_host_impl.cc(267)] Input request on unbound interface
[2697829:2697829:1215/182700.174136:WARNING:CONSOLE(20063)] "%cWarning: a promise was created in a handler at /mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:2390:45 but was not returned from it, see http://goo.gl/rRqMUw
    at new Promise (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:21221:10)
    at reloadTab (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1143:43)
    at chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:2390:45
From previous event:
    at shieldsPanelReducer (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:2389:18)
    at combination (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:25197:29)
    at dispatch (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:24957:22)
    at Object.dispatch (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:2020:16)
    at dispatchResponse (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:26616:32)
    at chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:25904:25 color: darkorange", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (20063)
```

## Steps to Reproduce

   1. Launch Brave from the terminal (e.g. `npm run brave`)
   2. Open a website and wait until finishes loading
   3. Open the Shields panel and change any option (e.g. enable or disable "Script blocking")
   4. Look into the output in the terminal window

## Actual result:

Errors such as the ones pasted above are seen whenever Shields' settings are changed

## Expected result:

No errors should show up when changing Shields' settings.

## Reproduces how often: 

Always

## Desktop Brave version:

Brave 1.20.28 (based on Chromium 88.0.4315.5)

## Version/Channel Information:

So far I only reproduced it with the nightly channel (master)

## Other Additional Information:

Doesn't seem to be causing any actual problem with Shields.

**Comment by bsclifton** [comment]
This issue hasn't had an update in a while - it's met the criteria for being stale. The issue is going to be closed for now. If this is still a problem, please leave a comment or re-open the issue. Thanks!
