### ISSUE TITLE
intermittent CI lint failure due to UnicodeDecodeError

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#13243]
occasionally CI will fail with this error while running clang-format in the lint stage:

```
06:39:40  Traceback (most recent call last):
06:39:40    File "/home/ubuntu/workspace/pr-brave-browser-issues-13233-post-init/src/brave/build/commands/scripts/lint.py", line 107, in <module>
06:39:40      sys.exit(main(sys.argv[1:]))
06:39:40    File "/home/ubuntu/workspace/pr-brave-browser-issues-13233-post-init/src/brave/build/commands/scripts/lint.py", line 66, in main
06:39:40      print('Error running format check: %s' % e.info)
06:39:40  AttributeError: 'exceptions.UnicodeEncodeError' object has no attribute 'info'
```

AFAICT, this never happens locally.

**Comment by diracdeltas** [comment]
this may have been fixed or suppressed by https://github.com/brave/brave-core/pull/7478. will keep an eye on it and close this issue if the error doesn't appear again.
