### ISSUE TITLE
Fix bug related to nightly custom notification

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#14686]
## Description 
This issue is to fix the error we have in nightly regarding the custom notification. 
Below is the log,
2021-03-12 11:18:26.773 26530-26530/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.brave.browser_nightly, PID: 26530
    java.lang.RuntimeException: Unable to start receiver org.chromium.chrome.browser.notifications.BraveOnboardingNotification: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3797)
        at android.app.ActivityThread.access$1400(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1870)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:907)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:387)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
        at android.app.Dialog.show(Dialog.java:342)
        at org.chromium.chrome.browser.dialogs.BraveAdsNotificationDialog.a(chromium-ChromePublic.apk-canary-412303510:8)
        at org.chromium.chrome.browser.notifications.BraveOnboardingNotification.onReceive(chromium-ChromePublic.apk-canary-412303510:16)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3788)
        at android.app.ActivityThread.access$1400(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1870) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 

## Steps to reproduce 

   1. Tap on BAT logo
   2. Tap on "Start using Brave Rewards" button

## Actual result 
Brave nightly app would crash to show custom ad notification.

## Expected result
Brave nightly app should not crash on custom ad notification

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.24.43 x64 nightly build
- Verified test plan from https://github.com/brave/brave-core/pull/8235

OnePlus 6T (Android 10) | Samsung Tab A (Android 10)
-- | -- 
<img width=300 src=https://user-images.githubusercontent.com/17010094/113723355-307d5a80-96e9-11eb-82bb-70e744af3b05.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/113723394-383cff00-96e9-11eb-883c-a164427cfefc.png>
