### ISSUE TITLE
test failure - components/test/brave_extension/background/events/cosmeticFilterEvents_test.ts in CI

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#15188]
```
[2021-04-05T09:53:14.162Z] Summary of all failing tests

[2021-04-05T09:53:14.162Z] FAIL components/test/brave_extension/background/events/cosmeticFilterEvents_test.ts

[2021-04-05T09:53:14.162Z]   ● cosmeticFilterEvents events › chrome.contextMenus.onClicked listener › onSelectorReturned › when prompting user with selector › when a selector is returned › calls window.prompt with selector as input

[2021-04-05T09:53:14.162Z] 

[2021-04-05T09:53:14.162Z]     TypeError: Cannot read property 'then' of undefined

[2021-04-05T09:53:14.162Z] 

[2021-04-05T09:53:14.162Z]       87 |         describe('when a selector is returned', function () {

[2021-04-05T09:53:14.162Z]       88 |           it('calls window.prompt with selector as input', function () {

[2021-04-05T09:53:14.162Z]     > 89 |             return cosmeticFilterEvents.onSelectorReturned('abc').then(() => {

[2021-04-05T09:53:14.162Z]          |                                                                  ^

[2021-04-05T09:53:14.163Z]       90 |               expect(lastInputText).toBe('CSS selector:')

[2021-04-05T09:53:14.163Z]       91 |               expect(lastPromptText).toBe('abc')

[2021-04-05T09:53:14.163Z]       92 |             })

[2021-04-05T09:53:14.163Z] 

[2021-04-05T09:53:14.163Z]       at Object.<anonymous> (components/test/brave_extension/background/events/cosmeticFilterEvents_test.ts:89:66)

[2021-04-05T09:53:14.163Z] 

[2021-04-05T09:53:14.163Z]   ● cosmeticFilterEvents events › chrome.contextMenus.onClicked listener › onSelectorReturned › when prompting user with selector › when a selector is not returned › calls window.prompt with `not found` message

[2021-04-05T09:53:14.163Z] 

[2021-04-05T09:53:14.163Z]     TypeError: Cannot read property 'then' of undefined

[2021-04-05T09:53:14.163Z] 

[2021-04-05T09:53:14.163Z]        95 |         describe('when a selector is not returned', function () {

[2021-04-05T09:53:14.163Z]        96 |           it('calls window.prompt with `not found` message', function () {

[2021-04-05T09:53:14.163Z]     >  97 |             return cosmeticFilterEvents.onSelectorReturned(null).then(() => {

[2021-04-05T09:53:14.163Z]           |                                                                 ^

[2021-04-05T09:53:14.163Z]        98 |               expect(lastInputText.indexOf('We were unable to automatically populat') > -1).toBe(true)

[2021-04-05T09:53:14.163Z]        99 |             })

[2021-04-05T09:53:14.163Z]       100 |           })

[2021-04-05T09:53:14.163Z] 

[2021-04-05T09:53:14.163Z]       at Object.<anonymous> (components/test/brave_extension/background/events/cosmeticFilterEvents_test.ts:97:65)

[2021-04-05T09:53:14.163Z] 

[2021-04-05T09:53:14.163Z]   ● cosmeticFilterEvents events › chrome.contextMenus.onClicked listener › onSelectorReturned › after selector prompt is shown › calls `chrome.tabs.insertCSS` when selector is NOT null/undefined

[2021-04-05T09:53:14.163Z] 

[2021-04-05T09:53:14.163Z]     TypeError: Cannot read property 'then' of undefined

[2021-04-05T09:53:14.163Z] 

[2021-04-05T09:53:14.163Z]       111 |         it('calls `chrome.tabs.insertCSS` when selector is NOT null/undefined', function () {

[2021-04-05T09:53:14.163Z]       112 |           selectorToReturn = '#test_selector'

[2021-04-05T09:53:14.163Z]     > 113 |           return cosmeticFilterEvents.onSelectorReturned(selectorToReturn).then(() => {

[2021-04-05T09:53:14.163Z]           |                                                                           ^

[2021-04-05T09:53:14.163Z]       114 |             let returnObj = {

[2021-04-05T09:53:14.163Z]       115 |               'code': '#test_selector {display: none !important;}',

[2021-04-05T09:53:14.163Z]       116 |               'cssOrigin': 'user'

[2021-04-05T09:53:14.163Z] 

[2021-04-05T09:53:14.163Z]       at Object.<anonymous> (components/test/brave_extension/background/events/cosmeticFilterEvents_test.ts:113:75)

[2021-04-05T09:53:14.163Z] 

[2021-04-05T09:53:14.163Z]   ● cosmeticFilterEvents events › chrome.contextMenus.onClicked listener › onSelectorReturned › after selector prompt is shown › does NOT call `chrome.tabs.insertCSS` when selector is undefined

[2021-04-05T09:53:14.163Z] 

[2021-04-05T09:53:14.163Z]     TypeError: Cannot read property 'then' of undefined

[2021-04-05T09:53:14.163Z] 

[2021-04-05T09:53:14.163Z]       121 |         it('does NOT call `chrome.tabs.insertCSS` when selector is undefined', function () {

[2021-04-05T09:53:14.163Z]       122 |           selectorToReturn = undefined

[2021-04-05T09:53:14.163Z]     > 123 |           return cosmeticFilterEvents.onSelectorReturned(undefined).then(() => {

[2021-04-05T09:53:14.163Z]           |                                                                    ^

[2021-04-05T09:53:14.163Z]       124 |             expect(insertCssSpy).not.toBeCalled()

[2021-04-05T09:53:14.163Z]       125 |           })

[2021-04-05T09:53:14.163Z]       126 |         })

[2021-04-05T09:53:14.163Z] 

[2021-04-05T09:53:14.163Z]       at Object.<anonymous> (components/test/brave_extension/background/events/cosmeticFilterEvents_test.ts:123:68)

[2021-04-05T09:53:14.163Z] 

[2021-04-05T09:53:14.163Z]   ● cosmeticFilterEvents events › chrome.contextMenus.onClicked listener › onSelectorReturned › after selector prompt is shown › does NOT call `chrome.tabs.insertCSS` when selector is null

[2021-04-05T09:53:14.163Z] 

[2021-04-05T09:53:14.163Z]     TypeError: Cannot read property 'then' of undefined

[2021-04-05T09:53:14.163Z] 

[2021-04-05T09:53:14.163Z]       127 |         it('does NOT call `chrome.tabs.insertCSS` when selector is null', function () {

[2021-04-05T09:53:14.163Z]       128 |           selectorToReturn = null

[2021-04-05T09:53:14.163Z]     > 129 |           return cosmeticFilterEvents.onSelectorReturned(null).then(() => {

[2021-04-05T09:53:14.163Z]           |                                                               ^

[2021-04-05T09:53:14.163Z]       130 |             expect(insertCssSpy).not.toBeCalled()

[2021-04-05T09:53:14.163Z]       131 |           })

[2021-04-05T09:53:14.163Z]       132 |         })

[2021-04-05T09:53:14.163Z] 

[2021-04-05T09:53:14.163Z]       at Object.<anonymous> (components/test/brave_extension/background/events/cosmeticFilterEvents_test.ts:129:63)
```

**Comment by antonok-edm** [comment]
@simonhong those should have been fixed by https://github.com/brave/brave-core/pull/8429 - you may need to rebase

**Comment by simonhong** [comment]
Duplicated with https://github.com/brave/brave-browser/issues/15109 and seems fixed now.
