### ISSUE TITLE
bundletool fails to generate APKs from AAB

### ISSUE THREAD

**Issue by bdantas** [brave/brave-browser#15827]
## Description
bundletool fails to generate APKs from AAB

## Steps to reproduce
   1.  Download bundletool and appropriate .aab file (my device is arm64, so I downloaded BraveMonoarm64.aab)
   2.  `$ alias bundletool='java -jar /home/bruno/Downloads/bundletool-all-1.6.0.jar'`
   3.  `$ bundletool build-apks --bundle=/home/bruno/Downloads/BraveMonoarm64.aab --output=/home/bruno/Downloads/BraveMonoarm64.apks`

## Actual result
Multiple errors of this sort: "error: failed to deserialize resources.pb: duplicate configuration in resource table." See below.

```
$ bundletool build-apks --bundle=/home/bruno/Downloads/BraveMonoarm64.aab --output=/home/bruno/Downloads/BraveMonoarm64.apks
WARNING: The APKs won't be signed and thus not installable unless you also pass a keystore via the flag --ks. See the command help for more information.
/tmp/6272904776128236573/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/6272904776128236573/proto.apk: error: failed to load APK.
/tmp/2071804396523564826/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/2071804396523564826/proto.apk: error: failed to load APK.
/tmp/6188646547516233480/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/6188646547516233480/proto.apk: error: failed to load APK.
/tmp/9019322073981279585/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/9019322073981279585/proto.apk: error: failed to load APK.
/tmp/6442691279476123884/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/6442691279476123884/proto.apk: error: failed to load APK.
/tmp/598732138771193428/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/598732138771193428/proto.apk: error: failed to load APK.
---snip---
/tmp/4148553829505242576/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/4148553829505242576/proto.apk: error: failed to load APK.
/tmp/5976620259936164327/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/5976620259936164327/proto.apk: error: failed to load APK.
[BT:1.6.0] Error: Command '[/tmp/AutoValue_BuildApksCommand5394129551921328319/output/linux/aapt2, convert, --output-format, binary, -o, /tmp/5976620259936164327/binary.apk, /tmp/5976620259936164327/proto.apk]' didn't terminate successfully (exit code: 1). Check the logs.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Command '[/tmp/AutoValue_BuildApksCommand5394129551921328319/output/linux/aapt2, convert, --output-format, binary, -o, /tmp/5976620259936164327/binary.apk, /tmp/5976620259936164327/proto.apk]' didn't terminate successfully (exit code: 1). Check the logs.
	at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
	at com.android.tools.build.bundletool.androidtools.DefaultCommandExecutor.executeImpl(DefaultCommandExecutor.java:57)
	at com.android.tools.build.bundletool.androidtools.DefaultCommandExecutor.execute(DefaultCommandExecutor.java:33)
	at com.android.tools.build.bundletool.androidtools.Aapt2Command$1.convertApkProtoToBinary(Aapt2Command.java:53)
	at com.android.tools.build.bundletool.io.ApkzlibApkSerializerHelper.writeToZipFile(ApkzlibApkSerializerHelper.java:136)
	at com.android.tools.build.bundletool.io.ApkzlibApkSerializerHelper.writeToZipFile(ApkzlibApkSerializerHelper.java:109)
	at com.android.tools.build.bundletool.io.SplitApkSerializer.writeToDisk(SplitApkSerializer.java:68)
	at com.android.tools.build.bundletool.io.SplitApkSerializer.writeSplitToDisk(SplitApkSerializer.java:42)
	at com.android.tools.build.bundletool.io.ApkSetBuilderFactory$ApkSetArchiveBuilder.addSplitApk(ApkSetBuilderFactory.java:106)
	at com.android.tools.build.bundletool.io.ApkSerializerManager$ApkSerializer.serialize(ApkSerializerManager.java:461)
	at com.android.tools.build.bundletool.io.ApkSerializerManager.lambda$null$3(ApkSerializerManager.java:225)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

## Expected result
No errors, APK gets built.

## Issue reproduces how often
100% of the time.

## Brave version
Release v1.24.84

**Comment by srirambv** [comment]
cc: @wchen342 @SergeyZhukovsky

**Comment by wchen342** [comment]
Please specify `--aapt2=third_party/android_build_tools/aapt2/aapt2` in the command line options.

**Comment by bdantas** [comment]
I get "No such file or directory" when I specify that:
```
$ alias bundletool='java -jar /home/bruno/Downloads/bundletool-all-1.6.0.jar'
$ bundletool build-apks --bundle=/home/bruno/Downloads/BraveMonoarm64.aab --output=/home/bruno/Downloads/BraveMonoarm64.apks --aapt2=third_party/android_build_tools/aapt2/aapt2
WARNING: The APKs won't be signed and thus not installable unless you also pass a keystore via the flag --ks. See the command help for more information.
[BT:1.6.0] Error: Error when executing command: [third_party/android_build_tools/aapt2/aapt2, convert, --output-format, binary, -o, /tmp/8464005318008573417/binary.apk, /tmp/8464005318008573417/proto.apk]
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Error when executing command: [third_party/android_build_tools/aapt2/aapt2, convert, --output-format, binary, -o, /tmp/8464005318008573417/binary.apk, /tmp/8464005318008573417/proto.apk]
	at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
	at com.android.tools.build.bundletool.androidtools.DefaultCommandExecutor.executeImpl(DefaultCommandExecutor.java:64)
	at com.android.tools.build.bundletool.androidtools.DefaultCommandExecutor.execute(DefaultCommandExecutor.java:33)
	at com.android.tools.build.bundletool.androidtools.Aapt2Command$1.convertApkProtoToBinary(Aapt2Command.java:53)
	at com.android.tools.build.bundletool.io.ApkzlibApkSerializerHelper.writeToZipFile(ApkzlibApkSerializerHelper.java:136)
	at com.android.tools.build.bundletool.io.ApkzlibApkSerializerHelper.writeToZipFile(ApkzlibApkSerializerHelper.java:109)
	at com.android.tools.build.bundletool.io.SplitApkSerializer.writeToDisk(SplitApkSerializer.java:68)
	at com.android.tools.build.bundletool.io.SplitApkSerializer.writeSplitToDisk(SplitApkSerializer.java:42)
	at com.android.tools.build.bundletool.io.ApkSetBuilderFactory$ApkSetArchiveBuilder.addSplitApk(ApkSetBuilderFactory.java:106)
	at com.android.tools.build.bundletool.io.ApkSerializerManager$ApkSerializer.serialize(ApkSerializerManager.java:461)
	at com.android.tools.build.bundletool.io.ApkSerializerManager.lambda$null$3(ApkSerializerManager.java:225)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Cannot run program "third_party/android_build_tools/aapt2/aapt2": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.android.tools.build.bundletool.androidtools.DefaultCommandExecutor.executeImpl(DefaultCommandExecutor.java:44)
	... 15 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
```

If I extract the `aapt2` binary (which seems to work fine) from bundletool-all-1.6.0.jar and specify absolute path to it, I get the same error in OP:
```
$ bundletool build-apks --bundle=/home/bruno/Downloads/BraveMonoarm64.aab --output=/home/bruno/Downloads/BraveMonoarm64.apks --aapt2=/home/bruno/Downloads/aapt2
WARNING: The APKs won't be signed and thus not installable unless you also pass a keystore via the flag --ks. See the command help for more information.
/tmp/1301313670253238887/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/1301313670253238887/proto.apk: error: failed to load APK.
/tmp/8183704293533134268/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/8183704293533134268/proto.apk: error: failed to load APK.
/tmp/3113985808270385457/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/3113985808270385457/proto.apk: error: failed to load APK.
/tmp/1763905903567853071/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/1763905903567853071/proto.apk: error: failed to load APK.
/tmp/3499703960617289264/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/3499703960617289264/proto.apk: error: failed to load APK.
/tmp/2497561008234805575/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/2497561008234805575/proto.apk: error: failed to load APK.
/tmp/3694967260907674759/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/3694967260907674759/proto.apk: error: failed to load APK.
/tmp/5636868933588915945/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/5636868933588915945/proto.apk: error: failed to load APK.
/tmp/3627439877516811646/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/3627439877516811646/proto.apk: error: failed to load APK.
/tmp/7261091687840686393/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/7261091687840686393/proto.apk: error: failed to load APK.
/tmp/3937451838202533042/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/3937451838202533042/proto.apk: error: failed to load APK.
/tmp/224797269343520384/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/224797269343520384/proto.apk: error: failed to load APK.
/tmp/2157508629635661745/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/2157508629635661745/proto.apk: error: failed to load APK.
/tmp/1270511194334690024/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/1270511194334690024/proto.apk: error: failed to load APK.
/tmp/2001013537372025258/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/2001013537372025258/proto.apk: error: failed to load APK.
/tmp/6902176121714054177/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/6902176121714054177/proto.apk: error: failed to load APK.
/tmp/5885463603070288329/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/5885463603070288329/proto.apk: error: failed to load APK.
/tmp/1898169375004400812/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/1898169375004400812/proto.apk: error: failed to load APK.
/tmp/4766520824858707958/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/4766520824858707958/proto.apk: error: failed to load APK.
/tmp/2929664999525526751/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/2929664999525526751/proto.apk: error: failed to load APK.
/tmp/1376535024568278780/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/1376535024568278780/proto.apk: error: failed to load APK.
/tmp/3223555200839502786/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/3223555200839502786/proto.apk: error: failed to load APK.
/tmp/5963621621292732799/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/5963621621292732799/proto.apk: error: failed to load APK.
/tmp/8143560627022605168/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/8143560627022605168/proto.apk: error: failed to load APK.
/tmp/4548966805934844532/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/4548966805934844532/proto.apk: error: failed to load APK.
/tmp/437398603066597304/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/437398603066597304/proto.apk: error: failed to load APK.
/tmp/907839177794404203/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/907839177794404203/proto.apk: error: failed to load APK.
/tmp/3184834720174607120/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/3184834720174607120/proto.apk: error: failed to load APK.
/tmp/2664986812285153577/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/2664986812285153577/proto.apk: error: failed to load APK.
/tmp/7124482966181222320/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/7124482966181222320/proto.apk: error: failed to load APK.
/tmp/6223719243400412676/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/6223719243400412676/proto.apk: error: failed to load APK.
/tmp/4690150362940132202/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/4690150362940132202/proto.apk: error: failed to load APK.
/tmp/7418839643149815187/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/7418839643149815187/proto.apk: error: failed to load APK.
/tmp/1454650301450238062/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/1454650301450238062/proto.apk: error: failed to load APK.
/tmp/140705872005395780/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/140705872005395780/proto.apk: error: failed to load APK.
/tmp/6781550679762131228/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/6781550679762131228/proto.apk: error: failed to load APK.
/tmp/1786028844483458108/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/1786028844483458108/proto.apk: error: failed to load APK.
/tmp/645669493392602740/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/645669493392602740/proto.apk: error: failed to load APK.
/tmp/4301068324096705522/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/4301068324096705522/proto.apk: error: failed to load APK.
/tmp/7469408096324494241/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/7469408096324494241/proto.apk: error: failed to load APK.
/tmp/3326441061797375149/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/3326441061797375149/proto.apk: error: failed to load APK.
/tmp/8788860074571796497/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/8788860074571796497/proto.apk: error: failed to load APK.
/tmp/2333892146143538148/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/2333892146143538148/proto.apk: error: failed to load APK.
/tmp/7742555302345804872/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/7742555302345804872/proto.apk: error: failed to load APK.
/tmp/3968053313695880474/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/3968053313695880474/proto.apk: error: failed to load APK.
/tmp/7489409925282355233/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/7489409925282355233/proto.apk: error: failed to load APK.
/tmp/3599824259139721694/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/3599824259139721694/proto.apk: error: failed to load APK.
/tmp/2683333364777298949/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/2683333364777298949/proto.apk: error: failed to load APK.
/tmp/8150477963181978809/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/8150477963181978809/proto.apk: error: failed to load APK.
/tmp/1436364307236286881/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/1436364307236286881/proto.apk: error: failed to load APK.
/tmp/6549148019816881942/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/6549148019816881942/proto.apk: error: failed to load APK.
/tmp/6041655225446756677/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/6041655225446756677/proto.apk: error: failed to load APK.
/tmp/3890831300527379207/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/3890831300527379207/proto.apk: error: failed to load APK.
/tmp/6490934043124550676/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/6490934043124550676/proto.apk: error: failed to load APK.
/tmp/2449087955427484364/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/2449087955427484364/proto.apk: error: failed to load APK.
/tmp/87402628441538474/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/87402628441538474/proto.apk: error: failed to load APK.
/tmp/5224517401992780959/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/5224517401992780959/proto.apk: error: failed to load APK.
/tmp/126675605795150413/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/126675605795150413/proto.apk: error: failed to load APK.
/tmp/6655212752514395723/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/6655212752514395723/proto.apk: error: failed to load APK.
/tmp/3971136227347108996/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/3971136227347108996/proto.apk: error: failed to load APK.
/tmp/4913789865443929596/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/4913789865443929596/proto.apk: error: failed to load APK.
/tmp/6160759757337023084/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/6160759757337023084/proto.apk: error: failed to load APK.
/tmp/732638574434987666/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/732638574434987666/proto.apk: error: failed to load APK.
/tmp/8314016857082159024/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/8314016857082159024/proto.apk: error: failed to load APK.
/tmp/4019371242292672188/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/4019371242292672188/proto.apk: error: failed to load APK.
/tmp/1168184266255073348/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/1168184266255073348/proto.apk: error: failed to load APK.
/tmp/3670610450383207790/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/3670610450383207790/proto.apk: error: failed to load APK.
/tmp/8089279445968777424/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/8089279445968777424/proto.apk: error: failed to load APK.
/tmp/345503360989323535/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/345503360989323535/proto.apk: error: failed to load APK.
/tmp/1830916307955611380/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/1830916307955611380/proto.apk: error: failed to load APK.
/tmp/7900206315724514726/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/7900206315724514726/proto.apk: error: failed to load APK.
/tmp/8752499149446810671/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/8752499149446810671/proto.apk: error: failed to load APK.
/tmp/3757534632817100281/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/3757534632817100281/proto.apk: error: failed to load APK.
/tmp/36176525597484179/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/36176525597484179/proto.apk: error: failed to load APK.
/tmp/4326637639837903121/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/4326637639837903121/proto.apk: error: failed to load APK.
[BT:1.6.0] Error: Command '[/home/bruno/Downloads/aapt2, convert, --output-format, binary, -o, /tmp/4326637639837903121/binary.apk, /tmp/4326637639837903121/proto.apk]' didn't terminate successfully (exit code: 1). Check the logs.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Command '[/home/bruno/Downloads/aapt2, convert, --output-format, binary, -o, /tmp/4326637639837903121/binary.apk, /tmp/4326637639837903121/proto.apk]' didn't terminate successfully (exit code: 1). Check the logs.
	at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
	at com.android.tools.build.bundletool.androidtools.DefaultCommandExecutor.executeImpl(DefaultCommandExecutor.java:57)
	at com.android.tools.build.bundletool.androidtools.DefaultCommandExecutor.execute(DefaultCommandExecutor.java:33)
	at com.android.tools.build.bundletool.androidtools.Aapt2Command$1.convertApkProtoToBinary(Aapt2Command.java:53)
	at com.android.tools.build.bundletool.io.ApkzlibApkSerializerHelper.writeToZipFile(ApkzlibApkSerializerHelper.java:136)
	at com.android.tools.build.bundletool.io.ApkzlibApkSerializerHelper.writeToZipFile(ApkzlibApkSerializerHelper.java:109)
	at com.android.tools.build.bundletool.io.SplitApkSerializer.writeToDisk(SplitApkSerializer.java:68)
	at com.android.tools.build.bundletool.io.SplitApkSerializer.writeSplitToDisk(SplitApkSerializer.java:42)
	at com.android.tools.build.bundletool.io.ApkSetBuilderFactory$ApkSetArchiveBuilder.addSplitApk(ApkSetBuilderFactory.java:106)
	at com.android.tools.build.bundletool.io.ApkSerializerManager$ApkSerializer.serialize(ApkSerializerManager.java:461)
	at com.android.tools.build.bundletool.io.ApkSerializerManager.lambda$null$3(ApkSerializerManager.java:225)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Maybe there's something about the `.aab` file that `aapt2` doesn't like.

**Comment by wchen342** [comment]
You need the `aapt2` from chromium source tree. chromium has a modified version of `aapt2` different from the public version in android sdk.

**Comment by bdantas** [comment]
I see. Thank you for your input--I would not have guessed.

Do you know where I can find the `aapt2` binary for linux x86_64? (I don't need the whole chromium development environment, just want to be able to create APK from Brave's AAB.)

**Comment by wchen342** [comment]
You can try download directly from [here](https://storage.googleapis.com/chrome-infra-packages/store/SHA256/476939c303a521a4bab23bf64c8c87a2d88f26877ee8aaa764ef0d1fe2852bcb?Expires=1620931143&GoogleAccessId=chrome-infra-packages%40appspot.gserviceaccount.com&Signature=HSkhlLzWZ6lB%2B7TiQ1HNqNJlMGekGzFkcQWX5ZnaNzXxTFknEAY%2Fwhai7Q70buqjyB0tRVVAsyOXaL6RL%2BqZ%2FRcjvZP1zQA%2BJhZ9%2Fwhxeqgnr25CqP2%2F%2BKIEaVQO0zAG2X%2FPfMrL7QU6ceSr9au66Sgc37OVjwKsSvfExIUr33cJ0xX4X%2FTm3JzoH0GpLA%2FRVAlsSUB1jTRxlX%2FcWezCw2w8fIpoRcSTBWSGiicdIkbr0iwa6HUc0zv0moDfU0i2lcVgRv7qvOvrxs2M%2F6z8CEvhiRwyNACWdcP%2BZoOp2sRn%2F0dfg7baXIhRGWFkVoi79w7CdBELu7LhiuRVhA9owg%3D%3D&response-content-disposition=attachment%3B+filename%3D%22android_build_tools-aapt2.zip%22).

**Comment by bdantas** [comment]
Thank you, wchen342!!! Now it works like a charm :)

For other users interested in building and installing the `.apks` file themselves:
1. Download appropriate `.aab` file from Brave's github page
2. Make sure you have `bundletool` and chromium project's `aapt2` (for the latter, see wchen342's link above)
2. Create a keystore if you don't already have one (see https://stackoverflow.com/a/15330139)
3. Build a self-signed `.apks` file. My command, as an example, was this:
```
$ alias bundletool='java -jar /home/bruno/Downloads/bundletool-all-1.6.0.jar'
$ bundletool build-apks --bundle=/home/bruno/Downloads/BraveMonoarm64.aab --output=/home/bruno/Downloads/BraveMonoarm64.apks --aapt2=/home/bruno/Downloads/aapt2 --ks=/home/bruno/Stuff/my-release-key.keystore --ks-pass=passWorD --ks-key-alias=gnuser --key-pass=passWorD
```
4. Enable debugging on your Android device, use cable to connect Android device to computer, on Android device click "File transfer", start adb on computer with `$ adb start-server`
5. Install the .apks to Android device. In my case, this was the command:
```
$ bundletool install-apks --apks=/home/bruno/Downloads/BraveMonoarm64.apks
```
Note that if brave-browser from an official app store is already installed on your Android device, step 5 will fail because when upgrading an app your device requires that current app version and new app version be signed with same signature. Therefore, you have to uninstall the official brave-browser before you can install your self-signed version (I used `oandbackup` app to backup my browser's data so that I could restore the data after installing the self-signed brave-browser version).

Happy hacking!

**Comment by bdantas** [comment]
P.S. A wishlist item:
It would be nice if a link to the appropriate `aapt2` binary were provided with each brave-browser release's "Assets". This way, "mere mortal" users such as myself would be alerted to the fact that the `aapt2` included in `buildtool` is not going to work. It would also safeguard against problems from users using an outdated `aapt2` from chromium source tree.
