### ISSUE TITLE
Ledger Nano doesn't works with Brave Nightly on Linux

### ISSUE THREAD

**Issue by gspe** [brave/brave-browser#16082]
## Description 

Ledger Nano X and S doesn't works with Brave Nightly on Linux system

## Steps to Reproduce

For example, using Tron web Wallet:
   1. https://tronscan.org
   2. Click on connect wallet
   3. Follow the instruction 

## Actual result:

Nothing happens

## Expected result:
Web Wallet open and be able to interact with it

## Reproduces how often: 

This happens every time with every wallet, Tron, Cardano, Ether...

## Brave version (brave://version info)

Version 1.27.16 Chromium: 91.0.4472.70 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
No with Brave Release Web Wallets works fine
- Can you reproduce this issue with the beta channel? 
Yes, it happens with the beta channel too.

## Other Additional Information:

- Is the issue reproducible on the latest version of Chrome? 
No it doesn't happens with Chromium Version 90.0.4430.212 (Developer Build) (64-bit)

**Comment by ProgrammingMyLife** [comment]
Are you on the latest firmware version for your ledger nano?

**Comment by ProgrammingMyLife** [comment]
Can you open the Developer Console and (Ctrl + Shift + I then go to Console) and try to pair the wallet then show us whats happening

**Comment by gspe** [comment]
I did some more test and this problem start to happen from Chromium 91.xxxx version

This is the log from console:

```
js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
91.c4923871.chunk.js:1 Deprecation warning: moment().subtract(period, number) is deprecated. Please use moment().subtract(number, period). See http://momentjs.com/guides/#/warnings/add-inverted-param/ for more info.
O @ 91.c4923871.chunk.js:1
walletConnect.08578cd3.chunk.js:1 
walletConnect.08578cd3.chunk.js:1 
walletConnect.08578cd3.chunk.js:1 e======= s {name: "TransportError", message: "Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE", stack: "Error\n    at new s (https://tronscan.org/static/js…nscan.org/static/js/91.c4923871.chunk.js:1:13197)", id: "U2F_4", originalError: Error: Sign failed
    at l (https://tronscan.org/static/js/91.c4923871.chunk.js:1:2407986)
    at …}
walletConnect.08578cd3.chunk.js:1 e======= s {name: "TransportError", message: "Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE", stack: "Error\n    at new s (https://tronscan.org/static/js…nscan.org/static/js/91.c4923871.chunk.js:1:13197)", id: "U2F_4", originalError: Error: Sign failed
    at l (https://tronscan.org/static/js/91.c4923871.chunk.js:1:2407986)
    at …}id: "U2F_4"message: "Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE"name: "TransportError"originalError: Error: Sign failed
    at l (https://tronscan.org/static/js/91.c4923871.chunk.js:1:2407986)
    at https://tronscan.org/static/js/91.c4923871.chunk.js:1:2407812
    at r.responseHandler_ (https://tronscan.org/static/js/91.c4923871.chunk.js:1:2411453)
    at https://tronscan.org/static/js/91.c4923871.chunk.js:1:2410258stack: "Error\n    at new s (https://tronscan.org/static/js/91.c4923871.chunk.js:1:450072)\n    at d.<anonymous> (https://tronscan.org/static/js/91.c4923871.chunk.js:1:739279)\n    at l (https://tronscan.org/static/js/91.c4923871.chunk.js:1:1270564)\n    at Generator.n._invoke (https://tronscan.org/static/js/91.c4923871.chunk.js:1:1270379)\n    at Generator.throw (https://tronscan.org/static/js/91.c4923871.chunk.js:1:1270983)\n    at r (https://tronscan.org/static/js/91.c4923871.chunk.js:1:12959)\n    at u (https://tronscan.org/static/js/91.c4923871.chunk.js:1:13197)"__proto__: Error
    at Object.<anonymous> (https://tronscan.org/static/js/91.c4923871.chunk.js:1:450563)
    at o (https://tronscan.org/static/js/main.4afaa8cf.js:1:571)
    at Object.<anonymous> (https://tronscan.org/static/js/91.c4923871.chunk.js:1:1555896)
    at Object.<anonymous> (https://tronscan.org/static/js/91.c4923871.chunk.js:1:1559888)
    at o (https://tronscan.org/static/js/main.4afaa8cf.js:1:571)
    at Object.<anonymous> (https://tronscan.org/static/js/91.c4923871.chunk.js:1:737819)
    at Object.<anonymous> (https://tronscan.org/static/js/91.c4923871.chunk.js:1:740364)
    at o (https://tronscan.org/static/js/main.4afaa8cf.js:1:571)
    at Object.444 (https://tronscan.org/static/js/main.4afaa8cf.js:1:293020)
    at o (https://tronscan.org/static/js/main.4afaa8cf.js:1:571)
walletConnect.08578cd3.chunk.js:1 e======= s {name: "TransportError", message: "Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE", stack: "Error\n    at new s (https://tronscan.org/static/js…nscan.org/static/js/91.c4923871.chunk.js:1:13197)", id: "U2F_4", originalError: Error: Sign failed
    at l (https://tronscan.org/static/js/91.c4923871.chunk.js:1:2407986)
    at …}
```

**Comment by wknapik** [comment]
For the snap package, see https://github.com/brave/brave-browser/issues/15003 (follow-up to https://github.com/brave/brave-browser/issues/6782). If this is not about the snap package, carry on.

**Comment by agowa338** [comment]
This may also be related to #6168 and #9925, as currently Ledger is also not working on Windows...

**Comment by srirambv** [comment]
CR91 broke wallet connection. This is [fixed](https://github.com/brave/brave-browser/issues/16204) in the latest release for Windows and macOS. Unfortunately this is not fixed on Linux so it will still fail with `TransportError: Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE`. We are working on a permanent fix for this and should be available soon.

**Comment by agowa338** [comment]
@srirambv Just updated and I cannot confirm that it is fixed on windows. It's still not working for me.

**Comment by bbondy** [comment]
@gspe can you confirm if it still does not work for you?

**Comment by gspe** [comment]
@bbondy Sorry for late answer but I didn't used Brave do to this problem.
I'm using Brave again in this days and I can say that it works again with ledger wallet.
So we can close this bug.
