### ISSUE TITLE
[Android] Uninitialized commandline instance in browser tests

### ISSUE THREAD

**Issue by wchen342** [brave/brave-browser#16244]
## Description 

Browser tests on Android will crash with the following error:

```
--------- beginning of crash
06-01 18:07:12.462  9246  9246 E AndroidRuntime: FATAL EXCEPTION: main
06-01 18:07:12.462  9246  9246 E AndroidRuntime: Process: org.chromium.android_browsertests_apk, PID: 9246
06-01 18:07:12.462  9246  9246 E AndroidRuntime: java.lang.AssertionError
06-01 18:07:12.462  9246  9246 E AndroidRuntime:     at org.chromium.base.CommandLine.getInstance(CommandLine.java:129)
06-01 18:07:12.462  9246  9246 E AndroidRuntime:     at org.chromium.chrome.browser.night_mode.GlobalNightModeStateProviderHolder.getInstance(GlobalNightModeStateProviderHolder.java:58)
06-01 18:07:12.462  9246  9246 E AndroidRuntime:     at org.chromium.chrome.browser.onboarding.P3aOnboardingActivity.onCreate(P3aOnboardingActivity.java:81)
06-01 18:07:12.462  9246  9246 E AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:7136)
06-01 18:07:12.462  9246  9246 E AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:7127)
06-01 18:07:12.462  9246  9246 E AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
06-01 18:07:12.462  9246  9246 E AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
06-01 18:07:12.462  9246  9246 E AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
06-01 18:07:12.462  9246  9246 E AndroidRuntime:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
06-01 18:07:12.462  9246  9246 E AndroidRuntime:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
06-01 18:07:12.462  9246  9246 E AndroidRuntime:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
06-01 18:07:12.462  9246  9246 E AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
06-01 18:07:12.462  9246  9246 E AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:106)
06-01 18:07:12.462  9246  9246 E AndroidRuntime:     at android.os.Looper.loop(Looper.java:193)
06-01 18:07:12.462  9246  9246 E AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6669)
06-01 18:07:12.462  9246  9246 E AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
06-01 18:07:12.462  9246  9246 E AndroidRuntime:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
06-01 18:07:12.462  9246  9246 E AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
06-01 18:07:12.476  9246  9246 I Process : Sending signal. PID: 9246 SIG: 9
```

This needs further investigation since the command line instance shall be initialized in browser tests as in normal runs.

## Steps to reproduce 

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by wchen342** [comment]
A new relative crash occurs during tests:

```
06-07 20:54:03.547 15070 15070 E AndroidRuntime: java.lang.AssertionError
06-07 20:54:03.547 15070 15070 E AndroidRuntime: 	at org.chromium.base.CommandLine.getInstance(CommandLine.java:129)
06-07 20:54:03.547 15070 15070 E AndroidRuntime: 	at org.chromium.chrome.browser.night_mode.GlobalNightModeStateProviderHolder.getInstance(GlobalNightModeStateProviderHolder.java:58)
06-07 20:54:03.547 15070 15070 E AndroidRuntime: 	at org.chromium.chrome.browser.ChromeBaseAppCompatActivity.createNightModeStateProvider(ChromeBaseAppCompatActivity.java:112)
06-07 20:54:03.547 15070 15070 E AndroidRuntime: 	at org.chromium.chrome.browser.ChromeBaseAppCompatActivity.attachBaseContext(ChromeBaseAppCompatActivity.java:39)
06-07 20:54:03.547 15070 15070 E AndroidRuntime: 	at android.app.Activity.attach(Activity.java:7051)
06-07 20:54:03.547 15070 15070 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2873)
06-07 20:54:03.547 15070 15070 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
06-07 20:54:03.547 15070 15070 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
06-07 20:54:03.547 15070 15070 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
06-07 20:54:03.547 15070 15070 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
06-07 20:54:03.547 15070 15070 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
06-07 20:54:03.547 15070 15070 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-07 20:54:03.547 15070 15070 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
06-07 20:54:03.547 15070 15070 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
06-07 20:54:03.547 15070 15070 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-07 20:54:03.547 15070 15070 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
06-07 20:54:03.547 15070 15070 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by srirambv** [comment]
Verification passed on Oppo R5 with Android 11 running 1.28.99 x64 Beta Build
- Verified test plan from https://github.com/brave/brave-core/pull/9104
- Verified onboarding flow works like before
------------
Verification passed on Samsung Tab A with Android 10 running 1.28.99 x64 Beta Build
- Verified test plan from https://github.com/brave/brave-core/pull/9104
- Verified onboarding flow works like before
