### ISSUE TITLE
Crash when going into shields (after aggressive setting landed)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#16520]
## Description 
Crash happening on shields aggressive mode; preference was updated from boolean to int

```
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer
        at android.app.SharedPreferencesImpl.getInt(SharedPreferencesImpl.java:302)
        at org.chromium.chrome.browser.privacy.settings.BravePrivacySettings.updatePreferences(BravePrivacySettings.java:342)
        at org.chromium.chrome.browser.privacy.settings.BravePrivacySettings.onCreatePreferences(BravePrivacySettings.java:204)
        at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:161)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2963)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:458)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:255)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2256)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:0)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2162)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:0)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2064)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:0)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3380)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:0)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3313)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:0)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:501)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1419)
        at android.app.Activity.performStart(Activity.java:7479)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3454)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Method.java)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

## Steps to reproduce 

   1. Have an older / existing Nightly profile
   2. Launch latest Brave Nightly (Android) 
   2. Tap on shields 
   3. Pick Privacy 

## Actual result 
Crashes

## Expected result
No crash

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
Closing as duplicate of https://github.com/brave/brave-browser/issues/16510
