### ISSUE TITLE
Brave release, beta, and nightly all crash during initial setup on OneUI 4.0 Beta 2, Galaxy S21 Ultra

### ISSUE THREAD

**Issue by meejle** [brave/brave-browser#18667]
## Description 
Whelp, this one is weirdly specific.

I'm on a clean install of OneUI 4.0 Beta 2 (Android 12) on my Samsung Galaxy S21 Ultra (Exynos). Build SP1A.210812.003.G998BXXU3ZUJ1.SP1A.210812.003.G998BXXU3ZUJ1.

I've tried installing Brave, Brave Beta, and Brave Nightly.

I get the initial screen that asks whether I want to allow diagnostic reporting or whatever. When I press the button to continue, the app crashes and dumps me back at the home screen.

I'm not necessarily asking for a fix, just posting in case it's something you guys will need to be aware of before OneUI releases later this year. ☺️

## Steps to reproduce 

   1. Install OneUI 4.0 Beta 2 as a clean install on a Samsung Galaxy S21 Ultra (Exynos)
   2. Download Brave
   3. Try to set it up

## Actual result 

It crashes.

## Expected result

It does not crash.

## Issue reproduces how often 

Every time.

## Version/Channel Information:

Um, idk. I tried downloading an older version from APKMirror but it also crashed.

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): Arm64v8a
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy S21 Ultra (Exynos)
   - Android version: 12 (OneUI 4.0 Beta)
   
## Brave version

1.30.87, 1.31.74 beta, 1.32.58 nightly, and 1.30.86.

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? No

### Additional information

N/A

**Comment by meejle** [comment]
> This issue doesn't happen with other chromium based browsers but only on Brave browser. I'm thinking it's a Brave specific issue and not an Android 12 issue. Bromite and Kiwi browsers have no such issues.
> 
> Tested on Oxygen OS 12 beta 1 on a OnePlus 9 Pro.

Sorry, yeah, I meant "an issue with Brave on Android 12 in general", rather than "an issue with Android 12 in general." I could've  been clearer. 👀

But still good information to help narrow it down. I'm pretty sure Chrome is disabled on my phone, and Firefox is my other go-to after Brave, so I hadn't tested it with another Chromium browser.

**Comment by Moon14590** [comment]
Brave is crashing for me as well. On startup. 
I'm on
• Android 12 (stable)
• arm64, Poco F1(beryllium), a custom rom with Pixel 5 fingerprint


https://catbin.up.railway.app/edabuygned

**Comment by Alexmoto714** [comment]
Same issue is happening to me as well on all builds 

Phone Type: Pixel 3a XL
Stable: 1.30.87
Dev: 1.32.76
Nightly: 1.33.22

**Comment by GeriYatola** [comment]
@srirambv  Build 1.31.88 now crashes at launch on Oneplus 8 running Android 11 build OP8_O2_BETA_12. Tried update and clean install. Freezes on launch after update just showing the address bar. On clean install welcome splash screen is shown, but the UI doesn't respond.

**Comment by meejle** [comment]
I just installed 1.31.88 Release from APKMirror (I guess it hasn't "rolled out" to me yet on the Play Store... 🙄) and the crash is fixed for me! Thank you guys.

**Comment by meejle** [comment]
Ahh, nope, scratch that. It worked for a little while, then froze, and now it opens but won't do anything. I either get JUST the splash screen, or JUST the omnibar. Back to Firefox I go... 😭

**Comment by umbraesoulsbane** [comment]
Not sure if this is supposed to be fixed or not. Originally was not having an issue on P4 XL nor 6 Pro. Then on Pro Brave wouldnt resume. Reinstalling doesn't fix. 

Guess it's time to switch browsers since I can't use Brave at all now.

**Comment by InfiniteInsight** [comment]
This is still a problem on Pixel 5, android 12.

Brave 1.31.90 

Only get the splash screen, then omni bar.. Then a crash.

Pretty annoying. I've got like $25 worth of bat that I haven't been able to link to a wallet because it's not 25 bat yet. Something tells me I'm going to lose a years worth of bat.

**Comment by Stumblinbear** [comment]
Getting this on Android 11, Brave 1.31.90.

**Comment by dee-kryvenko** [comment]
1.49.90 fixed it for me on Android 12 Pixel 3XL. I am unhappy though with how long time it took them to push the change from the moment the fix was merged. This is huge emergency showstopper - browser didn't work AT ALL for weeks and they seem to just keep their usual release schedule. This is simply unacceptable. Glad it is now fixed - but as I am currently currently trying to evaluate Brave browser - it didn't give me confidence these guys are doing business seriously.

**Comment by chris122380** [comment]
> 1.49.90 fixed it for me on Android 12 Pixel 3XL. I am unhappy though with how long time it took them to push the change from the moment the fix was merged. This is huge emergency showstopper - browser didn't work AT ALL for weeks and they seem to just keep their usual release schedule. This is simply unacceptable. Glad it is now fixed - but as I am currently currently trying to evaluate Brave browser - it didn't give me confidence these guys are doing business seriously.

You have to remember that even if Brave pushed this out right away that Google delays pushing out apps in the Play Store and not necessarily Brave.

**Comment by dee-kryvenko** [comment]
As a user, why should I care? How's having my browser not work for WEEKS can be ever justified? How come it was never tested on Android 12 betas?

**Comment by waltercool** [comment]
Sorry to bother everyone with this, but still happens at 1.35.103

System.err: java.lang.IllegalArgumentException: com.brave.browser: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
02-21 15:00:30.872 25134 25134 W System.err: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
02-21 15:00:30.872 25134 25134 W System.err:    at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
02-21 15:00:30.872 25134 25134 W System.err:    at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:465)
02-21 15:00:30.872 25134 25134 W System.err:    at android.app.PendingIntent.getActivity(PendingIntent.java:451)
02-21 15:00:30.872 25134 25134 W System.err:    at android.app.PendingIntent.getActivity(PendingIntent.java:415)
02-21 15:00:30.872 25134 25134 W System.err:    at JF0.f(chromium-MonochromePublic.apk-stable-413510323:2)
02-21 15:00:30.872 25134 25134 W System.err:    at org.chromium.components.media_router.BrowserMediaRouter.create(chromium-MonochromePublic.apk-stable-413510323:6)
02-21 15:00:30.872 25134 25134 W System.err:    at android.os.MessageQueue.nativePollOnce(Native Method)
02-21 15:00:30.872 25134 25134 W System.err:    at android.os.MessageQueue.next(MessageQueue.java:335)
02-21 15:00:30.872 25134 25134 W System.err:    at android.os.Looper.loopOnce(Looper.java:186)
02-21 15:00:30.872 25134 25134 W System.err:    at android.os.Looper.loop(Looper.java:313)
02-21 15:00:30.872 25134 25134 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:8633)
02-21 15:00:30.872 25134 25134 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
02-21 15:00:30.872 25134 25134 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
02-21 15:00:30.872 25134 25134 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
02-21 15:00:30.874 25134 25134 F chromium: [FATAL:jni_android.cc(306)] Please include Java exception stack in crash report

Was that commit applied to 1.35.x ?

**Comment by SergeyZhukovsky** [comment]
@waltercool yes the fix has been applied. Could you help us figure out your case?
- Does it happens every time you open Brave?
- Do you have any tabs with URL open there?
- What device do you have?
- Do you use Google Play Services?

**Comment by waltercool** [comment]
@SergeyZhukovsky
- It happens likely any time there is a video playing. Can't confirm this is 100% the case, but likely.
- That doesn't matter, it crashes for ex. as soon I open youtube.com, or some odysee video for example.
- Samsung Galaxy Tab S7+ with Android 12
- No. Disabled. BUT, after testing, if I do enable Google Play Services it doesn't crash.

**Comment by SergeyZhukovsky** [comment]
@waltercool from the call stack you provided I see it crashes on accessing `GoogleApiAvailability.getInstance()` inside chromium sources. I wonder does stock Chrome crashes as well with them disabled?

**Comment by waltercool** [comment]
Let me try and test today later, but I have installed Ungoogled-Chromium and does not crash.

**Comment by waltercool** [comment]
@SergeyZhukovsky Under Chrome for Android, no problems.

**Comment by SergeyZhukovsky** [comment]
did you test in Chrome with Google Play Services disabled as well?
