### ISSUE TITLE
PageGraph branch build failure

### ISSUE THREAD

**Issue by naifmeh** [brave/brave-browser#19040]
## Description 

Trying to build from the pagegraph's branch leads to a depot tools error when running "npm run init".

## Steps to Reproduce

   1. Clone the repository and switch to the pagegraph branch
   2. Run npm install
   3. Run npm run init

## Actual result:

```
/work/brave-browser
> gclient sync --reset --nohooks --revision src/brave@page-graph --revision src@refs/tags/83.0.4103.116 --force --with_tags --with_branch_heads --upstream
WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.
Syncing projects:  50% ( 1/ 2) src

src (ERROR)
----------------------------------------
[0:00:00] Started.
_____ src at refs/tags/83.0.4103.116
[0:00:08] Already up to date.
[0:00:08]
----------------------------------------

Traceback (most recent call last):
  File "/work/brave-browser/vendor/depot_tools/metrics.py", line 267, in print_notice_and_exit
    yield
  File "/work/brave-browser/vendor/depot_tools/gclient.py", line 3156, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/work/brave-browser/vendor/depot_tools/gclient.py", line 3142, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/work/brave-browser/vendor/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/work/brave-browser/vendor/depot_tools/gclient.py", line 2699, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/work/brave-browser/vendor/depot_tools/gclient.py", line 1737, in RunOnDeps
    patch_refs=patch_refs, target_branches=target_branches)
  File "/work/brave-browser/vendor/depot_tools/gclient_utils.py", line 907, in flush
    reraise(e[0], e[1], e[2])
  File "/work/brave-browser/vendor/depot_tools/gclient_utils.py", line 984, in run
    self.item.run(*self.args, **self.kwargs)
  File "/work/brave-browser/vendor/depot_tools/gclient.py", line 941, in run
    self.ParseDepsFile()
  File "/work/brave-browser/vendor/depot_tools/gclient.py", line 701, in ParseDepsFile
    filepath, self.get_vars(), self.get_builtin_vars())
  File "/work/brave-browser/vendor/depot_tools/gclient_eval.py", line 502, in Parse
    result = Exec(content, filename, vars_override, builtin_vars)
  File "/work/brave-browser/vendor/depot_tools/gclient_eval.py", line 357, in Exec
    value = _gclient_eval(vars_statement, filename)
  File "/work/brave-browser/vendor/depot_tools/gclient_eval.py", line 294, in _gclient_eval
    return _convert(node_or_string)
  File "/work/brave-browser/vendor/depot_tools/gclient_eval.py", line 252, in _convert
    for k, v in zip(node.keys, node.values))
  File "/work/brave-browser/vendor/depot_tools/gclient_eval.py", line 28, in __init__
    self.data = collections.OrderedDict(data)
  File "/usr/lib/python2.7/collections.py", line 69, in __init__
    self.__update(*args, **kwds)
  File "/usr/lib/python2.7/_abcoll.py", line 571, in update
    for key, value in other:
  File "/work/brave-browser/vendor/depot_tools/gclient_eval.py", line 252, in <genexpr>
    for k, v in zip(node.keys, node.values))
  File "/work/brave-browser/vendor/depot_tools/gclient_eval.py", line 266, in _convert
    filename, getattr(node, 'lineno', '<unknown>')))
ValueError: Var is the only allowed function (file '/work/brave-browser/src/DEPS', line 189)
null
null

```

## Expected result:

Expected "npm run init" to complete normally.

## Reproduces how often: 

Easily reproduced - Experimented on multiple Linux distributions

## Brave version (brave://version info)

Building from source from the "pagegraph" branch

## Other Additional Information:

The stack makes it seem like the DEPS file cannot include any other function than Var with the current version of depot_tool, which may not have been the case at the time of the release of the pagegraph branch.
I tried replacing Str() with Var(), however, the "npm run init" command reset the repository's content and stashes the changes.

Found one thread mentioning the issue, it can be found here: https://magpcss.org/ceforum/viewtopic.php?f=6&t=17901

**Comment by antonok-edm** [comment]
Fixed with https://github.com/brave/brave-core/commit/4b7e52ff9268e5af581fc03317ba4caaca824cee and https://github.com/brave/brave-browser/commit/38ed8b8116acc5199461135307ab219f128dd711, which adds a working Dockerfile.
