### ISSUE TITLE
Windows nightly builds fail on grd file generation

### ISSUE THREAD

**Issue by wknapik** [brave/brave-browser#19063]
[Slack thread](https://bravesoftware.slack.com/archives/C7VLGSR55/p1633794725296700)

* log0:
```
10:49:46  [28763/53617] ACTION //brave/components/brave_vpn/resources/panel:brave_vpn_panel_ui(//build/toolchain/win:win_clang_x86)
10:49:46  FAILED: gen/brave/web-ui-brave_vpn_panel/brave_vpn_panel.grd 
10:49:46  C:/jenkins/x86-nightly/src/brave/vendor/depot_tools/bootstrap-2@3_8_10_chromium_20_bin/python3/bin/python3.exe ../../brave/script/transpile-web-ui.py --output_path=gen/brave/web-ui-brave_vpn_panel --root_gen_dir=C:/jenkins/x86-nightly/src/out/Release_x86/gen --grd_name=brave_vpn_panel.grd --resource_name=brave_vpn_panel --depfile_path=C:/jenkins/x86-nightly/src/out/Release_x86/gen/brave/components/brave_vpn/resources/panel/brave_vpn_panel_ui.d --entry=brave_vpn_panel=C:/jenkins/x86-nightly/src/brave/components/brave_vpn/resources/panel/vpn_panel.tsx --production
10:49:46  Traceback (most recent call last):
10:49:46    File "../../brave/script/transpile-web-ui.py", line 118, in <module>
10:49:46      sys.exit(main())
10:49:46    File "../../brave/script/transpile-web-ui.py", line 31, in main
10:49:46      transpile_web_uis(args.production, webpack_gen_dir, root_gen_dir,
10:49:46    File "../../brave/script/transpile-web-ui.py", line 98, in transpile_web_uis
10:49:46      execute_stdout(args, env)
10:49:46    File "C:\jenkins\x86-nightly\src\brave\script\lib\util.py", line 212, in execute_stdout
10:49:46      execute(argv, env)
10:49:46    File "C:\jenkins\x86-nightly\src\brave\script\lib\util.py", line 192, in execute
10:49:46      print(stdout)
10:49:46    File "C:\jenkins\x86-nightly\src\brave\vendor\depot_tools\bootstrap-2@3_8_10_chromium_20_bin\python3\bin\lib\encodings\cp1252.py", line 19, in encode
10:49:46      return codecs.charmap_encode(input,self.errors,encoding_table)[0]
10:49:46  UnicodeEncodeError: 'charmap' codec can't encode character '\ufeff' in position 6541: character maps to <undefined>
```
* log1: https://ci.brave.com/job/test-brave-browser-build-windows-x64-mihai/22/execution/node/108/log/
* log2: https://ci.brave.com/job/test-brave-browser-build-windows-x86/305/execution/node/101/log/#24667736300f97e22-c981-4d1e-8d5b-6c0b7408d959
* log3: https://ci.brave.com/job/test-brave-browser-build-windows-x64/349/execution/node/103/log/#-124721069000f97e22-c981-4d1e-8d5b-6c0b7408d959

Changing `utf-8` to `utf-8-sig` in src/brave/script/lib/util.py does not appear to help.

**Comment by petemill** [comment]
What resolved this at the time?

**Comment by wknapik** [comment]
@petemill I don't recall us finding a fix. It just doesn't happen every build, looks like.

**Comment by petemill** [comment]
We think this current crop of related issues is caused by the `pinWindows` stage of the build pipeline, since the actual log shows that brave-browser's package.json has a bad char at position 0 (once the bad char is stripped out and python crashing is prevented):

```groovy
def pinWindows() {
    if (BRAVE_CORE_BRANCH) {
        ref = BRAVE_CORE_BRANCH.startsWith('v1.') ? 'tag' : 'branch'
        echo "Pinning brave-core locally to use ${ref} ${BRAVE_CORE_BRANCH}"
        powershell """
            \$ErrorActionPreference = "Stop"
            \$PSDefaultParameterValues['Out-File:Encoding'] = "utf8"
            jq "del(.config.projects[\\`"brave-core\\`"].branch) | del(.config.projects[\\`"brave-core\\`"].tag) | .config.projects[\\`"brave-core\\`"][\\`"${ref}\\`"]=\\`"${BRAVE_CORE_BRANCH}\\`"" package.json > package.json.new
            Move-Item -Force package.json.new package.json
        """
    }
}
```

So `jq` is probably putting a bad char (sometimes?)

**Comment by goodov** [comment]
> So `jq` is probably putting a bad char (sometimes?)

my bet is `powershell`.
