### ISSUE TITLE
New build fails on Mac Intel Monterey when using README.md: Failed: accessibility_tree_formatter_utils_mac.o

### ISSUE THREAD

**Issue by richorrichard** [brave/brave-browser#19395]
## Description 
New contributor trying to provision local dev environment, and trying to run Brave Browser build according to steps in README.md. Each of 4 times I've tried to build I've run into the same failure at the accessibility_tree_formatter_utils_mac.o step. 

## Steps to Reproduce
Follow steps to build project on MacOS

## Actual result:
Build failure with the following console output:
```console
/Users/<USER>/Sites/brave-browser/src
> autoninja -C /Users/<USER>/Sites/brave-browser/src/out/Component brave -k 1
ninja: Entering directory `/Users/<USER>/Sites/brave-browser/src/out/Component'
[2298/53920] ACTION //brave/build/rust:rust_lib_cargo_build(//build/toolchain/mac:clang_x64)
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
 Downloading crates ...
  Downloaded aho-corasick v0.7.18
  Downloaded hmac v0.7.1
  Downloaded regex v1.5.4
  Downloaded regex-syntax v0.6.25
  Downloaded serde_json v1.0.69
  Downloaded itertools v0.10.1
  Downloaded either v1.6.1
  Downloaded lazycell v1.3.0
  Downloaded rmp-serde v0.15.5
  Downloaded safemem v0.3.3
  Downloaded byte-tools v0.3.1
  Downloaded sha2 v0.8.2
  Downloaded futf v0.1.4
  Downloaded html5ever v0.25.1
  Downloaded libm v0.2.1
  Downloaded cssparser v0.27.2
  Downloaded serde v1.0.126
  Downloaded unicode-xid v0.2.2
  Downloaded lifeguard v0.6.1
  Downloaded mac v0.1.1
  Downloaded url v2.2.2
  Downloaded phf_codegen v0.8.0
  Downloaded string_cache_codegen v0.5.1
  Downloaded time-macros v0.2.3
  Downloaded typenum v1.13.0
  Downloaded utf-8 v0.7.6
  Downloaded time v0.3.4
  Downloaded siphasher v0.3.5
  Downloaded tendril v0.4.2
  Downloaded syn v1.0.72
  Downloaded phf_generator v0.8.0
  Downloaded crc32fast v1.2.1
  Downloaded convert_case v0.4.0
  Downloaded base64 v0.13.0
  Downloaded dtoa-short v0.3.3
  Downloaded digest v0.8.1
  Downloaded getrandom v0.1.16
  Downloaded markup5ever v0.10.1
  Downloaded generic-array v0.12.4
  Downloaded smallvec v1.6.1
  Downloaded rmp v0.8.10
  Downloaded ppv-lite86 v0.2.10
  Downloaded cssparser-macros v0.6.0
  Downloaded thiserror-impl v1.0.30
  Downloaded new_debug_unreachable v1.0.4
  Downloaded libc v0.2.107
  Downloaded lol_html v0.2.0
  Downloaded curve25519-dalek v1.2.6
  Downloaded selectors v0.22.0
  Downloaded seahash v3.0.7
  Downloaded encoding_rs v0.8.28
  Downloaded phf_macros v0.8.0
  Downloaded memchr v2.4.0
  Downloaded block-padding v0.1.5
  Downloaded flate2 v1.0.22
  Downloaded derive_more v0.99.13
  Downloaded adblock v0.4.1
  Downloaded autocfg v0.1.7
  Downloaded twoway v0.2.1
  Downloaded serde_derive v1.0.126
  Downloaded subtle v2.4.0
  Downloaded phf v0.8.0
  Downloaded string_cache v0.8.1
  Downloaded opaque-debug v0.2.3
  Downloaded thiserror v1.0.30
  Downloaded clear_on_drop v0.2.4
  Downloaded block-buffer v0.7.3
  Downloaded phf_shared v0.8.0
  Downloaded rand_pcg v0.2.1
  Downloaded proc-macro-hack v0.5.19
  Downloaded once_cell v1.8.0
  Downloaded dtoa v0.4.8
    Blocking waiting for file lock on package cache
   Compiling libc v0.2.107
   Compiling proc-macro2 v1.0.26
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.72
   Compiling autocfg v0.1.7
   Compiling rand_core v0.4.2
   Compiling getrandom v0.1.16
   Compiling cfg-if v1.0.0
   Compiling byteorder v1.4.3
   Compiling ppv-lite86 v0.2.10
   Compiling siphasher v0.3.5
   Compiling typenum v1.13.0
   Compiling memchr v2.4.0
   Compiling matches v0.1.8
   Compiling serde_derive v1.0.126
   Compiling autocfg v1.0.1
   Compiling serde v1.0.126
   Compiling proc-macro-hack v0.5.19
   Compiling itoa v0.4.7
   Compiling bitflags v1.2.1
   Compiling siphasher v0.2.3
   Compiling log v0.4.14
   Compiling cc v1.0.67
   Compiling precomputed-hash v0.1.1
   Compiling dtoa v0.4.8
   Compiling new_debug_unreachable v1.0.4
   Compiling tinyvec_macros v0.1.0
   Compiling maybe-uninit v2.0.0
   Compiling nodrop v0.1.14
   Compiling stable_deref_trait v1.2.0
   Compiling lazy_static v1.4.0
   Compiling mac v0.1.1
   Compiling libm v0.2.1
   Compiling utf-8 v0.7.6
   Compiling crc32fast v1.2.1
   Compiling ryu v1.0.5
   Compiling thin-slice v0.1.1
   Compiling percent-encoding v2.1.0
   Compiling safemem v0.3.3
   Compiling smallvec v1.6.1
   Compiling adler v1.0.2
   Compiling procedural-masquerade v0.1.6 (https://github.com/AndriusA/rust-cssparser?branch=glibc#ad2f4d3c)
   Compiling serde_json v1.0.69
   Compiling convert_case v0.4.0
   Compiling regex-syntax v0.6.25
   Compiling encoding_rs v0.8.28
   Compiling subtle v2.4.0
   Compiling subtle v1.0.0
   Compiling byte-tools v0.3.1
   Compiling lifeguard v0.6.1
   Compiling time-macros v0.2.3
   Compiling unchecked-index v0.2.2
   Compiling either v1.6.1
   Compiling lazycell v1.3.0
   Compiling cfg-if v0.1.10
   Compiling fake-simd v0.1.2
   Compiling seahash v3.0.7
   Compiling opaque-debug v0.2.3
   Compiling base64 v0.13.0
   Compiling once_cell v1.8.0
   Compiling rand_chacha v0.1.1
   Compiling rand_pcg v0.1.2
   Compiling rand v0.6.5
   Compiling rand_core v0.3.1
   Compiling phf_shared v0.8.0
   Compiling fxhash v0.2.1
   Compiling unicode-bidi v0.3.5
   Compiling miniz_oxide v0.4.4
   Compiling num-traits v0.2.14
   Compiling phf_shared v0.7.24
   Compiling tinyvec v1.2.0
   Compiling dtoa-short v0.3.3
   Compiling servo_arc v0.1.1
   Compiling futf v0.1.4
   Compiling form_urlencoded v1.0.1
   Compiling base64 v0.9.3
   Compiling clear_on_drop v0.2.4
   Compiling block-padding v0.1.5
   Compiling itertools v0.10.1
   Compiling time v0.3.4
   Compiling rand_isaac v0.1.1
   Compiling rand_hc v0.1.0
   Compiling rand_xorshift v0.1.1
   Compiling tendril v0.4.2
   Compiling phf v0.7.24
   Compiling unicode-normalization v0.1.17
   Compiling rand_jitter v0.1.4
   Compiling rand_os v0.1.3
   Compiling quote v1.0.9
   Compiling aho-corasick v0.7.18
   Compiling twoway v0.2.1
   Compiling generic-array v0.12.4
   Compiling smallvec v0.6.14
   Compiling rand_core v0.5.1
   Compiling idna v0.2.3
   Compiling digest v0.8.1
   Compiling crypto-mac v0.7.0
   Compiling block-buffer v0.7.3
   Compiling regex v1.5.4
   Compiling flate2 v1.0.22
   Compiling rmp v0.8.10
   Compiling rand_pcg v0.2.1
   Compiling rand_chacha v0.2.2
   Compiling url v2.2.2
   Compiling phf_generator v0.7.24
   Compiling hmac v0.7.1
   Compiling sha2 v0.8.2
   Compiling curve25519-dalek v1.2.6
   Compiling rand v0.7.3
   Compiling speedreader v0.1.0 (/Users/<USER>/Sites/brave-browser/src/brave/components/speedreader/rust/lib)
   Compiling phf_codegen v0.7.24
   Compiling selectors v0.21.0
   Compiling cssparser v0.27.2
   Compiling cssparser-macros v0.6.0
   Compiling cssparser v0.25.9 (https://github.com/AndriusA/rust-cssparser?branch=glibc#ad2f4d3c)
   Compiling html5ever v0.25.1
   Compiling derive_more v0.99.13
   Compiling thiserror-impl v1.0.30
   Compiling cssparser-macros v0.3.6 (https://github.com/AndriusA/rust-cssparser?branch=glibc#ad2f4d3c)
   Compiling phf_generator v0.8.0
   Compiling challenge-bypass-ristretto v1.0.0-pre.0
   Compiling phf_codegen v0.8.0
   Compiling string_cache_codegen v0.5.1
   Compiling phf_macros v0.8.0
   Compiling challenge-bypass-ristretto-ffi v1.0.0-pre.2 (/Users/<USER>/Sites/brave-browser/src/brave/vendor/challenge_bypass_ristretto_ffi)
   Compiling thiserror v1.0.30
   Compiling selectors v0.22.0
   Compiling markup5ever v0.10.1
   Compiling phf v0.8.0
   Compiling string_cache v0.8.1
   Compiling rmp-serde v0.13.7
   Compiling rmp-serde v0.15.5
   Compiling lol_html v0.2.0
   Compiling adblock v0.4.1
   Compiling kuchiki v0.8.1 (https://github.com/brave/kuchiki?branch=speedreader#589eadca)
   Compiling readability v0.1.4 (/Users/<USER>/Sites/brave-browser/src/brave/components/speedreader/rust/lib/src/readability)
   Compiling speedreader-ffi v0.1.0 (/Users/<USER>/Sites/brave-browser/src/brave/components/speedreader/rust/ffi)
   Compiling adblock-ffi v0.1.0 (/Users/<USER>/Sites/brave-browser/src/brave/components/adblock_rust_ffi)
   Compiling brave-rust v0.1.0 (/Users/<USER>/Sites/brave-browser/src/brave/build/rust)
    Finished release [optimized] target(s) in 6m 44s
[34269/53920] OBJCXX obj/content/browser/browser/accessibility_tree_formatter_utils_mac.o
FAILED: obj/content/browser/browser/accessibility_tree_formatter_utils_mac.o 
/Users/<USER>/Sites/brave-browser/src/brave/script/redirect-cc.py ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/content/browser/browser/accessibility_tree_formatter_utils_mac.o.d -DBRAVE_SERVICES_KEY=\"dummytoken\" -DUPDATER_DEV_ENDPOINT=\"\" -DUPDATER_PROD_ENDPOINT=\"\" -DDCHECK_ALWAYS_ON=1 -D_LIBCPP_HAS_NO_ALIGNED_ALLOCATION -DCR_XCODE_VERSION=1310 -DCR_CLANG_REVISION=\"llvmorg-14-init-5759-g02895eed-1\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DCOMPONENT_BUILD -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_ABI_VERSION=Cr -D_LIBCPP_ENABLE_NODISCARD -D_LIBCPP_DEBUG=0 -DCR_LIBCXX_REVISION=79a2e924d96e2fc1e4b937c42efd08898fa472d7 -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=0 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DCONTENT_IMPLEMENTATION -DUSE_V8_CONTEXT_SNAPSHOT -DV8_CONTEXT_SNAPSHOT_FILENAME=\"v8_context_snapshot.x86_64.bin\" -DV8_USE_EXTERNAL_STARTUP_DATA -DWEBP_EXTERN=extern -DUSE_EGL -D_WTL_NO_AUTOMATIC_NAMESPACE -DABSL_CONSUME_DLL -DBORINGSSL_SHARED_LIBRARY -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -DPROTOBUF_USE_DLLS -DSK_UNTIL_CRBUG_1187654_IS_FIXED -DSK_WIN_FONTMGR_NO_SIMULATIONS -DSK_CODEC_DECODES_PNG -DSK_CODEC_DECODES_WEBP -DSK_ENCODE_PNG -DSK_ENCODE_WEBP -DSK_ENABLE_SKSL -DSK_USER_CONFIG_HEADER=\"../../skia/config/SkUserConfig.h\" -DSK_GL -DSK_CODEC_DECODES_JPEG -DSK_ENCODE_JPEG -DSK_HAS_WUFFS_LIBRARY -DSKIA_DLL -DSKCMS_API=__attribute__\(\(visibility\(\"default\"\)\)\) -DSK_SUPPORT_GPU=1 -DSK_GPU_WORKAROUNDS_HEADER=\"gpu/config/gpu_driver_bug_workaround_autogen.h\" -DSK_BUILD_FOR_MAC -DSK_METAL -DWEBRTC_ENABLE_SYMBOL_EXPORT -DWEBRTC_ENABLE_AVX2 -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=0 -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DWEBRTC_MAC -DABSL_ALLOCATOR_NOTHROW=1 -DWEBRTC_USE_BUILTIN_ISAC_FIX=0 -DWEBRTC_USE_BUILTIN_ISAC_FLOAT=1 -DWEBRTC_HAVE_SCTP -DNO_MAIN_THREAD_WRAPPING -DLEVELDB_PLATFORM_CHROMIUM=1 -DLEVELDB_SHARED_LIBRARY -DI18N_ADDRESS_VALIDATION_DATA_URL=\"https://chromium-i18n.appspot.com/ssl-aggregate-address/\" -DUSING_V8_SHARED -DV8_COMPRESS_POINTERS -DV8_COMPRESS_POINTERS_IN_SHARED_CAGE -DV8_31BIT_SMIS_ON_64BIT_ARCH -DV8_VIRTUAL_MEMORY_CAGE -DV8_DEPRECATION_WARNINGS -DCPPGC_CAGED_HEAP -DANGLE_USE_ABSEIL -DSQLITE_OMIT_ANALYZE -DSQLITE_OMIT_AUTOINIT -DSQLITE_OMIT_AUTOMATIC_INDEX -DSQLITE_OMIT_AUTORESET -DSQLITE_OMIT_COMPILEOPTION_DIAGS -DSQLITE_OMIT_COMPLETE -DSQLITE_OMIT_EXPLAIN -DSQLITE_OMIT_GET_TABLE -DSQLITE_OMIT_INTROSPECTION_PRAGMAS -DSQLITE_DEFAULT_LOOKASIDE=0,0 -DSQLITE_OMIT_LOOKASIDE -DSQLITE_OMIT_TCL_VARIABLE -DSQLITE_OMIT_REINDEX -DSQLITE_OMIT_TRACE -DSQLITE_OMIT_UPSERT -DSQLITE_OMIT_WINDOWFUNC -DSQLITE_ENABLE_FTS3 -DSQLITE_DISABLE_FTS3_UNICODE -DSQLITE_DISABLE_FTS4_DEFERRED -DSQLITE_ENABLE_ICU -DSQLITE_SECURE_DELETE -DSQLITE_THREADSAFE=1 -DSQLITE_MAX_WORKER_THREADS=0 -DSQLITE_MAX_MMAP_SIZE=268435456 -DSQLITE_DEFAULT_FILE_PERMISSIONS=0600 -DSQLITE_DEFAULT_LOCKING_MODE=1 -DSQLITE_DEFAULT_MEMSTATUS=1 -DSQLITE_DEFAULT_PAGE_SIZE=4096 -DSQLITE_DEFAULT_PCACHE_INITSZ=0 -DSQLITE_LIKE_DOESNT_MATCH_BLOBS -DSQLITE_OMIT_DEPRECATED -DSQLITE_OMIT_PROGRESS_CALLBACK -DSQLITE_OMIT_SHARED_CACHE -DSQLITE_USE_ALLOCA -DSQLITE_OMIT_DECLTYPE -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_HAVE_ISNAN -DSQLITE_ENABLE_BATCH_ATOMIC_WRITE -DSQLITE_TEMP_STORE=3 -DSQLITE_ENABLE_LOCKING_STYLE=1 -DSQLITE_ENABLE_API_ARMOR -DUSE_CUPS -DFLAC__NO_DLL -I../../brave/chromium_src -I../.. -Igen -I../../buildtools/third_party/libc++ -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -I../../third_party/khronos -I../../gpu -I../../third_party/libwebp/src -Igen/third_party/dawn/src/include -I../../third_party/dawn/src/include -I../../third_party/libyuv/include -I../../third_party/jsoncpp/source/include -I../../third_party/wtl/include -I../../third_party/abseil-cpp -I../../third_party/boringssl/src/include -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/ced/src -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../third_party/skia -I../../third_party/wuffs/src/release/c -I../../third_party/mesa_headers -Igen/net/third_party/quiche/src -I../../net/third_party/quiche/overrides -I../../net/third_party/quiche/src/common/platform/default -I../../net/third_party/quiche/src -I../../third_party/webrtc_overrides -I../../third_party/webrtc -Igen/third_party/webrtc -I../../third_party/libwebm/source -I../../third_party/leveldatabase -I../../third_party/leveldatabase/src -I../../third_party/leveldatabase/src/include -Igen/third_party/metrics_proto -I../../third_party/zlib -I../../third_party/libaddressinput/src/cpp/include -I../../v8/include -Igen/v8/include -I../../third_party/angle/src/common/third_party/base -Igen/angle -I../../third_party/angle/include -I../../third_party/brotli/include -I../../third_party/distributed_point_functions -I../../third_party/distributed_point_functions/src -Igen/third_party/distributed_point_functions -I../../third_party/re2/src  -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing -fstack-protector -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -fcomplete-member-pointers -arch x86_64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -ffile-compilation-dir=. -no-canonical-prefixes -Wall -Werror -Wextra -Wimplicit-fallthrough -Wthread-safety -Wextra-semi -Wunguarded-availability -Wno-missing-field-initializers -Wno-unused-parameter -Wloop-analysis -Wno-unneeded-internal-declaration -Wenum-compare-conditional -Wno-psabi -Wno-ignored-pragma-optimize -Wno-builtin-assume-aligned-alignment -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-bitwise-instead-of-logical -O2 -fno-omit-frame-pointer -gdwarf-4 -g2 -gdwarf-aranges -Xclang -debug-info-kind=limited -isysroot ../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk -mmacosx-version-min=10.11.0 -ftrivial-auto-var-init=pattern -fvisibility=hidden -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang raw-ptr-template-as-trivial-member -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wshadow -Wexit-time-destructors -DPROTOBUF_ALLOW_DEPRECATED=1 -std=c++14 -fno-trigraphs -Wno-trigraphs -stdlib=libc++ -fobjc-call-cxx-cdtors -Wobjc-missing-property-synthesis -fno-exceptions -fno-rtti -nostdinc++ -isystem../../buildtools/third_party/libc++/trunk/include -isystem../../buildtools/third_party/libc++abi/trunk/include -fvisibility-inlines-hidden -include obj/content/browser/browser/precompile.h-mm -c ../../content/browser/accessibility/accessibility_tree_formatter_utils_mac.mm -o obj/content/browser/browser/accessibility_tree_formatter_utils_mac.o
../../content/browser/accessibility/accessibility_tree_formatter_utils_mac.mm:15:11: error: functions that differ only in their return type cannot be overloaded
CFTypeRef AXTextMarkerRangeCopyStartMarker(CFTypeRef);
~~~~~~~~~ ^
../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/HIServices.framework/Headers/AXUIElement.h:524:24: note: previous declaration is here
extern AXTextMarkerRef AXTextMarkerRangeCopyStartMarker (AXTextMarkerRangeRef textMarkerRange);
       ~~~~~~~~~~~~~~~ ^
../../content/browser/accessibility/accessibility_tree_formatter_utils_mac.mm:17:11: error: functions that differ only in their return type cannot be overloaded
CFTypeRef AXTextMarkerRangeCopyEndMarker(CFTypeRef);
~~~~~~~~~ ^
../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/HIServices.framework/Headers/AXUIElement.h:534:24: note: previous declaration is here
extern AXTextMarkerRef AXTextMarkerRangeCopyEndMarker (AXTextMarkerRangeRef textMarkerRange);
       ~~~~~~~~~~~~~~~ ^
../../content/browser/accessibility/accessibility_tree_formatter_utils_mac.mm:265:9: error: no matching function for call to 'AXTextMarkerRangeCopyStartMarker'
        AXTextMarkerRangeCopyStartMarker(static_cast<CFTypeRef>(target))));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/HIServices.framework/Headers/AXUIElement.h:524:24: note: candidate function not viable: cannot convert argument of incomplete type 'CFTypeRef' (aka 'const void *') to 'AXTextMarkerRangeRef _Nonnull' (aka 'const __AXTextMarkerRange *') for 1st argument
extern AXTextMarkerRef AXTextMarkerRangeCopyStartMarker (AXTextMarkerRangeRef textMarkerRange);
                       ^
../../content/browser/accessibility/accessibility_tree_formatter_utils_mac.mm:269:9: error: no matching function for call to 'AXTextMarkerRangeCopyEndMarker'
        AXTextMarkerRangeCopyEndMarker(static_cast<CFTypeRef>(target))));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/HIServices.framework/Headers/AXUIElement.h:534:24: note: candidate function not viable: cannot convert argument of incomplete type 'CFTypeRef' (aka 'const void *') to 'AXTextMarkerRangeRef _Nonnull' (aka 'const __AXTextMarkerRange *') for 1st argument
extern AXTextMarkerRef AXTextMarkerRangeCopyEndMarker (AXTextMarkerRangeRef textMarkerRange);
                       ^
4 errors generated.
[34274/53920] CXX obj/content/browser/browser/shared_worker_connector_impl.o
ninja: build stopped: subcommand failed.
null
null
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brave-core@1.34.7 build: `node ./build/commands/scripts/commands.js build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the brave-core@1.34.7 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/<USER>/.npm/_logs/2021-11-12T02_18_40_210Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brave@1.34.7 build: `npm --prefix src/brave run build --`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the brave@1.34.7 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/<USER>/.npm/_logs/2021-11-12T02_18_40_324Z-debug.log
```
and the following debug log:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/<USER>/.nvm/versions/node/v14.18.1/bin/node',
1 verbose cli   '/Users/<USER>/.nvm/versions/node/v14.18.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.18.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle brave@1.34.7~prebuild: brave@1.34.7
6 info lifecycle brave@1.34.7~build: brave@1.34.7
7 verbose lifecycle brave@1.34.7~build: unsafe-perm in lifecycle true
8 verbose lifecycle brave@1.34.7~build: PATH: /Users/<USER>/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/<USER>/Sites/brave-browser/node_modules/.bin:/Users/<USER>/.nvm/versions/node/v14.18.1/bin:/Users/<USER>/.mozbuild/arcanist/bin:/Users/<USER>/.mozbuild/moz-phab:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
9 verbose lifecycle brave@1.34.7~build: CWD: /Users/<USER>/Sites/brave-browser
10 silly lifecycle brave@1.34.7~build: Args: [ '-c', 'npm --prefix src/brave run build --' ]
11 silly lifecycle brave@1.34.7~build: Returned: code: 1  signal: null
12 info lifecycle brave@1.34.7~build: Failed to exec build script
13 verbose stack Error: brave@1.34.7 build: `npm --prefix src/brave run build --`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/<USER>/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/Users/<USER>/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
14 verbose pkgid brave@1.34.7
15 verbose cwd /Users/<USER>/Sites/brave-browser
16 verbose Darwin 21.1.0
17 verbose argv "/Users/<USER>/.nvm/versions/node/v14.18.1/bin/node" "/Users/<USER>/.nvm/versions/node/v14.18.1/bin/npm" "run" "build"
18 verbose node v14.18.1
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error brave@1.34.7 build: `npm --prefix src/brave run build --`
22 error Exit status 1
23 error Failed at the brave@1.34.7 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

## Expected result:
Complete Brave build

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Current master

## Version/Channel Information:
n/a

## Other Additional Information:

n/a

**Comment by IgorKhomenko** [comment]
Same with Big Sur 11.5.1

**Comment by IgorKhomenko** [comment]
Seems this is because of MacOSX12.0.sdk is used.
Probably using older MacOSX SDK may work

**Comment by IgorKhomenko** [comment]
In the end, it's related to Chromium

was addressed here https://chromium.googlesource.com/chromium/src.git/+/11a0c895953506d063c3dc8076a6bfd1f037eaf5

**Comment by richorrichard** [comment]
I spent the last week testing and rebuilding different versions between other work and as far as I can tell the chrome bugfix solved this issue. I'm going to close my own issue since I no longer can replicate.
