### ISSUE TITLE
Cannot build brave-extension on Windows

### ISSUE THREAD

**Issue by crazy-max** [brave/brave-browser#1945]
## Description 
On a VM on Windows 10 (same thing on a bare computer on Windows 10), I have tried to execute `npm run init` or `npm run sync -- --all` through git-bash but I've got this stack around chromedriver :

```
$ npm run sync -- --all

> brave@0.55.21 sync C:\brave-browser
> node ./scripts/sync.js "--all"

git -C C:\brave-browser\src fetch --all --tags
Fetching origin
remote: Counting objects: 16586, done
remote: Finding sources: 100% (35/35)
remote: Total 35 (delta 1), reused 24 (delta 1)
Unpacking objects: 100% (35/35), done.
From https://chromium.googlesource.com/chromium/src
   c4e604aa9276..18cb7920ca96  lkgr       -> origin/lkgr
   3915d213cd9e..338e2095e09b  master     -> origin/master
git -C C:\brave-browser\src clean -f
git -C C:\brave-browser\src reset --hard refs/tags/70.0.3538.77
git -C C:\brave-browser\src\brave fetch --all --tags
Fetching origin
git -C C:\brave-browser\src\brave clean -f
git -C C:\brave-browser\src\brave reset --hard origin/0.55.x
gclient sync --force --nohooks --with_branch_heads --with_tags
Syncing projects: 100% (112/112), done.
gclient runhooks
Hook 'vpython.bat -vpython-spec src/.vpython -vpython-tool install' took 349.35 secs
Hook ''C:\brave-browser\vendor\depot_tools\win_tools-2_7_6_bin\python\bin\python.exe' src/brave/script/bootstrap.py' took 26.60 secs
Hook ''C:\brave-browser\vendor\depot_tools\win_tools-2_7_6_bin\python\bin\python.exe' src/brave/script/apply-patches.py' took 100.88 secs
Running hooks: 100% (77/77) init
________ running 'C:\brave-browser\vendor\depot_tools\win_tools-2_7_6_bin\python\bin\python.exe src/brave/script/init-brave-extension.py' in 'C:\brave-browser'

> chromedriver@2.38.3 install C:\brave-browser\src\brave\vendor\brave-extension\node_modules\chromedriver
> node install.js

Downloading https://chromedriver.storage.googleapis.com/2.38/chromedriver_win32.zip
Saving to C:\Temp\chromedriver\chromedriver_win32.zip
Received 781K...
Received 1566K...
Received 2350K...
Received 3134K...
Received 3299K total.
Extracting zip contents
C:\brave-browser\src\brave\vendor\brave-extension\node_modules\kew\kew.js:189
  if (this._error || this._hasData) throw new Error("Unable to resolve or reject the same promise twice")
                                    ^

Error: Unable to resolve or reject the same promise twice
    at Promise.reject (C:\brave-browser\src\brave\vendor\brave-extension\node_modules\kew\kew.js:189:43)
    at Request.<anonymous> (C:\brave-browser\src\brave\vendor\brave-extension\node_modules\chromedriver\install.js:191:14)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\brave-browser\src\brave\vendor\brave-extension\node_modules\request\request.js:878:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-modules-resolve-imports@1.3.0 requires a peer of postcss@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-addons-test-utils@15.6.2 requires a peer of react-dom@^15.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chromedriver@2.38.3 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromedriver@2.38.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\tmp\npm-cache\_logs\2018-11-01T12_46_57_796Z-debug.log

Traceback (most recent call last):
  File "src/brave/script/init-brave-extension.py", line 39, in <module>
    sys.exit(main())
  File "src/brave/script/init-brave-extension.py", line 17, in main
    update_node_modules('.', args.verbose)
  File "src/brave/script/init-brave-extension.py", line 36, in update_node_modules
    execute_stdout(args, env)
  File "C:\brave-browser\src\brave\script\lib\util.py", line 182, in execute_stdout
    execute(argv, env)
  File "C:\brave-browser\src\brave\script\lib\util.py", line 170, in execute
    raise e
subprocess.CalledProcessError: Command '['npm.cmd', 'install']' returned non-zero exit status 1
Error: Command 'C:\\brave-browser\\vendor\\depot_tools\\win_tools-2_7_6_bin\\python\\bin\\python.exe src/brave/script/init-brave-extension.py' returned non-zero exit status 1 in C:\brave-browser
Hook ''C:\brave-browser\vendor\depot_tools\win_tools-2_7_6_bin\python\bin\python.exe' src/brave/script/init-brave-extension.py' took 24.18 secs
null
null
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brave@0.55.21 sync: `node ./scripts/sync.js "--all"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the brave@0.55.21 sync script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\tmp\npm-cache\_logs\2018-11-01T12_46_58_074Z-debug.log
```

## Steps to Reproduce

   1. exec `npm run init` or `npm run sync -- --all`
   2. Failed at chromedriver install part

## Reproduces how often

Easily reproduced

## Brave version (brave://version info)

brave-browser branch 0.55.x (0.55.21)

### Reproducible on current release:

Don't know

**Comment by crazy-max** [comment]
I have cloned the brave-extension project and try an npm install and the same error appears

**Comment by crazy-max** [comment]
Ok if I use a custom CDN url for chromedriver, it works :

`CHROMEDRIVER_CDNURL=https://npm.taobao.org/mirrors/chromedriver npm run sync -- --all`

cc: @bbondy @srirambv

**Comment by h2grover** [comment]
@all Is there any workaround for the same, getting the same error on windows.

**Comment by bsclifton** [comment]
Closing - Brave extension has mostly been removed at this point in favor of native code
