### ISSUE TITLE
Clear browsing data crashes or hangs Brave - application not responding

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#19467]
## Description 

`Clear browsing data` crashes or hangs Brave - application not responding

## Steps to reproduce 

   1. new install of `1.32.103`
   2. launch Brave
   3. tap on the 3 vertical dots menu item on the bottom toolbar
   4. tap `Settings`
   5. tap `Brave shields & privacy`
   6. tap on `Clear browsing data`

## Actual result 

`Brave keeps stopping` dialog comes up.

![Screenshot_20211115-163903](https://user-images.githubusercontent.com/387249/141875846-60791b57-e963-4de8-bcdb-1c9831faf4ad.png)

https://user-images.githubusercontent.com/387249/141875912-75df0c04-cb2e-4fbf-b3df-bd36c38b7b6e.mp4

## Expected result
Clear browsing data without hanging/crashing

## Issue reproduces how often 
100%

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): `arm`
   - Device type (Phone, Tablet, Phablet): Google Pixel XL
   - Android version: 9
   
## Brave version

`1.32.103`

**Comment by stephendonner** [comment]
Crash stack doesn't look all that helpful: https://share.backtrace.io/api/share/oIEuZ3A0x1sx2Y9Em2UiZmm1

**Comment by stephendonner** [comment]
Here's the crash stack I have from Android Studio:

```
    --------- beginning of crash
2021-11-15 16:56:21.598 29332-29332/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.brave.browser, PID: 29332
    java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.preference.Preference.O(java.lang.CharSequence)' on a null object reference
        at org.chromium.chrome.browser.browsing_data.ClearBrowsingDataFragmentBasic.J1(chromium-MonochromePublic.apk-stable-413210323:37)
        at xC1.S0(chromium-MonochromePublic.apk-stable-413210323:10)
        at org.chromium.chrome.browser.browsing_data.ClearBrowsingDataFragmentBasic.S0(chromium-MonochromePublic.apk-stable-413210323:1)
        at Ox0.e(chromium-MonochromePublic.apk-stable-413210323:9)
        at Ox0.k(chromium-MonochromePublic.apk-stable-413210323:18)
        at sx0.F(chromium-MonochromePublic.apk-stable-413210323:146)
        at sx0.f0(chromium-MonochromePublic.apk-stable-413210323:9)
        at sx0.E(chromium-MonochromePublic.apk-stable-413210323:5)
        at wn.i(chromium-MonochromePublic.apk-stable-413210323:3)
        at Mx0.B(chromium-MonochromePublic.apk-stable-413210323:34)
        at Mx0.s(chromium-MonochromePublic.apk-stable-413210323:2)
        at lJ.a(chromium-MonochromePublic.apk-stable-413210323:10)
        at DK1.c(chromium-MonochromePublic.apk-stable-413210323:24)
        at androidx.recyclerview.widget.LinearLayoutManager.i1(chromium-MonochromePublic.apk-stable-413210323:6)
        at androidx.recyclerview.widget.LinearLayoutManager.T0(chromium-MonochromePublic.apk-stable-413210323:12)
        at androidx.recyclerview.widget.LinearLayoutManager.l0(chromium-MonochromePublic.apk-stable-413210323:119)
        at androidx.recyclerview.widget.RecyclerView.t(chromium-MonochromePublic.apk-stable-413210323:14)
        at androidx.recyclerview.widget.RecyclerView.r(chromium-MonochromePublic.apk-stable-413210323:15)
        at androidx.recyclerview.widget.RecyclerView.onLayout(chromium-MonochromePublic.apk-stable-413210323:3)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at androidx.viewpager2.widget.ViewPager2.onLayout(chromium-MonochromePublic.apk-stable-413210323:8)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.b(chromium-MonochromePublic.apk-stable-413210323:22)
        at MK2.onLayoutChild(chromium-MonochromePublic.apk-stable-413210323:1)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(chromium-MonochromePublic.apk-stable-413210323:8)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
2021-11-15 16:56:21.599 29332-29332/? E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2792)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2319)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2021-11-15 16:56:21.806 29567-29567/? D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10260 <<<<<<
2021-11-15 16:56:21.966 29567-29567/? D/AndroidRuntime: Calling main entry org.chromium.components.crash.browser.CrashpadMain
2021-11-15 16:56:22.068 29567-29567/? W/chromium: [1115/165622.067559:WARNING:exception_snapshot_linux.cc(427)] Unhandled signal -1
2021-11-15 16:56:22.069 29567-29567/? E/chromium: [1115/165622.068960:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: Permission denied (13)
2021-11-15 16:56:22.093 29567-29567/? D/AndroidRuntime: Shutting down VM
2021-11-15 16:56:22.130 902-3978/? W/ActivityManager:   Force finishing activity com.brave.browser/org.chromium.chrome.browser.settings.BraveSettingsActivity
2021-11-15 16:56:22.139 29332-29332/? I/Process: Sending signal. PID: 29332 SIG: 9
```

**Comment by GeetaSarvadnya** [comment]
Verification passed on Android ARM - Galaxy Verion 11 running `Bravemonox64.apk_1.32.106`

**Comment by stephendonner** [comment]
Verified `PASSED` using my STR on Brave `1.32.106, Chromium 96.0.4664.45` on a Google Pixel XL running Android 9.
