### ISSUE TITLE
Brave News crashes after scrolling for some time

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20350]
## Description 

Brave News crashes after scrolling for some time

## Steps to Reproduce

   1. install `1.35.74`
   2. launch Brave
   3. load `brave://flags`
   4. enable Brave News
   5. restart
   6. open a new-tab page
   7. tap to `Show Brave News`
   8. scroll...until you crash

## Actual result:

Crash:

```    --------- beginning of crash
2022-01-05 15:37:15.248 13048-13048/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.brave.browser_beta, PID: 13048
    java.lang.ClassCastException: android.widget.LinearLayout$LayoutParams cannot be cast to HT1
        at GT1.P(Unknown Source:4)
        at androidx.recyclerview.widget.LinearLayoutManager.s1(chromium-MonochromePublic.apk-beta-413507423:17)
        at androidx.recyclerview.widget.LinearLayoutManager.o1(chromium-MonochromePublic.apk-beta-413507423:5)
        at androidx.recyclerview.widget.LinearLayoutManager.B0(chromium-MonochromePublic.apk-beta-413507423:2)
        at androidx.recyclerview.widget.RecyclerView.m0(chromium-MonochromePublic.apk-beta-413507423:7)
        at androidx.recyclerview.widget.c.run(chromium-MonochromePublic.apk-beta-413507423:24)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:693)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

https://user-images.githubusercontent.com/387249/148305529-c3902638-ca97-4376-88ad-2f372c9dd59f.mp4

Backtrace: https://share.backtrace.io/api/share/dx1MVD5WT8Z44Is1EtDOJD0

## Expected result:

No crash.

## Reproduces how often: 

100% after some time

## Brave version (brave://version info)

`1.35.74, Chromium 97.0.4692.71`

Google Pixel XL running Android 9.0

cc @alexsafe @kjozwiak @srirambv

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.36.75, Chromium 98.0.4758.66` on a `Google Pixel XL` (`arm64`) running `Android 9.0`.

Followed both my original steps to reproduce, as well as additional potential crash triggers. No crashes.

https://user-images.githubusercontent.com/387249/151448923-c8842c96-ea17-4712-8261-e3785cb8ae27.mp4
