### ISSUE TITLE
Crash adding new tab with Brave News, after closing others

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20689]
## Description 

Crash adding new tab with Brave News, after closing others

## Steps to reproduce 

   1. install `1.36.63`
   2. launch Brave
   3. tap through onboarding
   4. tap the 3-dots menu
   5. tap `Settings`
   6. tap `Appearance`
   7. tap to set `Enable Tab Groups` to `Off`
   8. tap on `RELAUNCH NOW`
   9. swipe down a bit
   10. tap to `Turn on Brave News`
   11. on the bottom toolbar, tap on the `[1]`
   12. tap `+`
   13. tap on `[2]`
   14. tap on its `X` to remove the 2nd tab
   15. tap to remove the 1st tab
   16. now tap on the bottom `+` button

## Actual result 

Boom 💣 

https://user-images.githubusercontent.com/387249/151062087-13c33005-9f35-49ee-8000-26929d25854b.mp4

```
    --------- beginning of crash
2022-01-25 13:20:40.643 28386-28386/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.brave.browser_nightly, PID: 28386
    java.lang.NullPointerException: Attempt to invoke interface method 'int org.chromium.chrome.browser.tab.Tab.getId()' on a null object reference
        at org.chromium.chrome.browser.ntp.BraveNewTabPageLayout.onAttachedToWindow(chromium-MonochromePublic.apk-canary-413606623:101)
        at android.view.View.dispatchAttachedToWindow(View.java:18347)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3397)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5077)
        at android.view.ViewGroup.addView(ViewGroup.java:4865)
        at android.view.ViewGroup.addView(ViewGroup.java:4837)
        at nf2.E(chromium-MonochromePublic.apk-canary-413606623:17)
        at rf2.E(chromium-MonochromePublic.apk-canary-413606623:13)
        at A01.J(chromium-MonochromePublic.apk-canary-413606623:5)
        at q01.J(chromium-MonochromePublic.apk-canary-413606623:4)
        at s01.J(chromium-MonochromePublic.apk-canary-413606623:1)
        at z01.y(chromium-MonochromePublic.apk-canary-413606623:18)
        at Ws2.y(chromium-MonochromePublic.apk-canary-413606623:3)
        at Zs2.i(chromium-MonochromePublic.apk-canary-413606623:23)
        at HC.i(chromium-MonochromePublic.apk-canary-413606623:117)
        at HC.j(chromium-MonochromePublic.apk-canary-413606623:2)
        at HC.k(chromium-MonochromePublic.apk-canary-413606623:4)
        at HC.f(chromium-MonochromePublic.apk-canary-413606623:6)
        at ep2.e(chromium-MonochromePublic.apk-canary-413606623:2)
        at gS.onClick(chromium-MonochromePublic.apk-canary-413606623:2)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

## Expected result

No crash

## Issue reproduces how often 

100%

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): `Google Pixel XL` phone
   - Android version: `9.0`.
   
## Brave version

`1.36.66, Chromium 98.0.4758.66`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @alexsafe @mattmcalister @srirambv

**Comment by stephendonner** [comment]
Found while testing https://github.com/brave/brave-browser/issues/20540.

**Comment by stephendonner** [comment]
Verified `PASSED` using 1.36.73, Chromium 98.0.4758.66` on a `Google Pixel XL` (`arm64`) running `Android 9.0`.

Followed my original steps to reproduce, as well as others known to cause a crash, and confirmed no crash.


https://user-images.githubusercontent.com/387249/151273095-21dec1fb-74b0-40ac-ba9b-38a6c89cf7d5.mp4
