### ISSUE TITLE
Browser crash when a publisher is tipped

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20696]
## Description 
Browser crash when a publisher is tipped

## Steps to reproduce 

   1. Enable staging rewards
   2. Claim Grant
   3. Tip a verified publisher, browser crash

## Actual result 

https://user-images.githubusercontent.com/17010094/151107551-719099e6-6263-4175-9627-5548d6bbdc16.mp4

## Expected result
No crash

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version:11
   
## Brave version
1.36.66

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

Crash Report https://share.backtrace.io/api/share/0PXJAmQLeMFcs7S8LtqAu3

**Comment by samartnik** [comment]
Crash srack:
```
 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4710)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4752)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1993)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7266)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
        at org.chromium.chrome.browser.app.BraveActivity.onActivityResult(BraveActivity.java:1125)
        at android.app.Activity.dispatchActivityResult(Activity.java:7809)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4703)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4752) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1993) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7266) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975) 
```

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.35.96 x64 build
- Verified no crash when sending a one time tip to a publisher
- Verified no crash when setting a recurring tip to a publisher

https://user-images.githubusercontent.com/17010094/151488951-aa730ad4-0a31-4322-9b3e-4e34511459ec.mp4


---------
Verification passed on Samsung Tab A with Android 10 running 1.35.96 x64 build
- Verified no crash when sending a one time tip to a publisher
- Verified no crash when setting a recurring tip to a publisher

https://user-images.githubusercontent.com/17010094/151488923-56ba69d8-3c71-4335-b9fb-fc65bc3ac018.mp4
