### ISSUE TITLE
Crash closing many stacked tabs with tab groups disabled

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20769]
## Description 

Crash closing many stacked tabs with tab groups disabled

## Steps to reproduce 

   1. install `1.37.5`
   2. launch Brave
   3. tap through onboarding
   4. tap on the 3-dots menu on the bottom toolbar
   5. tap `Settings`
   6. tap `Appearance`
   7. tap to set `Enable Tab Groups` to `Off`
   8. tap `RELAUNCH NOW`
   9.  swipe down
   10. tap to `Show Brave News`
   11. open a bunch of new-tab pages
   12. now, tap to close/undo/open new ones
   13. repeat steps 11-2 until you crash

## Actual result 

Crash:
```
2022-01-28 00:44:10.863 5331-5347/? I/ActivityManager: Start proc 26122:com.brave.browser_nightly:sandboxed_process13/u0i920 for service com.brave.browser_nightly/org.chromium.content.app.SandboxedProcessService13
2022-01-28 00:44:10.924 26122-26122/? W/boxed_process13: type=1400 audit(0.0:13703): avc: denied { getattr } for path="/data/data/com.brave.browser_nightly" dev="sda35" ino=396560 scontext=u:r:isolated_app:s0:c152,c259,c512,c768 tcontext=u:object_r:app_data_file:s0:c135,c257,c512,c768 tclass=dir permissive=0
2022-01-28 00:44:10.936 26122-26122/? I/cr_SplitCompatApp: Launched version=98.1.37.5 minSdkVersion=24 isBundle=false processName=com.brave.browser_nightly:sandboxed_process13 isIsolated=true
2022-01-28 00:44:15.524 5331-5347/? I/ActivityManager: Start proc 26152:com.brave.browser_nightly:sandboxed_process14/u0i921 for service com.brave.browser_nightly/org.chromium.content.app.SandboxedProcessService14
2022-01-28 00:44:15.607 26152-26152/? W/boxed_process14: type=1400 audit(0.0:13704): avc: denied { getattr } for path="/data/data/com.brave.browser_nightly" dev="sda35" ino=396560 scontext=u:r:isolated_app:s0:c153,c259,c512,c768 tcontext=u:object_r:app_data_file:s0:c135,c257,c512,c768 tclass=dir permissive=0
2022-01-28 00:44:15.642 26152-26152/? I/cr_SplitCompatApp: Launched version=98.1.37.5 minSdkVersion=24 isBundle=false processName=com.brave.browser_nightly:sandboxed_process14 isIsolated=true
2022-01-28 00:44:17.777 5331-5347/? I/ActivityManager: Start proc 26246:com.brave.browser_nightly:sandboxed_process15/u0i922 for service com.brave.browser_nightly/org.chromium.content.app.SandboxedProcessService15
2022-01-28 00:44:17.847 26246-26246/? W/boxed_process15: type=1400 audit(0.0:13705): avc: denied { getattr } for path="/data/data/com.brave.browser_nightly" dev="sda35" ino=396560 scontext=u:r:isolated_app:s0:c154,c259,c512,c768 tcontext=u:object_r:app_data_file:s0:c135,c257,c512,c768 tclass=dir permissive=0
2022-01-28 00:44:17.861 26246-26246/? I/cr_SplitCompatApp: Launched version=98.1.37.5 minSdkVersion=24 isBundle=false processName=com.brave.browser_nightly:sandboxed_process15 isIsolated=true
2022-01-28 00:44:19.027 5331-5347/? I/ActivityManager: Start proc 26283:com.brave.browser_nightly:sandboxed_process16/u0i923 for service com.brave.browser_nightly/org.chromium.content.app.SandboxedProcessService16
2022-01-28 00:44:19.157 26283-26283/? W/boxed_process16: type=1400 audit(0.0:13706): avc: denied { getattr } for path="/data/data/com.brave.browser_nightly" dev="sda35" ino=396560 scontext=u:r:isolated_app:s0:c155,c259,c512,c768 tcontext=u:object_r:app_data_file:s0:c135,c257,c512,c768 tclass=dir permissive=0
2022-01-28 00:44:19.179 26283-26283/? I/cr_SplitCompatApp: Launched version=98.1.37.5 minSdkVersion=24 isBundle=false processName=com.brave.browser_nightly:sandboxed_process16 isIsolated=true
2022-01-28 00:44:20.384 5331-5347/? I/ActivityManager: Start proc 26310:com.brave.browser_nightly:sandboxed_process17/u0i924 for service com.brave.browser_nightly/org.chromium.content.app.SandboxedProcessService17
2022-01-28 00:44:20.487 26310-26310/? W/boxed_process17: type=1400 audit(0.0:13707): avc: denied { getattr } for path="/data/data/com.brave.browser_nightly" dev="sda35" ino=396560 scontext=u:r:isolated_app:s0:c156,c259,c512,c768 tcontext=u:object_r:app_data_file:s0:c135,c257,c512,c768 tclass=dir permissive=0
2022-01-28 00:44:20.500 26310-26310/? I/cr_SplitCompatApp: Launched version=98.1.37.5 minSdkVersion=24 isBundle=false processName=com.brave.browser_nightly:sandboxed_process17 isIsolated=true
2022-01-28 00:44:21.653 5331-5347/? I/ActivityManager: Start proc 26340:com.brave.browser_nightly:sandboxed_process18/u0i925 for service com.brave.browser_nightly/org.chromium.content.app.SandboxedProcessService18
2022-01-28 00:44:21.741 26340-26340/? W/boxed_process18: type=1400 audit(0.0:13708): avc: denied { getattr } for path="/data/data/com.brave.browser_nightly" dev="sda35" ino=396560 scontext=u:r:isolated_app:s0:c157,c259,c512,c768 tcontext=u:object_r:app_data_file:s0:c135,c257,c512,c768 tclass=dir permissive=0
2022-01-28 00:44:21.753 26340-26340/? I/cr_SplitCompatApp: Launched version=98.1.37.5 minSdkVersion=24 isBundle=false processName=com.brave.browser_nightly:sandboxed_process18 isIsolated=true
2022-01-28 00:44:23.027 25638-25638/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.brave.browser_nightly, PID: 25638
    java.lang.ClassCastException: com.google.android.material.textview.MaterialTextView cannot be cast to android.widget.ScrollView
        at Zu0.m(chromium-MonochromePublic.apk-canary-413700523:10)
        at fg.run(chromium-MonochromePublic.apk-canary-413700523:3)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2022-01-28 00:44:24.179 5331-7481/? W/ActivityManager:   Force finishing activity com.brave.browser_nightly/com.google.android.apps.chrome.Main
2022-01-28 00:44:24.400 5331-5405/? W/InputDispatcher: channel 'e5a2956 com.brave.browser_nightly/com.google.android.apps.chrome.Main (server)' ~ Consumer closed input channel or an error occurred.  events=0xd
2022-01-28 00:44:24.400 5331-5405/? E/InputDispatcher: channel 'e5a2956 com.brave.browser_nightly/com.google.android.apps.chrome.Main (server)' ~ Channel is unrecoverably broken and will be disposed!
2022-01-28 00:44:24.403 5331-5652/? I/WindowManager: WIN DEATH: Window{e5a2956 u0 com.brave.browser_nightly/com.google.android.apps.chrome.Main}
2022-01-28 00:44:24.403 5331-5652/? W/InputDispatcher: Attempted to unregister already unregistered input channel 'e5a2956 com.brave.browser_nightly/com.google.android.apps.chrome.Main (server)'
2022-01-28 00:44:24.403 5331-9294/? I/ActivityManager: Process com.brave.browser_nightly (pid 25638) has died: vis  +99TOP 
```

## Expected result

No crash

## Issue reproduces how often 

100% with time & patience

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): `Google Pixel XL` phone
   - Android version: `9.0`
   
## Brave version

1.37.5, Chromium 98.0.4758.74`

cc @alexsafe @srirambv @kjozwiak

**Comment by stephendonner** [comment]
https://user-images.githubusercontent.com/387249/151518261-6324bf29-fe48-43ef-9f01-2ec68b5d6fdd.mp4

**Comment by stephendonner** [comment]
Not reopening, yet, but I still see a crash using the same steps.  It's being discussed over in https://bravesoftware.slack.com/archives/CU56GUJ1H/p1643759025432129, whether to file a new issue or what.

**Comment by kjozwiak** [comment]
Will require `1.36.99` or higher.

**Comment by stephendonner** [comment]
Verified `PASSED` using `1.36.99, Chromium 98.0.4758.102` on a `Google Pixel XL` (`arm64`) running `Android 9.0`.

See verification notes over in https://github.com/brave/brave-browser/issues/20850#issuecomment-1045412764 (same steps, slightly different stack trace, but covered all the same).
