### ISSUE TITLE
Send to your devices crashes the application in latest Beta 

### ISSUE THREAD

**Issue by gbil** [brave/brave-browser#20822]
## Description 
Trying to send a page to other Sync'd devices crashed the app 

## Steps to reproduce 

   1. Open a page
   2. From the Menu click on the share icon
   3. click on "Send to your devices"

## Actual result 
App crashes 

## Expected result
Page to be shared or some message

## Issue reproduces how often 
Every time

## Version/Channel Information:
Beta

- Can you reproduce this issue with the current Play Store version?  haven't tried as it needs to setup sync for this 
- Can you reproduce this issue with the current Play Store Beta version?  YES
- Can you reproduce this issue with the current Play Store Nightly version?  haven't tried as it needs to setup sync for this 

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone&Table
   - Android version:12 and 11
   
## Brave version
Brave: 1.36.80 Chromium: 98.0.4758.74 (Official Build) beta (64-bit)
Revision: d0fe1ec4df090cd3eb02b591228505e12ea476e9-refs/branch-heads/4758@{#935}
OS: Android 12; Build/SP1A.2108212.016

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by MBR-0001** [comment]
Here's a stack trace
```
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: com.brave.browser_beta, PID: 22107
E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.chromium.components.signin.base.CoreAccountInfo.getEmail()' on a null object reference
E AndroidRuntime:        at Mj0.<init>(chromium-MonochromePublic6432.aab-beta-413608024:48)
E AndroidRuntime:        at HW.onResult(chromium-MonochromePublic6432.aab-beta-413608024:9)
E AndroidRuntime:        at TW.onClick(chromium-MonochromePublic6432.aab-beta-413608024:14)
E AndroidRuntime:        at android.view.View.performClick(View.java:7448)
E AndroidRuntime:        at android.view.View.performClickInternal(View.java:7425)
E AndroidRuntime:        at android.view.View.access$3600(View.java:810)
E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:28305)
E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7664)
E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
