### ISSUE TITLE
Changing network throws error about decimal value and causes the page to become blank

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20888]
## Description 

Changing network throws error about decimal value and causes the page to become blank

## Steps to Reproduce

   1. Install 1.36.83 build
   2. Switch to swap and enter an input value
   3. Wait for the conversion value to update
   4. Select network dropdown and select `Ropsten`
   5. Page goes blank, console throws error 

## Actual result:

https://user-images.githubusercontent.com/17010094/152516997-f84d24e8-f3bc-4f76-b0e0-88347efa866f.mov

<details>
<summary>Full log from console</summary>
<br/>

```
brave_wallet_page.bundle.js:5389 TypeError: Cannot read properties of undefined (reading 'decimals')
    at brave_wallet_page.bundle.js:2389:4013
    at Object.fa [as useMemo] (brave_wallet_page.bundle.js:5389:61567)
    at Object.t.useMemo (brave_wallet_page.bundle.js:5381:5984)
    at c (brave_wallet_page.bundle.js:2389:3932)
    at brave_wallet_page.bundle.js:6391:13107
    at Jo (brave_wallet_page.bundle.js:5389:57930)
    at Na (brave_wallet_page.bundle.js:5389:66791)
    at gA (brave_wallet_page.bundle.js:5389:105388)
    at ls (brave_wallet_page.bundle.js:5389:96717)
    at As (brave_wallet_page.bundle.js:5389:96642)
    at $A (brave_wallet_page.bundle.js:5389:93672)
    at brave_wallet_page.bundle.js:5389:45314
    at t.unstable_runWithPriority (brave_wallet_page.bundle.js:5397:3844)
    at Li (brave_wallet_page.bundle.js:5389:45023)
    at zi (brave_wallet_page.bundle.js:5389:45259)
    at Hi (brave_wallet_page.bundle.js:5389:45194)
eA @ brave_wallet_page.bundle.js:5389
r.callback @ brave_wallet_page.bundle.js:5389
uo @ brave_wallet_page.bundle.js:5389
oA @ brave_wallet_page.bundle.js:5389
fs @ brave_wallet_page.bundle.js:5389
t.unstable_runWithPriority @ brave_wallet_page.bundle.js:5397
Li @ brave_wallet_page.bundle.js:5389
hs @ brave_wallet_page.bundle.js:5389
$A @ brave_wallet_page.bundle.js:5389
(anonymous) @ brave_wallet_page.bundle.js:5389
t.unstable_runWithPriority @ brave_wallet_page.bundle.js:5397
Li @ brave_wallet_page.bundle.js:5389
zi @ brave_wallet_page.bundle.js:5389
Hi @ brave_wallet_page.bundle.js:5389
es @ brave_wallet_page.bundle.js:5389
notify @ brave_wallet_page.bundle.js:5618
t.notifyNestedSubs @ brave_wallet_page.bundle.js:5618
t.handleChangeWrapper @ brave_wallet_page.bundle.js:5618
f @ brave_wallet_page.bundle.js:5618
(anonymous) @ brave_wallet_page.bundle.js:5618
(anonymous) @ brave_wallet_page.bundle.js:5618
(anonymous) @ brave_wallet_page.bundle.js:5618
dispatch @ brave_wallet_page.bundle.js:5618
(anonymous) @ brave_wallet_page.bundle.js:5618
await in (anonymous) (async)
(anonymous) @ brave_wallet_page.bundle.js:5618
(anonymous) @ brave_wallet_page.bundle.js:5618
dispatch @ brave_wallet_page.bundle.js:5618
ft @ brave_wallet_page.bundle.js:5618
await in ft (async)
(anonymous) @ brave_wallet_page.bundle.js:5618
await in (anonymous) (async)
(anonymous) @ brave_wallet_page.bundle.js:5618
(anonymous) @ brave_wallet_page.bundle.js:5618
(anonymous) @ brave_wallet_page.bundle.js:5618
We @ brave_wallet_page.bundle.js:6391
(anonymous) @ brave_wallet_page.bundle.js:6391
A @ brave_wallet_page.bundle.js:5389
f @ brave_wallet_page.bundle.js:5389
(anonymous) @ brave_wallet_page.bundle.js:5389
m @ brave_wallet_page.bundle.js:5389
at @ brave_wallet_page.bundle.js:5389
it @ brave_wallet_page.bundle.js:5389
At @ brave_wallet_page.bundle.js:5389
ft @ brave_wallet_page.bundle.js:5389
P @ brave_wallet_page.bundle.js:5389
G @ brave_wallet_page.bundle.js:5389
_t @ brave_wallet_page.bundle.js:5389
Xt @ brave_wallet_page.bundle.js:5389
t.unstable_runWithPriority @ brave_wallet_page.bundle.js:5397
Li @ brave_wallet_page.bundle.js:5389
O @ brave_wallet_page.bundle.js:5389
Kt @ brave_wallet_page.bundle.js:5389
brave_wallet_page.bundle.js:2389 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'decimals')
    at brave_wallet_page.bundle.js:2389:4013
    at Object.fa [as useMemo] (brave_wallet_page.bundle.js:5389:61567)
    at Object.t.useMemo (brave_wallet_page.bundle.js:5381:5984)
    at c (brave_wallet_page.bundle.js:2389:3932)
    at brave_wallet_page.bundle.js:6391:13107
    at Jo (brave_wallet_page.bundle.js:5389:57930)
    at Na (brave_wallet_page.bundle.js:5389:66791)
    at gA (brave_wallet_page.bundle.js:5389:105388)
    at ls (brave_wallet_page.bundle.js:5389:96717)
    at As (brave_wallet_page.bundle.js:5389:96642)
    at $A (brave_wallet_page.bundle.js:5389:93672)
    at brave_wallet_page.bundle.js:5389:45314
    at t.unstable_runWithPriority (brave_wallet_page.bundle.js:5397:3844)
    at Li (brave_wallet_page.bundle.js:5389:45023)
    at zi (brave_wallet_page.bundle.js:5389:45259)
    at Hi (brave_wallet_page.bundle.js:5389:45194)
```
</details>

## Expected result:
No error or page blank

## Reproduces how often: 

Easy on Swap screen but a little hard on Send screen but still happens

## Brave version (brave://version info)

Brave | 1.36.83 Chromium: 98.0.4758.87 (Official Build) beta (arm64)
-- | --
Revision | `e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Couldn't repro

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @onyb

**Comment by onyb** [comment]
I believe I fixed it as part of https://github.com/brave/brave-core/pull/12403. Can you please check again? @srirambv

**Comment by srirambv** [comment]
Yes this looks fixed now. Verified on 

Brave | 1.37.77 Chromium: 99.0.4844.45 (Official Build) beta (64-bit)
-- | --
Revision | `edbc0b8343c7b10fddb0e1b4efb280b0f6e38cab-refs/branch-heads/4844@{#788}`
OS | Linux

Closing the issue as invalid
