### ISSUE TITLE
Brave build error

### ISSUE THREAD

**Issue by kjkpoi** [brave/brave-browser#20912]
## Description 
I followed the Brave Page Graph build on https://github.com/brave/brave-browser/wiki/PageGraph.
I got error messages belows when I execute 'npm run init'.

> brave@1.12.48 init
> node ./scripts/sync.js --init

node:internal/validators:119
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.join (node:path:1172:7)
    at new Config (/home/kjkpoi/PageGraph/brave-browser/lib/config.js:45:28)
    at Object.<anonymous> (/home/kjkpoi/PageGraph/brave-browser/lib/config.js:646:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'ERR_INVALID_ARG_TYPE'
}

## Steps to Reproduce

I followed the link https://github.com/brave/brave-browser/wiki/PageGraph

   1. git clone -b page-graph https://github.com/brave/brave-browser
   2. npm install
   3. npm run init
'npm run init' occurs error

## Actual result:
> brave@1.12.48 init
> node ./scripts/sync.js --init

node:internal/validators:119
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.join (node:path:1172:7)
    at new Config (/home/kjkpoi/PageGraph/brave-browser/lib/config.js:45:28)
    at Object.<anonymous> (/home/kjkpoi/PageGraph/brave-browser/lib/config.js:646:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'ERR_INVALID_ARG_TYPE'
}

## Expected result:
Build success

## Reproduces how often: 
Every time

**Comment by pooneh-nb** [comment]
@kjkpoi How did you solve this?
