### ISSUE TITLE
Browser crash when trying to close tabs with Brave News enabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#21110]
## Description 
Browser crash when trying to close tabs with News enabled

## Steps to reproduce 

   1. Install 1.36.94 x64 beta build
   2. Enable News via flag
   3. Open a bunch of tabs and wait for the news feed to load
   4. Start closing the tabs one by one, browser crashes

## Actual result 
Browser crash when trying to close tabs with Brave News enabled

```
2022-02-15 11:26:58.466 22005-22005/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.brave.browser_beta, PID: 22005
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
        at Yu0.m(chromium-MonochromePublic.apk-beta-413609423:32)
        at fg.run(chromium-MonochromePublic.apk-beta-413609423:3)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8107)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

## Expected result
No crash

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Tablet - Samsung Tab A
   - Android version: 10
   
## Brave version
1.36.94 x64 Beta Build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @alexsafe @mattmcalister

**Comment by timchilds** [comment]
Closing this one out. Per 03/30 Android triage meeting, this is no longer reproducible and likely fixed by ticket #20689.
