### ISSUE TITLE
Relaunching the app after changing the language in settings results in the app not loading successfully

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#21417]
## Description 
Relaunching the app after changing the language settings results in the app not loading successfully

## Steps to reproduce 

   1. Navigate to settings menu > languages
   2. Change language under 'Brave's Language
   3. Restart app from the prompt bar

## Actual result 
Brave app doesn't load successfully

https://user-images.githubusercontent.com/17885425/156439888-7853b883-f44c-4a9d-8c55-278bb456eea2.mp4

## Expected result
Brave restart succesfully

## Issue reproduces how often 
Intermittent 75% repro rate

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Mobile, Samsung GS 21
   - Android version: 12
   
## Brave version
`1.36.108 Chromium 99.0.4844.51`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Thanks for symbolising @SergeyZhukovsky 👍 Looks like the above crash that @Uni-verse and myself experienced will be addressed by uplifting https://github.com/brave/brave-core/pull/12455 into `1.37.x`  & `1.36.x` via https://github.com/brave/brave-core/pull/12457 and https://github.com/brave/brave-core/pull/12458.

```
2022-03-02 17:03:30.776 9204-9226/com.brave.browser_default E/AndroidRuntime: FATAL EXCEPTION: ActivityPreload
    Process: com.brave.browser_default, PID: 9204
    java.lang.ExceptionInInitializerError
        at org.chromium.base.ContextUtils$Holder.access$100(ContextUtils.java:35)
        at org.chromium.base.ContextUtils.getAppSharedPreferences(ContextUtils.java:94)
        at org.chromium.chrome.browser.preferences.SharedPreferencesManager.readInt(SharedPreferencesManager.java:248)
        at org.chromium.chrome.browser.flags.CachedFlagsSafeMode.shouldEnterSafeMode(CachedFlagsSafeMode.java:165)
        at org.chromium.chrome.browser.flags.CachedFlagsSafeMode.onFlagChecked(CachedFlagsSafeMode.java:76)
        at org.chromium.chrome.browser.flags.CachedFeatureFlags.getConsistentBooleanValue(CachedFeatureFlags.java:369)
        at org.chromium.chrome.browser.flags.BooleanCachedFieldTrialParameter.getValue(BooleanCachedFieldTrialParameter.java:32)
        at org.chromium.chrome.browser.tasks.tab_management.BraveTabUiFeatureUtilities.maybeOverrideEnableTabGroupAutoCreationPreference(BraveTabUiFeatureUtilities.java:19)
        at org.chromium.chrome.browser.app.BraveActivity.<init>(BraveActivity.java:237)
        at org.chromium.chrome.browser.ChromeTabbedActivity.<init>(ChromeTabbedActivity.java:451)
        at org.chromium.chrome.browser.ChromeTabbedActivity$Preload.<init>(ChromeTabbedActivity.java:408)
        at java.lang.Class.newInstance(Native Method)
        at org.chromium.chrome.browser.base.SplitChromeApplication$1.lambda$runImmediatelyInBackgroundThread$0(SplitChromeApplication.java:114)
        at org.chromium.chrome.browser.base.SplitChromeApplication$1$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
        at android.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceManager.java:555)
        at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:545)
        at org.chromium.base.ContextUtils.fetchAppSharedPreferences(ContextUtils.java:82)
        at org.chromium.base.ContextUtils.access$000(ContextUtils.java:28)
        at org.chromium.base.ContextUtils$Holder.<clinit>(ContextUtils.java:37)
        at org.chromium.base.ContextUtils$Holder.access$100(ContextUtils.java:35) 
        at org.chromium.base.ContextUtils.getAppSharedPreferences(ContextUtils.java:94) 
        at org.chromium.chrome.browser.preferences.SharedPreferencesManager.readInt(SharedPreferencesManager.java:248) 
        at org.chromium.chrome.browser.flags.CachedFlagsSafeMode.shouldEnterSafeMode(CachedFlagsSafeMode.java:165) 
        at org.chromium.chrome.browser.flags.CachedFlagsSafeMode.onFlagChecked(CachedFlagsSafeMode.java:76) 
        at org.chromium.chrome.browser.flags.CachedFeatureFlags.getConsistentBooleanValue(CachedFeatureFlags.java:369) 
        at org.chromium.chrome.browser.flags.BooleanCachedFieldTrialParameter.getValue(BooleanCachedFieldTrialParameter.java:32) 
        at org.chromium.chrome.browser.tasks.tab_management.BraveTabUiFeatureUtilities.maybeOverrideEnableTabGroupAutoCreationPreference(BraveTabUiFeatureUtilities.java:19) 
        at org.chromium.chrome.browser.app.BraveActivity.<init>(BraveActivity.java:237) 
        at org.chromium.chrome.browser.ChromeTabbedActivity.<init>(ChromeTabbedActivity.java:451) 
        at org.chromium.chrome.browser.ChromeTabbedActivity$Preload.<init>(ChromeTabbedActivity.java:408) 
        at java.lang.Class.newInstance(Native Method) 
        at org.chromium.chrome.browser.base.SplitChromeApplication$1.lambda$runImmediatelyInBackgroundThread$0(SplitChromeApplication.java:114) 
        at org.chromium.chrome.browser.base.SplitChromeApplication$1$$ExternalSyntheticLambda0.run(Unknown Source:4) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
2022-03-02 17:03:30.858 9204-9204/com.brave.browser_default I/browser_defaul: Rejecting re-init on previously-failed class java.lang.Class<org.chromium.base.ContextUtils$Holder>: java.lang.ExceptionInInitializerError: 
    (Throwable with no stack trace)
2022-03-02 17:03:30.858 9204-9204/com.brave.browser_default D/AndroidRuntime: Shutting down VM
2022-03-02 17:03:30.858 9204-9204/com.brave.browser_default I/Process: Sending signal. PID: 9204 SIG: 9
```

**Comment by kjozwiak** [comment]
Closing as this will be fixed by https://github.com/brave/brave-core/pull/12455.

**Comment by Uni-verse** [comment]
Per https://github.com/brave/brave-browser/issues/21417#issuecomment-1057452277

Verified does not repro on 1.38.17 Chromium 99.0.4844.51.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.36.110 x64 build
- Verified steps from issue description
- Verified changing language and selecting `Restart Brave` doesn't crash the browser

https://user-images.githubusercontent.com/17010094/156968853-81ac741c-657b-4f7b-84e9-880d8a8da2d8.mp4

@Uni-verse @kjozwiak  would be good if either of you gave test as well as I wasn't able repro the issue on older builds.
