### ISSUE TITLE
Consistent crashing - Bus Error or Seg Fault

### ISSUE THREAD

**Issue by improvethings** [brave/brave-browser#2151]
## Description 

Consistent crashing - Bus Error or Seg Fault

## Steps to Reproduce

   1. I'm not sure yet how to reproduce. All I can say is it's happening several times a day.

## Actual result:

[31974:31997:1114/202208.883920:ERROR:power_save_blocker_x11.cc(330)] No response to Inhibit() request!
[31974:31974:1114/202210.109857:ERROR:latency_info.cc(144)] Surface::TakeLatencyInfoFromFrame, LatencyInfo vector size 101 is too big.
[31974:31974:1114/202210.690377:ERROR:latency_info.cc(144)] Surface::TakeLatencyInfoFromFrame, LatencyInfo vector size 101 is too big.
[31974:31997:1114/202210.779148:ERROR:object_proxy.cc(616)] Failed to call method: org.gnome.SessionManager.Uninhibit: object_path= /org/gnome/SessionManager: org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
[31974:31997:1114/202210.779177:ERROR:power_save_blocker_x11.cc(403)] No response to Uninhibit() request!
[31974:31997:1114/202210.786031:ERROR:object_proxy.cc(616)] Failed to call method: org.gnome.SessionManager.Inhibit: object_path= /org/gnome/SessionManager: org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
[31974:31997:1114/202210.786269:ERROR:power_save_blocker_x11.cc(330)] No response to Inhibit() request!
[31974:31997:1114/202212.670678:ERROR:object_proxy.cc(616)] Failed to call method: org.gnome.SessionManager.Uninhibit: object_path= /org/gnome/SessionManager: org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
[31974:31997:1114/202212.670734:ERROR:power_save_blocker_x11.cc(403)] No response to Uninhibit() request!
[31974:31997:1114/202212.681075:ERROR:object_proxy.cc(616)] Failed to call method: org.gnome.SessionManager.Inhibit: object_path= /org/gnome/SessionManager: org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
[31974:31997:1114/202212.681130:ERROR:power_save_blocker_x11.cc(330)] No response to Inhibit() request!
[31974:31997:1114/202214.595274:ERROR:object_proxy.cc(616)] Failed to call method: org.gnome.SessionManager.Uninhibit: object_path= /org/gnome/SessionManager: org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
[31974:31997:1114/202214.595317:ERROR:power_save_blocker_x11.cc(403)] No response to Uninhibit() request!
[31974:31997:1114/202214.680705:ERROR:object_proxy.cc(616)] Failed to call method: org.gnome.SessionManager.Inhibit: object_path= /org/gnome/SessionManager: org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
[31974:31997:1114/202214.681540:ERROR:power_save_blocker_x11.cc(330)] No response to Inhibit() request!

Crash dump id: 3bee497cbe329d03
Window crashed. Reloading...
Window crashed. Reloading...

Crash dump id: 9216576955061ae8
Window crashed. Reloading...
[31974:31974:1114/202217.485158:ERROR:media_internals.cc(102)] Cannot get RenderProcessHost
[31974:31997:1114/202217.486085:ERROR:object_proxy.cc(616)] Failed to call method: org.gnome.SessionManager.Uninhibit: object_path= /org/gnome/SessionManager: org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
[31974:31997:1114/202217.486132:ERROR:power_save_blocker_x11.cc(403)] No response to Uninhibit() request!
[31974:31997:1114/202217.499119:ERROR:object_proxy.cc(616)] Failed to call method: org.gnome.SessionManager.Uninhibit: object_path= /org/gnome/SessionManager: org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
[31974:31997:1114/202217.499188:ERROR:power_save_blocker_x11.cc(403)] No response to Uninhibit() request!
[31974:31997:1114/202217.500713:ERROR:object_proxy.cc(616)] Failed to call method: org.gnome.SessionManager.Uninhibit: object_path= /org/gnome/SessionManager: org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
[31974:31997:1114/202217.500835:ERROR:power_save_blocker_x11.cc(403)] No response to Uninhibit() request!
[31974:31997:1114/202217.501329:ERROR:object_proxy.cc(616)] Failed to call method: org.gnome.SessionManager.Uninhibit: object_path= /org/gnome/SessionManager: org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
[31974:31997:1114/202217.501419:ERROR:power_save_blocker_x11.cc(403)] No response to Uninhibit() request!

Crash dump id: 534098d33f953a22

[1]+  Segmentation fault      brave

## Expected result:

Not to unexpectedly crash while using it

## Reproduces how often: 

No steps to reproduce. Happens several times a day. Also seems to happen if I leave it open over night, if that helps.

## Brave version (brave://version info)

bug reporting software says to do brave://version info, that doesn't work. about:brave does, for me.

Brave | 0.25.2
-- | --
V8 | 6.9.427.23
rev | 8ea2a9c
Muon | 8.1.8
OS Release | 4.14.74-1.pvops.qubes.x86_64
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 69.0.3497.100

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

This is on QubesOS R4.0, in a Debian 9 AppVM.

I'm getting thosuands of these logs when running it from the command line: 
ERROR:power_save_blocker_x11.cc(330)] No response to Inhibit() request!
ERROR:latency_info.cc(144)] Surface::TakeLatencyInfoFromFrame, LatencyInfo vector size 102 is too big.
ERROR:object_proxy.cc(616)] Failed to call method: org.gnome.SessionManager.Uninhibit: object_path= /org/gnome/SessionManager: org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

When I restart it after a crash, I get this: 
$ brave &
[1] 5243
user@machine:~$ Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[5271:5271:1114/202227.911108:ERROR:sandbox_linux.cc(379)] InitializeSandbox() called with multiple threads in process gpu-process.
Crash reporting enabled
[5243:5243:1114/202228.980632:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.
(node:5243) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 window-renderer-ready listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 window-renderer-ready listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:262:19)
    at BrowserWindow.addListener (events.js:279:10)
    at BrowserWindow.once (events.js:308:8)
    at Immediate.setImmediate (/usr/lib/brave/resources/app.asar/app/browser/tabs.js:1139:15)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
(node:5243) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 window-renderer-ready listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 window-renderer-ready listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:262:19)
    at BrowserWindow.addListener (events.js:279:10)
    at BrowserWindow.once (events.js:308:8)
    at Immediate.setImmediate (/usr/lib/brave/resources/app.asar/app/browser/tabs.js:1139:15)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
[1:1:1114/202248.936521:ERROR:budget_service.cc(145)] Unable to connect to the Mojo BudgetService.

**Comment by srirambv** [comment]
Please upgrade to Brave-Browser. You are currently on muon which is deprecated. You can find install instructions [here](https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux)
