### ISSUE TITLE
Fix underlying cause of license check failure in CI

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#23229]
@simonhong fixed #23226 with a temporary workaround in https://github.com/brave/brave-core/pull/13585. The goal of this issue is to revert https://github.com/brave/brave-core/pull/13585 and to fix the underlying cause of the license check failure:

```
 FAILED: gen/components/resources/about_credits.html 
09:21:44  python3 ../../tools/licenses.py --target-os=linux --depfile gen/components/resources/about_credits.d credits gen/components/resources/about_credits.html
09:21:44  Traceback (most recent call last):
09:21:44    File "../../tools/licenses.py", line 896, in <module>
09:21:44      sys.exit(main())
09:21:44    File "../../tools/licenses.py", line 878, in main
09:21:44      if not GenerateCredits(args.file_template, args.entry_template,
09:21:44    File "../../tools/licenses.py", line 745, in GenerateCredits
09:21:44      CheckBraveMissingLicense(target_os, path, e)
09:21:44    File "/home/ubuntu/workspace/brave-browser-build-linux-x64-nightly/src/brave/script/brave_license_helper.py", line 171, in CheckBraveMissingLicense
09:21:44      raise error
09:21:44    File "../../tools/licenses.py", line 743, in GenerateCredits
09:21:44      metadata = ParseDir(path, _REPOSITORY_ROOT)
09:21:44    File "../../tools/licenses.py", line 451, in ParseDir
09:21:44      raise LicenseError("missing README.chromium or licenses.py "
09:21:44 
 __main__.LicenseError: missing README.chromium or licenses.py SPECIAL_CASES entry in brave/vendor/_gclient_bat-native-anonize_00dk005n
```

Associated Slack thread: https://bravesoftware.slack.com/archives/CA5FPHWLF/p1654215962937719

**Comment by mherrmann** [comment]
This issue is obsolete since https://github.com/brave/brave-core/pull/13585.
