### ISSUE TITLE
License checking failure from CI

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#23226]
```
 FAILED: gen/components/resources/about_credits.html 
09:21:44  python3 ../../tools/licenses.py --target-os=linux --depfile gen/components/resources/about_credits.d credits gen/components/resources/about_credits.html
09:21:44  Traceback (most recent call last):
09:21:44    File "../../tools/licenses.py", line 896, in <module>
09:21:44      sys.exit(main())
09:21:44    File "../../tools/licenses.py", line 878, in main
09:21:44      if not GenerateCredits(args.file_template, args.entry_template,
09:21:44    File "../../tools/licenses.py", line 745, in GenerateCredits
09:21:44      CheckBraveMissingLicense(target_os, path, e)
09:21:44    File "/home/ubuntu/workspace/brave-browser-build-linux-x64-nightly/src/brave/script/brave_license_helper.py", line 171, in CheckBraveMissingLicense
09:21:44      raise error
09:21:44    File "../../tools/licenses.py", line 743, in GenerateCredits
09:21:44      metadata = ParseDir(path, _REPOSITORY_ROOT)
09:21:44    File "../../tools/licenses.py", line 451, in ParseDir
09:21:44      raise LicenseError("missing README.chromium or licenses.py "
09:21:44 
 __main__.LicenseError: missing README.chromium or licenses.py SPECIAL_CASES entry in brave/vendor/_gclient_bat-native-anonize_00dk005n
```

**Comment by goodov** [comment]
This workaround can be removed now, underlying bug was fixed in upstream:
https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/3724051
