### ISSUE TITLE
Web.whatsapp.com fails to authenticate and returns "Make sure you computer has an active internet connection"

### ISSUE THREAD

**Issue by r3lai** [brave/brave-browser#23382]
## Description 
Whatsapp web interface fails to authenticate, and enters into infinite loop when logging out.

- Sometimes QR codes do not show up
- Fresh browser restart will bring up the QR code to scan
- Once scanned, it enters into authentication, but eventually crashes out with error "Make sure you computer has an active internet connection"

## Steps to Reproduce

   1. Open a private browser
   2. Go to web.whatsapp.com
   3. Scan the QR code with your mobile phone using Whatsapp
   4. Wait to see the error
Whatsapp Web seems to load fine for Latest chrome version (Version 102.0.5005.115 (Official Build) (64-bit)), and Firefox

## Actual result:
Video of error generated: https://photos.google.com/share/AF1QipMOGcCAVdJiFN-JgSlF8qM9TLux1nUKT2Yg25vq4Syf_jJPybwOb2jsU0pA7lwvGw?key=OTAta3BqWmw5djVKQ2xyV0J0OTNyZkdDbzhVc25R

## Expected result:
Whatsapp is logged in

## Reproduces how often: 

- Constantly since V1.39.120 (June 8th, 2022) was installed

## Brave version (info found on brave://version)

Brave	1.39.120 Chromium: 102.0.5005.99 (Official Build) (64-bit) 
Revision	870f7bcc58dfa811cc68c2186439721385e086d0-refs/branch-heads/5005@{#1125}
OS	Windows 10 Version 21H2 (Build 19044.1706)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the dev channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?  No

**Comment by rebron** [comment]
cc: @ryanbr

**Comment by ryanbr** [comment]
Hey, just testing this. Working for me here. 

Can you clear the cookies & cache in `brave://settings/clearBrowserData` then restart Brave? @r3lai

**Comment by sav-valerio** [comment]
I'm having the same issue, but only with my original "personal" profile.
I tried logging in with another one and it's working fine.

Also tried clearing up the cookies and the cache but no dice.

The only strange thing I noticed is that the following requests stay on pending:
<img width="846" alt="image" src="https://user-images.githubusercontent.com/14777542/173191165-a14e630f-a2ec-4b41-b4f3-d2c8796b7b8d.png">

**Comment by ryanbr** [comment]
Which browser extension is causing it @sav-valerio

**Comment by rambhosale** [comment]
After clearing browser data and disabling all the extensions it is working again

**Comment by sav-valerio** [comment]
@ryanbr I think it's Tampermonkey but I'm not 100% sure because after logging in it's working fine even after enabling it back.

**Comment by ryanbr** [comment]
> After clearing browser data and disabling all the extensions it is working again

Okay, re-enable extensions, do you see the issue return? @rambhosale  Which extensions do you have?

**Comment by r3lai** [comment]
I've taken the additional checks on the extension side, and have identified the "Honey" app (https://chrome.google.com/webstore/detail/honey-automatic-coupons-c/bmnlcjabgnpnenekpadlanbbkooimhnj) as the culprit. Disabling this app and restarting the browser will allow Whatsapp web to run normally.

**Comment by rambhosale** [comment]
@ryanbr I think it is "Honey" as mentioned by @r3lai 
here are the extensions that I use if it can help further
Honey, react dev tools, vue dev tools, markdown viewer, JSON viewer, Vimium, Grammarly

**Comment by michau-krakow** [comment]
I don't use "Honey" extension and still have issues with Whatsapp so this is more complicated.
For me it seem to work until I re-enable "Disable HTML5 Autoplay (Reloaded)" extension - then it stops working and disabling all extensions again does NOT help. Then for Whatsapp to work again I need to do the magic with clearing cache are reseting page settings - it looks like the extension is doing something nasty it can't revert then...

**Comment by ryanbr** [comment]
Do I need a login to Honey to test this @r3lai ? Whats the steps, Install Honey, then open web.whatapp.com ?

**Comment by Lim4** [comment]
> 



> Hey, I am experiencing the same issue but I have not the Honey extension. I try disable all extensions but it still not works. I also deleted cookies and storage, but chat sockets always be pending.
> 
> When WhatsApp QR is finally loaded (sometimes and after a lot of time), browser throw the next exception on read it with the smartphone:
> 
> ```
> Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Partial response (status code 206) is unsupported
>     at serviceworker.js:1:46087
>     at Generator.next (<anonymous>)
>     at t (serviceworker.js:1:32220)
>     at o (serviceworker.js:1:32431)
> ```
> 
> I try other browsers and WhatsApp works in all of them. I have the v1.40.105 x64 version (Windows 11). I also proved the private mode (with no extensions) with the same result.

Hello Martín
I'm having the same problem as you

**Comment by Lim4** [comment]
Hello Brave team
A user has managed to make Whatsapp Web work this way
The bug has to do with enabling/disabling hardware acceleration.
https://community.brave.com/t/whatsapp-web-is-not-working/402693/63

**Comment by kunsel** [comment]
Having the same issue, did disable plugins, cleared cache, tried to turn on/off hardware acceleration...

**Comment by mpperez3** [comment]
> Having the same issue, did disable plugins, cleared cache, tried to turn on/off hardware acceleration...

Try in this way:  swap hardware acceleration (for me, works with turn off )> clear cookies & cache > kill brave process >  try again

It works for me.

**Comment by Josema** [comment]
> Hello Brave team A user has managed to make Whatsapp Web work this way The bug has to do with enabling/disabling hardware acceleration. https://community.brave.com/t/whatsapp-web-is-not-working/402693/63

This does not work for me. Tried also cleaning cache and disabling plugins. 

My version is:
```
[Version 1.41.100 Chromium: 103.0.5060.134 (Official Build) (64-bit)](https://brave.com/latest/)
```

**Comment by kunsel** [comment]
> > Having the same issue, did disable plugins, cleared cache, tried to turn on/off hardware acceleration...
> 
> Try in this way: swap hardware acceleration (for me, works with turn off )> clear cookies & cache > kill brave process > try again
> 
> It works for me.

Did not work for me. Though I use multiple profiles.

**Comment by mpperez3** [comment]
New method. 

1. Disable hardware acceleration.
2. Restart brave
3. The QR code should have appeared to be readed
4. Open a new config tab with the hardware acceleration option
5. Read the QR code with the smartphone
6. Wait some seconds (don't wait for website to finish loading or an error message)
7. Enable hardware acceleration and fast restart (Without wait for the whatsapp loading end or error message)

Let me know if it works :)

**Comment by kunsel** [comment]
Okay, THAT actually worked.
Thanks a lot!

**Comment by NadavOz** [comment]
> New method.
> 
> 1. Remove all whatsapp cookies and storage (you can do it quickly from the lock of the navigation bar)
> 2. Disable hardware acceleration.
> 3. Restart Brave
> 4. Go to the whatsapp web. The QR code should have appeared fast in this way to be readed
> 5. Open a new config tab with the Brave hardware acceleration option
> 6. Read the QR code with the smartphone
> 7. Wait some seconds (don't wait for website to finish loading or an error message)
> 8. Enable the hardware acceleration and fast restart (Without wait for the whatsapp loading end or error message)
> 
> Let me know if it works :)

Worked for me as well

**Comment by ancho85** [comment]
> New method.
> 
> 1. Remove all whatsapp cookies and storage (you can do it quickly from the lock of the navigation bar)
> 2. Disable hardware acceleration.
> 3. Restart Brave
> 4. Go to the whatsapp web. The QR code should have appeared fast in this way to be readed
> 5. Open a new config tab with the Brave hardware acceleration option
> 6. Read the QR code with the smartphone
> 7. Wait some seconds (don't wait for website to finish loading or an error message)
> 8. Enable the hardware acceleration and fast restart (Without wait for the whatsapp loading end or error message)

This method also worked for me.

**Comment by GamingwithAnikYT** [comment]
> New method.
> 
> 1. Remove all whatsapp cookies and storage (you can do it quickly from the lock of the navigation bar)
> 2. Disable hardware acceleration.
> 3. Restart Brave
> 4. Go to the whatsapp web. The QR code should have appeared fast in this way to be readed
> 5. Open a new config tab with the Brave hardware acceleration option
> 6. Read the QR code with the smartphone
> 7. Wait some seconds (don't wait for website to finish loading or an error message)
> 8. Enable the hardware acceleration and fast restart (Without wait for the whatsapp loading end or error message)

thank u sooooo much

**Comment by zcraber** [comment]
I don't have the Honey extension installed, still facing the issue. Tried from a private window, but it didn't work either.

**Comment by jonathansampson** [comment]
@zcraber Does it work if you disable hardware acceleration (from brave://settings/system), restart Brave, then relaunch Brave?

**Comment by zcraber** [comment]
> @zcraber Does it work if you disable hardware acceleration (from brave://settings/system), restart Brave, then relaunch Brave?

I just tried it. Yes, it worked!

**Comment by Patoinf** [comment]
@ryanbr @mpperez3  @Lim4 

Hi there guys! Wanted to add my little grain of salt...

Don't use any of the fore mentioned extensions, but was having the exact same issue. So I tried 
disable all extensions + clear cache + brave restart: WhatsApp web started working normally.

Then started enabling extensions one bye one as to find which one was the problem. Found that at least 3 of my 10 extensions triggered the issue ("CrxMouse Chrome™ Gestures", "HBO Max Extended: tools to fix HBO" and "Simple Allow Copy"). I say at least because then i decided to stop the exercise. (Let's say many extensions cause the problem and just use other browser.)

Then I read about this Hardware Acceleration method and was about to try it out BUT:

**THE INTERESTING PART**
Forgetting to close the failed (Make sure you computer has an active internet connection) tab; Having surrendered to my fate I re-enabled all extensions and went about my day.The next time my attention focused on that tab (not too long after), I clicked it with the intention of closing it... There it was: a FULLY working, logged in, normal Whatsapp web session 
(with a matching  "Goggle Chrome" session listed on "Linked Devices" tab on my phone's WhatsApp app.)

Have reloaded the tab a couple of times, and it loads perfectly every time.
(Doesn't make sense to me, when testing, enabling an extension and reloading always triggered the issue.
Have NOT restarted the browser since (Grew tired of doing it over and over again while testing)

**[Version 1.42.88 Chromium: 104.0.5112.81 (Official Build) (x86_64)](https://brave.com/latest/)**

**Comment by levicki** [comment]
@ryanbr @rebron I have the same issue and I did some additional testing.

In my case, the problem is caused by TamperMonkey extension.

I tried blacklisting `*://web.whatsapp.com/*` in TamperMonkey settings (so the icon shows it is disabled for that site) and restarting the browser, but that didn't help at all.

Only completely disabling the extension and restarting the browser causes the problem to go away.

Now if I only knew what TamperMonkey does that stops WebSocket connections from working (I also get chat request as pending like the others above).

**Comment by VeganBurger** [comment]
I was experiencing the same error (up-to-date version of Brave for Linux prompting "Make sure you computer has an active internet connection").

This was caused by an add-in as well. In my case, the add-in was DuckDuckGo Privacy Essentials (since this add-in blocks all of Meta's trackers, which probably are required for the web version to work properly). The error was solved by disabling site protection in the web.whatsapp.com domain. This can be done by clicking on the add-in > Unprotected Sites > Add unprotected site > add web.whatsapp.com

![image](https://user-images.githubusercontent.com/100070731/190192277-6a82c93b-1a08-4f75-b795-f16ee5d372d7.png)

**Comment by milovangudelj** [comment]
I tried the method suggested by @mpperez3 and it worked fine, finally.

I'm glad that I'm able to use the app again, but it shouldn't require me to use finicky workarounds that don't work for everybody to be able to run it.

As far as I'm concerned this has not been fixed yet.

**Comment by oktayderman** [comment]
Solution is disabling "hardware acceleration" and clearing cookies in your browser settings. and logout whatsapp and relogin.
I was having problem at edge,opera in ubuntu. Problem gone thanks

**Comment by FDBnet** [comment]
### Description

WhatsApp Web fails to load QR code after clearing browser data. Console shows error: `[comms] stopComms called before startComms`. The issue persists when attempting to log in via phone number.

### Steps to Reproduce

1. Clear all browser data (cookies, cache, history) for web.whatsapp.com
2. Go to https://web.whatsapp.com
3. Attempt to log in (via QR Code or phone number)
4. QR Code fails to load indefinitely

### Actual Result

- QR Code never loads (infinite loading spinner)
- Console error: `ErrorUtils caught an error: [comms] stopComms called before startComms`
- Login via phone number also fails
- Memory heap: ~336 MB

### Expected Result

QR Code should load normally, allowing login to WhatsApp Web.

### Reproduces how often

Every time after clearing browser data.

### Brave Version

Brave: 1.85.111
Chromium: 143.0.7499.40 (64-bit)
V8: 14.3.127.16

### Operating System

Pop!_OS 22.04 LTS (Ubuntu-based)
Kernel: 6.16.3-76061603-generic x86_64

### User Agent

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36

### Additional Information

**Checklist:**
- [ ] Does the issue resolve itself when disabling Brave Shields? No
- [ ] Is the issue reproducible on the latest version of Chrome? **No**
- [ ] Does disabling hardware acceleration help? (Not tested)

**Console error details:**
```
ErrorUtils caught an error: [comms] stopComms called before startComms
Subsequent non-fatal errors won't be logged; see https://fburl.com/debugjs
```

This appears to be a WebSocket/communication initialization issue specific to Brave after clearing site data.

**Comment by JustOptimize** [comment]
@FDBnet I can't repro, can you try reproducing without extentions?

**Comment by FDBnet** [comment]
Thanks, @JustOptimize! Yesterday, when I got back to work and tried to connect to WhatsApp Web, I saw the error was gone. The issue had persisted for a few hours after I cleared all browsing data (cache and files) from Brave—it wasn't generating the QR Code.
