### ISSUE TITLE
Lisense Error

### ISSUE THREAD

**Issue by coderYipq** [brave/brave-browser#23569]
## Steps to Reproduce

   1. npm run init
   2. npm run build

## Actual result:

FAILED: gen/components/resources/about_credits.html 
python3 ../../tools/licenses.py --target-os=mac --depfile gen/components/resources/about_credits.d credits gen/components/resources/about_credits.html
Traceback (most recent call last):
  File "../../tools/licenses.py", line 903, in <module>
    sys.exit(main())
  File "../../tools/licenses.py", line 885, in main
    if not GenerateCredits(args.file_template, args.entry_template,
  File "../../tools/licenses.py", line 752, in GenerateCredits
    CheckBraveMissingLicense(target_os, path, e)
  File "/Users/xielongqing/Desktop/brave-browser/brave-browser/src/brave/script/brave_license_helper.py", line 177, in CheckBraveMissingLicense
    raise error
  File "../../tools/licenses.py", line 750, in GenerateCredits
    metadata = ParseDir(path, _REPOSITORY_ROOT)
  File "../../tools/licenses.py", line 496, in ParseDir
    raise LicenseError("Errors in %s:\n %s\n" % (path, ";\n ".join(errors)))
__main__.LicenseError: Errors in brave/components/brave_new_tab_ui/data:
 License file not found. Either add a file named LICENSE, import upstream's COPYING if available, or add a 'License File:' line to README.chromium with the appropriate path.

## Expected result:
I don't know

## Reproduces how often: 

No steps to reproduce

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
cc: @petemill @fmarier When you guys have a chance can you take a look
