### ISSUE TITLE
Brave Extension README - How to run local for external devs

### ISSUE THREAD

**Issue by kirkins** [brave/brave-browser#2404]
## Description 

Hello, I read in a AMA that Brave welcomes contributions from outside enthusiasts. I would like to run the repo called `brave-extension` but am unsure of use after compiling.

I followed the instructions from the readme and have webpack running, and imported the unpacked version of the extension. Clicking on the brave icon only shows an empty white box. I also tried on Chromium with the same results.

## Steps to Reproduce

   1. Clone and `npm install` brave-extension repo
   2. Run `npm run dev`
   3. Load `dev` folder as an unpacked extension.
   4. Local version of extension doesn't work as expected. _(clicking Brave icon shows empty white box)_

## Actual result:

![](https://i.imgur.com/kPQZAxb.png)

![](https://imgur.com/TLsNrno.png)

## Expected result:

To see working local version of the extension with modified text from `app/_locales/en_US/messages.json` for testing.

## Reproduces how often: 

Other times I try the same thing and use the update button on the extension page. In that case I see the normal version of the extension. I know it isn't my local version because I modified the text in `app/_locales/en_US/messages.json` _(also tried GB English to make sure)_ so I can tell if it is loading the default extension or my local version. I was never able to get it to load my local version.

Also tried to load as an extension in Chromium instead of Brave with same result, though I'm assuming it needs to be run in Brave.

## Brave version (brave://version info)

0.59.2 Chromium: 71.0.3578.80 (Official Build) dev (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kirkins** [comment]
**Update:** I'm trying something else now. I built the `brave-browser` repo and that is working for me.

Now I want to update the extension part without re-compiling the whole project.

My plan was to replace `brave-browser/src/brave/vendor/brave-extension` with my modified version and run `npm run build`.

I'm finding that `npm run build` doesn't work I get the following:

```
> brave-extension@1.0.0 build /home/philip/tmp/brave-extension
> node scripts/build

[Copy assets]
--------------------------------------------------------------------------------
rm: no paths given
mkdir: no paths given
cp: cannot create directory 'undefined': No such file or directory
cp: dest is not a directory (too many sources)

  rendered /home/philip/tmp/brave-extension/undefined/background.html
  rendered /home/philip/tmp/brave-extension/undefined/braveShieldsPanel.html
  rendered /home/philip/tmp/brave-extension/undefined/inject.html
[Webpack Build]
--------------------------------------------------------------------------------
/home/philip/tmp/brave-extension/node_modules/webpack-cli/bin/cli.js:244
				throw err;
				^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1155:7)
    at Object.<anonymous> (/home/philip/tmp/brave-extension/webpack/prod.config.js:28:16)
    at Module._compile (/home/philip/tmp/brave-extension/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (/home/philip/tmp/brave-extension/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/home/philip/tmp/brave-extension/node_modules/webpack-cli/bin/convert-argv.js:133:13)
    at requireConfig (/home/philip/tmp/brave-extension/node_modules/webpack-cli/bin/convert-argv.js:135:6)
    at /home/philip/tmp/brave-extension/node_modules/webpack-cli/bin/convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/philip/tmp/brave-extension/node_modules/webpack-cli/bin/convert-argv.js:140:15)
    at yargs.parse (/home/philip/tmp/brave-extension/node_modules/webpack-cli/bin/cli.js:241:39)
    at Object.parse (/home/philip/tmp/brave-extension/node_modules/webpack-cli/node_modules/yargs/yargs.js:563:18)
    at /home/philip/tmp/brave-extension/node_modules/webpack-cli/bin/cli.js:219:8
    at Object.<anonymous> (/home/philip/tmp/brave-extension/node_modules/webpack-cli/bin/cli.js:538:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/philip/tmp/brave-extension/node_modules/webpack/bin/webpack.js:155:2)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
exec: /home/philip/tmp/brave-extension/node_modules/webpack-cli/bin/cli.js:244
				throw err;
				^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1155:7)
    at Object.<anonymous> (/home/philip/tmp/brave-extension/webpack/prod.config.js:28:16)
    at Module._compile (/home/philip/tmp/brave-extension/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (/home/philip/tmp/brave-extension/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/home/philip/tmp/brave-extension/node_modules/webpack-cli/bin/convert-argv.js:133:13)
    at requireConfig (/home/philip/tmp/brave-extension/node_modules/webpack-cli/bin/convert-argv.js:135:6)
    at /home/philip/tmp/brave-extension/node_modules/webpack-cli/bin/convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/philip/tmp/brave-extension/node_modules/webpack-cli/bin/convert-argv.js:140:15)
    at yargs.parse (/home/philip/tmp/brave-extension/node_modules/webpack-cli/bin/cli.js:241:39)
    at Object.parse (/home/philip/tmp/brave-extension/node_modules/webpack-cli/node_modules/yargs/yargs.js:563:18)
    at /home/philip/tmp/brave-extension/node_modules/webpack-cli/bin/cli.js:219:8
    at Object.<anonymous> (/home/philip/tmp/brave-extension/node_modules/webpack-cli/bin/cli.js:538:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/philip/tmp/brave-extension/node_modules/webpack/bin/webpack.js:155:2)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

Erorr: webpack failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brave-extension@1.0.0 build: `node scripts/build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the brave-extension@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/philip/.npm/_logs/2018-12-07T18_45_33_736Z-debug.log

```

**Comment by kirkins** [comment]
I fixed my build issue by creating a default build folder if one isn't set as an environment variable.

https://github.com/kirkins/brave-extension/commit/8b529a69c64cf95d19aff9b205d24343bf0cbcb5

But after successfully building inside the `brave-browser` project I still don't see my changes.
