### ISSUE TITLE
Fix crash on attempting to upload minidump

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#24124]
## Description 
```
java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.android.apps.chrome.crash.ACTION_UPLOAD cmp=http://webaddress.elided/ (has extras) }: app is in background uid UidRecord{9899a8c u0a247 CACC idle change:cached procs:2 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1786)
	at android.app.ContextImpl.startService(ContextImpl.java:1718)
	at android.content.ContextWrapper.startService(ContextWrapper.java:730)
	at org.chromium.chrome.browser.crash.MinidumpUploadServiceImpl.tryUploadCrashDumpNow(MinidumpUploadServiceImpl.java:399)
	at org.chromium.chrome.browser.crash.LogcatExtractionRunnable.uploadMinidump(LogcatExtractionRunnable.java:58)
	at org.chromium.chrome.browser.crash.ChromePureJavaExceptionReporter.uploadMinidump(ChromePureJavaExceptionReporter.java:37)
	at androidx.core.content.res.ResourcesCompat$FontCallback.b(ResourcesCompat.java:190)
	at org.chromium.chrome.browser.crash.ChromePureJavaExceptionReporter.reportJavaException(ChromePureJavaExceptionReporter.java:53)
	at org.chromium.chrome.browser.compositor.CompositorViewHolder$3.run(CompositorViewHolder.java:63)
```

## Steps to reproduce 

There is no known way to reproduce it, just follow test plan to check if fix works https://github.com/brave/brave-browser/issues/24124#issuecomment-1189123175

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by samartnik** [comment]
Test plan for QA:
Since there is no known way to reproduce the issue, just double check that crashes are uploaded with new implementation.
For this:
1. Make sure crash reporting option is on.
2. Enter `brave://inducebrowsercrashforrealz/` into url bar and click `->` on screen keyboard. It should crash the browser.
3. Goto `brave://crashes`. You should see the crash and it should be uploaded.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.41.99 x64 build
- Verified steps from [#24124 (comment)](https://github.com/brave/brave-browser/issues/24124#issuecomment-1189123175)
- Verified with automatic crash reporting enabled, causing a browser crash and relaunching automatically uploads the data 
- Verified with automatic crash reporting disabled, causing a browser crash and relaunching doesn't upload the crash data automatically instead need to upload it manually
