### ISSUE TITLE
Fix crash from GPS on trying to createScaledBitmap

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#24154]
## Description 
There is a crash from GPS

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at AwContents$$ExternalSyntheticLambda4.done(AwContents.java:485)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at AwContents$$ExternalSyntheticLambda4.run(AwContents.java:473)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 5103628 byte allocation with 1616416 free bytes and 1578KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
	at android.graphics.Bitmap.nativeCreate(Bitmap.java)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:977)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:948)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:755)
	at FragmentStrictMode$$ExternalSyntheticLambda0.b(FragmentStrictMode.java:490)
	at AwContents$$ExternalSyntheticLambda3.call(AwContents.java:119)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
```

## Steps to reproduce 

Could not reproduce, crash is taken from GPS.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by deeppandya** [comment]
we will wait for the next release to verify this crash if it's happening with chroumim changes or brave changes.

**Comment by samartnik** [comment]
Crash is gone in the latest release, likely was fixed in the upstream.
