### ISSUE TITLE
Build fail in "brave_extension_grit" target

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#243]
When build is failed, there is no `js` folder in `brave\\browser\\resources\\brave_extension`.
Tested on Win10 with latest version(`2519846d7042cb296c`).

```
c:/Projects/brave/brave-browser-debug/vendor/depot_tools/win_tools-2_7_6_bin/python/bin/python.exe ../../tools/grit/grit.py -i ../../brave/browser/resources/brave_extension.grd build -o gen/brave/browser/resources --depdir . --depfile gen/brave/browser/resources/brave_extension_grit_stamp.d --write-only-new=1 --depend-on-stamp -D _chromium -E CHROMIUM_BUILD=chromium -D toolkit_views -D use_aura -E root_gen_dir=../../../out/Release/gen -p ../../tools/gritsettings/startup_resources_win.txt --assert-file-list=obj/brave/browser/resources/brave_extension_grit_expected_outputs.txt
Error processing node <?xml version="1.0" encoding="UTF-8"?>
<include file="brave_extension/js/braveShieldsPanel.bundle.js" name="IDR_BRAVE_EXTENSON_SHIELDS_BUNDLE_JS" type="BINDATA" />
Traceback (most recent call last):
  File "../../tools/grit/grit.py", line 15, in <module>
    grit.grit_runner.Main(sys.argv[1:])
  File "c:\Projects\brave\brave-browser-debug\src\tools\grit\grit\grit_runner.py", line 249, in Main
    toolobject.Run(options, args[1:])
  File "c:\Projects\brave\brave-browser-debug\src\tools\grit\grit\tool\build.py", line 256, in Run
    self.Process()
  File "c:\Projects\brave\brave-browser-debug\src\tools\grit\grit\tool\build.py", line 397, in Process
    self.ProcessNode(self.res, output, outfile)
  File "c:\Projects\brave\brave-browser-debug\src\tools\grit\grit\tool\build.py", line 320, in ProcessNode
    formatted = formatter(node, output_node.GetLanguage(), output_dir=base_dir)
  File "c:\Projects\brave\brave-browser-debug\src\tools\grit\grit\format\data_pack.py", line 83, in Format
    value = node.GetDataPackValue(lang, UTF8)
  File "c:\Projects\brave\brave-browser-debug\src\tools\grit\grit\node\include.py", line 86, in GetDataPackValue
    data = util.ReadFile(filename, util.BINARY)
  File "c:\Projects\brave\brave-browser-debug\src\tools\grit\grit\util.py", line 207, in ReadFile
    with open(filename, mode) as f:
IOError: [Errno 2] No such file or directory: u'..\\..\\brave\\browser\\resources\\brave_extension\\js\\braveShieldsPanel.bundle.js'
[10092/35657] CXX obj/third_party/widevine/cdm/widevinecdmadapter/ppapi_cdm_adapter.obj
```

**Comment by simonhong** [comment]
Duplicated issue https://github.com/brave/brave-browser/issues/253
