### ISSUE TITLE
Android 6 and 7 crash on Solana network

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#24566]
## Steps to reproduce 

   1. Open wallet on Android 6 or 7
   2. Select Solana network
   3. Tap on Solana asset on Portfolio screen.

## Actual result 
Brave crashes
[device-2022-08-10-100730.webm](https://user-images.githubusercontent.com/12011303/183925087-e9309bf8-d5d3-45d8-864c-2975e133d3bd.webm)

## Expected result
No crash

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

```
    Process: com.brave.browser_default, PID: 18650
    android.content.res.Resources$NotFoundException: File res/drawable/ic_sol_asset_icon.xml from drawable resource ID #0x7f09044e
        at android.content.res.Resources.loadDrawableForCookie(Resources.java:2640)
        at android.content.res.Resources.loadDrawable(Resources.java:2540)
        at android.content.res.Resources.getDrawable(Resources.java:806)
        at org.chromium.base.ApiCompatibilityUtils.getDrawableForDensity(ApiCompatibilityUtils.java:311)
        at org.chromium.base.ApiCompatibilityUtils.getDrawable(ApiCompatibilityUtils.java:280)
        at org.chromium.chrome.browser.crypto_wallet.util.Utils.lambda$setBitmapResource$4(Utils.java:756)
        at org.chromium.chrome.browser.crypto_wallet.util.Utils$$ExternalSyntheticLambda4.run(D8$$SyntheticClass)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/$ic_sol_asset_icon__0.xml from color state list resource ID #0x7f0900a3
        at android.content.res.Resources.loadColorStateListForCookie(Resources.java:2750)
        at android.content.res.Resources.loadColorStateList(Resources.java:2699)
        at android.content.res.TypedArray.getColor(TypedArray.java:439)
        at android.graphics.drawable.VectorDrawable$VFullPath.updateStateFromTypedArray(VectorDrawable.java:1605)
        at android.graphics.drawable.VectorDrawable$VFullPath.inflate(VectorDrawable.java:1584)
        at android.graphics.drawable.VectorDrawable.inflateInternal(VectorDrawable.java:666)
        at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:571)
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1215)
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1124)
        at android.content.res.Resources.loadDrawableForCookie(Resources.java:2630)
        at android.content.res.Resources.loadDrawable(Resources.java:2540) 
        at android.content.res.Resources.getDrawable(Resources.java:806) 
        at org.chromium.base.ApiCompatibilityUtils.getDrawableForDensity(ApiCompatibilityUtils.java:311) 
        at org.chromium.base.ApiCompatibilityUtils.getDrawable(ApiCompatibilityUtils.java:280) 
        at org.chromium.chrome.browser.crypto_wallet.util.Utils.lambda$setBitmapResource$4(Utils.java:756) 
        at org.chromium.chrome.browser.crypto_wallet.util.Utils$$ExternalSyntheticLambda4.run(D8$$SyntheticClass) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #16: invalid color state list tag gradient
        at android.content.res.ColorStateList.createFromXmlInner(ColorStateList.java:217)
        at android.content.res.ColorStateList.createFromXml(ColorStateList.java:201)
        at android.content.res.Resources.loadColorStateListForCookie(Resources.java:2746)
        at android.content.res.Resources.loadColorStateList(Resources.java:2699) 
        at android.content.res.TypedArray.getColor(TypedArray.java:439) 
        at android.graphics.drawable.VectorDrawable$VFullPath.updateStateFromTypedArray(VectorDrawable.java:1605) 
        at android.graphics.drawable.VectorDrawable$VFullPath.inflate(VectorDrawable.java:1584) 
        at android.graphics.drawable.VectorDrawable.inflateInternal(VectorDrawable.java:666) 
        at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:571) 
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1215) 
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1124) 
        at android.content.res.Resources.loadDrawableForCookie(Resources.java:2630) 
        at android.content.res.Resources.loadDrawable(Resources.java:2540) 
        at android.content.res.Resources.getDrawable(Resources.java:806) 
        at org.chromium.base.ApiCompatibilityUtils.getDrawableForDensity(ApiCompatibilityUtils.java:311) 
        at org.chromium.base.ApiCompatibilityUtils.getDrawable(ApiCompatibilityUtils.java:280) 
        at org.chromium.chrome.browser.crypto_wallet.util.Utils.lambda$setBitmapResource$4(Utils.java:756) 
        at org.chromium.chrome.browser.crypto_wallet.util.Utils$$ExternalSyntheticLambda4.run(D8$$SyntheticClass) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
```

**Comment by LaurenWags** [comment]
Reproduced the crash with the following physical device:
* Asus Zenfone (x86) with Android 6 using `1.44.34`

Unable to reproduce crash with the following physical device:
* Samsung Galaxy J7 Neo with Android 7 using `1.44.34`

**Comment by LaurenWags** [comment]
Verified using

* Asus Zenfone (x86) with Android 6 using `1.42.93`
* Samsung Galaxy J7 Neo with Android 7 using `1.42.93`

Reproduced the issue with Android 6 device, but not 7 as per https://github.com/brave/brave-browser/issues/24566#issuecomment-1211178634

Verified the below for both Android 6 and 7 devices:
* Selecting Solana asset on the portfolio screen did not cause a crash
* Confirmed this for the following network selections: `Solana Mainnet Beta`, `Solana Testnet`, `Solana Devnet`
