### ISSUE TITLE
Fail compilation

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#253]
Issue reported on browser-laptop repo https://github.com/brave/browser-laptop/issues/14303

### Description
Fail compilation of brave browser.
`include file="brave_extension/js/braveShieldsPanel.bundle.js" name="IDR_BRAVE_EXTENSON_SHIELDS_BUNDLE_JS" type="BINDATA" />
Traceback (most recent call last):
  File "../../tools/grit/grit.py", line 15, in <module>
    grit.grit_runner.Main(sys.argv[1:])
  File "E:\brave-browser\src\tools\grit\grit\grit_runner.py", line 249, in Main
    toolobject.Run(options, args[1:])
  File "E:\brave-browser\src\tools\grit\grit\tool\build.py", line 256, in Run
    self.Process()
  File "E:\brave-browser\src\tools\grit\grit\tool\build.py", line 397, in Process
    self.ProcessNode(self.res, output, outfile)
  File "E:\brave-browser\src\tools\grit\grit\tool\build.py", line 320, in ProcessNode
    formatted = formatter(node, output_node.GetLanguage(), output_dir=base_dir)
  File "E:\brave-browser\src\tools\grit\grit\format\data_pack.py", line 83, in Format
    value = node.GetDataPackValue(lang, UTF8)
  File "E:\brave-browser\src\tools\grit\grit\node\include.py", line 86, in GetDataPackValue
    data = util.ReadFile(filename, util.BINARY)
  File "E:\brave-browser\src\tools\grit\grit\util.py", line 207, in ReadFile
    with open(filename, mode) as f:
IOError: [Errno 2] No such file or directory: u'..\\..\\brave\\browser\\resources\\brave_extension\\js\\braveShieldsPanel.bundle.js'`

I happens when I start compiling of project with flags `yarn build --debug_build=true --official_build=false --no_branding_update`. Compilation script deletes directory `..\\..\\brave\\browser\\resources\\brave_extension` and then copy there files but without js directory, so i need every time put here js directory when script delete it.

### Steps to Reproduce

start compiling of project with flags `yarn build --debug_build=true --

**Actual result:**

**Expected result:**

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Version 66.0.3359.170 (Developer Build) (64-bit)

**Reproducible on current live release:**

**Comment by srirambv** [comment]
issue reported by @Biunovich

**Comment by bbondy** [comment]
Should be fixed in this merge, please re-open if not:
https://github.com/brave/brave-extension/commit/6b37b60aab471f13406f4cd0249b44a5b1b8acb1


Make sure to update src/brave/vendor/brave-extension before trying, and a new `npm install` in that dir.
