### ISSUE TITLE
Uncaught Errors and Unchecked runtime.lastError - `settings/?search=`

### ISSUE THREAD

**Issue by mbiesiad** [brave/brave-browser#25460]
## Description 
Using `settings/?search=` occurs `Uncaught Errors` and `Unchecked runtime.lastError`.

## Steps to Reproduce
   1. Open Brave, click F12 (DevTools)
   2. Go to: `brave://settings/?search=`
   3. See Console  
   4. Go to: `brave://settings/?search=amp`
   5. Check Console, go to: `brave://settings/?search=test`

## Actual result:
For `brave://settings/?search=amp` occurs: 

`Uncaught Error: Unexpected condition on chrome://settings/?search=amp: Could not find value for shouldExposeElementsForTesting
    at expect (load_time_data.m.js:202:13)
    at LoadTimeData.getValue (load_time_data.m.js:57:5)
    at LoadTimeData.getBoolean (load_time_data.m.js:148:24)
    at SettingsWalletNetworksSubpage.connectedCallback (settings.js:1741:613)
    at HTMLElement.__ensureInstance (polymer_bundled.min.js:1:54630)
    at HTMLElement.__render (polymer_bundled.min.js:1:53568)
    at c._callback (polymer_bundled.min.js:1:53216)
    at polymer_bundled.min.js:1:1360
    at MutationObserver.<anonymous> (polymer_bundled.min.js:1:207)`

and:
`Unchecked runtime.lastError: IPFS node is not launched`

---

For `brave://settings/?search=test` occurs: 

`Uncaught Error: Unexpected condition on chrome://settings/?search=test: Could not find value for shouldExposeElementsForTesting
    at expect (load_time_data.m.js:202:13)
    at LoadTimeData.getValue (load_time_data.m.js:57:5)
    at LoadTimeData.getBoolean (load_time_data.m.js:148:24)
    at SettingsWalletNetworksSubpage.connectedCallback (settings.js:1741:613)
    at HTMLElement.__ensureInstance (polymer_bundled.min.js:1:54630)
    at HTMLElement.__render (polymer_bundled.min.js:1:53568)
    at c._callback (polymer_bundled.min.js:1:53216)
    at polymer_bundled.min.js:1:1360
    at MutationObserver.<anonymous> (polymer_bundled.min.js:1:207)`

and:

`Uncaught Error: Assertion failed: An associated control was expected for SETTINGS-SUBPAGE Sieci, but was not found.
    at assert$1 (shared.rollup.js:14:57)
    at revealParentSection (settings.js:4494:2078)
    at doSearch (settings.js:4494:1110)
    at doSearch (settings.js:4494:1600)
    at doSearch (settings.js:4494:1600)
    at doSearch (settings.js:4494:1600)
    at doSearch (settings.js:4494:1600)
    at doSearch (settings.js:4494:1682)
    at doSearch (settings.js:4494:1600)
    at doSearch (settings.js:4494:1600)`

## Expected result:
It's fixed and secured.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
1.43.93 Chromium: 105.0.5195.127

## Miscellaneous Information:
Screenshots:

`brave://settings/?search=amp` result:
![image](https://user-images.githubusercontent.com/18367606/190830790-c6e2fcc0-75d4-466e-9275-5613625df13d.png)

`brave://settings/?search=test` result:
![image](https://user-images.githubusercontent.com/18367606/190830664-ec3acd6a-e0b1-4db0-9abf-27c3194e6efb.png)

Best wishes,

**Comment by rebron** [comment]
cc: @petemill
