### ISSUE TITLE
'npm run init' fails because 'https://registry.npmjs.org/create-run' cannot be found

### ISSUE THREAD

**Issue by anddsz** [brave/brave-browser#25600]
## Description 
'https://registry.npmjs.org/create-run' not found.

## Steps to Reproduce

   1. Clone git@github.com:brave/brave-core
   2. Run 'npm install'
   3. Run 'npm run init'

## Actual result:

'npm run init' fails because 'https://registry.npmjs.org/create-run' cannot be found.

## Expected result:
'npm run init' should proceed as intended.

## Reproduces how often: 
Everytime.

## Brave version (brave://version info)
Compiling from source.

## Version/Channel Information:
Straight from git@github.com:brave/brave-core

- Can you reproduce this issue with the current release?
Probably not.
- Can you reproduce this issue with the beta channel? 
Maybe.
- Can you reproduce this issue with the nightly channel?
I think so.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
Not related.
- Does the issue resolve itself when disabling Brave Rewards?
Not related.
- Is the issue reproducible on the latest version of Chrome?
Not sure.

## Miscellaneous Information:
```console
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@8.19.2
2 info using node@v18.9.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 6ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 4ms
6 timing config:load:builtin Completed in 6ms
7 timing config:load:cli Completed in 9ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/home/neraid/src/brave-browser/src/brave/.npmrc Completed in 1ms
10 timing config:load:project Completed in 14ms
11 timing config:load:file:/home/neraid/.npmrc Completed in 5ms
12 timing config:load:user Completed in 6ms
13 timing config:load:file:/usr/etc/npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 2ms
16 timing config:load:credentials Completed in 3ms
17 timing config:load:setEnvs Completed in 3ms
18 timing config:load Completed in 52ms
19 timing npm:load:configload Completed in 52ms
20 timing npm:load:mkdirpcache Completed in 4ms
21 timing npm:load:mkdirplogs Completed in 2ms
22 verbose title npm init run
23 verbose argv "init" "run"
24 timing npm:load:setTitle Completed in 3ms
25 timing config:load:flatten Completed in 10ms
26 timing npm:load:display Completed in 16ms
27 verbose logfile logs-max:10 dir:/home/neraid/.npm/_logs
28 verbose logfile /home/neraid/.npm/_logs/2022-09-24T18_04_52_714Z-debug-0.log
29 timing npm:load:logFile Completed in 17ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 1ms
32 timing npm:load Completed in 98ms
33 silly logfile start cleaning logs, removing 1 files
34 silly logfile done cleaning log files
35 timing arborist:ctor Completed in 3ms
36 timing arborist:ctor Completed in 1ms
37 http fetch GET 404 https://registry.npmjs.org/create-run 2115ms (cache skip)
38 http fetch GET 404 https://registry.npmjs.org/create-run 443ms (cache skip)
39 timing command:init Completed in 11553ms
40 verbose stack HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/create-run - Not found
40 verbose stack     at /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:95:15
40 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
40 verbose stack     at async RegistryFetcher.packument (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:92:19)
40 verbose stack     at async RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:124:23)
40 verbose stack     at async getManifest (/usr/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:32:22)
40 verbose stack     at async missingFromTree (/usr/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:60:22)
40 verbose stack     at async /usr/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:153:32
40 verbose stack     at async Promise.all (index 0)
40 verbose stack     at async exec (/usr/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:151:3)
40 verbose stack     at async Init.execCreate (/usr/lib/node_modules/npm/lib/commands/init.js:126:5)
41 verbose statusCode 404
42 verbose pkgid create-run@latest
43 verbose cwd /home/neraid/src/brave-browser/src/brave
44 verbose Linux 5.19.10-arch1-1
45 verbose node v18.9.1
46 verbose npm  v8.19.2
47 error code E404
48 error 404 Not Found - GET https://registry.npmjs.org/create-run - Not found
49 error 404
50 error 404  'create-run@latest' is not in this registry.
51 error 404
51 error 404 Note that you can also install from a
52 error 404 tarball, folder, http url, or git url.
53 verbose exit 1
54 timing npm Completed in 11982ms
55 verbose code 1
56 error A complete log of this run can be found in:
56 error     /home/neraid/.npm/_logs/2022-09-24T18_04_52_714Z-debug-0.log
```

**Comment by anddsz** [comment]
Oh well. It just seems like I had unfortunate timing.
