### ISSUE TITLE
intermittent error in terminal while syncing two devices 'Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2579]
## Description 
Sometimes I see the error below in terminal when two devices are syncing. Once there were missing bookmarks (after waiting a few hours) and the second time there weren't any missing bookmarks.

```
[18657:18657:1214/180755.351478:ERROR:CONSOLE(0)] "Error in event handler: TypeError: Cannot read property 'children' of undefined
    at Object.NodeState.moveBookmark (chrome://bookmarks/crisper.js:36:3559)
    at Object.NodeState.updateNodes (chrome://bookmarks/crisper.js:36:4755)
    at Object.reduceAction (chrome://bookmarks/crisper.js:36:7120)
    at Store.reduce_ (chrome://bookmarks/crisper.js:44:1112)
    at chrome://bookmarks/crisper.js:44:960
    at Store.dispatchInternal_ (chrome://bookmarks/crisper.js:44:1015)
    at Store.dispatchAsync (chrome://bookmarks/crisper.js:44:869)
    at Store.dispatch (chrome://bookmarks/crisper.js:44:927)
    at dispatch (chrome://bookmarks/crisper.js:48:726)
    at onBookmarkMoved (chrome://bookmarks/crisper.js:48:1287)", source: chrome://bookmarks/?id=9 (0)
```

## Steps to Reproduce

   1. Launch devices via terminal (Device A was macOS laptop, Device B was Linux VM)
   2. Import bookmarks onto Device A (1-2k)
   3. Sync two devices
   4. Watch terminal while devices sync.

## Actual result:
Sometimes an error is displayed:
```
[18657:18657:1214/180755.351478:ERROR:CONSOLE(0)] "Error in event handler: TypeError: Cannot read property 'children' of undefined
    at Object.NodeState.moveBookmark (chrome://bookmarks/crisper.js:36:3559)
    at Object.NodeState.updateNodes (chrome://bookmarks/crisper.js:36:4755)
    at Object.reduceAction (chrome://bookmarks/crisper.js:36:7120)
    at Store.reduce_ (chrome://bookmarks/crisper.js:44:1112)
    at chrome://bookmarks/crisper.js:44:960
    at Store.dispatchInternal_ (chrome://bookmarks/crisper.js:44:1015)
    at Store.dispatchAsync (chrome://bookmarks/crisper.js:44:869)
    at Store.dispatch (chrome://bookmarks/crisper.js:44:927)
    at dispatch (chrome://bookmarks/crisper.js:48:726)
    at onBookmarkMoved (chrome://bookmarks/crisper.js:48:1287)", source: chrome://bookmarks/?id=9 (0)
```

## Expected result:
No error

## Reproduces how often: 
Unsure

## Brave version (brave://version info)

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? unsure

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
cc @brave/legacy_qa

**Comment by darkdh** [comment]
@AlexeyBarabash this is related to our "Pending Bookmarks"

**Comment by AlexeyBarabash** [comment]
@darkdh yes, maybe will need to modify chromium js files related to bookmarks.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.59.20 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows 7

Used test plan from https://github.com/brave/brave-core/pull/1179. No errors in console.
Used STR from OP. No errors in terminal.
