### ISSUE TITLE
Unit tests fail to compile on Windows

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#2586]
Unit tests are failing to compile on Windows with the latest `master`"

```FAILED: chrome.7z setup.ex_ gen/chrome/installer/mini_installer/mini_installer/packed_files.rc
C:/work/brave-browser/vendor/depot_tools/win_tools-2_7_6_bin/python/bin/python.exe ../../chrome/tools/build/win/create_installer_archive.py --build_dir . --staging_dir gen/chrome/installer/mini_installer/mini_installer --input_file ../../chrome/installer/mini_installer/chrome.release --resource_file_path gen/chrome/installer/mini_installer/mini_installer/packed_files.rc --target_arch=x64 --distribution=_google_chrome --output_dir . --chrome_runtime_deps gen/chrome_component.runtime_deps --setup_runtime_deps gen/setup.runtime_deps --enable_hidpi=1 --component_build=1 --skip_archive_compression--depfile gen/chrome/installer/mini_installer/archive.d
Traceback (most recent call last):
  File "../../chrome/tools/build/win/create_installer_archive.py", line 718, in <module>
    sys.exit(main(options))
  File "../../chrome/tools/build/win/create_installer_archive.py", line 615, in main
    sign_binaries(staging_dir)
  File "C:\work\brave-browser\src\brave\script\sign_binaries.py", line 41, in sign_binaries
    sign_binary(binary)
  File "C:\work\brave-browser\src\brave\script\sign_binaries.py", line 46, in sign_binary
    run_cmd(cmd)
  File "C:\work\brave-browser\src\brave\script\sign_binaries.py", line 26, in run_cmd
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE)
  File "C:\work\brave-browser\vendor\depot_tools\win_tools-2_7_6_bin\python\bin\lib\subprocess.py", line 709, in __init__
    errread, errwrite)
  File "C:\work\brave-browser\vendor\depot_tools\win_tools-2_7_6_bin\python\bin\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

**Comment by emerick** [comment]
This is caused by an error in the `DEPS` introduced in #1839.
