### ISSUE TITLE
Crash in Rewards sendTip

### ISSUE THREAD

**Issue by sujitacharya2005** [brave/brave-browser#26107]
2022-10-18 12:18:19.559 23146-23146/com.brave.browser_default E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.brave.browser_default, PID: 23146
    java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
        at org.chromium.chrome.browser.rewards.BraveRewardsTippingPanelFragment.initRadioButtons(BraveRewardsTippingPanelFragment.java:189)
        at org.chromium.chrome.browser.rewards.BraveRewardsTippingPanelFragment.onCreateView(BraveRewardsTippingPanelFragment.java:108)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:557)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

## Description 
Getting ArrayIndexOutOfBoundsException when click on sendTip.

## Steps to reproduce 

   1. when go to [duckduckgo.com](http://duckduckgo.com/)
   2. click Send tip from rewards panel
   

## Version/Channel Information:

 Nightly version

## Device details
   - all

**Comment by kjozwiak** [comment]
The above requires `1.46.78` or higher for `1.46.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Reproduced the issue in `1.46.56` or `1.46.64` using the steps below:

Clean profile 1.46.56 or `1.46.64`
Open DDG
Click on BR panel
Enable rewards, select the geo and skip the rewards onboarding flow
Click on send a tip
Brave doesn't crash

Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.46.99`

Ensured there is no crash when one-time tip is sent to a publisher. Steps followed are as below
