### ISSUE TITLE
Windows Arm64 delta update generation fails

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#26237]
Our CI build currently gives the following error when generating delta update files for Arm64

```
Traceback (most recent call last):
File "../../chrome/tools/build/win/create_installer_archive.py", line 677, in <module>
  sys.exit(main(options))
File "../../chrome/tools/build/win/create_installer_archive.py", line 573, in main
  archive_file = CreateArchiveFile(options, staging_dir,
File "../../chrome/tools/build/win/create_installer_archive.py", line 323, in CreateArchiveFile
  GenerateDiffPatch(options, prev_archive_file, archive_file, patch_file)
File "../../chrome/tools/build/win/create_installer_archive.py", line 174, in GenerateDiffPatch
  RunSystemCommand(cmd, options.verbose)
File "../../chrome/tools/build/win/create_installer_archive.py", line 232, in RunSystemCommand
  output = subprocess.check_output(cmd, stderr=subprocess.STDOUT)
File "C:\jenkins\arm64-nightly\src\brave\vendor\depot_tools\bootstrap-2@3_8_10_chromium_23_bin\python3\bin\lib\subprocess.py", line 415, in check_output
  return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "C:\jenkins\arm64-nightly\src\brave\vendor\depot_tools\bootstrap-2@3_8_10_chromium_23_bin\python3\bin\lib\subprocess.py", line 493, in run
  with Popen(*popenargs, **kwargs) as process:
File "C:\jenkins\arm64-nightly\src\brave\vendor\depot_tools\bootstrap-2@3_8_10_chromium_23_bin\python3\bin\lib\subprocess.py", line 858, in __init__
  self._execute_child(args, executable, preexec_fn, close_fds,
File "C:\jenkins\arm64-nightly\src\brave\vendor\depot_tools\bootstrap-2@3_8_10_chromium_23_bin\python3\bin\lib\subprocess.py", line 1311, in _execute_child
  hp, ht, pid, tid = _winapi.CreateProcess(executable, args,

 OSError: [WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher
```

## How to test

Once this issue is fixed and a first Nightly with it has come out, download and install an older Arm64 Nightly. Install and open [Fiddler Classic](https://www.telerik.com/fiddler) to inspect network requests. Open `brave://settings/help` in the Nightly Brave. It should update to the new version. Fiddler should show that a `delta.exe` file - and no other file - was downloaded. Restarting Brave should show the new version in `brave://settings/help`.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.47.149 Chromium: 109.0.5414.46 (Official Build) beta (64-bit)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | Windows 11 Version 22H2 (Build 22621.963)
```

**Comment by mherrmann** [comment]
@MadhaviSeelam can you try again, updating from 1.47.136? I just checked on the update server. We don't have a delta update from 1.47.115 but we do have one from 1.47.136. Then, I would expect to see `brave_installer-delta-arm64.exe` in the logs. Sorry for the back and forth.

**Comment by MadhaviSeelam** [comment]
@mherrmann I still don't see `brave_installer-delta-arm64.exe` and  the logs show `brave_installer-arm64.exe`.  

my testing shows 9.57am and it still shows same.  However, I see brave_installer-delta-arm64.exe` in the logs at 3:01:56
```
[01/03/23 09:57:11.701][BraveUpdate:goopdate][43504:44852][OmahaPolicyManager::set_policy][Group Policy][[CachedOmahaPolicy][is_initialized][0][is_managed][0][auto_update_check_period_minutes][-1][download_preference][][cache_size_limit][-1][cache_life_limit][-1][updates_suppressed][-1][-1][-1][proxy_mode][][proxy_server][][proxy_pac_url][][install_default][-1][update_default][-1]]
[01/03/23 09:57:19.490][BraveUpdate:goopdate][43504:159488][Installing][display name: Brave Beta][app id: {103BD053-949B-43A8-9120-2E424887DE11}][installer path: C:\Program Files (x86)\BraveSoftware\Update\Install\{F86561B4-0622-4031-891B-5AEECF6EB668}\brave_installer-arm64.exe][manifest args: --chrome-beta][installer data: ][untrusted data: ][priority: 10]
[01/03/23 09:57:19.490][BraveUpdate:goopdate][43504:159488][Running installer][C:\Program Files (x86)\BraveSoftware\Update\Install\{F86561B4-0622-4031-891B-5AEECF6EB668}\brave_installer-arm64.exe][--chrome-beta][{103BD053-949B-43A8-9120-2E424887DE11}]
[01/03/23 09:57:27.126][BraveUpdate:goopdate][43504:159488][InstallerResult][{103BD053-949B-43A8-9120-2E424887DE11}][0]
[01/03/23 09:57:27.126][BraveUpdate:goopdate][43504:159488][InstallApp returned][0x0][{103BD053-949B-43A8-9120-2E424887DE11}][type:1][code: 30][][]
```

```
[01/03/23 03:01:56.969][BraveUpdate:goopdate][71604:54920][Installing][display name: Brave Beta][app id: {103BD053-949B-43A8-9120-2E424887DE11}][installer path: C:\Program Files (x86)\BraveSoftware\Update\Install\{09EF4768-E23C-4BEC-BBBF-131B1F07C333}\brave_installer-delta-arm64.exe][manifest args: --chrome-beta][installer data: ][untrusted data: ][priority: 0]
[01/03/23 03:01:56.969][BraveUpdate:goopdate][71604:54920][Running installer][C:\Program Files (x86)\BraveSoftware\Update\Install\{09EF4768-E23C-4BEC-BBBF-131B1F07C333}\brave_installer-delta-arm64.exe][--chrome-beta][{103BD053-949B-43A8-9120-2E424887DE11}]
[01/03/23 03:10:45.121][BraveUpdate:goopdate][71604:54920][InstallerResult][{103BD053-949B-43A8-9120-2E424887DE11}][0]
[01/03/23 03:10:45.121][BraveUpdate:goopdate][71604:54920][InstallApp returned][0x0][{103BD053-949B-43A8-9120-2E424887DE11}][type:1][code: 30][][]
```

**Comment by mherrmann** [comment]
@MadhaviSeelam it could be that when you tested, there was already a newer release. To explain: We only generate deltas from the exact previous version to the current one. So say there's already version 1 and version 2 comes out. Then we generate a delta from version 1 -> version 2. But now suppose version 3 comes out and you're on version 1. Then there is a delta from 2->3, but no delta from 1->3. My suspicion is that this is what happened when you tested.

Sorry to - again - ask you to try again. But can you re-test by installing the (public) release before the latest (public) one? For Beta, at the moment, the public releases are:

* Beta v1.48.113
* Beta v1.47.161
* Beta v1.47.149
* Beta v1.47.136

So you'd install v1.47.161. Do note though please that at this very moment, the release of Beta v1.48.113 is still in progress, so the delta actually has not yet been uploaded to the update server. It's all a bit complicated.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.47.161 Chromium: 109.0.5414.61 (Official Build) beta (64-bit)
-- | --
Revision | 846c6eff1c374cde417a9cdc44193545cc07f354-refs/branch-heads/5414@{#1030}
OS | Windows 11 Version 22H2 (Build 22621.963)
```

1. install `1.47.161` Beta installer `BraveBrowserBetaSetupArm64.exe` with admin privileges 
2. verified that brave is installed successfully
3. added following to registry keys to enable logging to check delta upgrades 
      - New-Item –Path "HKLM:\SOFTWARE\WOW6432Node\BraveSoftware" –Name UpdateDev
      - New-ItemProperty -Path "HKLM:\SOFTWARE\WOW6432Node\BraveSoftware\UpdateDev" -Name "IsEnabledLogToFile" -Value ”1”
4. Go to `brave://settings/help`
5. Open Fiddler and check the `delta-arm.exe` file for the host `updates-cdn2.bravesoftware.com` entry
6. verified logs show `brave_installer-arm64.exe` file in the request `https://updates-cdn2.bravesoftware.com/build/Brave-Browser-Beta/arm64-be/win/109.1.47.149/brave_installer-arm64.exe` 
7. go to `C:\ProgramData\BraveSoftware\Update\Log`
8. verified installer path shows `brave_installer-delta-arm64.exe` file
           `Installing][display name: Brave Beta][app id: {103BD053-949B-43A8-9120-2E424887DE11}][installer path: C:\Program Files (x86)\BraveSoftware\Update\Install\{01BA3F4E-957F-43D2-93B3-ED2481148A88}\brave_installer-delta-arm64.exe][manifest args: --chrome-beta][installer data: ][untrusted data: ][priority: 10]`
9. clicked Relaunch to verify public release `1.48.113`

step 1|step 3|step 4|step 6|step 8|step 9
----|----|----|----|------|-----
<img width="951" alt="image" src="https://user-images.githubusercontent.com/98358127/210834830-a5ca221f-8c5b-4676-9321-2d7aa03197e9.png">|<img width="608" alt="image" src="https://user-images.githubusercontent.com/98358127/210839555-1440ca45-0613-4362-b10b-b0bf2d0924ff.png">|<img width="942" alt="image" src="https://user-images.githubusercontent.com/98358127/210836724-a656125f-ac25-4734-acd8-7a50876e3367.png">|<img width="959" alt="image" src="https://user-images.githubusercontent.com/98358127/210835030-dc333db4-6b4e-41d6-8126-fd0e59d00934.png">|<img width="957" alt="image" src="https://user-images.githubusercontent.com/98358127/210845019-3409eb42-25ab-4683-a558-086d952c8e51.png">|<img width="952" alt="image" src="https://user-images.githubusercontent.com/98358127/210839591-defdad3c-2b6a-4b26-997d-236a00ba759b.png">


`Initial install of 1.47.161`
```
[01/05/23 09:45:23.844][BraveUpdate:goopdate][196436:35500][Installing][display name: Brave-Browser-Beta][app id: {103BD053-949B-43A8-9120-2E424887DE11}][installer path: C:\Program Files (x86)\BraveSoftware\Update\Install\{23AA18E5-F812-4AD8-8BE7-786BA76FB449}\brave_installer_109_1_47_161.exe][manifest args: --do-not-launch-chrome --chrome-beta][installer data: ][untrusted data: ][priority: 10]
[01/05/23 09:45:23.844][BraveUpdate:goopdate][196436:35500][Running installer][C:\Program Files (x86)\BraveSoftware\Update\Install\{23AA18E5-F812-4AD8-8BE7-786BA76FB449}\brave_installer_109_1_47_161.exe][--do-not-launch-chrome --chrome-beta][{103BD053-949B-43A8-9120-2E424887DE11}]
[01/05/23 09:45:31.730][BraveUpdate:goopdate][196436:35500][InstallerResult][{103BD053-949B-43A8-9120-2E424887DE11}][0]
[01/05/23 09:45:31.730][BraveUpdate:goopdate][196436:35500][InstallApp returned][0x0][{103BD053-949B-43A8-9120-2E424887DE11}][type:1][code: 0][]["C:\Program Files\BraveSoftware\Brave-Browser-Beta\Application\brave.exe" --from-installer]
[01/05/23 09:45:31.787][BraveUpdate:goopdate][196436:109028][Started process][88436]
```

Confirmed deltas on update - `brave_installer-delta-arm64.exe`
```
[01/05/23 09:47:40.597][BraveUpdate:goopdate][90220:166592][Installing][display name: Brave Beta][app id: {103BD053-949B-43A8-9120-2E424887DE11}][installer path: C:\Program Files (x86)\BraveSoftware\Update\Install\{01BA3F4E-957F-43D2-93B3-ED2481148A88}\brave_installer-delta-arm64.exe][manifest args: --chrome-beta][installer data: ][untrusted data: ][priority: 10]
[01/05/23 09:47:40.597][BraveUpdate:goopdate][90220:166592][Running installer][C:\Program Files (x86)\BraveSoftware\Update\Install\{01BA3F4E-957F-43D2-93B3-ED2481148A88}\brave_installer-delta-arm64.exe][--chrome-beta][{103BD053-949B-43A8-9120-2E424887DE11}]
[01/05/23 09:47:59.831][BraveUpdate:goopdate][90220:166592][InstallerResult][{103BD053-949B-43A8-9120-2E424887DE11}][0]
[01/05/23 09:47:59.831][BraveUpdate:goopdate][90220:166592][InstallApp returned][0x0][{103BD053-949B-43A8-9120-2E424887DE11}][type:1][code: 30][][]
[01/05/23 09:47:59.908][BraveUpdate:goopdate][90220:166592][Started process][124192]
[01/05/23 09:47:59.954][BraveCrashHandler][124192:120584][ConfigManager::LoadGroupPolicies][Machine is not Enterprise Managed]
[01/05/23 09:47:59.957][BraveCrashHandler][124192:120584][ConfigManager::LoadGroupPolicies][No Group Policies found under key][HKLM\Software\Policies\BraveSoftware\Update\]
[01/05/23 09:47:59.957][BraveCrashHandler][124192:120584][OmahaPolicyManager::set_policy][Group Policy][[CachedOmahaPolicy][is_initialized][0][is_managed][0][auto_update_check_period_minutes][-1][download_preference][][cache_size_limit][-1][cache_life_limit][-1][updates_suppressed][-1][-1][-1][proxy_mode][][proxy_server][][proxy_pac_url][][install_default][-1][update_default][-1]]
[01/05/23 09:47:59.967][BraveUpdate:goopdate][90220:166592][Started process][150796]
[01/05/23 09:47:59.967][BraveCrashHandler][124192:120584][CrashHandler::RunUntilShutdown]
[01/05/23 09:47:59.998][BraveUpdate:goopdate][90220:166592][Started process][147096]
[01/05/23 09:48:00.024][BraveUpdate:goopdate][90220:166592][Started process][129596]
[01/05/23 09:48:00.030][BraveUpdate:goopdate][139628:181532][DllEntry exit][0x00000000]
```
