### ISSUE TITLE
Search widget is not added 

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#27036]
## Steps to reproduce 

   1. Launch Brave beta
   2. Touch address bar
   3. `Try the Brave search widget` bubble is shown and Touch `Add widget`

## Actual result 
Launcher is crashed with LG V40 (Android 10, model name - `LM-V409N`)
Nothing happened with LG Velvet (Android 12, model name - `LM-G910N`)
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version:Android 10 and Android 12
   
## Brave version
Beta 1.47.99

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

Got below log from LG V40
```
2022-11-28 19:19:21.655 13806-13806/? I/LGPQLauncher:  CueTouchDelegateView.activate(T)
2022-11-28 19:19:21.674 16097-16097/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.lge.launcher3, PID: 16097
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lge.launcher3/com.android.launcher3.dragndrop.AddItemActivity}: java.lang.ClassCastException: android.app.ContextImpl cannot be cast to com.android.launcher3.Launcher
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3323)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3462)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2063)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7615)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
     Caused by: java.lang.ClassCastException: android.app.ContextImpl cannot be cast to com.android.launcher3.Launcher
        at com.android.launcher3.Launcher.getLauncher(Launcher.java:6987)
        at com.android.launcher3.dragndrop.AddItemActivity.setupWidget(AddItemActivity.java:235)
        at com.android.launcher3.dragndrop.AddItemActivity.onCreate(AddItemActivity.java:115)
        at android.app.Activity.performCreate(Activity.java:7812)
        at android.app.Activity.performCreate(Activity.java:7801)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3298)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3462) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2063) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7615) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964) 
```

**Comment by simonhong** [comment]
cc @deeppandya

**Comment by DorBSoft** [comment]
Happens with my own app when calling AppWidgetManager.requestPinAppWidget() on LG G5 Android 8.0.0. 
I thought this might be happening only on old LG. The fact that it happens on newer models is bad news.

**Comment by bsclifton** [comment]
@timchilds is this still an issue? If so - where do you think it falls priority-wise?
