### ISSUE TITLE
Crash on review request dialog

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#27750]
Not sure is it possible to replicate or not. I got it when a dialog to review an app appeared and I clicked on a smile to review it. It happened on Nightly build v1.49.11.

Crash stack is:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
        at android.content.ComponentName.<init>(ComponentName.java:132)
        at android.content.Intent.<init>(Intent.java:7432)
        at com.google.android.play.core.review.c.a(c.java:5)
        at org.chromium.chrome.browser.rate.BraveAskPlayStoreRatingDialog.lambda$rating$3(BraveAskPlayStoreRatingDialog.java:109)
        at com.google.android.play.core.tasks.a.run(a.java:0)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by kjozwiak** [comment]
As discussed, the above will be checked/verified via https://github.com/brave/brave-browser/issues/25777.
