### ISSUE TITLE
Crash on wallet creation

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#27805]
There is a crash from time to time on wallet creation with such a stack trace:
```
2023-01-13 14:04:07.700 28199-28199 System.err              pid-28199                            W  java.lang.NullPointerException: Attempt to invoke virtual method 'void org.chromium.brave_wallet.mojom.BraveWalletService_Internal$BraveWalletServiceGetSelectedCoinParams.<init>(org.chromium.brave_wallet.mojom.BraveWalletService$GetSelectedCoin_Response)' on a null object reference
2023-01-13 14:04:07.700 28199-28199 System.err              pid-28199                            W  java.lang.NullPointerException: Attempt to invoke virtual method 'void org.chromium.brave_wallet.mojom.BraveWalletService_Internal$Proxy.getSelectedCoin(org.chromium.brave_wallet.mojom.BraveWalletService$GetSelectedCoin_Response)' on a null object reference
<OR> 2023-01-13 14:04:07.700 28199-28199 System.err              pid-28199                            W  java.lang.NullPointerException: Attempt to invoke virtual method 'void org.chromium.brave_wallet.mojom.BraveWalletService_Internal$Proxy.getSelectedCoin(org.chromium.brave_wallet.mojom.BraveWalletService$GetSelectedCoin_Response)' on a null object reference
<OR> 2023-01-13 14:04:07.700 28199-28199 System.err              pid-28199                            W  java.lang.NullPointerException: Attempt to invoke virtual method 'void org.chromium.brave_wallet.mojom.BraveWalletService_Internal$Proxy.getSelectedCoin(org.chromium.brave_wallet.mojom.BraveWalletService$GetSelectedCoin_Response)' on a null object reference
<OR> 2023-01-13 14:04:07.700 28199-28199 System.err              pid-28199                            W  java.lang.NullPointerException: Attempt to invoke virtual method 'void org.chromium.brave_wallet.mojom.BraveWalletService_Internal$Proxy.getSelectedCoin(org.chromium.brave_wallet.mojom.BraveWalletService$GetSelectedCoin_Response)' on a null object reference
<OR> 2023-01-13 14:04:07.700 28199-28199 System.err              pid-28199                            W  java.lang.NullPointerException: Attempt to invoke virtual method 'void org.chromium.brave_wallet.mojom.BraveWalletService_Internal$Proxy.getSelectedCoin(org.chromium.brave_wallet.mojom.BraveWalletService$GetSelectedCoin_Response)' on a null object reference
<OR> 2023-01-13 14:04:07.700 28199-28199 System.err              pid-28199                            W  java.lang.NullPointerException: Attempt to invoke virtual method 'void org.chromium.mojo.bindings.Interface$AbstractProxy$HandlerImpl.getMessageReceiver(org.chromium.brave_wallet.mojom.BraveWalletService$GetSelectedCoin_Response)' on a null object reference
2023-01-13 14:04:07.700 28199-28199 System.err              pid-28199                            W  java.lang.NullPointerException: Attempt to invoke virtual method 'void org.chromium.brave_wallet.mojom.BraveWalletService_Internal$Proxy.getSelectedCoin(org.chromium.brave_wallet.mojom.BraveWalletService$GetSelectedCoin_Response)' on a null object reference
2023-01-13 14:04:07.700 28199-28199 System.err              pid-28199                            W      at org.chromium.chrome.browser.app.domain.KeyringModel.update(KeyringModel.java:147)
2023-01-13 14:04:07.700 28199-28199 System.err              pid-28199                            W      at org.chromium.chrome.browser.app.domain.KeyringModel.keyringCreated(KeyringModel.java:299)
2023-01-13 14:04:07.700 28199-28199 System.err              pid-28199                            W      at org.chromium.brave_wallet.mojom.KeyringServiceObserver_Internal$Stub.accept(KeyringServiceObserver_Internal.java:277)
2023-01-13 14:04:07.700 28199-28199 System.err              pid-28199                            W      at org.chromium.mojo.bindings.RouterImpl.handleIncomingMessage(RouterImpl.java:238)
2023-01-13 14:04:07.700 28199-28199 System.err              pid-28199                            W      at org.chromium.mojo.bindings.RouterImpl$HandleIncomingMessageThunk.accept(RouterImpl.java:33)
2023-01-13 14:04:07.700 28199-28199 System.err              pid-28199                            W      at org.chromium.mojo.bindings.Connector.readAndDispatchMessage(Connector.java:210)
2023-01-13 14:04:07.700 28199-28199 System.err              pid-28199                            W      at org.chromium.mojo.bindings.Connector.readOutstandingMessages(Connector.java:176)
2023-01-13 14:04:07.700 28199-28199 System.err              pid-28199                            W      at org.chromium.mojo.bindings.Connector.onWatcherResult(Connector.java:152)
2023-01-13 14:04:07.700 28199-28199 System.err              pid-28199                            W      at org.chromium.mojo.bindings.Connector$WatcherCallback.onResult(Connector.java:142)
2023-01-13 14:04:07.700 28199-28199 System.err              pid-28199                            W      at org.chromium.mojo.system.impl.WatcherImpl.onHandleReady(WatcherImpl.java:56)
2023-01-13 14:04:07.700 28199-28199 System.err              pid-28199                            W      at android.os.MessageQueue.nativePollOnce(Native Method)
2023-01-13 14:04:07.700 28199-28199 System.err              pid-28199                            W      at android.os.MessageQueue.next(MessageQueue.java:335)
2023-01-13 14:04:07.700 28199-28199 System.err              pid-28199                            W      at android.os.Looper.loopOnce(Looper.java:186)
2023-01-13 14:04:07.700 28199-28199 System.err              pid-28199                            W      at android.os.Looper.loop(Looper.java:313)
2023-01-13 14:04:07.700 28199-28199 System.err              pid-28199                            W      at android.app.ActivityThread.main(ActivityThread.java:8751)
2023-01-13 14:04:07.700 28199-28199 System.err              pid-28199                            W      at java.lang.reflect.Method.invoke(Native Method)
2023-01-13 14:04:07.700 28199-28199 System.err              pid-28199                            W      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
2023-01-13 14:04:07.700 28199-28199 System.err              pid-28199                            W      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

I could replicate it on 1.49.x release version and it happens 1 out of 5 times to me. STR:
1. Make a fresh Brave install
2. Settings->Wallet
3. Create new wallet

Observe a crash on creating wallet wizard.
A video of the crash:

https://user-images.githubusercontent.com/12011303/213286255-4062c73b-91e2-4c8f-8694-5dd2d4454b5e.mp4

**Comment by kjozwiak** [comment]
The above requires `1.47.178` or higher for `1.47.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Lenovo Tab with Android 12 running 1.47.181 x64 build
- Verified steps from issue description and [brave/brave-core#16728](https://github.com/brave/brave-core/pull/16728)
- Verified no crash when creating wallet 
- Verified on clean install and upgrade 
--------------
Verification passed on Oppo Reno 5 with Android 13 running 1.47.181 x64 build
- Verified steps from issue description and [brave/brave-core#16728](https://github.com/brave/brave-core/pull/16728)
- Verified no crash when creating wallet 
- Verified no crash when skipping fingerprint registration for wallet unlock
- Verified no crash when opting into fingerprint registration for wallet unlock
- Verified on clean install and upgrade
