### ISSUE TITLE
Crash when trying to add `pravda.com.ua` RSS feed into Brave News v2

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#27952]
## Description 

Crash when trying to add `pravda.com.ua` RSS feed into Brave News v2

## Steps to reproduce 

   1. install `1.48.134`
   2. launch Brave
   3. open `brave://flags`
   4. tap to `Enable` `Brave News v2`
   5. tap to `Relaunch` Brave
   6. tap the 3-dots menu
   7. tap `Settings` -> `Brave News` or `Brave News`, top-level menu item
   8. enter `pravda.com.ua` into the `Search for site, topic or RSS feed` textfield
   9. tap `Get Feeds`
   

## Actual result 

Crash:

```
2023-01-21 23:35:35.001 14071-14071 AndroidRuntime          pid-14071                            E  FATAL EXCEPTION: main
                                                                                                    Process: com.brave.browser_beta, PID: 14071
                                                                                                    java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
                                                                                                    	at java.util.ArrayList.get(ArrayList.java:437)
                                                                                                    	at Uz.s(chromium-MonochromePublic.apk-beta-414813423:415)
                                                                                                    	at xS1.t(chromium-MonochromePublic.apk-beta-414813423:1)
                                                                                                    	at androidx.recyclerview.widget.b.k(chromium-MonochromePublic.apk-beta-414813423:1117)
                                                                                                    	at d51.b(chromium-MonochromePublic.apk-beta-414813423:59)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.c1(chromium-MonochromePublic.apk-beta-414813423:1)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.O0(chromium-MonochromePublic.apk-beta-414813423:54)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.g0(chromium-MonochromePublic.apk-beta-414813423:810)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.t(chromium-MonochromePublic.apk-beta-414813423:79)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.onMeasure(chromium-MonochromePublic.apk-beta-414813423:64)
                                                                                                    	at android.view.View.measure(View.java:23169)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
                                                                                                    	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
                                                                                                    	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
                                                                                                    	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
                                                                                                    	at android.view.View.measure(View.java:23169)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                                    	at android.view.View.measure(View.java:23169)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
                                                                                                    	at androidx.coordinatorlayout.widget.CoordinatorLayout.s(chromium-MonochromePublic.apk-beta-414813423:7)
                                                                                                    	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onMeasureChild(chromium-MonochromePublic.apk-beta-414813423:77)
                                                                                                    	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(chromium-MonochromePublic.apk-beta-414813423:783)
                                                                                                    	at android.view.View.measure(View.java:23169)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                                    	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(chromium-MonochromePublic.apk-beta-414813423:160)
                                                                                                    	at android.view.View.measure(View.java:23169)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
                                                                                                    	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
                                                                                                    	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
                                                                                                    	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
                                                                                                    	at android.view.View.measure(View.java:23169)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                                    	at android.view.View.measure(View.java:23169)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
                                                                                                    	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
                                                                                                    	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
                                                                                                    	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
                                                                                                    	at android.view.View.measure(View.java:23169)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                                    	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:716)
                                                                                                    	at android.view.View.measure(View.java:23169)
                                                                                                    	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2718)
                                                                                                    	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1572)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1855)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:696)
2023-01-21 23:35:35.001 14071-14071 AndroidRuntime          pid-14071                            E  	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:873)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6718)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

## Expected result

No crash, and the feed-source loads/is added

## Issue reproduces how often 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): `Google Pixel XL`
   - Android version: `9`
   
## Brave version

`1.48.134`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

/cc @mattmcalister @tapanmodh @deeppandya @srirambv @Uni-verse @kjozwiak

**Comment by kjozwiak** [comment]
The above requires `1.48.141` or higher for `1.48.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using `Brave` `1.48.141`, `Chromium` `109.0.5414.119` on a `Google Pixel XL` running `Android 9`

Followed my original steps to reproduce

#### Confirmed no crash while adding feed sources from `pravda.com.ua` from search


https://user-images.githubusercontent.com/387249/214912529-12bbed4b-c26a-4ad6-b13f-121b300b575e.mp4



NOTE: https://github.com/brave/brave-browser/issues/28021 now exists, but this is a better experience
