### ISSUE TITLE
Issue with re-bookmarking webpage / bookmark icon disabled after bookmarking again [CR110]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#28099]
## Description 
Attempting to bookmark, unbookmark and then rebookmark will not work. Results in app crash sometimes

Logs: 

```
Initial Crash 

01-27 12:13:58.249 11381 11381 I GestureDetector: obtain mCurrentDownEvent. id: 308257065 caller: hq2.a:3 org.chromium.chrome.browser.toolbar.bottom.BraveScrollingBottomViewResourceFrameLayout.onInterceptTouchEvent:6 android.view.ViewGroup.dispatchTouchEvent:2836 
01-27 12:13:58.320 11381 11381 W System.err: 	at TD.F(chromium-MonochromePublic6432.aab-canary-414906424:11)
01-27 12:13:58.320 11381 11381 W System.err: 	at bI2.d(chromium-MonochromePublic6432.aab-canary-414906424:3)
01-27 12:13:58.320 11381 11381 W System.err: 	at St.e(chromium-MonochromePublic6432.aab-canary-414906424:1)
01-27 12:13:58.320 11381 11381 W System.err: 	at org.chromium.chrome.browser.bookmarks.BookmarkBridge.bookmarkModelLoaded(chromium-MonochromePublic6432.aab-canary-414906424:25)
01-27 12:13:58.320 11381 11381 W System.err: 	at rD1.k(chromium-MonochromePublic6432.aab-canary-414906424:22)
01-27 12:13:58.320 11381 11381 W System.err: 	at tg.run(chromium-MonochromePublic6432.aab-canary-414906424:15)
01-27 12:13:58.321 11381 11381 F chromium: [FATAL:jni_android.cc(286)] Please include Java exception stack in crash report
01-27 12:13:58.793 17914 17914 E chromium: [0127/121358.793222:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: Permission denied (13)


```
```
Relaunching and attempting to bookmark/unbookmark/rebookmark url



01-27 12:25:42.599 19812 19812 I GestureDetector: obtain mCurrentDownEvent. id: 886024468 caller: hq2.a:3 org.chromium.chrome.browser.toolbar.bottom.BraveScrollingBottomViewResourceFrameLayout.onInterceptTouchEvent:6 android.view.ViewGroup.dispatchTouchEvent:2836 
01-27 12:25:43.469 19812 19891 W chromium: [WARNING:spdy_session.cc(3484)] Received HEADERS for invalid stream 3
01-27 12:25:47.133 19812 19812 I GestureDetector: obtain mCurrentDownEvent. id: 710243176 caller: hq2.a:3 org.chromium.chrome.browser.toolbar.bottom.BraveScrollingBottomViewResourceFrameLayout.onInterceptTouchEvent:6 android.view.ViewGroup.dispatchTouchEvent:2836 
01-27 12:25:47.690 19812 19812 I GestureDetector: obtain mCurrentDownEvent. id: 57479554 caller: hq2.a:3 org.chromium.chrome.browser.toolbar.bottom.BraveScrollingBottomViewResourceFrameLayout.onInterceptTouchEvent:6 android.view.ViewGroup.dispatchTouchEvent:2836 
01-27 12:25:47.901 20039 20039 W chromium: [0127/122547.900850:warning:exception_snapshot_linux.cc(263)] fpsimd not found
01-27 12:25:47.902 20039 20039 E chromium: [0127/122547.902081:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: Permission denied (13)
01-27 12:25:48.608 19812 19812 I GestureDetector: obtain mCurrentDownEvent. id: 476613293 caller: hq2.a:3 org.chromium.chrome.browser.toolbar.bottom.BraveScrollingBottomViewResourceFrameLayout.onInterceptTouchEvent:6 android.view.ViewGroup.dispatchTouchEvent:2836 
01-27 12:25:49.550 19812 19812 I GestureDetector: obtain mCurrentDownEvent. id: 213833912 caller: hq2.a:3 org.chromium.chrome.browser.toolbar.bottom.BraveScrollingBottomViewResourceFrameLayout.onInterceptTouchEvent:6 android.view.ViewGroup.dispatchTouchEvent:2836 
```

## Steps to reproduce 

   1. Install 1.49.64
   2. Load any webpage
   3. bookmark page, then un-bookmark and then bookmark again using toolbar

## Actual result 

[Uploading bookmark_crash_1_49_64.mp4…](https://user-images.githubusercontent.com/17885425/215160827-3e280b52-ccaf-40c7-8b9a-02e732038535.mp4)

Bookmark icon becomes disabled

## Expected result
Bookmarking should work

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? N/A
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS21 
   - Android version: 13
   
## Brave version
`1.49.64, Chromium 110.0.5481.52`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

Symbolized crash stack:
```
 java.lang.AssertionError
                                                                                                    	at org.chromium.chrome.browser.bookmarks.TabBookmarker.addOrEditBookmark(TabBookmarker.java:101)
                                                                                                    	at org.chromium.chrome.browser.bookmarks.TabBookmarker.addOrEditBookmark(TabBookmarker.java:62)
                                                                                                    	at org.chromium.chrome.browser.app.BraveActivity.addOrEditBookmark(BraveActivity.java:2006)
                                                                                                    	at org.chromium.chrome.browser.toolbar.bottom.BrowsingModeBottomToolbarCoordinator.lambda$new$0$org-chromium-chrome-browser-toolbar-bottom-BrowsingModeBottomToolbarCoordinator(BrowsingModeBottomToolbarCoordinator.java:133)
                                                                                                    	at org.chromium.chrome.browser.toolbar.bottom.BrowsingModeBottomToolbarCoordinator$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
                                                                                                    	at android.view.View.performClick(View.java:6597)
                                                                                                    	at android.view.View.performClickInternal(View.java:6574)
                                                                                                    	at android.view.View.access$3100(View.java:778)
                                                                                                    	at android.view.View$PerformClick.run(View.java:25885)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:873)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6669)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by MadhaviSeelam** [comment]
Couldn't reproduce this issue Win 11 x64 with Chromium 110
```
Brave | 1.49.69 Chromium: 110.0.5481.52 (Official Build) nightly (64-bit)
-- | --
Revision | 979113183ded4544a2c443aceb1629c430907e52-refs/branch-heads/5481@{#636}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```

**Comment by kjozwiak** [comment]
> Couldn't reproduce this issue Win 11 x64 with Chromium 110
> 
> ```
> Brave | 1.49.69 Chromium: 110.0.5481.52 (Official Build) nightly (64-bit)
> -- | --
> Revision | 979113183ded4544a2c443aceb1629c430907e52-refs/branch-heads/5481@{#636}
> OS | Windows 11 Version 21H2 (Build 22000.1455)
> ```

Same. Spent some time creating/moving/deleting bookmarks without any issues. Also created folders and moved those around without any issues. Definitely seems like `Android` related.

**Comment by kjozwiak** [comment]
The above requires `1.48.153` or higher for `1.48.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version:

```
Brave	1.48.155 Chromium: 110.0.5481.77 (Official Build) (64-bit) 
Revision	65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS	Android 13; Build/TP1A.220624.014
```

- Ensured user is able to bookmark, un-bookmarked and then re-bookmark a page on a `new profile`
- Ensured user is able to re-bookmarked pages on an `upgraded profile`
- Ensured user is able to un-bookmark and then re-bookmark pages that were bookmarked in the previous version
- Ensured user is able to delete bookmarks and bookmark folders

![screenshot-1675459645936](https://user-images.githubusercontent.com/17885425/216719300-2fedfa79-2d85-4eed-acfb-4ce4a32afe36.png)
