### ISSUE TITLE
Errors when opening Swap page and sometimes make it hard to select a token

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#28140]
## Description 

Errors when opening Swap page and sometimes make it hard to select a token

## Steps to Reproduce

   1. Load account with balance
   2. Go to the new swap page
   3. Check console, throws error about fetching balance
   4. Try to select a token from the token list, doesn't select on first click. Have to click multiple times to select it

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/215544158-bb1f672a-5a98-4642-a890-2640a9eb7cbc.png)

```
7brave_wallet_page.bundle.js:155 Error querying balance: error=execution reverted asset= {"contractAddress":"0x8E3BCC334657560253B83f08331d85267316e08a","name":"Rubic","logo":"chrome://erc-token-images/brbc.png","isToken":true,"visible":true,"decimals":18,"symbol":"BRBC","coingeckoId":"","chainId":"0x1","coin":60}
7brave_wallet_page.bundle.js:155 Error querying balance: error=An internal error has occurred asset= {"contractAddress":"0xd55fce7cdab84d84f2ef3f99816d765a2a94a509","name":"Chain Games","logo":"chrome://erc-token-images/chain.png","isToken":true,"visible":true,"decimals":18,"symbol":"CHAIN","coingeckoId":"","chainId":"0x1","coin":60}
3brave_wallet_page.bundle.js:155 Error querying balance: error=execution reverted asset= {"contractAddress":"0x8E3BCC334657560253B83f08331d85267316e08a","name":"Rubic","logo":"chrome://erc-token-images/brbc.png","isToken":true,"visible":true,"decimals":18,"symbol":"BRBC","coingeckoId":"","chainId":"0x1","coin":60}
3brave_wallet_page.bundle.js:155 Error querying balance: error=An internal error has occurred asset= {"contractAddress":"0xd55fce7cdab84d84f2ef3f99816d765a2a94a509","name":"Chain Games","logo":"chrome://erc-token-images/chain.png","isToken":true,"visible":true,"decimals":18,"symbol":"CHAIN","coingeckoId":"","chainId":"0x1","coin":60}
2brave_wallet_page.bundle.js:155 Error querying balance: error=execution reverted asset= {"contractAddress":"0x8E3BCC334657560253B83f08331d85267316e08a","name":"Rubic","logo":"chrome://erc-token-images/brbc.png","isToken":true,"visible":true,"decimals":18,"symbol":"BRBC","coingeckoId":"","chainId":"0x1","coin":60}
2brave_wallet_page.bundle.js:155 Error querying balance: error=An internal error has occurred asset= {"contractAddress":"0xd55fce7cdab84d84f2ef3f99816d765a2a94a509","name":"Chain Games","logo":"chrome://erc-token-images/chain.png","isToken":true,"visible":true,"decimals":18,"symbol":"CHAIN","coingeckoId":"","chainId":"0x1","coin":60}
13brave_wallet_page.bundle.js:155 Error querying balance: error=execution reverted asset= {"contractAddress":"0x8E3BCC334657560253B83f08331d85267316e08a","name":"Rubic","logo":"chrome://erc-token-images/brbc.png","isToken":true,"visible":true,"decimals":18,"symbol":"BRBC","coingeckoId":"","chainId":"0x1","coin":60}
brave_wallet_page.bundle.js:9502 Uncaught (in promise) Error: Failed to fetch price: eth-wusdt
    at brave_wallet_page.bundle.js:9502:849
    at async brave_wallet_page.bundle.js:155:66494
brave_wallet_page.bundle.js:9502 Uncaught (in promise) Error: Failed to fetch price: eth-wusdt
    at brave_wallet_page.bundle.js:9502:849
    at async brave_wallet_page.bundle.js:155:66528
brave_wallet_page.bundle.js:155 Error querying balance: error=An internal error has occurred asset= {"contractAddress":"0xd55fce7cdab84d84f2ef3f99816d765a2a94a509","name":"Chain Games","logo":"chrome://erc-token-images/chain.png","isToken":true,"visible":true,"decimals":18,"symbol":"CHAIN","coingeckoId":"","chainId":"0x1","coin":60}
brave_wallet_page.bundle.js:155 Error querying balance: error=execution reverted asset= {"contractAddress":"0x8E3BCC334657560253B83f08331d85267316e08a","name":"Rubic","logo":"chrome://erc-token-images/brbc.png","isToken":true,"visible":true,"decimals":18,"symbol":"BRBC","coingeckoId":"","chainId":"0x1","coin":60}
brave_wallet_page.bundle.js:9502 Uncaught (in promise) Error: Failed to fetch price: eth-wusdt
    at brave_wallet_page.bundle.js:9502:849
    at async brave_wallet_page.bundle.js:155:66494
brave_wallet_page.bundle.js:9502 Uncaught (in promise) Error: Failed to fetch price: eth-wusdt
    at brave_wallet_page.bundle.js:9502:849
    at async brave_wallet_page.bundle.js:155:66528
8brave_wallet_page.bundle.js:155 Error querying balance: error=An internal error has occurred asset= {"contractAddress":"0xd55fce7cdab84d84f2ef3f99816d765a2a94a509","name":"Chain Games","logo":"chrome://erc-token-images/chain.png","isToken":true,"visible":true,"decimals":18,"symbol":"CHAIN","coingeckoId":"","chainId":"0x1","coin":60}
brave_wallet_page.bundle.js:9502 Uncaught (in promise) Error: Failed to fetch price: eth-wusdt
    at brave_wallet_page.bundle.js:9502:849
    at async brave_wallet_page.bundle.js:155:66528
3brave_wallet_page.bundle.js:155 Error querying balance: error=An internal error has occurred asset= {"contractAddress":"0xd55fce7cdab84d84f2ef3f99816d765a2a94a509","name":"Chain Games","logo":"chrome://erc-token-images/chain.png","isToken":true,"visible":true,"decimals":18,"symbol":"CHAIN","coingeckoId":"","chainId":"0x1","coin":60}
brave_wallet_page.bundle.js:155 Error querying balance: error=execution reverted asset= {"contractAddress":"0x8E3BCC334657560253B83f08331d85267316e08a","name":"Rubic","logo":"chrome://erc-token-images/brbc.png","isToken":true,"visible":true,"decimals":18,"symbol":"BRBC","coingeckoId":"","chainId":"0x1","coin":60}
3brave_wallet_page.bundle.js:155 Error querying balance: error=An internal error has occurred asset= {"contractAddress":"0xd55fce7cdab84d84f2ef3f99816d765a2a94a509","name":"Chain Games","logo":"chrome://erc-token-images/chain.png","isToken":true,"visible":true,"decimals":18,"symbol":"CHAIN","coingeckoId":"","chainId":"0x1","coin":60}
brave_wallet_page.bundle.js:9502 Uncaught (in promise) Error: Failed to fetch price: eth-wusdt
    at brave_wallet_page.bundle.js:9502:849
    at async brave_wallet_page.bundle.js:155:66494
2brave_wallet_page.bundle.js:9502 Uncaught (in promise) Error: Failed to fetch price: eth-wusdt
    at brave_wallet_page.bundle.js:9502:849
    at async brave_wallet_page.bundle.js:155:66528
brave_wallet_page.bundle.js:9502 Uncaught (in promise) Error: Failed to fetch price: eth-wusdt
    at brave_wallet_page.bundle.js:9502:849
    at async brave_wallet_page.bundle.js:155:66494
brave_wallet_page.bundle.js:9502 Uncaught (in promise) Error: Failed to fetch price: eth-wusdt
    at brave_wallet_page.bundle.js:9502:849
    at async brave_wallet_page.bundle.js:155:66528
brave_wallet_page.bundle.js:155 Error querying balance: error=execution reverted asset= {"contractAddress":"0x8E3BCC334657560253B83f08331d85267316e08a","name":"Rubic","logo":"chrome://erc-token-images/brbc.png","isToken":true,"visible":true,"decimals":18,"symbol":"BRBC","coingeckoId":"","chainId":"0x1","coin":60}
brave_wallet_page.bundle.js:155 Error querying balance: error=An internal error has occurred asset= {"contractAddress":"0xd55fce7cdab84d84f2ef3f99816d765a2a94a509","name":"Chain Games","logo":"chrome://erc-token-images/chain.png","isToken":true,"visible":true,"decimals":18,"symbol":"CHAIN","coingeckoId":"","chainId":"0x1","coin":60}
```

## Expected result:
No errors about fetching balance and able to select token in one click

## Reproduces how often: 

Easy and very often

## Brave version (brave://version info)

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Windows 11 Version 22H2 (Build 22621.755)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @onyb @Douglashdaniel @josheleonard

**Comment by Douglashdaniel** [comment]
Is no longer an issue after we moved `Swap V2` into `brave-core`. Closing as `Invalid`
