### ISSUE TITLE
Exception when no internet connection load Brave News

### ISSUE THREAD

**Issue by sujitacharya2005** [brave/brave-browser#28197]
## Description 
![image](https://user-images.githubusercontent.com/32419898/216033143-fa46d2c7-0cf3-4243-9d45-2946d80725d4.png)

2024-06-09 16:16:49.798 30968-30968 cr_BTSPrefs             com.brave.browser_nightly            E  No data found for task id: 53
2024-06-09 16:16:49.798 30968-30968 cr_BkgrdTaskScheduler   com.brave.browser_nightly            E  Task cannot be canceled because no data was found instorage or data was invalid
2024-06-09 16:16:49.805 30968-31059 chromium                com.brave.browser_nightly            E  [ERROR:ssl_client_socket_impl.cc(985)] handshake failed; returned -1, SSL error code 1, net_error -201
2024-06-09 16:16:49.807 30968-30968 chromium                com.brave.browser_nightly            E  [ERROR:feed_controller.cc(126)] Brave News Publisher list was empty
2024-06-09 16:16:49.814 30968-30968 AndroidRuntime          com.brave.browser_nightly            D  Shutting down VM
2024-06-09 16:16:49.815 30968-30968 AndroidRuntime          com.brave.browser_nightly            E  FATAL EXCEPTION: main
                                                                                                    Process: com.brave.browser_nightly, PID: 30968
                                                                                                    java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionDz{4178ef9 position=3 id=-1, oldPos=3, pLpos:-1 scrap [attachedScrap] update tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{a69d70c VFE...... ......I. 0,154-1080,2016 #7f010970 app:id/recyclerview}, adapter:Iz@b20fd1f, layout:androidx.recyclerview.widget.LinearLayoutManager@dde6855, context:org.chromium.chrome.browser.ChromeTabbedActivity@661bb98
                                                                                                    	at androidx.recyclerview.widget.b.k(chromium-MonochromePublic6432.aab-canary-414907727:552)
                                                                                                    	at n51.b(chromium-MonochromePublic6432.aab-canary-414907727:59)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.c1(chromium-MonochromePublic6432.aab-canary-414907727:1)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.O0(chromium-MonochromePublic6432.aab-canary-414907727:54)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.g0(chromium-MonochromePublic6432.aab-canary-414907727:810)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.s(chromium-MonochromePublic6432.aab-canary-414907727:366)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.r(chromium-MonochromePublic6432.aab-canary-414907727:64)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.onLayout(chromium-MonochromePublic6432.aab-canary-414907727:8)
                                                                                                    	at android.view.View.layout(View.java:23693)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6413)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:23693)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6413)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:23693)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6413)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:23693)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6413)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at org.chromium.chrome.browser.compositor.CompositorViewHolder.onLayout(chromium-MonochromePublic6432.aab-canary-414907727:6)
                                                                                                    	at android.view.View.layout(View.java:23693)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6413)
                                                                                                    	at androidx.coordinatorlayout.widget.CoordinatorLayout.r(chromium-MonochromePublic6432.aab-canary-414907727:390)
                                                                                                    	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(chromium-MonochromePublic6432.aab-canary-414907727:47)
                                                                                                    	at android.view.View.layout(View.java:23693)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6413)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:23693)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6413)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:23693)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6413)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:23693)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6413)
                                                                                                    	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
                                                                                                    	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
                                                                                                    	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
                                                                                                    	at android.view.View.layout(View.java:23693)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6413)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
2024-06-09 16:16:49.815 30968-30968 AndroidRuntime          com.brave.browser_nightly            E  	at com.android.internal.policy.DecorView.onLayout(DecorView.java:799)
                                                                                                    	at android.view.View.layout(View.java:23693)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6413)
                                                                                                    	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3999)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3372)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2328)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9087)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:832)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

## Steps to reproduce 

   1. No Internet connection
   2. launch application
   3.  load brave news
   4. exception

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
## Verified `PASSED` using `1.50.9`, `Chromium` `110.0.5481.77` on a `Google Pixel XL` (`arm64`) running `Android 9`

### Steps:
1. installed `1.50.9`
2. launched Brave
3. disabled Wi-Fi
4. tapped through onboarding
5. swiped up on the new-tab page
6. tapped `Show Brave News`


### Confirmed Brave restarts now, rather than hard-crashing, when it hits this case

1.50.9 | 1.49.77
------|--------
<video src="https://user-images.githubusercontent.com/387249/216797731-cf2b2c65-aacb-49e0-bc12-8cb440261b71.mp4"> | <video src="https://user-images.githubusercontent.com/387249/216797750-e3a56b3f-9c22-45db-9690-665791aa54fa.mp4">

**Comment by kjozwiak** [comment]
The above requires `1.48.157` or higher for `1.48.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using `1.48.157`, `Chromium` `110.0.5481.77` on a `Google Pixel XL` running `Android 9`

### Steps:
1. installed `1.48.157`
2. launched Brave
3. disabled Wi-Fi
4. tapped through onboarding
5. swiped up on the new-tab page
6. tapped Show Brave News

#### Confirmed Brave restarts now, rather than hard-crashing, when it hits this case

https://user-images.githubusercontent.com/387249/217102775-0d8fa903-4b5c-488d-b476-fcba948f539c.mp4
