### ISSUE TITLE
audit-deps fails on windows

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#2834]
```
\Microsoft\WindowsApps;C:\Users\Pranjal\AppData\Roaming\npm
9 verbose lifecycle brave@0.61.0~audit_deps: CWD: c:\b
10 silly lifecycle brave@0.61.0~audit_deps: Args: [ '/d /s /c', 'node ./scripts/audit.js' ]
11 silly lifecycle brave@0.61.0~audit_deps: Returned: code: 1  signal: null
12 info lifecycle brave@0.61.0~audit_deps: Failed to exec audit_deps script
13 verbose stack Error: brave@0.61.0 audit_deps: `node ./scripts/audit.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:30
1:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.j
s:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid brave@0.61.0
```

**Comment by kjozwiak** [comment]
@jumde is there anything that QA can do here or should we make this `QA/No`?

**Comment by jumde** [comment]
Updated to `QA/No`
