### ISSUE TITLE
Cache private search provider's template url data

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#28361]
With debug build, I can get assert failure from `BraveSearchEngineAdapter::getTemplateUrlByShortName`
when previsouly used private search provider is not included in newly updated provider list.
Because of this, https://github.com/brave/brave-browser/issues/28232 happens when SK's default list is updated.
```
2023-02-08 15:07:55.694 32547-32547/? A/chromium: #00 pc 0x00004c7a /data/app/com.brave.browser_default-36BN_ezUV3RsYdqk71y7pw==/lib/arm/libwebdata_common.cr.so
2023-02-08 15:07:55.694 32547-32547/? A/chromium: #01 pc 0x00ffe3a0 /data/app/com.brave.browser_default-36BN_ezUV3RsYdqk71y7pw==/lib/arm/libchrome.cr.so
2023-02-08 15:07:55.694 32547-32547/? A/chromium: Crash keys:
2023-02-08 15:07:55.694 32547-32547/? A/chromium:   "exception_info" = "java.lang.AssertionError: This should not happen!
2023-02-08 15:07:55.694 32547-32547/? A/chromium:     at xy.k(chromium-ChromePublic.apk-default-415001910:40)
2023-02-08 15:07:55.694 32547-32547/? A/chromium:     at xy.n(chromium-ChromePublic.apk-default-415001910:6)
2023-02-08 15:07:55.694 32547-32547/? A/chromium:     at xy.I(chromium-ChromePublic.apk-default-415001910:10)
2023-02-08 15:07:55.695 32547-32547/? A/chromium:     at org.chromium.components.search_engines.TemplateUrlService.templateUrlServiceLoaded(chromium-ChromePublic.apk-default-415001910:25)
2023-02-08 15:07:55.695 32547-32547/? A/chromium:     at android.os.MessageQueue.nativePollOnce(Native Method)
2023-02-08 15:07:55.695 32547-32547/? A/chromium:     at android.os.MessageQueue.next(MessageQueue.java:336)
2023-02-08 15:07:55.695 32547-32547/? A/chromium:     at android.os.Looper.loop(Looper.java:174)
```

To resolve this, android also need to cache current private provider's TemplateURLData and add it when it's not included in the default list as we did for desktop(https://github.com/brave/brave-core/pull/17015).

* STR
1. Go to search engine settings
2. Change private window's provider
3. Check `default_private_search_provider_data` is updated properly at brave://prefs-internals/

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.50.112 Chromium: 112.0.5615.49 (Official Build) (32-bit)
--- | ---
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Android 13; Build/TQ2A.230305.008.E1
```

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/28361#issue-1575320002, went through the following:

**Default `default_private_search_provider_data` after installing Brave (not changing SE)**

**`Example`** | **`Example`**
----------------|----------------
![Screenshot_20230403-230807](https://user-images.githubusercontent.com/2602313/229677286-8984ae30-fa39-4de6-aafa-90b8378bc6f5.png) | ![Screenshot_20230403-230759](https://user-images.githubusercontent.com/2602313/229677299-06bb3320-0b53-41fa-8aed-a3996d637cc1.png)

**Changing PB SE to `DDG`**

**`Example`** | **`Example`**
----------------|----------------
![Screenshot_20230403-230249](https://user-images.githubusercontent.com/2602313/229677423-239c871f-bc9c-4f3f-9b61-adc541ad39e6.png) | ![Screenshot_20230403-230124](https://user-images.githubusercontent.com/2602313/229677432-0bf2e023-6fd5-4101-a270-239022baa16d.png)

**Changing PB SE to `Startpage`**

**`Example`** | **`Example`**
----------------|----------------
![Screenshot_20230403-230149](https://user-images.githubusercontent.com/2602313/229677511-a683ee3c-964a-42fa-8191-ed4b0474f9c2.png) | ![Screenshot_20230403-230230](https://user-images.githubusercontent.com/2602313/229677521-fdeb4386-2143-43e5-bb54-58969c72d765.png)

**Changing PB SE to `Google`**

**`Example`** | **`Example`**
----------------|----------------
![Screenshot_20230403-230516](https://user-images.githubusercontent.com/2602313/229677652-089976ce-3183-4e30-b07b-9f2f27e4a517.png) | ![Screenshot_20230403-230403](https://user-images.githubusercontent.com/2602313/229677657-27c87fcb-5380-4c0e-88dc-1b454bef329f.png)

**Changing PB SE to `Bing`**

**`Example`** | **`Example`**
----------------|----------------
![Screenshot_20230403-230508](https://user-images.githubusercontent.com/2602313/229677841-9b47359c-bc28-4688-9632-ecca1392be35.png) | ![Screenshot_20230403-230455](https://user-images.githubusercontent.com/2602313/229677854-27d97c48-f62c-4f10-a7d1-d6ff5b5bce7b.png)

**Changing PB SE to `Brave`**

**`Example`** | **`Example`**
----------------|----------------
![Screenshot_20230403-230807](https://user-images.githubusercontent.com/2602313/229677286-8984ae30-fa39-4de6-aafa-90b8378bc6f5.png) | ![Screenshot_20230403-230549](https://user-images.githubusercontent.com/2602313/229677940-ce62facc-55fe-4ae7-9a40-2ea6d66cd824.png)
