### ISSUE TITLE
CI build fails at "create_dist" stage

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#28503]
```
[2023-02-13T15:13:39.496Z] python.exe "C:\ws\src\brave\vendor\omaha\omaha\installers\generate_tarball.py" -o scons-out\opt-win\obj\standalone\payload_UNOFFICIAL_BraveBrowserStandaloneNightlySetup_110_1_50_30.tar scons-out\opt-win\staging\BraveUpdate.exe scons-out\opt-win\staging\BraveCrashHandler.exe scons-out\opt-win\staging\goopdate.dll scons-out\opt-win\staging\BraveUpdateBroker.exe scons-out\opt-win\staging\BraveUpdateOnDemand.exe scons-out\opt-win\staging\BraveUpdateComRegisterShell64.exe scons-out\opt-win\staging\psmachine.dll scons-out\opt-win\staging\psmachine_64.dll scons-out\opt-win\staging\psuser.dll scons-out\opt-win\staging\psuser_64.dll scons-out\opt-win\staging\BraveCrashHandler64.exe scons-out\opt-win\staging\BraveUpdateCore.exe scons-out\opt-win\staging\BraveCrashHandlerArm64.exe scons-out\opt-win\staging\BraveUpdateComRegisterShellArm64.exe scons-out\opt-win\staging\psmachine_arm64.dll scons-out\opt-win\staging\psuser_arm64.dll scons-out\opt-win\staging\goopdateres_am.dll scons-out\opt-win\staging\goopdateres_ar.dll scons-out\opt-win\staging\goopdateres_bg.dll scons-out\opt-win\staging\goopdateres_bn.dll scons-out\opt-win\staging\goopdateres_ca.dll scons-out\opt-win\staging\goopdateres_cs.dll scons-out\opt-win\staging\goopdateres_da.dll scons-out\opt-win\staging\goopdateres_de.dll scons-out\opt-win\staging\goopdateres_el.dll scons-out\opt-win\staging\goopdateres_en.dll scons-out\opt-win\staging\goopdateres_en-GB.dll scons-out\opt-win\staging\goopdateres_es.dll scons-out\opt-win\staging\goopdateres_es-419.dll scons-out\opt-win\staging\goopdateres_et.dll scons-out\opt-win\staging\goopdateres_fa.dll scons-out\opt-win\staging\goopdateres_fi.dll scons-out\opt-win\staging\goopdateres_fil.dll scons-out\opt-win\staging\goopdateres_fr.dll scons-out\opt-win\staging\goopdateres_gu.dll scons-out\opt-win\staging\goopdateres_hi.dll scons-out\opt-win\staging\goopdateres_hr.dll scons-out\opt-win\staging\goopdateres_hu.dll scons-out\opt-win\staging\goopdateres_id.dll scons-out\opt-win\staging\goopdateres_is.dll scons-out\opt-win\staging\goopdateres_it.dll scons-out\opt-win\staging\goopdateres_iw.dll scons-out\opt-win\staging\goopdateres_ja.dll scons-out\opt-win\staging\goopdateres_kn.dll scons-out\opt-win\staging\goopdateres_ko.dll scons-out\opt-win\staging\goopdateres_lt.dll scons-out\opt-win\staging\goopdateres_lv.dll scons-out\opt-win\staging\goopdateres_ml.dll scons-out\opt-win\staging\goopdateres_mr.dll scons-out\opt-win\staging\goopdateres_ms.dll scons-out\opt-win\staging\goopdateres_nl.dll scons-out\opt-win\staging\goopdateres_no.dll scons-out\opt-win\staging\goopdateres_pl.dll scons-out\opt-win\staging\goopdateres_pt-BR.dll scons-out\opt-win\staging\goopdateres_pt-PT.dll scons-out\opt-win\staging\goopdateres_ro.dll scons-out\opt-win\staging\goopdateres_ru.dll scons-out\opt-win\staging\goopdateres_sk.dll scons-out\opt-win\staging\goopdateres_sl.dll scons-out\opt-win\staging\goopdateres_sr.dll scons-out\opt-win\staging\goopdateres_sv.dll scons-out\opt-win\staging\goopdateres_sw.dll scons-out\opt-win\staging\goopdateres_ta.dll scons-out\opt-win\staging\goopdateres_te.dll scons-out\opt-win\staging\goopdateres_th.dll scons-out\opt-win\staging\goopdateres_tr.dll scons-out\opt-win\staging\goopdateres_uk.dll scons-out\opt-win\staging\goopdateres_ur.dll scons-out\opt-win\staging\goopdateres_vi.dll scons-out\opt-win\staging\goopdateres_zh-CN.dll scons-out\opt-win\staging\goopdateres_zh-TW.dll scons-out\opt-win\obj\standalone\brave_installer_110_1_50_30.exe.{C6CB981E-DB30-4876-8639-109F8933582C} scons-out\opt-win\obj\standalone\UNOFFICIAL_BraveBrowserStandaloneNightlySetup_110_1_50_30.exe_manifest\OfflineManifest.gup
[2023-02-13T15:13:39.498Z] Install file: "scons-out\opt-win\obj\mi_exe_stub\x86_encoder\bcj2.exe" as "scons-out\opt-win\staging\bcj2.exe"
[2023-02-13T15:13:39.498Z] "C:\ws\src\brave\vendor\omaha\omaha\scons-out\opt-win/staging/bcj2.exe" "scons-out\opt-win\obj\standalone\payload_UNOFFICIAL_BraveBrowserStandaloneNightlySetup_110_1_50_30.tar" "scons-out\opt-win\obj\standalone\payload_UNOFFICIAL_BraveBrowserStandaloneNightlySetup_110_1_50_30.tar.bcj"
[2023-02-13T15:13:39.498Z] scons: *** [scons-out\opt-win\obj\standalone\payload_UNOFFICIAL_BraveBrowserStandaloneNightlySetup_110_1_50_30.tar.bcj] Error -1073740791
[2023-02-13T15:13:39.498Z] scons: building terminated because of errors.
[2023-02-13T15:13:39.498Z] Error in hammer.bat:132.
[2023-02-13T15:13:39.499Z] Traceback (most recent call last):
[2023-02-13T15:13:39.499Z]   File "../../brave/vendor/omaha/build_omaha.py", line 219, in <module>
[2023-02-13T15:13:39.499Z]     sys.exit(main())
[2023-02-13T15:13:39.499Z]   File "../../brave/vendor/omaha/build_omaha.py", line 206, in main
[2023-02-13T15:13:39.499Z]     build(omaha_dir, installer_metadata_dir, args.debug)
[2023-02-13T15:13:39.499Z]   File "../../brave/vendor/omaha/build_omaha.py", line 49, in build
[2023-02-13T15:13:39.499Z]     sp.check_call(command, stderr=sp.STDOUT, env=env)
[2023-02-13T15:13:39.499Z]   File "C:\ws\src\brave\vendor\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python3\bin\lib\subprocess.py", line 364, in check_call
[2023-02-13T15:13:39.499Z]     raise CalledProcessError(retcode, cmd)
[2023-02-13T15:13:39.499Z] subprocess.CalledProcessError: Command '['hammer.bat', 'MODE=opt-win', '--all', '--standalone_installers_dir=C:/ws/src/out/Static\\..\\..\\brave\\vendor\\omaha\\omaha\\scons-out\\opt-win\\Brave_Installers\\standalone', '--authenticode_password=****', '--sha1_authenticode_password=****', '--sha2_authenticode_password=****', '--authenticode_hash=8D5AB0D8CAD7C59EE747691E2234C5762EF62683', '--sha1_authenticode_hash=8D5AB0D8CAD7C59EE747691E2234C5762EF62683', '--sha2_authenticode_hash=8D5AB0D8CAD7C59EE747691E2234C5762EF62683', '--use_authenticode_machine_store']' returned non-zero exit status 2.
```

## Reproduces how often: 

Always.

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.50.108 Chromium: 112.0.5615.39 (Official Build) (64-bit)
-- | --
Revision | a0e7b9718a92bcd1cf33b7c95316caff3fc20714-refs/branch-heads/5615@{#753}
OS | Windows 10 Version 21H2 (Build 19044.2728)

```
