### ISSUE TITLE
[Android] App crashes when connecting rewards account [Staging]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#28791]
## Description 
After entering credentials and 2FA, brave app will not respond and eventually crash

**Not able to reproduce on nightly with C110 (1.50.58)**

```
2023-02-27 17:51:41.720 6928-8758/? E/ProcessStats: Executing service ServiceState{8f38fc3 org.chromium.content.app.SandboxedProcessService0 pkg=com.brave.browser_nightly proc=f7713c3} without owner
2023-02-27 17:51:41.726 24153-24153/? I/cr_SplitCompatApp: Launched version=111.1.50.62 minSdkVersion=24 isBundle=true processName=com.brave.browser_nightly:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:305 isIsolated=true
2023-02-27 17:51:41.733 6928-11039/? W/ActivityManager: Exception when unbinding service com.brave.browser_nightly/org.chromium.content.app.SandboxedProcessService0:299
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:653)
        at android.app.IApplicationThread$Stub$Proxy.scheduleUnbindService(IApplicationThread.java:1445)
        at com.android.server.am.ActiveServices.removeConnectionLocked(ActiveServices.java:5138)
        at com.android.server.am.ActiveServices.unbindServiceLocked(ActiveServices.java:3310)
        at com.android.server.am.ActivityManagerService.unbindService(ActivityManagerService.java:15021)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2966)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3077)
        at android.os.Binder.execTransactInternal(Binder.java:1316)
        at android.os.Binder.execTransact(Binder.java:1280)
2023-02-27 17:51:41.733 6928-11039/? E/ProcessStats: Executing service ServiceState{8f38fc3 org.chromium.content.app.SandboxedProcessService0 pkg=com.brave.browser_nightly proc=f7713c3} without owner
2023-02-27 17:51:41.733 6928-11039/? E/ProcessStats: Foregrounding service ServiceState{8f38fc3 org.chromium.content.app.SandboxedProcessService0 pkg=com.brave.browser_nightly proc=f7713c3} without owner
2023-02-27 17:51:41.733 6928-11039/? E/ProcessStats: Binding service ServiceState{8f38fc3 org.chromium.content.app.SandboxedProcessService0 pkg=com.brave.browser_nightly proc=f7713c3} without owner
2023-02-27 17:51:41.733 6928-11039/? E/ProcessStats: Starting service ServiceState{8f38fc3 org.chromium.content.app.SandboxedProcessService0 pkg=com.brave.browser_nightly proc=f7713c3} without owner
2023-02-27 17:51:41.733 6928-11039/? E/ProcessStats: Binding service ServiceState{8f38fc3 org.chromium.content.app.SandboxedProcessService0 pkg=com.brave.browser_nightly proc=f7713c3} without owner
2023-02-27 17:51:41.734 6928-11039/? W/ActivityManager: Exception when destroying service com.brave.browser_nightly/org.chromium.content.app.SandboxedProcessService0:299
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:653)
        at android.app.IApplicationThread$Stub$Proxy.scheduleStopService(IApplicationThread.java:1318)
        at com.android.server.am.ActiveServices.bringDownServiceLocked(ActiveServices.java:4976)
        at com.android.server.am.ActiveServices.bringDownServiceIfNeededLocked(ActiveServices.java:4791)
        at com.android.server.am.ActiveServices.removeConnectionLocked(ActiveServices.java:5162)
        at com.android.server.am.ActiveServices.unbindServiceLocked(ActiveServices.java:3310)
        at com.android.server.am.ActivityManagerService.unbindService(ActivityManagerService.java:15021)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2966)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3077)
        at android.os.Binder.execTransactInternal(Binder.java:1316)
        at android.os.Binder.execTransact(Binder.java:1280)
2023-02-27 17:51:41.734 6928-11039/? E/ProcessStats: Executing service ServiceState{8f38fc3 org.chromium.content.app.SandboxedProcessService0 pkg=com.brave.browser_nightly proc=f7713c3} without owner
2023-02-27 17:51:41.734 6928-11039/? E/ProcessStats: Foregrounding service ServiceState{8f38fc3 org.chromium.content.app.SandboxedProcessService0 pkg=com.brave.browser_nightly proc=f7713c3} without owner
2023-02-27 17:51:41.734 6928-11039/? E/ProcessStats: Binding service ServiceState{8f38fc3 org.chromium.content.app.SandboxedProcessService0 pkg=com.brave.browser_nightly proc=f7713c3} without owner
2023-02-27 17:51:41.734 6928-11039/? E/ProcessStats: Starting service ServiceState{8f38fc3 org.chromium.content.app.SandboxedProcessService0 pkg=com.brave.browser_nightly proc=f7713c3} without owner
2023-02-27 17:51:41.734 6928-11039/? E/ProcessStats: Starting service ServiceState{8f38fc3 org.chromium.content.app.SandboxedProcessService0 pkg=com.brave.browser_nightly proc=f7713c3} without owner
2023-02-27 17:51:41.734 6928-11039/? E/ProcessStats: Binding service ServiceState{8f38fc3 org.chromium.content.app.SandboxedProcessService0 pkg=com.brave.browser_nightly proc=f7713c3} without owner
```

## Steps to reproduce 

   1. Install 1.50.62 C111
   2. Enabled staging rewards env
   3. Connect to Uphold or Gemini
   4. Login, authorize and enter 2FA

## Actual result 
After 2FA screen, app stops responding and crashes later

![screenshot-1677533787397](https://user-images.githubusercontent.com/17885425/221707767-886cfa11-4ec7-4f76-84ff-e148c6eb6ceb.png)

## Expected result
Should connect successfully

## Issue reproduces how often 
Always

## Version/Channel Information: 

Not able to reproduce on nightly with C110 (1.50.58)

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy S21
   - Android version: 13
   
## Brave version
`1.50.62, Chromium 111.0.5563.33`

**Comment by kjozwiak** [comment]
The above requires `1.49.116` or higher for `1.49.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21` using version:

```
Brave	1.49.117 Chromium: 111.0.5563.50 (Official Build) (64-bit) 
Revision	39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS	Android 13; Build/TP1A.220624.014
```

- Ensured connecting to external rewards account is successful.
- Ensured app does not crash when logging in

<table><tr><td>

https://user-images.githubusercontent.com/17885425/222578972-f3a20652-313c-44ee-b23d-31faef6f7702.mp4

</td><td>

https://user-images.githubusercontent.com/17885425/222579063-a6fafd5d-d4ba-461b-80e1-dfc191315b5d.mp4

</td></tr></table>

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.49.118`

- Ensured that there is no crash when external custodian wallet Uphold/Gemini is connected 
- Ensured that there is no crash while sending one-time tip to a pubs
- Ensured that there is no crash while sending monthy tip to a pubs
- Ensured that there is no crash while sending default/custom tips to a pubs
- Ensured that there is no crash while performing AC

**_Uphold_**

Example | Example | Example | Example | Example | Example | Example | Example | Example | Example
----------|-----------|----------|-----------|-----------|----------|----------|-----------|-----------|---------


**_Gemini_**

Example | Example | Example | Example | Example | Example | Example | Example | Example | Example | Example | Example | Example
----------|-----------|----------|-----------|-----------|----------|----------|-----------|-----------|---------|---|----|----
![Screenshot_20230402-205154_Brave](https://user-images.githubusercontent.com/38657976/222769111-38523967-0f07-4c33-abb3-51bc52ab06ff.jpg) | ![Screenshot_20230402-205336_Brave](https://user-images.githubusercontent.com/38657976/222769128-3aff0679-f5da-4ab1-9cc4-c07bdb2966c0.jpg) | ![Screenshot_20230402-205343_Brave](https://user-images.githubusercontent.com/38657976/222769130-86d241dd-9d3a-4c49-8b74-bc3347c75313.jpg) | ![Screenshot_20230402-205353_Brave](https://user-images.githubusercontent.com/38657976/222769133-42df4b64-21fa-4327-9d54-d4cacbd8e826.jpg) | ![Screenshot_20230402-205405_Brave](https://user-images.githubusercontent.com/38657976/222769138-aa8859d7-fb22-41a6-a02a-3bb16d8c10ce.jpg) | ![Screenshot_20230402-205419_Brave](https://user-images.githubusercontent.com/38657976/222769141-d0516537-8c79-4caa-86bb-fc4d1e565c3e.jpg) | ![Screenshot_20230402-205444_Brave](https://user-images.githubusercontent.com/38657976/222769142-f7b4ee3a-26fe-437b-bef1-da4f7fac6c59.jpg) | ![Screenshot_20230402-205629_Brave](https://user-images.githubusercontent.com/38657976/222769147-0a260a3b-194e-40a4-b840-952cf0a9e4ab.jpg) | ![Screenshot_20230402-205721_Brave](https://user-images.githubusercontent.com/38657976/222769157-545d7555-8769-4a03-9445-a06f777ddf06.jpg) | ![Screenshot_20230402-211049_Brave](https://user-images.githubusercontent.com/38657976/222769159-c4de16c3-ca51-45ee-b1c5-b5d052952f56.jpg) | ![Screenshot_20230502-211816_Brave](https://user-images.githubusercontent.com/38657976/222769167-7e83e7b5-90b1-4c7b-9522-ec69c4ce0225.jpg) | ![Screenshot_20230502-211841_Brave](https://user-images.githubusercontent.com/38657976/222769171-c7bc63f0-787e-4fe8-bd50-24b1e8d69a26.jpg) | ![Screenshot_20230502-211900_Brave](https://user-images.githubusercontent.com/38657976/222769175-578e10a7-a9a5-4cc6-86cd-eaacb02b4c0a.jpg)
