### ISSUE TITLE
[Android] Crash on rewards tipping

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#29041]
I found that crash in backtrace on a stable 1.49.122 version. It's unknown why that could happen. Most likely Activity was on a state to be destroyed or was destroying. We would better catch `NullPointerException` and ignore it.
For verifying just make sure that tips go through.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setAlpha(float)' on a null object reference
        at org.chromium.chrome.browser.rewards.BraveRewardsTipConfirmationListener.V2(BraveRewardsTipConfirmationListener.java:5)
        at org.chromium.chrome.browser.BraveRewardsNativeWorker.onBalance(BraveRewardsNativeWorker.java:571)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loopOnce(Looper.java:186)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by kjozwiak** [comment]
The above requires `1.50.121` or higher for `1.50.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.50.121`

Ensured that one-time/monthly tipping worked without any crashes/obvious issues as per the following:

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------|---------------
![Screenshot_20230419_181716](https://user-images.githubusercontent.com/38657976/233083883-a9128e78-c9e4-4bda-b525-e00280020469.jpg) | ![Screenshot_20230419_181733](https://user-images.githubusercontent.com/38657976/233083901-b41970c1-5139-4cf5-8d1a-5f0016eff776.jpg) | ![Screenshot_20230419_181753](https://user-images.githubusercontent.com/38657976/233083911-095c40c6-b629-44ab-a21c-5d6f3e7a6b4e.jpg) | ![Screenshot_20230419_181848](https://user-images.githubusercontent.com/38657976/233083914-2863bdec-731f-481f-a786-5ac9591860f0.jpg) | ![Screenshot_20230519_182115](https://user-images.githubusercontent.com/38657976/233083917-1da828ef-3a9a-49b9-b41d-ed347241ad58.jpg)
