### ISSUE TITLE
Crash on Bottom Toolbar init

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#29184]
I found that crash in backtrace on a stable 1.49.122 version. It's unknown why that could happen. We better ignore that and keep an app alive. I think it's safe to fix and uplift as it will be just a null check. Nothing has to be done to verify that as it's on a bottom toolbar init. So basically make sure Brave opens.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'org.chromium.components.browser_ui.widget.gesture.SwipeGestureListener$SwipeHandler org.chromium.chrome.browser.compositor.layouts.LayoutManagerImpl.getToolbarSwipeHandler()' on a null object reference
        at org.chromium.chrome.browser.toolbar.bottom.BottomToolbarCoordinator.initializeWithNative(BottomToolbarCoordinator.java:270)
        at org.chromium.chrome.browser.toolbar.bottom.BraveBottomControlsCoordinator.initializeWithNative(BraveBottomControlsCoordinator.java:102)
        at org.chromium.chrome.browser.toolbar.BraveToolbarManager.initializeWithNative(BraveToolbarManager.java:287)
        at org.chromium.chrome.browser.ChromeTabbedActivity.initializeToolbarManager(ChromeTabbedActivity.java:863)
        at org.chromium.base.CallbackController$CancelableRunnable.run(CallbackController.java:130)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loopOnce(Looper.java:186)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8741)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by kjozwiak** [comment]
Going to label this as `QA/No` as this will get checked by default when QA runs through the reduced manual passes for the maintenance release.
