### ISSUE TITLE
Crash in set Brave as a default browser

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#29428]
I found that crash in `1.49.x`. We need fix it and uplift to a stable channel. For verifying just make sure that you can set Brave as a default browser via a dialog that appears on a 5th open of the browser.

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1610)
        at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1650)
        at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:341)
        at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:306)
        at androidx.fragment.app.DialogFragment.show(DialogFragment.java:508)
        at org.chromium.chrome.browser.set_default_browser.BraveSetDefaultBrowserUtils.showBraveSetDefaultBrowserDialog(BraveSetDefaultBrowserUtils.java:112)
        at org.chromium.chrome.browser.set_default_browser.BraveSetDefaultBrowserUtils.checkSetDefaultBrowserModal(BraveSetDefaultBrowserUtils.java:71)
        at org.chromium.chrome.browser.app.BraveActivity.finishNativeInitialization(BraveActivity.java:997)
        at org.chromium.chrome.browser.ChromeTabbedActivity.finishNativeInitialization(ChromeTabbedActivity.java:1029)
        at org.chromium.base.CallbackController$CancelableRunnable.run(CallbackController.java:130)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:339)
        at android.os.Looper.loop(Looper.java:200)
        at android.app.ActivityThread.main(ActivityThread.java:8312)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

**Comment by kjozwiak** [comment]
The above requires `1.50.117` or higher for `1.50.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on Samsung Galaxy S21 running Android 13 using the following version(s):

```
Brave	1.50.120 Chromium: 112.0.5615.121 (Official Build) (64-bit) 
Revision	39cc4e45904ae9f1741c4fbaa866e629c96f2268-refs/branch-heads/5615_51@{#8}
OS	Android 13; Build/TP1A.220624.014
```
- Ensured that crash does not occur when setting brave as default browser on the 5th app launch.

https://user-images.githubusercontent.com/17885425/232836837-c5934fb1-7030-4554-b993-4a7fdc9eec6c.mp4
