### ISSUE TITLE
Crash on DApps dialogs on Android 8

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#29538]
That issue was originally discovered by @vadimstruts and has such a crash stack. It exists in the current `1.49.132` stable.

```
2023-04-05 15:08:34.901  5064-5064  AndroidRuntime          com.brave.browser_default            E  FATAL EXCEPTION: main
                                                                                                    Process: com.brave.browser_default, PID: 5064
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.brave.browser_default/org.chromium.chrome.browser.crypto_wallet.activities.BraveWalletDAppsActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                                                    	at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                                    	at android.os.Looper.loop(Looper.java:164)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                                                    Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
                                                                                                    	at android.app.Activity.onCreate(Activity.java:986)
                                                                                                    	at androidx.core.app.ComponentActivity.onCreate(ComponentActivity.java:88)
                                                                                                    	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:378)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:216)
                                                                                                    	at org.chromium.chrome.browser.ChromeBaseAppCompatActivity.onCreate(ChromeBaseAppCompatActivity.java:97)
                                                                                                    	at org.chromium.chrome.browser.init.AsyncInitializationActivity.onCreateInternal(AsyncInitializationActivity.java:361)
                                                                                                    	at org.chromium.chrome.browser.init.AsyncInitializationActivity.onCreate(AsyncInitializationActivity.java:301)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:6975)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
                                                                                                    	at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                                    	at android.os.Looper.loop(Looper.java:164) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

Steps:
1. Create a wallet.
2. Go to `app.uniswap.org`.
3. Connect a wallet through the website and try to pick a different network there.

**Comment by kjozwiak** [comment]
The above requires `1.50.118` or higher for `1.50.x` verification 👍

**Comment by kjozwiak** [comment]
Going to label this one as `QA/No` as @srirambv verified the above via https://github.com/brave/brave-browser/issues/29655#issuecomment-1513061136 👍
