### ISSUE TITLE
Speechify extension not working in Brave Linux 

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#30377]
## Description 

The Speechify extension does not work in Linux but does work on macOS and Windows machines. There may be other extensions and or websites with similar functionality that are affected by this issue as well. Note that the extension does work fine when using Chrome on a Linux machine. The following console information is output when attempting to use the extension:
![image](https://github.com/brave/brave-browser/assets/3299098/18693b35-f3fd-4fd7-83d6-db8ebfb93a59)

[then after reload]
![image](https://github.com/brave/brave-browser/assets/3299098/2e7e0dfd-e72f-42e7-922f-0b782c6dbc11)
![image](https://github.com/brave/brave-browser/assets/3299098/36a945ce-0b3e-494d-9a34-7c189f4ebd19)

## Steps to Reproduce

   1. Install Speechify extension
   2. Visit site with text
   3. Attempt to use Speechify to read text to your

## Actual result:

Nothing happens

## Expected result:
Text should be read back to you

## Reproduces how often: 

Easily

## Version/Channel Information:

- Can you reproduce this issue with the current release? Y
- Can you reproduce this issue with the beta channel? Y
- Can you reproduce this issue with the nightly channel? Y

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N
- Does the issue resolve itself when disabling Brave Rewards? N
- Is the issue reproducible on the latest version of Chrome? N

## Miscellaneous Information:

User report:
https://community.brave.com/t/speechify-text-to-speech-app-and-extension-isnt-working-on-brave/486968/8

**Comment by rillian** [comment]
The CSP denial for the audio `data:` urls seems incorrect, and it's strange that it would be different on linux than on other platforms.

Might be worth checking the console on a system where the add-on works to see if those same errors are present, and thus unrelated to the problem?

**Comment by mr-michael-davies** [comment]
I am having the same issue.

From what I can tell this is the error I get when I hit play:

chunk-SIIC3S2O.js:19 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getProgressFromCursor')
    at Object.clickfalse (chunk-SIIC3S2O.js:19:904)
    at HTMLButtonElement.gt (chunk-YPPVDZBN.js:1:5054)
    
 As above, I am running on Manjaro Linux, works fine in Google Chrome (but not Chromium).

**Comment by rillian** [comment]
> works fine in Google Chrome (but not Chromium).

ouch

**Comment by hex20dec** [comment]
Same issue here. Running Ubuntu 20.04.6. Brave Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (64-bit).
With brave current build, I cannot even get it to install it speechify. Getting an error saying invalid manifest.
I tried the beta and nightly and was able to install the extension but getting similar errors in the console.

**Comment by pau1tuck** [comment]
Same issue here. Can't say I'm thrilled about having to switch to Google Chrome or Microsoft Edge just to use the app. The extension does work in both, however.

**Comment by phsb5321** [comment]
Hello guy, any solution so far ?
I'm having the same issue.

**Comment by mr-michael-davies** [comment]
> Hello guy, any solution so far ?
> I'm having the same issue.

I still have the same problem.

**Comment by marthinus-engelbrecht** [comment]
Having the same issue, this might be a deal breaker for me.

**Comment by SirLorrence** [comment]
Are you guys using the apt install package or flatpak? I'm having the same issue.

**Comment by phsb5321** [comment]
Hello, I'm using flatpack brave here. I'm having the same issue, any solution ?

**Comment by SirLorrence** [comment]
@phsb5321 As of now, using Google Chrome (yeah I know) on Linux is the best option until it's fixed. I've also tested Chromium flatpak, but Chrome just works better.

**Comment by phsb5321** [comment]
> @phsb5321 As of now, using Google Chrome (yeah I know) on Linux is the best option until it's fixed. I've also tested Chromium flatpak, but Chrome just works better.

Thanks, so sad about it. It just goes to show how hard it its to distance oneself from google.

**Comment by HaloGamer33** [comment]
The problem is also present on Arch linux with brave installed through yay.

**Comment by tech42676** [comment]
Same issue, tried flatpak and install from brave.com, same issue, also chromium has same issue as well.

**Comment by inomade-agencia** [comment]
I have the same problem. Using Brave on PopOS.

**Comment by eversondantas** [comment]
Same problem with Brave on Debian. Any workaround available (that does not include giving up on Brave or Speechify)?

**Comment by cycle-five** [comment]
Same issue still here on Ubuntu 24.04.

**Comment by stevenha75** [comment]
Same issue w/ LTS Pop OS

**Comment by ciczan** [comment]
Issue happens on "Ubuntu 24.04.1 LTS". 
And also opening articles from the app doesn´t work.

**Comment by ciczan** [comment]
Strangely, the Medium reader, that is based on Speechify works fine.

**Comment by SirLorrence** [comment]
It looks to be resolved with the recent patches. Is it working for anyone else also?
