### ISSUE TITLE
Crash after closing bookmarked tabs

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#30437]
## Description 
Crash when creating new tab after closing bookmarked tab(s)

```
2023-05-18 14:43:48.486 1440-1583/? I/WindowManager: Reparenting to original parent: Surface(name=b3f433c com.brave.browser_nightly/com.google.android.apps.chrome.Main)/@0x4ad41f, destroy=true, surface=Surface(name=4df06b4 PopupWindow:aab2ad3)/@0x85b25aa
2023-05-18 14:43:48.755 1326-1326/? I/LayerHistory: com.brave.browser_nightly/com.google.android.apps.chrome.Main$_26708#10770 Max (can't resolve refresh rate)
2023-05-18 14:43:48.813 1440-1582/? D/SGM:GameManager: identifyForegroundApp. com.brave.browser_nightly, mCurrentUserId: 0, callerUserId: 0
2023-05-18 14:43:48.813 1440-1582/? D/SGM:PkgDataHelper: getGamePkgData(). com.brave.browser_nightly
2023-05-18 14:43:50.017 1440-1495/? I/WindowManager: Reparenting to leash, surface=Surface(name=4df06b4 PopupWindow:aab2ad3)/@0x85b25aa, leashParent=Surface(name=b3f433c com.brave.browser_nightly/com.google.android.apps.chrome.Main)/@0x4ad41f
2023-05-18 14:43:50.020 1440-1495/? V/WindowManager: Changing focus from Window{4df06b4 u0 PopupWindow:aab2ad3 EXITING} to Window{b3f433c u0 com.brave.browser_nightly/com.google.android.apps.chrome.Main} displayId=0 Callers=com.android.server.wm.RootWindowContainer.updateFocusedWindowLocked:585 com.android.server.wm.WindowManagerService.updateFocusedWindowLocked:6715 com.android.server.wm.WindowState.setupWindowForRemoveOnExit:3201 com.android.server.wm.WindowState.removeIfPossible:3169 
2023-05-18 14:43:50.024 1440-1495/? D/WindowManager: updateSystemBarAttributes: displayId=0, win=Window{b3f433c u0 com.brave.browser_nightly/com.google.android.apps.chrome.Main}, navColorWin=Window{b3f433c u0 com.brave.browser_nightly/com.google.android.apps.chrome.Main}, focusedCanBeNavColorWin=false, behavior=1, appearance=24, statusBarAppearanceRegions=[AppearanceRegion{LIGHT_STATUS_BARS bounds=[0,0][1080,2400]}], requestedVisibilities=, from=com.android.server.wm.DisplayPolicy.focusChangedLw:3214 com.android.server.wm.DisplayContent.updateFocusedWindowLocked:4564 com.android.server.wm.RootWindowContainer.updateFocusedWindowLocked:585 
2023-05-18 14:43:50.026 2641-2641/? D/NavigationBar: onSystemBarAttributesChanged() -  displayId:0, appearance:24, packageName: com.brave.browser_nightly (APPEARANCE_LIGHT_STATUS_BARS APPEARANCE_LIGHT_NAVIGATION_BARS ), navbarColorManagedByIme:false
2023-05-18 14:43:50.045 1326-1326/? I/SurfaceFlinger: [b3f433c com.brave.browser_nightly/com.google.android.apps.chrome.Main#10720] FrameRatePriority: 1
2023-05-18 14:43:50.046 1440-4895/? D/InputDispatcher: Focus entered window (0): b3f433c com.brave.browser_nightly/com.google.android.apps.chrome.Main
2023-05-18 14:43:50.172 1440-1583/? I/WindowManager: Reparenting to original parent: Surface(name=b3f433c com.brave.browser_nightly/com.google.android.apps.chrome.Main)/@0x4ad41f, destroy=true, surface=Surface(name=4df06b4 PopupWindow:aab2ad3)/@0x85b25aa
2023-05-18 14:43:50.190 1326-1326/? D/SurfaceFlinger: Display 4630947232161729154 HWC layers:
         DEVICE | 0x79c4209a30 | 0002 | RGBA_8888    |    0.0    0.0 1080.0 2176.0 |    0   80 1080 2256 | com.brave.browser_nightly/ChromeChildSurface#10778
         DEVICE | 0x79c4215850 | 0100 | RGBA_8888    |    0.0    0.0 1080.0 2400.0 |    0    0 1080 2400 | com.brave.browser_nightly/com.google.android.apps.chrome.Main$_26708#10770
         DEVICE | 0x79c420ece0 | 0100 | RGBA_8888    |    0.0    0.0 1080.0   80.0 |    0    0 1080   80 | StatusBar$_2641#86
         DEVICE | 0x79c420c2b0 | 0100 | RGBA_8888    |    0.0    0.0   67.0  329.0 | 1013  436 1080  765 | com.samsung.android.app.cocktailbars[...]ervice.CocktailBarService$_4971#8973
         DEVICE | 0x79c421bfd0 | 0100 | RGBA_8888    |    0.0    0.0 1080.0  144.0 |    0 2256 1080 2400 | NavigationBar0$_2641#79
2023-05-18 14:43:50.554 1440-1582/? D/SGM:GameManager: identifyForegroundApp. com.brave.browser_nightly, mCurrentUserId: 0, callerUserId: 0
2023-05-18 14:43:50.554 1440-1582/? D/SGM:PkgDataHelper: getGamePkgData(). com.brave.browser_nightly
2023-05-18 14:43:50.700 1326-1326/? I/LayerHistory: com.brave.browser_nightly/com.google.android.apps.chrome.Main$_26708#10770 Max (can't resolve refresh rate)
2023-05-18 14:43:52.187 1440-1495/? I/ActivityManager: Killing 27245:com.brave.browser_nightly:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:7/u0a2153i-8993 (adj 0): isolated not needed
2023-05-18 14:43:52.199 1440-1495/? I/ActivityManager: Killing 27185:com.brave.browser_nightly:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:6/u0a2153i-8994 (adj 0): isolated not needed
2023-05-18 14:43:52.232 1440-5549/? E/ProcessStats: Executing service ServiceState{90040d4 org.chromium.content.app.SandboxedProcessService0 pkg=com.brave.browser_nightly proc=a5c5fb7} without owner
2023-05-18 14:43:52.235 1440-5549/? E/ProcessStats: Binding service ServiceState{90040d4 org.chromium.content.app.SandboxedProcessService0 pkg=com.brave.browser_nightly proc=a5c5fb7} without owner
2023-05-18 14:43:52.235 1440-5549/? E/ProcessStats: Starting service ServiceState{90040d4 org.chromium.content.app.SandboxedProcessService0 pkg=com.brave.browser_nightly proc=a5c5fb7} without owner
2023-05-18 14:43:52.235 1440-5549/? E/ProcessStats: Binding service ServiceState{90040d4 org.chromium.content.app.SandboxedProcessService0 pkg=com.brave.browser_nightly proc=a5c5fb7} without owner
2023-05-18 14:43:52.236 1440-5549/? I/ActivityManager: Killing 26966:com.brave.browser_nightly:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:3/u0a2153i-8997 (adj 0): isolated not needed
2023-05-18 14:43:52.248 26708-26778/? I/cr_TopSites: Finished saving top sites list to file:/data/user/0/com.brave.browser_nightly/app_top_sites/top_sites
2023-05-18 14:43:52.280 1440-1731/? I/ActivityManager: Start proc 27332:com.brave.browser_nightly:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:8/u0ai8 for  {com.brave.browser_nightly/org.chromium.content.app.SandboxedProcessService0:8}
2023-05-18 14:43:52.309 1440-5549/? I/ActivityManager: DSS OFF for com.brave.browser_nightly
2023-05-18 14:43:52.313 1440-5549/? D/DexController: init process display: set packageProcessId, displayId=0, same_package_proc=ProcessRecord{c718224 26708:com.brave.browser_nightly/u0a2153}, app=ProcessRecord{283f8dc 27332:com.brave.browser_nightly:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:8/u0a2153i-8992}
2023-05-18 14:43:52.313 1440-1495/? V/WindowManager: Relayout Window{b3f433c u0 com.brave.browser_nightly/com.google.android.apps.chrome.Main}: viewVisibility=0 req=1080x2400 d0
2023-05-18 14:43:52.317 26708-26708/? I/ViewRootImpl@f7ff343[Main]: updateBoundsLayer: t = android.view.SurfaceControl$Transaction@888f32 sc = Surface(name=Bounds for - com.brave.browser_nightly/com.google.android.apps.chrome.Main@1)/@0x896328b frame = 404
2023-05-18 14:43:52.341 27332-27332/? I/cr_SplitCompatApp: Launched version=114.1.53.47 minSdkVersion=1 isBundle=true processName=com.brave.browser_nightly:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:8 isIsolated=true
2023-05-18 14:43:52.625 1440-1495/? V/WindowManager: Relayout Window{b3f433c u0 com.brave.browser_nightly/com.google.android.apps.chrome.Main}: viewVisibility=0 req=1080x2400 d0
2023-05-18 14:43:52.627 26708-26708/? I/ViewRootImpl@f7ff343[Main]: updateBoundsLayer: t = android.view.SurfaceControl$Transaction@888f32 sc = Surface(name=Bounds for - com.brave.browser_nightly/com.google.android.apps.chrome.Main@1)/@0x896328b frame = 438
2023-05-18 14:43:52.723 26708-26748/? E/AndroidRuntime: FATAL EXCEPTION: GcStateAssertQueue
    Process: com.brave.browser_nightly, PID: 26708
    wn1: Object of type O5 was GC'ed without cleanup. Refer to "Caused by" for where object was created.
        at xn1.run(chromium-MonochromePublic6432.aab-canary-415304724:45)
     Caused by: wn1: vvv This is where object was created. vvv
        at zn1.a(chromium-MonochromePublic6432.aab-canary-415304724:7)
        at org.chromium.ui.base.WindowAndroid.<init>(chromium-MonochromePublic6432.aab-canary-415304724:14)
        at org.chromium.ui.base.WindowAndroid.<init>(chromium-MonochromePublic6432.aab-canary-415304724:2)
        at O5.<init>(chromium-MonochromePublic6432.aab-canary-415304724:8)
        at O5.<init>(chromium-MonochromePublic6432.aab-canary-415304724:4)
        at org.chromium.chrome.browser.app.bookmarks.BraveBookmarkActivity.onCreate(chromium-MonochromePublic6432.aab-canary-415304724:17)
        at android.app.Activity.performCreate(Activity.java:8578)
        at android.app.Activity.performCreate(Activity.java:8557)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4147)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4312)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2571)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8741)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
2023-05-18 14:43:52.730 1440-5549/? W/ActivityManager: crash : com.brave.browser_nightly,12153
```

## Steps to reproduce 

   1. Install `1.53.47, Chromium 114.0.5735.26`
   2. Open some tabs
   3. Open tab view, tap on 3 dot menu, select `Select tabs`
   4. Select all tabs then use 3 dot menu at the top right to bookmark tab(s)
   5. Open new tab
   6. Open Bookmarks, select tab/tabs bookmarked earlier
   7. In tab view, use 3 dot menu and `Close all` or select tabs and then `Close tab` from menu
   8. Now, open another new tab using `+`

## Actual result 

https://github.com/brave/brave-browser/assets/17885425/c77873cd-3201-49d1-b1bd-db178d96c375

## Expected result
Should not crash

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version?  No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS 21
   - Android version: 13
   
## Brave version
`1.53.47, Chromium 114.0.5735.26`

**Comment by SergeyZhukovsky** [comment]
cc @tapanmodh . That is related to the crash https://github.com/brave/brave-browser/issues/30408

**Comment by tapanmodh** [comment]
Thank you @Uni-verse and @SergeyZhukovsky. I'll fix it

**Comment by kjozwiak** [comment]
Removing the `C114` from title as the above isn't related to `C114` as per @SergeyZhukovsky. The above was related to the `Import/Export` which is only in `1.53.x` and not `1.52.x`.

**Comment by vlad-hoff** [comment]
Verified on `Google Pixel 7` and `Galaxy Tab S8` using version(s):
```
Device/OS: 
- Google Pixel 7 [panther_beta-user 14 UPB2.230407.014 release-keys]
- SM-X700 Galaxy Tab S8 [gts8wifixx-user 13 TP1A.220624.014 release-keys]
Brave build: 1.53.76
Chromium: 114.0.5735.90 (Official Build) beta (64-bit)
Revision: 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
```
---------------------------

**STEPS:**
   1. Launch Brave
   2. Open some tabs
   3. Open tab view, tap on 3 dot menu, select `Select tabs`
   4. Select all tabs then use 3 dot menu at the top right to bookmark tab(s)
   5. Open new tab
   6. Open Bookmarks, select tab/tabs bookmarked earlier
   7. In tab view, use 3 dot menu and `Close all` or select tabs and then `Close tab` from menu
   8. Now, open another new tab using `+`

**ACTUAL RESULTS:**
- Verified that Brave is not crashing when creating a new tab after closing bookmarked tab(s)

https://github.com/brave/brave-browser/assets/128532965/d361e1f8-aff7-4015-807f-8b5be6494b7b

https://github.com/brave/brave-browser/assets/128532965/2d6bc38a-8235-4455-b8a1-48fc8f3a0783
