### ISSUE TITLE
Crash on not earning dialog

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#30821]
I found that crash in backtrace on a stable 1.52.120 channel:

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1632)
        at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1672)
        at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:341)
        at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:306)
        at androidx.fragment.app.DialogFragment.show(DialogFragment.java:507)
        at org.chromium.chrome.browser.toolbar.top.BraveToolbarLayoutImpl$3.showNotificationNotEarningDialog(BraveToolbarLayoutImpl.java:550)
        at org.chromium.chrome.browser.toolbar.top.BraveToolbarLayoutImpl$3.onPageLoadFinished(BraveToolbarLayoutImpl.java:532)
        at org.chromium.chrome.browser.tab.TabImpl.didFinishPageLoad(TabImpl.java:1122)
        at org.chromium.chrome.browser.tab.TabWebContentsObserver$Observer.didFinishLoadInPrimaryMainFrame(TabWebContentsObserver.java:206)
        at org.chromium.content.browser.webcontents.WebContentsObserverProxy.didFinishLoadInPrimaryMainFrame(WebContentsObserverProxy.java:285)
        at org.chromium.content.browser.webcontents.WebContentsObserverProxy.didFinishLoadInPrimaryMainFrame(WebContentsObserverProxy.java:275)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loopOnce(Looper.java:186)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8757)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by kjozwiak** [comment]
The above requires `1.52.124` or higher for `1.52.x` verification 👍

**Comment by vlad-hoff** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 [panther_beta-user 14 UPB3.230519.008 release-keys]
Brave build: 1.52.125 
Chromium: 114.0.5735.110 (Official Build) (64-bit)
Revision: 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
```
---------------------------

**STEPS:**
1. Launch Brave > Enable Rewards in settings
2. Go to Android system setting > Apps > Find Brave > Notification, turn off notifications for Ads
3. Go back to Brave and go to `brave://rewards` > Verify the dialog 

**ACTUAL RESULTS:**
- Verified that dialog from https://github.com/brave/brave-core/pull/18766#issue-1743404090 is shown
- Verified that app crash is not happening
- Verified that closing notification pop-up message and refreshing the page, opens notification again

https://github.com/brave/brave-browser/assets/128532965/305c679a-fabb-4c22-82f9-5fce41b35814
