### ISSUE TITLE
uglifyjs not transpiling es6 is making builds impossible

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#309]
first reported by @bkero @mbacchi (thanks!)

STR: `yarn build Release --debug_build=false --official_build=true --channel=beta`
Result: See log below
Expected: Build should finish ok

<details>
<summary>error log (click to show)</summary>

```
13:12:53  94% asset optimization 1ms asset optimization
13:12:53  95% emitting 7ms emitting
13:12:53 Hash: 2e347febcb9b7f6e91a8
13:12:53 Version: webpack 3.12.0
13:12:53 Time: 4888ms
13:12:53                                  Asset       Size  Chunks                    Chunk Names
13:12:53   674f50d287a8c48dc19ba404d20fe713.eot     166 kB          [emitted]         
13:12:53   b6dd4b1292cfd4470e58486c56ad0832.svg    3.69 kB          [emitted]         
13:12:53   983d8695aa002ca6bd477e212eb0aa93.svg    1.14 kB          [emitted]         
13:12:53   d8b8faf285739ea99b0469855a73fb45.svg    1.14 kB          [emitted]         
13:12:53   e0d5b857416a206ba4d7096e598ad6d1.svg    1.14 kB          [emitted]         
13:12:53   6c337c63662ee0ba4e57f6f8156d69ce.svg    1.14 kB          [emitted]         
13:12:53   fd85070af5114d6ac462c466e78448e4.svg    3.75 kB          [emitted]         
13:12:53   314e7529efec41c8867019815f4d8dad.svg  882 bytes          [emitted]         
13:12:53   41943a7d37ac5c61823a2a17c4e06070.svg  733 bytes          [emitted]         
13:12:53 af7ae505a9eed503f8b8e6982036873e.woff2    77.2 kB          [emitted]         
13:12:53  fee66e712a8a08eef5805a46892932ad.woff      98 kB          [emitted]         
13:12:53   b06871f281fee6b241d60582ae9369b9.ttf     166 kB          [emitted]         
13:12:53   912ec66d7572ff821749319396470bde.svg     444 kB          [emitted]  [big]  
13:12:53 1ff8e6c958ca4fa6d8e8680f32cddd0d.woff2    38.1 kB          [emitted]         
13:12:53 8a06c170adbf19e0dffcbe868719e6ce.woff2    38.1 kB          [emitted]         
13:12:53                brave_new_tab.bundle.js     881 kB       0  [emitted]  [big]  brave_new_tab
13:12:53               brave_payments.bundle.js  539 bytes       1  [emitted]         brave_payments
13:12:53   [31] (webpack)/buildin/global.js 509 bytes {0} [built]
13:12:53        [] -> factory:281ms building:70ms = 351ms
13:12:53  [104] (webpack)/buildin/harmony-module.js 596 bytes {0} [built]
13:12:53        [] -> factory:282ms building:70ms = 352ms
13:12:53  [136] (webpack)/buildin/module.js 517 bytes {0} [built]
13:12:53        [] -> factory:23ms building:17ms = 40ms
13:12:53     + 416 hidden modules
13:12:53 
13:12:53 ERROR in brave_new_tab.bundle.js from UglifyJs
13:12:53 Unexpected token: operator (>) [brave_new_tab.bundle.js:2471,28]
13:12:53 npm ERR! code ELIFECYCLE
13:12:53 npm ERR! errno 2
13:12:53 npm ERR! brave@1.0.0 web-ui: `webpack --config src/brave/components/webpack/prod.config.js --progress --profile --colors`
13:12:53 npm ERR! Exit status 2
13:12:53 npm ERR! 
13:12:53 npm ERR! Failed at the brave@1.0.0 web-ui script.
13:12:53 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
13:12:53 
13:12:53 npm ERR! A complete log of this run can be found in:
13:12:53 npm ERR!     /home/ubuntu/.npm/_logs/2018-06-07T20_12_53_025Z-debug.log
13:12:53 
13:12:53 Traceback (most recent call last):
13:12:53   File "../../brave/script/transpile-web-ui.py", line 39, in <module>
13:12:53     sys.exit(main())
13:12:53   File "../../brave/script/transpile-web-ui.py", line 12, in main
13:12:53     transpile_web_uis('.', args.production, args.target_gen_dir[0])
13:12:53   File "../../brave/script/transpile-web-ui.py", line 36, in transpile_web_uis
13:12:53     execute_stdout(args, env)
13:12:53   File "/var/lib/jenkins/workspace/brave-browser-build-linux/src/brave/script/lib/util.py", line 182, in execute_stdout
13:12:53     execute(argv, env)
13:12:53   File "/var/lib/jenkins/workspace/brave-browser-build-linux/src/brave/script/lib/util.py", line 170, in execute
13:12:53     raise e
13:12:53 subprocess.CalledProcessError: Command '['npm', 'run', 'web-ui']' returned non-zero exit status 2
```
</details>

**Comment by cezaraugusto** [comment]
security audit asked in https://github.com/brave/internal/issues/367
