### ISSUE TITLE
Mojom serialisation/deserialisation crash while passing account object (Android)

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#31073]
## Description 
Mojom serialisation crash for pass account object (Android)

## Steps to reproduce 

   1. Open wallet, go to account tab
   2. Click on any account

## Actual result 
[serialization-crash.webm](https://github.com/brave/brave-browser/assets/11755381/f51c1a11-9301-4ae3-bf05-e740d12122d0)

## Expected result
App should not crash

## Issue reproduces how often 
easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version? Y

## Device details
   - Install type (ARM, x86): x86
   - Device type (Phone, Tablet, Phablet): phone
   - Android version: 11
   
## Brave version
1.54.61 Chromium: 114.0.5735.133 (Developer Build) unknown (32-bit) 

### Additional information

```
06-15 12:39:36.563  9142  9142 E AndroidRuntime: Process: com.brave.browser_default, PID: 9142
06-15 12:39:36.563  9142  9142 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.brave.browser_default/org.chromium.chrome.browser.crypto_wallet.activities.AccountDetailActivity}: org.chromium.mojo.bindings.DeserializationException: Incorrect memory range.
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7656)
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
06-15 12:39:36.563  9142  9142 E AndroidRuntime: Caused by: org.chromium.mojo.bindings.DeserializationException: Incorrect memory range.
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at org.chromium.mojo.bindings.Decoder$Validator.claimMemory(Decoder.java:85)
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at org.chromium.mojo.bindings.Decoder.readDataHeader(Decoder.java:144)
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at org.chromium.mojo.bindings.Decoder.readAndValidateDataHeader(Decoder.java:194)
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at org.chromium.brave_wallet.mojom.AccountInfo.decode(AccountInfo.java:59)
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at org.chromium.brave_wallet.mojom.AccountInfo.deserialize(AccountInfo.java:38)
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at org.chromium.brave_wallet.mojom.AccountInfo.deserialize(AccountInfo.java:47)
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at org.chromium.chrome.browser.crypto_wallet.util.WalletUtils.getAccountInfoFromIntent(WalletUtils.java:107)
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at org.chromium.chrome.browser.crypto_wallet.activities.AccountDetailActivity.triggerLayoutInflation(AccountDetailActivity.java:71)
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at org.chromium.chrome.browser.init.AsyncInitializationActivity.setContentViewAndLoadLibrary(AsyncInitializationActivity.java:192)
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at org.chromium.chrome.browser.init.ChromeBrowserInitializer.handlePreNativeStartupAndLoadLibraries(ChromeBrowserInitializer.java:170)
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at org.chromium.chrome.browser.init.AsyncInitializationActivity.onCreateInternal(AsyncInitializationActivity.java:383)
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at org.chromium.chrome.browser.init.AsyncInitializationActivity.onCreate(AsyncInitializationActivity.java:305)
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7994)
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7978)
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
06-15 12:39:36.563  9142  9142 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
```

cc: @supermassive

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.57.18 x64 Beta build
- Verified steps from issue description
- Verified no crash when selecting Accounts 

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/d41f92bf-1cb2-432d-a208-93d093b74ef3> | <video src=https://github.com/brave/brave-browser/assets/17010094/2e8bdae6-c3cf-4f96-877e-fb5ff2237a31>
