### ISSUE TITLE
Crash on `SelectedAccountResponsesCollector.java` when getting chain Id for origin for Filecoin

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#31103]
## Description 

Observing a crash on the line `mJsonRpcService.getChainIdForOrigin(CoinType.FIL, origin, chainId -> {` when launching the app.

Stacktrace:
```
2023-06-16 16:44:44.952 10845-10845/com.brave.browser_default A/chromium: Crash keys:
2023-06-16 16:44:44.952 10845-10845/com.brave.browser_default A/chromium:   "exception_info" = "org.chromium.mojo.bindings.SerializationException: Trying to encode a null pointer for a non-nullable type.
2023-06-16 16:44:44.952 10845-10845/com.brave.browser_default A/chromium:     at org.chromium.mojo.bindings.Encoder.encodeNullPointer(Encoder.java:510)
2023-06-16 16:44:44.952 10845-10845/com.brave.browser_default A/chromium:     at org.chromium.mojo.bindings.Encoder.encode(Encoder.java:214)
2023-06-16 16:44:44.952 10845-10845/com.brave.browser_default A/chromium:     at org.chromium.brave_wallet.mojom.JsonRpcService_Internal$JsonRpcServiceGetChainIdForOriginParams.encode(JsonRpcService_Internal.java:4797)
2023-06-16 16:44:44.952 10845-10845/com.brave.browser_default A/chromium:     at org.chromium.mojo.bindings.Struct.serializeWithHeader(Struct.java:81)
2023-06-16 16:44:44.952 10845-10845/com.brave.browser_default A/chromium:     at org.chromium.brave_wallet.mojom.JsonRpcService_Internal$Proxy.getChainIdForOrigin(JsonRpcService_Internal.java:480)
2023-06-16 16:44:44.952 10845-10845/com.brave.browser_default A/chromium:     at org.chromium.chrome.browser.crypto_wallet.util.SelectedAccountResponsesCollector.getAccounts(SelectedAccountResponsesCollector.java:53)
2023-06-16 16:44:44.952 10845-10845/com.brave.browser_default A/chromium:     at org.chromium.chrome.browser.app.domain.CryptoModel.lambda$refreshTransactions$7$org-chromium-chrome-browser-app-domain-CryptoModel(CryptoModel.java:213)
2023-06-16 16:44:44.952 10845-10845/com.brave.browser_default A/chromium:     at org.chromium.chrome.browser.app.domain.CryptoModel$$ExternalSyntheticLambda6.call(Unknown Source:6)
2023-06-16 16:44:44.952 10845-10845/com.brave.browser_default A/chromium:     at org.chromium.brave_wallet.mojom.KeyringService_Internal$KeyringServiceGetAllAccountsResponseParamsForwardToCallback.accept(KeyringService_Internal.java:4869)
2023-06-16 16:44:44.952 10845-10845/com.brave.browser_default A/chromium:     at org.chromium.mojo.bindings.RouterImpl.handleIncomingMessage(RouterImpl.java:235)
2023-06-16 16:44:44.952 10845-10845/com.brave.browser_default A/chromium:     at org.chromium.mojo.bindings.RouterImpl.-$$Nest$mhandleIncomingMessage(Unknown Source:0)
2023-06-16 16:44:44.952 10845-10845/com.brave.browser_default A/chromium:     at org.chromium.mojo.bindings.RouterImpl$HandleIncomingMessageThunk.accept(RouterImpl.java:33)
2023-06-16 16:44:44.952 10845-10845/com.brave.browser_default A/chromium:     at org.chromium.mojo.bindings.Connector.readAndDispatchMessage(Connector.java:210)
2023-06-16 16:44:44.952 10845-10845/com.brave.browser_default A/chromium:     at org.chromium.mojo.bindings.Connector.readOutstandingMessages(Connector.java:176)
2023-06-16 16:44:44.952 10845-10845/com.brave.browser_default A/chromium:     at org.chromium.mojo.bindings.Connector.onWatcherResult(Connector.java:152)
2023-06-16 16:44:44.952 10845-10845/com.brave.browser_default A/chromium:     at org.chromium.mojo.bindings.Connector.-$$Nest$monWatcherResult(Unknown Source:0)
2023-06-16 16:44:44.952 10845-10845/com.brave.browser_default A/chromium:     at org.chromium.mojo.bindings.Connector$WatcherCallback.onResult(Connector.java:142)
2023-06-16 16:44:44.952 10845-10845/com.brave.browser_default A/chromium:     at org.chromium.mojo.system.impl.WatcherImpl.onHandleReady(WatcherImpl.java:56)
2023-06-16 16:44:44.952 10845-10845/com.brave.browser_default A/chromium:     at android.os.MessageQueue.nativePollOnce(Native Method)
2023-06-16 16:44:44.952 10845-10845/com.brave.browser_default A/chromium:     at android.os.MessageQueue.next(MessageQueue.java:335)
2023-06-16 16:44:44.952 10845-10845/com.brave.browser_default A/chromium:     at android.os.Looper.loop(Looper.java:183)
2023-06-16 16:44:44.952 10845-10845/com.brave.browser_default A/chromium:     at android.app.ActivityThread.main(ActivityThread.java:7656)
2023-06-16 16:44:44.952 10845-10845/com.brave.browser_default A/chromium:     at java.lang.reflect.Method.invoke(Native Method)
2023-06-16 16:44:44.952 10845-10845/com.brave.browser_default A/chromium:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
2023-06-16 16:44:44.952 10845-10845/com.brave.browser_default A/chromium: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)" 
```

**Comment by Pavneet-Sing** [comment]
Removing QA/Yes as it cannot be tested without enabling filecoin support. @simoarpe will test it and confirm. TIA!

**Comment by simoarpe** [comment]
Tested locally, issue fixed.
