### ISSUE TITLE
Crash on Brave news

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#31823]
I found that crash in GPS on nightly 1.58.38.
```
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views. Expected: main Calling: ThreadPoolForeg
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9972)
        at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:2002)
        at android.view.View.requestLayout(View.java:26417)
        at android.view.View.requestLayout(View.java:26417)
        at android.view.View.requestLayout(View.java:26417)
        at android.view.View.requestLayout(View.java:26417)
        at android.view.View.requestLayout(View.java:26417)
        at android.view.View.requestLayout(View.java:26417)
        at android.view.View.requestLayout(View.java:26417)
        at android.view.View.requestLayout(View.java:26417)
        at android.view.View.requestLayout(View.java:26417)
        at android.view.View.requestLayout(View.java:26417)
        at android.view.View.requestLayout(View.java:26417)
        at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:4917)
        at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.triggerUpdateProcessor(RecyclerView.java:6096)
        at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeInserted(RecyclerView.java:6071)
        at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeInserted(RecyclerView.java:13186)
        at androidx.recyclerview.widget.RecyclerView$Adapter.notifyItemInserted(RecyclerView.java:8149)
        at org.chromium.chrome.browser.ntp.BraveNtpAdapter.setNewsLoading(BraveNtpAdapter.java:502)
        at org.chromium.chrome.browser.ntp.BraveNewTabPageLayout.lambda$getFeed$10(BraveNewTabPageLayout.java:898)
```

It's caused by that PR https://github.com/brave/brave-core/pull/19294. We should call UI work on UI thread https://github.com/brave/brave-core/pull/19294/files#diff-6257f9d8d05fe791ce3819781a80d04f5557b55f66c4c686ce939c73d7245a1fL894

**Comment by SergeyZhukovsky** [comment]
There is another crash related to the above PR as well:
```
java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView{1aae4fd VFE...... ......I. 0,123-1080,1896 #7f010a32 app:id/recyclerview}, adapter:VE@2a1cf24, layout:org.chromium.chrome.browser.brave_news.LinearLayoutManagerWrapper@88ccec6, context:org.chromium.chrome.browser.ChromeTabbedActivity@6b66e9e
        at androidx.recyclerview.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:3477)
        at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeInserted(RecyclerView.java:6069)
        at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeInserted(RecyclerView.java:13186)
        at androidx.recyclerview.widget.RecyclerView$Adapter.notifyItemInserted(RecyclerView.java:8149)
        at org.chromium.chrome.browser.ntp.BraveNtpAdapter.setNewsLoading(BraveNtpAdapter.java:502)
        at org.chromium.chrome.browser.ntp.BraveNewTabPageLayout.lambda$getFeed$10(BraveNewTabPageLayout.java:898)
```
We would be ok if we call the UI modifications in the UI thread as well here.

**Comment by kjozwiak** [comment]
@AlexeyBarabash ran into the above as well and mentioned the following via Slack:

> (1) [c3c80800-b231-6e0a-0000-000000000000](https://brave.sp.backtrace.io/p/brave/debug?filters=W1siX3J4aWQiLCJlcXVhbCIsImMzYzgwODAwLWIyMzEtNmUwYS0wMDAwLTAwMDAwMDAwMDAwMCJdXQ%3D%3D&fingerprint=dff172ed7003c50ac45fbcf62a69214fb232226171896ec302f400fa51fb3b54&debug=(%2253efdd8%22,0,0))
> (3) [a6c80800-b231-6e0a-0000-000000000000](https://brave.sp.backtrace.io/p/brave/debug?filters=W1siX2RlbGV0ZWQiLCJlcXVhbCIsIjAiXSxbIl9yeGlkIiwiZXF1YWwiLCJhNmM4MDgwMC1iMjMxLTZlMGEtMDAwMC0wMDAwMDAwMDAwMDAiXV0%3D&fingerprint=e713e01e966ca9a0bfbf0e92fcac7abda1f58b37fdd29aeb8de66a2ec6b2f122&debug=(%2253efdbb%22,0,0))
> (2) [b3c80800-b231-6e0a-0000-000000000000](https://brave.sp.backtrace.io/p/brave/debug?filters=W1siX2RlbGV0ZWQiLCJlcXVhbCIsIjAiXSxbIl9yeGlkIiwiZXF1YWwiLCJiM2M4MDgwMC1iMjMxLTZlMGEtMDAwMC0wMDAwMDAwMDAwMDAiXV0%3D&fingerprint=e713e01e966ca9a0bfbf0e92fcac7abda1f58b37fdd29aeb8de66a2ec6b2f122&debug=(%2253efdc8%22,0,0))
> (4) [a5c80800-b231-6e0a-0000-000000000000](https://brave.sp.backtrace.io/p/brave/debug?filters=W1siX2RlbGV0ZWQiLCJlcXVhbCIsIjAiXSxbIl9yeGlkIiwiZXF1YWwiLCJhNWM4MDgwMC1iMjMxLTZlMGEtMDAwMC0wMDAwMDAwMDAwMDAiXV0%3D&fingerprint=e713e01e966ca9a0bfbf0e92fcac7abda1f58b37fdd29aeb8de66a2ec6b2f122&debug=(%2253efdba%22,0,0))
> (5) [ccb50800-b231-6e0a-0000-000000000000](https://brave.sp.backtrace.io/p/brave/debug?filters=W1siX2RlbGV0ZWQiLCJlcXVhbCIsIjAiXSxbIl9yeGlkIiwiZXF1YWwiLCJjY2I1MDgwMC1iMjMxLTZlMGEtMDAwMC0wMDAwMDAwMDAwMDAiXV0%3D&fingerprint=e713e01e966ca9a0bfbf0e92fcac7abda1f58b37fdd29aeb8de66a2ec6b2f122&debug=(%2253eeaf1%22,0,0))
> 
> 
> All are Java exceptions and happened just when I clicked the website shortcut on new tab page. (1), (2), (3) happened when I used phone in split screen mode with Brave at bottom part; (4) and (5) happened in normal mode, Brave

Added the above for some more context re: how to possibly reproduce the above crashes that @SergeyZhukovsky found.

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21 5G` using version:

```
1.58.106 Chromium: 116.0.5845.114 (Official Build) beta (64-bit) 
Revision	601f5c9afccc48f581021ae0e0ee6c85b58821d2
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
- Ensured does not happen for each of the conditions mentioned in https://github.com/brave/brave-browser/issues/31823#issuecomment-1650118887
- Ensured open Brave News articles works

Example | Example
-|-
![Screenshot 2023-09-05 at 4 24 52 PM](https://github.com/brave/brave-browser/assets/17885425/6a5793ac-2bb2-4a70-9182-9d646928f678) | ![Screenshot 2023-09-05 at 6 27 28 PM](https://github.com/brave/brave-browser/assets/17885425/d6738192-b801-4fbe-886c-f954707359d7)
