### ISSUE TITLE
Crash after opening wallet on registerForActivityResult

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#31882]
## Description 
Crash after opening wallet on registerForActivityResult on latest master.

## Steps to reproduce 

   1. Sync core
   2. Log into wallet
   3. Crashing on [registerForActivityResult](https://github.com/brave/brave-core/blob/master/android/java/org/chromium/chrome/browser/crypto_wallet/fragments/NftGridFragment.java#L139)

## Actual result 
Using `registerForActivityResult` is causing a crash

## Expected result
App should not crash

## Issue reproduces how often 
easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version? N
- Can you reproduce this issue with the current master? Y

## Device details
   - Install type (ARM, x86):  x86
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version:  11 or 8
   
## Brave version
1.58.48 Chromium: 115.0.5790.114 (Developer Build) unknown (32-bit) 

### Additional info
[Discussion thread](https://bravesoftware.slack.com/archives/C03MMJ4CHEZ/p1690368517151229)

```
07-26 15:27:05.018 15170 15170 E AndroidRuntime: java.lang.VerifyError: Verifier rejected class androidx.fragment.app.Fragment$7: androidx.activity.result.ActivityResultRegistry androidx.fragment.app.Fragment$7.apply(java.lang.Void) failed to verify: androidx.activity.result.ActivityResultRegistry androidx.fragment.app.Fragment$7.apply(java.lang.Void): [0x19] 'this' argument 'Reference: android.app.Activity' not instance of 'Reference: androidx.activity.ComponentActivity' (declaration of 'androidx.fragment.app.Fragment$7' appears in /data/app/~~Rt6IN19vfBFH6-fbNMklpw==/com.brave.browser_default-WoRBWl_NRMkUuVKpZPtrZA==/base.apk)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at androidx.fragment.app.Fragment.registerForActivityResult(Fragment.java:3571)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at org.chromium.chrome.browser.crypto_wallet.fragments.NftGridFragment.onCreateView(NftGridFragment.java:139)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3114)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:557)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1751)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:274)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1247)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1095)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1619)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.view.View.measure(View.java:25466)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.widget.LinearLayout.measureVertical(LinearLayout.java:995)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.view.View.measure(View.java:25466)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.view.View.measure(View.java:25466)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:142)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.view.View.measure(View.java:25466)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.view.View.measure(View.java:25466)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.view.View.measure(View.java:25466)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.view.View.measure(View.java:25466)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:747)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.view.View.measure(View.java:25466)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3397)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2228)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2486)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:731)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7656)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
07-26 15:27:05.018 15170 15170 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.58.117 x64 build
- Verified steps from [brave/brave-core#19452](https://github.com/brave/brave-core/pull/19452)
- Verified no crash when opening wallet
- Verified no crash hiding NFTs
- Verified no crash when re-enabling NFTs
- Encountered [#32864](https://github.com/brave/brave-browser/issues/32864)

https://github.com/brave/brave-browser/assets/17010094/46184c7f-3dbc-4a6d-9726-7d26fec01c7a
