### ISSUE TITLE
Searching for "theme" in brave://settings page doesn't work

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#32013]
Looks like a regression with cr116 bump:

STR:

1. Open Nightly (e.g. 1.58.57)
2. Navigate to brave://settings
3. Click on the search icon
4. Type in "theme" into the search box

**Observe:**
* No results found.
* Open DevTools and observe multiple instances of the following error:
<pre>
shared.rollup.js:27 Uncaught Error: Assertion failed: An associated control was expected for SETTINGS-SUBPAGE themes, but was not found.
    at assert (shared.rollup.js:27:55)
    at revealParentSection (settings.js:4132:2177)
    at doSearch (settings.js:4132:1278)
    at doSearch (settings.js:4132:1699)
    at doSearch (settings.js:4132:1699)
    at doSearch (settings.js:4132:1699)
    at doSearch (settings.js:4132:1781)
    at doSearch (settings.js:4132:1699)
    at doSearch (settings.js:4132:1699)
    at doSearch (settings.js:4132:1699)
</pre>

**Expected result:**
Searching for theme returns results with "Get started" and "Appearance" pages.

**Edit:** In a debug build the results are shown, but the console error is still present.

**Comment by mkarolin** [comment]
This is no longer reproducible (1.68.6 Nightly/1.67.78 Beta/1.65.132 Release).
