### ISSUE TITLE
Settings WebUI doesn't load fully in Debug build on master.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#32514]
Likely due to https://github.com/brave/brave-core/pull/19377

STR:
1. Build Debug build of Brave on the master branch
2. Start Brave and navigate to brave://settings
3. Observe settings menu is loaded (with missing icons) but the right hand side isn't.
4. Open Console and observe errors:
<pre>
Uncaught TypeError: Cannot read properties of undefined (reading 'has')
    at prototype._updateIcon (iron_icon.js:86:34)
    at Object.Me [as fn] (polymer_bundled.min.js:1:30905)
    at me (polymer_bundled.min.js:1:25407)
    at i._propertiesChanged (polymer_bundled.min.js:1:36523)
    at i._flushProperties (polymer_bundled.min.js:1:18048)
    at i.ready (polymer_bundled.min.js:1:36184)
    at i.ready (polymer_bundled.min.js:1:49541)
    at i.ready (polymer_bundled.min.js:1:80233)
    at i.ready (polymer_bundled.min.js:1:87021)
    at i._enableProperties (polymer_bundled.min.js:1:17854)
</pre>

cc: @fallaciousreasoning

**Comment by fallaciousreasoning** [comment]
That's almost certainly the cause @mkarolin - I'll take a look

**Comment by fallaciousreasoning** [comment]
Interesting, what OS are you on, as it seems to be working fine on Linux (tip of tree)

**Comment by mkarolin** [comment]
@fallaciousreasoning on Windows:

From what I saw, the assignment of leo objects to the window happens after iron-icons tries to look for it.

1.59.46 Chromium: 116.0.5845.114 (Developer Build) (64-bit) 

![image](https://github.com/brave/brave-browser/assets/41635752/c4ac066e-44a7-4ee8-9a9f-d2768978337f)
