### ISSUE TITLE
[Android] Add foregroundservice type for android 14 changes

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#32906]
## Description 
With CR117, we are targeting android 14. and for android 14, we have to declare a foreground service type for the service we use for wireguard tunnel. 

## Steps to reproduce 

   1. install 1.60.10 nightly build
   2. enable vpn from QA pref
   3. buy the subscription
   4. try to enable the vpn

## Actual result 
Crash with below stack : 
`java.lang.RuntimeException: Unable to start service org.chromium.chrome.browser.vpn.wireguard.WireguardService@31afc0e with Intent { cmp=com.brave.browser_nightly/org.chromium.chrome.browser.vpn.wireguard.WireguardService }: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{c8fb904 9249:com.brave.browser_nightly/u0a485} targetSDK=34
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4839)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2289)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    Caused by: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{c8fb904 9249:com.brave.browser_nightly/u0a485} targetSDK=34
                                                                                                    	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
                                                                                                    	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
                                                                                                    	at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
                                                                                                    	at android.os.Parcel.readParcelable(Parcel.java:4852)
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3041)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3024)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2966)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at KG2.invoke(chromium-MonochromePublic6432.aab-canary-426000722:22)
                                                                                                    	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
                                                                                                    	at $Proxy8.setServiceForeground(Unknown Source)
                                                                                                    	at android.app.Service.startForeground(Service.java:775)
                                                                                                    	at uP3.e(chromium-MonochromePublic6432.aab-canary-426000722:19)
                                                                                                    	at fS2.onStartCommand(chromium-MonochromePublic6432.aab-canary-426000722:3)
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4821)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2289) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205) 
                                                                                                    	at android.os.Looper.loop(Looper.java:294) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) `

## Expected result
Vpn should work as expected

## Issue reproduces how often 
easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Going to label this one as `QA/No` & `release-notes/exclude` as this will basically get checked/verified via https://github.com/brave/brave-browser/issues/30673 👍 @vlad-hoff @deeppandya please change if you feel differently.
