### ISSUE TITLE
App crashes shortly after launch on fresh profile [Android 8.1.0]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#32988]
## Description 
App crashes shortly after launch on fresh profile, happening in 1.58.x. Regression as this does not crash in 1.57.x using same steps. 

Not reproducible on `Samsung GS 21` | `Android 13`

```
2023-09-13 16:44:33.900 1922-1922/? W/ResourceType: Failure getting entry for 0x7f010d5e (t=0 e=3422) (error -75)
2023-09-13 16:44:33.978 1922-1982/? D/OpenGLRenderer: HWUI GL Pipeline
2023-09-13 16:44:33.980 1922-1922/? D/AndroidRuntime: Shutting down VM
2023-09-13 16:44:33.980 1922-1922/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.brave.browser, PID: 1922
    java.lang.RuntimeException: Unable to instantiate service com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService: java.lang.ClassNotFoundException: Didn't find class "com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService" on path: DexPathList[[zip file "/data/app/com.brave.browser-eVC6uZo8OfRnoW9o2rm_9Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.brave.browser-eVC6uZo8OfRnoW9o2rm_9Q==/lib/arm64, /data/app/com.brave.browser-eVC6uZo8OfRnoW9o2rm_9Q==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3324)
        at android.app.ActivityThread.-wrap4(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService" on path: DexPathList[[zip file "/data/app/com.brave.browser-eVC6uZo8OfRnoW9o2rm_9Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.brave.browser-eVC6uZo8OfRnoW9o2rm_9Q==/lib/arm64, /data/app/com.brave.browser-eVC6uZo8OfRnoW9o2rm_9Q==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3321)
        at android.app.ActivityThread.-wrap4(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

## Steps to reproduce 

   1. Fresh install
   2. Complete onboarding
   3. Wait 30 seconds or so
   4. Does not matter what user does in this time. 
   
## Actual result 
App crashes after launch

https://github.com/brave/brave-browser/assets/17885425/8e46e890-630a-4345-abcc-084bfc93b96a

## Expected result
Should not crash

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? TBD 
- Can you reproduce this issue with the current Play Store Nightly version? TBD

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 2 XL
   - Android version: 8.1.0
   
## Brave version
1.58.122

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.58.124` or higher for `1.58.x` verification 👍

**Comment by Uni-verse** [comment]
Created follow up below as this is still reproducible on Android 8.1.0 using GPS build (1.58.124)

https://github.com/brave/brave-browser/issues/33011

**Comment by kjozwiak** [comment]
> Created follow up below as this is still reproducible on Android 8.1.0 using GPS build (1.58.124)
> 
> #33011

As per the above, removing the `QA/Yes` label as we'll verify the above via https://github.com/brave/brave-browser/issues/33010 & https://github.com/brave/brave-browser/issues/33011.
