### ISSUE TITLE
[Follow up to #32988] App crash on Android 8

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#33011]
## Description 
App crashes every 30 seconds on Android 8, restarting does not fix.

```
2023-09-14 09:41:52.007 30795-30795/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.brave.browser, PID: 30795
    java.lang.RuntimeException: Unable to instantiate service com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService: java.lang.ClassNotFoundException: Didn't find class "com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService" on path: DexPathList[[zip file "/data/app/com.brave.browser-5ycD0blPKiw3xJnaAw6s5Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.brave.browser-5ycD0blPKiw3xJnaAw6s5Q==/lib/arm64, /data/app/com.brave.browser-5ycD0blPKiw3xJnaAw6s5Q==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3324)
        at android.app.ActivityThread.-wrap4(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService" on path: DexPathList[[zip file "/data/app/com.brave.browser-5ycD0blPKiw3xJnaAw6s5Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.brave.browser-5ycD0blPKiw3xJnaAw6s5Q==/lib/arm64, /data/app/com.brave.browser-5ycD0blPKiw3xJnaAw6s5Q==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3321)
        at android.app.ActivityThread.-wrap4(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
2023-09-14 09:41:52.636 31359-31359/? D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10160 <<<<<<
```

## Steps to reproduce 

   1. Install 1.58.x
   2. Launch app
   3. Wait 1-2 minutes to confirm

## Actual result 
Crashes

## Expected result
No crash

## Issue reproduces how often 
Always 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? No

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 2 XL 
   - Android version: 8.1.0
   
## Brave version
1.58.124, 1.58.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Closing the above as this was fixed via https://github.com/brave/brave-core/pull/20166. @deeppandya will be creating a PR for `master` and also an uplift into `1.59.x` once @SergeyZhukovsky & @vlad-hoff verify that the above has been fixed on `Android 8`, `Android 13` & `Android 14` 👍

**Comment by Uni-verse** [comment]
Verified on Pixel 2 XL using version(s):

```
Brave	1.58.125 Chromium: 117.0.5938.62 (Official Build) (64-bit) 
Revision	8ed90c22c7a876855ef8cb4c2872dd7b69beb594
OS	Android 8.1.0; Build/OPM2.171026.006.H1; 27; REL
```
- Ensured no crashes are happening on new profile as well as existing profile (1.57 -> 1.58)

Example | Example
-|-
![Screenshot 2023-09-14 at 9 16 39 PM](https://github.com/brave/brave-browser/assets/17885425/74402e46-f7d9-4223-aebe-0041811842a3) | ![Screenshot 2023-09-14 at 9 22 12 PM](https://github.com/brave/brave-browser/assets/17885425/7a847ae0-c86b-4651-9907-1f2de7cb3768)
