### ISSUE TITLE
Brave ANR/crash on first launch [1.58.124]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#33010]
## Description 
Brave crashes often with latest GPS build (1.58.124) on first launch. App is sluggish and device heats up. Possibly related to billing client (see logs)

Crash report ID: fde90100-0209-b80a-0000-000000000000
Verbose logs: [SamsungGS21_logcat1.log](https://github.com/brave/brave-browser/files/12611347/SamsungGS21_logcat1.log)

```
2023-09-14 12:24:38.445 1629-3608/? W/ActivityManager: Exception when unbinding service com.brave.browser/org.chromium.content.app.PrivilegedProcessService0
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:662)
        at android.app.IApplicationThread$Stub$Proxy.scheduleUnbindService(IApplicationThread.java:1445)
        at com.android.server.am.ActiveServices.removeConnectionLocked(ActiveServices.java:5194)
        at com.android.server.am.ActiveServices.killServicesLocked(ActiveServices.java:5734)
        at com.android.server.am.ActivityManagerService.cleanUpApplicationRecordLocked(ActivityManagerService.java:14698)
        at com.android.server.am.ActivityManagerService.handleAppDiedLocked(ActivityManagerService.java:3842)
        at com.android.server.am.ActivityManagerService.appDiedLocked(ActivityManagerService.java:4036)
        at com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied(ActivityManagerService.java:1832)
        at android.os.IBinder$DeathRecipient.binderDied(IBinder.java:323)
        at android.os.BinderProxy.sendDeathNotice(BinderProxy.java:781)

```
```
2023-09-14 12:24:38.512 1629-2011/? W/WindowManager: Exception thrown during dispatchAppVisibility Window{8a434f8 u0 com.brave.browser/com.google.android.apps.chrome.Main EXITING}
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:662)
        at android.view.IWindow$Stub$Proxy.dispatchAppVisibility(IWindow.java:658)
        at com.android.server.wm.WindowState.sendAppVisibilityToClients(WindowState.java:4200)
        at com.android.server.wm.WindowContainer.sendAppVisibilityToClients(WindowContainer.java:1246)
        at com.android.server.wm.WindowToken.setClientVisible(WindowToken.java:431)
        at com.android.server.wm.ActivityRecord.setClientVisible(ActivityRecord.java:7691)
        at com.android.server.wm.ActivityRecord.onAnimationFinished(ActivityRecord.java:8590)
        at com.android.server.wm.ActivityRecord.postApplyAnimation(ActivityRecord.java:6252)
        at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:6224)
        at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:6228)
        at com.android.server.wm.AppTransitionController.handleClosingApps(AppTransitionController.java:1279)
        at com.android.server.wm.AppTransitionController.handleAppTransitionReady(AppTransitionController.java:304)
        at com.android.server.wm.RootWindowContainer.checkAppTransitionReady(RootWindowContainer.java:1182)
        at com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace(RootWindowContainer.java:1022)
        at com.android.server.wm.RootWindowContainer.performSurfacePlacement(RootWindowContainer.java:950)
        at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop(WindowSurfacePlacer.java:185)
        at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:134)
        at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:123)
        at com.android.server.wm.WindowSurfacePlacer$Traverser.run(WindowSurfacePlacer.java:65)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.os.HandlerThread.run(HandlerThread.java:67)
        at com.android.server.ServiceThread.run(ServiceThread.java:44)
## Steps to reproduce <!-- Please add a series of steps to reproduce the issue -->
```

   1. Install 1.58.124 (GPS internal beta)
   2. Launch App
   3. Begin to interact/try typing in url bar

## Actual result 
UI hangs/performance issues observed followed by ANR/crash

![Screenshot 2023-09-14 at 11 30 36 AM](https://github.com/brave/brave-browser/assets/17885425/f1f27e37-7762-4557-a1ae-c4ed426d6766)

## Expected result
No crash

## Issue reproduces how often 
50%

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No 
- Can you reproduce this issue with the current Play Store Nightly version? No

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS 21 
   - Android version: Android 13
   
## Brave version
1.58.124

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

[SamsungGS21_logcat1.log](https://github.com/brave/brave-browser/files/12611347/SamsungGS21_logcat1.log)

**Comment by kjozwiak** [comment]
Closing the above as this was fixed via https://github.com/brave/brave-core/pull/20166. @deeppandya will be creating a PR for `master` and also an uplift into `1.59.x` once @SergeyZhukovsky & @vlad-hoff verify that the above has been fixed on `Android 8`, `Android 13` & `Android 14` 👍

**Comment by Uni-verse** [comment]
Verified on `Android 8` per https://github.com/brave/brave-browser/issues/33011#issuecomment-1720358144 & https://github.com/brave/brave-browser/issues/33011#issuecomment-1720368693

**Comment by Uni-verse** [comment]
Verified on Samsung Galaxy S21 5G using version(s):

```
Brave	1.58.125 Chromium: 117.0.5938.62 (Official Build) (64-bit) 
Revision	8ed90c22c7a876855ef8cb4c2872dd7b69beb594
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured no performance issues or ANRs are observed on fresh install as well as on upgraded profile.
- Ensured Brave Rewards, Shields and changing default setting does not cause performance issues or ANR. 
- Ensured re-launching app several times and opening some tabs does not cause ANR or sluggishness.
