### ISSUE TITLE
[Android] Billing client 6.0.1 issue with end connection

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#33090]
We have an issue with billing client with below stack : 

```
Exception java.lang.OutOfMemoryError: Could not allocate JNI Env: Failed anonymous mmap(0x0, 8192, 0x3, 0x22, -1, 0): Operation not permitted. See process maps in the log.
  at java.lang.Thread.nativeCreate
  at java.lang.Thread.start (Thread.java:883)
  at java.util.concurrent.ThreadPoolExecutor.addWorker (ThreadPoolExecutor.java:975)
  at java.util.concurrent.ThreadPoolExecutor.execute (ThreadPoolExecutor.java:1382)
  at java.util.concurrent.AbstractExecutorService.submit (AbstractExecutorService.java:140)
  at com.android.billingclient.api.BillingClientImpl.zzS (com.android.billingclient:billing@@6.0.1:3)
  at com.android.billingclient.api.BillingClientImpl.zzo (BillingClientImpl.java:51)
  at com.android.billingclient.api.zzaf.onServiceConnected (com.android.billingclient:billing@@6.0.1:4)
  at android.app.LoadedApk$ServiceDispatcher.doConnected (LoadedApk.java:2007)
  at android.app.LoadedApk$ServiceDispatcher$RunConnection.run (LoadedApk.java:2039)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7615)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:964)
```

Based on above stack, we may need to explicitly end the connection for the billing client. 

I am unable to reproduce the issue on the devices i have with android 7.1, android 8, android 11 and android 14 with strict mode enabled. 

There is another stack that is most likely related to the above resources leakage and has a common fix:
```
java.lang.IllegalStateException: Too many receivers, total of 1000, registered for pid: 23338, callerPackage: http://webaddress.elided/
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2445)
        at android.os.Parcel.createException(Parcel.java:2421)
        at android.os.Parcel.readException(Parcel.java:2404)
        at android.os.Parcel.readException(Parcel.java:2346)
        at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6524)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1838)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1799)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:760)
        at org.chromium.base.compat.ApiHelperForO.registerReceiver(ApiHelperForO.java:139)
        at org.chromium.base.ContextUtils.registerBroadcastReceiver(ContextUtils.java:301)
        at org.chromium.base.ContextUtils.registerProtectedBroadcastReceiver(ContextUtils.java:226)
        at org.chromium.chrome.browser.night_mode.PowerSavingModeMonitor.start(PowerSavingModeMonitor.java:84)
        at org.chromium.chrome.browser.night_mode.PowerSavingModeMonitor.updateAccordingToAppState(PowerSavingModeMonitor.java:70)
        at org.chromium.chrome.browser.night_mode.PowerSavingModeMonitor.lambda$new$0(PowerSavingModeMonitor.java:63)
        at org.chromium.base.ApplicationStatus.onStateChange(ApplicationStatus.java:501)
        at org.chromium.base.ApplicationStatus$2.onActivityStarted(ApplicationStatus.java:372)
        at android.app.Application.dispatchActivityStarted(Application.java:405)
        at android.app.Activity.dispatchActivityStarted(Activity.java:1406)
        at android.app.Activity.onStart(Activity.java:1922)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:344)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
        at org.chromium.chrome.browser.init.AsyncInitializationActivity.onStart(AsyncInitializationActivity.java:530)
        at org.chromium.chrome.browser.app.ChromeActivity.onStart(ChromeActivity.java:1402)
        at org.chromium.chrome.browser.ChromeTabbedActivity.onStart(ChromeTabbedActivity.java:3007)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
        at android.app.Activity.performStart(Activity.java:8315)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4060)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by kjozwiak** [comment]
The above requires `1.58.129` or higher for `1.58.x` verification 👍 @Uni-verse @vlad-hoff changed to `QA/Yes` so we can at least run through a quick spot check of VPN.

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7` using the following build version(s):

```
Brave	1.58.129 Chromium: 117.0.5938.88 (Official Build) (64-bit) 
Revision	0ab74dc5473bd9dcd0a85653872988a5655aff6b
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
- Ensured purchasing and installing VPN is succesful.
- Ensured tunneling is working by using `ipinfo.io`.
- Ensured purchasing yearly subscription on `fresh` profile and monthly subscription on `existing` profile enables VPN.
- Ensured switching to another region will update the VPN.
- Ensured searching on fresh profile via the URL bar does not cause freezing or ANR/crash. 
- Ensured restarting Brave does not cause performance issues. 

Example | Example | Example | Example
-|-|-|-
![Screenshot 2023-09-20 at 6 20 51 PM](https://github.com/brave/brave-browser/assets/17885425/686c0229-29f5-4f7c-bc4b-40ee6b7c248f) | ![Screenshot 2023-09-20 at 6 21 02 PM](https://github.com/brave/brave-browser/assets/17885425/341edb3d-7bf5-4ae8-a816-c091a63f73fc) | ![Screenshot 2023-09-20 at 6 21 23 PM](https://github.com/brave/brave-browser/assets/17885425/fc257004-0b6c-4ece-ab57-6b9fc11b2067) | ![Screenshot 2023-09-20 at 6 23 02 PM](https://github.com/brave/brave-browser/assets/17885425/2c377065-35be-49e0-93d7-2740b71fc26d)
