### ISSUE TITLE
Perf tests failures after CR118 merge

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#33328]
The issue with telemetry patches.
```
18:38:10  [ RUN      ] speedometer2/Speedometer2
18:38:10  LocalServerBackend started: [{"name": "http", "port": 56523}]
18:38:10  
18:38:10  
18:38:10  (WARNING) 2023-09-29 04:37:19,383 inspector_log._OnMessage:28  DevTools console [network]: Failed to load resource: the server responded with a status of 404 (File not found) 
18:38:10  http://127.0.0.1:56523/favicon.ico
18:38:10  (WARNING) 2023-09-29 04:38:02,947 shared_page_state.DumpStateUponStoryRunFailure:108  Cannot dump browser state: No browser.
18:38:10  (ERROR) 2023-09-29 04:38:03,049 story_runner.RunStorySet:360  Exception raised during story run.
18:38:10  Traceback (most recent call last):
18:38:10    File "C:\jenkins\x64-nightly\src\third_party\catapult\telemetry\telemetry\internal\story_runner.py", line 349, in RunStorySet
18:38:10      _RunStoryAndProcessErrorIfNeeded(story, results, state, test,
18:38:10    File "C:\jenkins\x64-nightly\src\third_party\catapult\telemetry\telemetry\internal\story_runner.py", line 198, in _RunStoryAndProcessErrorIfNeeded
18:38:10      state.DidRunStory(results)
18:38:10    File "C:\jenkins\x64-nightly\src\third_party\catapult\common\py_trace_event\py_trace_event\trace_event_impl\decorators.py", line 55, in traced_function
18:38:10      return func(*args, **kwargs)
18:38:10    File "C:\jenkins\x64-nightly\src\third_party\catapult\telemetry\telemetry\page\shared_page_state.py", line 123, in DidRunStory
18:38:10      self._StopBrowser()
18:38:10    File "C:\jenkins\x64-nightly\src\third_party\catapult\telemetry\telemetry\page\shared_page_state.py", line 347, in _StopBrowser
18:38:10      self._possible_browser.CleanUpEnvironment()
18:38:10    File "C:\jenkins\x64-nightly\src\third_party\catapult\telemetry\telemetry\internal\browser\possible_browser.py", line 107, in CleanUpEnvironment
18:38:10      self._TearDownEnvironment()
18:38:10    File "C:\jenkins\x64-nightly\src\brave\script\override_utils.py", line 57, in wrapped_method
18:38:10      return new_method(self, original_method, *args, **kwargs)
18:38:10    File "<string>", line 14, in _TearDownEnvironment
18:38:10    File "C:\Users\administrator.WIN-HPLAPTOP1-S\.vpython-root\store\python_venv-54gcscaqn8232r91aoaskcr66c\contents\lib\shutil.py", line 733, in rmtree
18:38:10      if _rmtree_islink(path):
18:38:10    File "C:\Users\administrator.WIN-HPLAPTOP1-S\.vpython-root\store\python_venv-54gcscaqn8232r91aoaskcr66c\contents\lib\shutil.py", line 577, in _rmtree_islink
18:38:10      st = os.lstat(path)
18:38:10  TypeError: lstat: path should be string, bytes or os.PathLike, not NoneType
18:38:10  (ERROR) 2023-09-29 04:38:03,049 page_test_results.Fail:305  Traceback (most recent call last):
18:38:10    File "C:\jenkins\x64-nightly\src\third_party\catapult\telemetry\telemetry\internal\story_runner.py", line 349, in RunStorySet
18:38:10      _RunStoryAndProcessErrorIfNeeded(story, results, state, test,
18:38:10    File "C:\jenkins\x64-nightly\src\third_party\catapult\telemetry\telemetry\internal\story_runner.py", line 198, in _RunStoryAndProcessErrorIfNeeded
18:38:10      state.DidRunStory(results)
18:38:10    File "C:\jenkins\x64-nightly\src\third_party\catapult\common\py_trace_event\py_trace_event\trace_event_impl\decorators.py", line 55, in traced_function
18:38:10      return func(*args, **kwargs)
18:38:10    File "C:\jenkins\x64-nightly\src\third_party\catapult\telemetry\telemetry\page\shared_page_state.py", line 123, in DidRunStory
18:38:10      self._StopBrowser()
18:38:10    File "C:\jenkins\x64-nightly\src\third_party\catapult\telemetry\telemetry\page\shared_page_state.py", line 347, in _StopBrowser
18:38:10      self._possible_browser.CleanUpEnvironment()
18:38:10    File "C:\jenkins\x64-nightly\src\third_party\catapult\telemetry\telemetry\internal\browser\possible_browser.py", line 107, in CleanUpEnvironment
18:38:10      self._TearDownEnvironment()
18:38:10    File "C:\jenkins\x64-nightly\src\brave\script\override_utils.py", line 57, in wrapped_method
18:38:10      return new_method(self, original_method, *args, **kwargs)
18:38:10    File "<string>", line 14, in _TearDownEnvironment
18:38:10    File "C:\Users\administrator.WIN-HPLAPTOP1-S\.vpython-root\store\python_venv-54gcscaqn8232r91aoaskcr66c\contents\lib\shutil.py", line 733, in rmtree
18:38:10      if _rmtree_islink(path):
18:38:10    File "C:\Users\administrator.WIN-HPLAPTOP1-S\.vpython-root\store\python_venv-54gcscaqn8232r91aoaskcr66c\contents\lib\shutil.py", line 577, in _rmtree_islink
18:38:10      st = os.lstat(path)
18:38:10  TypeError: lstat: path should be string, bytes or os.PathLike, not NoneType
18:38:10 
```

**Comment by atuchin-m** [comment]
Can't reproduce, it was a problem with a custom compare configuration.
I will reopen if needed.
