### ISSUE TITLE
Crash in a crypto wallet component

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#33386]
I found that crash in a backtrace on a stable 1.58.135. We should fix and uplift to the stable channel.

```
java.util.UnknownFormatConversionException: Conversion = 'End of String'
        at java.util.Formatter$FormatSpecifierParser.peek(Formatter.java:2642)
        at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2603)
        at java.util.Formatter.parse(Formatter.java:2558)
        at java.util.Formatter.format(Formatter.java:2505)
        at java.util.Formatter.format(Formatter.java:2459)
        at java.lang.String.format(String.java:2870)
        at org.chromium.chrome.browser.crypto_wallet.fragments.onboarding_fragments.DownloadComponentProgressFragment.showHideProgressByItem(DownloadComponentProgressFragment.java:104)
        at org.chromium.chrome.browser.crypto_wallet.fragments.onboarding_fragments.DownloadComponentProgressFragment.lambda$setupDownloadProgress$0(DownloadComponentProgressFragment.java:71)
        at org.chromium.chrome.browser.component_updater.BraveComponentUpdater.componentStateUpdated(BraveComponentUpdater.java:91)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:206)
        at android.app.ActivityThread.main(ActivityThread.java:8653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by kjozwiak** [comment]
The above requires `1.59.113` or higher for `1.59.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.59.115 x64 build
- Verified steps from [brave/brave-core#20378](https://github.com/brave/brave-core/pull/20378)
- Verified no crash when Wallet data file component is being downloaded on backup wallet screen
- Verified both during onboarding and manually launching the backup wallet screen when component is being downloaded
