### ISSUE TITLE
i already run the registration with

### ISSUE THREAD

**Issue by cemcemi** [brave/brave-browser#37381]
i already run the registration with 
`accountManager.requestSmsVerificationCode(false, captcha, challenge);`
without any problem. the verification code already sent to the phone number that has been included. but when i tried to verify it with code
 ```
accountManager.verifyAccountWithCode(verificationCode, store.getSignalingKey(),
                store.getLocalRegistrationId(), false, PIN, unidentifiedAccessKey, true);
```
and when it executed in my main class. an error occurs like this:
```
Exception in thread "main" org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: Bad response: 400 
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:894)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:791)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.verifyAccountCode(PushServiceSocket.java:223)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.verifyAccountWithCode(SignalServiceAccountManager.java:203)
```

any idea?

i'm using jdk 1.8 and signal-service-java version 2.15.3

_Ursprünglich gepostet von @hanunggulmp in https://github.com/signalapp/libsignal-service-java/issues/84_

**Comment by ShivanKaul** [comment]
This doesn't look related to Brave.

**Comment by bsclifton** [comment]
The only way I can see this maybe related to Brave would be if push messaging not working on the site

You can try to enable `Use Google services for push messaging` here (requires a relaunch):
brave://settings/privacy
