### ISSUE TITLE
Crash in BookmarkEditActivity.onDestroy

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#37687]
We have that crash stack from users from time to time. Maybe we call something wrong and it causes upstream code to crash:

```
java.lang.RuntimeException: Unable to destroy activity {HTTP://WEBADDRESS.ELIDED}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5468)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5497)
	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:102)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2313)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:263)
	at android.app.ActivityThread.main(ActivityThread.java:8266)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at org.chromium.chrome.browser.app.bookmarks.BookmarkEditActivity.onDestroy(chromium-MonochromePublic64.aab-stable-426411624:21)
	at android.app.Activity.performDestroy(Activity.java:8399)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1345)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5453)
	... 11 more
```

**Comment by SergeyZhukovsky** [comment]
That issue has been fixed by upstream
https://github.com/chromium/chromium/commit/85140bca464f8ea1ff9a082a33f9c655ebf48e8e
https://issues.chromium.org/issues/333030305
