### ISSUE TITLE
After the last update of Nightly version it completely stopped working.

### ISSUE THREAD

**Issue by NotMainstream** [brave/brave-browser#38027]
After the last update of Brave Nightly on Android it completely stopped working. Every time I click on Brave icon the browser appears and then disappears after 2 seconds. I looked through the logs but could not see anything relevant. Please check it out.

**Comment by Wyckoffan** [comment]
Same here, I am using Pixel 8 with Graphene OS, here the log:

type: crash
osVersion: google/shiba/shiba:14/AP1A.240405.002.B1/2024042200:user/release-keys
package: com.brave.browser_nightly:426706124
process: com.brave.browser_nightly
processUptime: 1391 + 357 ms
installer: com.aurora.store

org.chromium.base.JniAndroid$UncaughtExceptionException: Native stack trace:
#00 pc 0x0000000005205353 /data/app/~~947CyxXp1GCgeApmCqgC-A==/com.brave.browser_nightly-TulH09c95aK9Vsz0N-R_Cw==/base.apk (offset 0x19cc000)
#01 pc 0x000000000756ae57 /data/app/~~947CyxXp1GCgeApmCqgC-A==/com.brave.browser_nightly-TulH09c95aK9Vsz0N-R_Cw==/base.apk (offset 0x19cc000)
#02 pc 0x0000000007567c4f /data/app/~~947CyxXp1GCgeApmCqgC-A==/com.brave.browser_nightly-TulH09c95aK9Vsz0N-R_Cw==/base.apk (offset 0x19cc000)
#03 pc 0x00000000051fa983 /data/app/~~947CyxXp1GCgeApmCqgC-A==/com.brave.browser_nightly-TulH09c95aK9Vsz0N-R_Cw==/base.apk (offset 0x19cc000)
#04 pc 0x00000000051facab /data/app/~~947CyxXp1GCgeApmCqgC-A==/com.brave.browser_nightly-TulH09c95aK9Vsz0N-R_Cw==/base.apk (offset 0x19cc000)
#05 pc 0x00000000063b0d1b /data/app/~~947CyxXp1GCgeApmCqgC-A==/com.brave.browser_nightly-TulH09c95aK9Vsz0N-R_Cw==/base.apk (offset 0x19cc000)
#06 pc 0x0000000006da148b /data/app/~~947CyxXp1GCgeApmCqgC-A==/com.brave.browser_nightly-TulH09c95aK9Vsz0N-R_Cw==/base.apk (offset 0x19cc000)
#07 pc 0x0000000006da1433 /data/app/~~947CyxXp1GCgeApmCqgC-A==/com.brave.browser_nightly-TulH09c95aK9Vsz0N-R_Cw==/base.apk (offset 0x19cc000)
#08 pc 0x0000000006da13a7 /data/app/~~947CyxXp1GCgeApmCqgC-A==/com.brave.browser_nightly-TulH09c95aK9Vsz0N-R_Cw==/base.apk (offset 0x19cc000)
#09 pc 0x0000000000000683 /system/lib64/libutils.so
#10 pc 0x00000000000b6593 /system/lib64/libandroid_runtime.so

	at org.chromium.base.JniAndroid.handleException(chromium-MonochromePublic64.aab-canary-426706124:21)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:344)
	at android.os.Looper.loopOnce(Looper.java:189)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.SecurityException: com.brave.browser_nightly: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3191)
	at android.os.Parcel.createException(Parcel.java:3175)
	at android.os.Parcel.readException(Parcel.java:3151)
	at android.os.Parcel.readException(Parcel.java:3093)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5799)
	at java.lang.reflect.Method.invoke(Native Method)
	at hB2.invoke(chromium-MonochromePublic64.aab-canary-426706124:22)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy9.registerReceiverWithFeature(Unknown Source)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1885)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1825)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1813)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:756)
	at pO3.b(chromium-MonochromePublic64.aab-canary-426706124:28)
	at pO3.c(chromium-MonochromePublic64.aab-canary-426706124:21)
	at cC.O(chromium-MonochromePublic64.aab-canary-426706124:1883)
	at org.chromium.chrome.browser.ChromeTabbedActivity.O(chromium-MonochromePublic64.aab-canary-426706124:8)
	at pX.run(chromium-MonochromePublic64.aab-canary-426706124:194)
	at xP.run(chromium-MonochromePublic64.aab-canary-426706124:8)
	... 10 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14425)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2623)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2802)
	at android.os.Binder.execTransactInternal(Binder.java:1525)
	at android.os.Binder.execTransact(Binder.java:1464)
	
	
Some Copilot suggestions:

The crash report you provided indicates that the crash occurred in the `com.brave.browser_nightly` package of the Brave browser's nightly build. The crash seems to be related to a `java.lang.SecurityException` and a `android.os.RemoteException` that were thrown during the execution of the application.

The key part of the error message is:

```java
java.lang.SecurityException: com.brave.browser_nightly: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
```

This exception is thrown when an application tries to register a broadcast receiver in its manifest file without specifying whether the receiver is exported (can be called by other apps) or not exported (cannot be called by other apps). 

The second part of the crash report indicates that the crash was caused by a `android.os.RemoteException`. This exception is thrown when a `RemoteException` is encountered during the execution of a remote procedure call (RPC). 

The key part of the error message is:

```java
android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14425)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2623)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2802)
	at android.os.Binder.execTransactInternal(Binder.java:1525)
	at android.os.Binder.execTransact(Binder.java:1464)
```

This indicates that the `registerReceiverWithFeature` method in the `ActivityManagerService` class caused the `RemoteException`. This method is part of the Android operating system's internal APIs and is used to register a broadcast receiver.

To debug this issue, you would need to look into the specific code where the `registerReceiverWithFeature` method is called and ensure that for each receiver declared in the manifest file, either `RECEIVER_EXPORTED` or `RECEIVER_NOT_EXPORTED` is specified. It's also recommended to check the inter-process communication between your application and the Android system services.

Please note that this is a high-level analysis based on the information provided in the crash report. For a more detailed analysis, you may need to look into the specific code where the exception is thrown. It's also recommended to test the application thoroughly after making any changes to ensure that the issue is resolved and no new issues are introduced. If the problem persists, consider reaching out to the Brave browser's support or developer community for more specific guidance.

**Comment by Wyckoffan** [comment]
Yes, I confirm as well the issue being solved with the latest update.
