### ISSUE TITLE
HBO/MAX does NOT work on Brave

### ISSUE THREAD

**Issue by shivv3r** [brave/brave-browser#38950]
### Description

Hi, there is an issue since like a month or two with Brave while trying to play content from HBO/MAX. I've tried few devices and I have the same issue everywhere with Brave, but if I use another browser Firefox/Edge it works without any issues.

![image](https://github.com/brave/brave-browser/assets/63784451/7c2b69c2-4280-4fba-8292-e9b6346898ee)

### Steps to reproduce

1. Login to HBO/MAX
2. Try to play something
3. The error page appears 

### Actual result

![image](https://github.com/brave/brave-browser/assets/63784451/2c0bc76e-fd7a-4129-a846-dd93193aeafc)

### Expected result

The video should play.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.66.118

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [X] in the latest version of Chrome

**Comment by rebron** [comment]
cc: @ryanbr

**Comment by drone1** [comment]
Same for me. and here are my logs:

```
default.beam-amer.prd.api.max.com/users/me/customAttributes/webVideoPlaybackSettings:1 
            
            
           Failed to load resource: the server responded with a status of 404 ()
chunk-play-core-app.e38d2b7665cb8b2b3aaa.sha.js:1489 Unexpected optIn result, retrying communicating with the Adobe Visitor api.
reviewConsents @ chunk-play-core-app.e38d2b7665cb8b2b3aaa.sha.js:1489
gtm.js:1 
            
            
           Failed to load resource: net::ERR_NAME_NOT_RESOLVED
dpm.demdex.net/id?d_visid_ver=5.2.0&d_fieldgroup=AAM&d_rtbd=json&d_ver=2&d_orgid=BC501253513148ED0A490D45%40AdobeOrg&d_nsid=0&d_mid=31759613949328126416574919744214045946&ts=1741279385051:1 
            
            
           Failed to load resource: net::ERR_NAME_NOT_RESOLVED
sdk.iad-01.braze.com/api/v3/data/:1 
            
            
           Failed to load resource: net::ERR_NAME_NOT_RESOLVED
VM80 brightline.webkit.sdk.2.2.2.js:1342 {adSessionID: 'beam', advertisingIdentifier: null, appSessionId: 'beam', applicationIdentifier: 'play.max.com', applicationName: 'beam', …}
VM80 brightline.webkit.sdk.2.2.2.js:103 [BL]  [BL] config Request failed: 0
VM80 brightline.webkit.sdk.2.2.2.js:1356 
            
            
           POST https://services.brightline.tv/api/v2/config/1018 net::ERR_NAME_NOT_RESOLVED
init @ VM80 brightline.webkit.sdk.2.2.2.js:1356
init @ 7439.530f23b9b6dcf525aea2.sha.js:1
Xd @ 7439.530f23b9b6dcf525aea2.sha.js:322
create @ 7439.530f23b9b6dcf525aea2.sha.js:322
initialize @ 19697.bbdb95fd283f2a74a814.sha.js:1
ve @ 48335.44aed5a34360f853ed3b.sha.js:1
buildPlayerWithUI @ 48335.44aed5a34360f853ed3b.sha.js:1
(anonymous) @ 96551.3bbabbea24d431ed5070.sha.js:32
ri @ 11819.c2ee4768672e4aaff79c.sha.js:2
Ss @ 11819.c2ee4768672e4aaff79c.sha.js:2
(anonymous) @ 11819.c2ee4768672e4aaff79c.sha.js:2
S @ 11819.c2ee4768672e4aaff79c.sha.js:2
T @ 11819.c2ee4768672e4aaff79c.sha.js:2
95016.d85949794888f4bde783.sha.js:1 
            
            
           GET https://pagead2.googlesyndication.com/getconfig/sodar?tid=pal&tv=1.0 net::ERR_NAME_NOT_RESOLVED
bn @ 95016.d85949794888f4bde783.sha.js:1
(anonymous) @ 95016.d85949794888f4bde783.sha.js:1
nn @ 95016.d85949794888f4bde783.sha.js:1
mn @ 95016.d85949794888f4bde783.sha.js:1
ln.get @ 95016.d85949794888f4bde783.sha.js:1
ut @ 95016.d85949794888f4bde783.sha.js:1
rt @ 95016.d85949794888f4bde783.sha.js:1
yt @ 95016.d85949794888f4bde783.sha.js:1
getGooglePalNonce @ 7439.530f23b9b6dcf525aea2.sha.js:1
Qo._getPALNonce @ 7439.530f23b9b6dcf525aea2.sha.js:1
(anonymous) @ 7439.530f23b9b6dcf525aea2.sha.js:1
(anonymous) @ 34669.b76b14e1eecae01bf4af.sha.js:1
n._trySubscribe @ 2930.f14d5dd8aea0400e6572.sha.js:1
(anonymous) @ 2930.f14d5dd8aea0400e6572.sha.js:1
i @ 2930.f14d5dd8aea0400e6572.sha.js:1
n.subscribe @ 2930.f14d5dd8aea0400e6572.sha.js:1
(anonymous) @ 34669.b76b14e1eecae01bf4af.sha.js:1
(anonymous) @ 2930.f14d5dd8aea0400e6572.sha.js:1
(anonymous) @ 2930.f14d5dd8aea0400e6572.sha.js:1
i @ 2930.f14d5dd8aea0400e6572.sha.js:1
n.subscribe @ 2930.f14d5dd8aea0400e6572.sha.js:1
o @ 34669.b76b14e1eecae01bf4af.sha.js:1
(anonymous) @ 34669.b76b14e1eecae01bf4af.sha.js:1
n._trySubscribe @ 2930.f14d5dd8aea0400e6572.sha.js:1
(anonymous) @ 2930.f14d5dd8aea0400e6572.sha.js:1
i @ 2930.f14d5dd8aea0400e6572.sha.js:1
n.subscribe @ 2930.f14d5dd8aea0400e6572.sha.js:1
(anonymous) @ 2930.f14d5dd8aea0400e6572.sha.js:1
(anonymous) @ 2930.f14d5dd8aea0400e6572.sha.js:1
(anonymous) @ 2930.f14d5dd8aea0400e6572.sha.js:1
i @ 2930.f14d5dd8aea0400e6572.sha.js:1
n.subscribe @ 2930.f14d5dd8aea0400e6572.sha.js:1
(anonymous) @ 34669.b76b14e1eecae01bf4af.sha.js:1
(anonymous) @ 2930.f14d5dd8aea0400e6572.sha.js:1
(anonymous) @ 2930.f14d5dd8aea0400e6572.sha.js:1
i @ 2930.f14d5dd8aea0400e6572.sha.js:1
n.subscribe @ 2930.f14d5dd8aea0400e6572.sha.js:1
(anonymous) @ 34669.b76b14e1eecae01bf4af.sha.js:1
a @ 34669.b76b14e1eecae01bf4af.sha.js:1
build @ 7439.530f23b9b6dcf525aea2.sha.js:1
resolve @ chunk-play-core-app.e38d2b7665cb8b2b3aaa.sha.js:1489
(anonymous) @ 48335.44aed5a34360f853ed3b.sha.js:1
Promise.then
_load @ 48335.44aed5a34360f853ed3b.sha.js:1
(anonymous) @ 48335.44aed5a34360f853ed3b.sha.js:1
Promise.then
load @ 48335.44aed5a34360f853ed3b.sha.js:1
(anonymous) @ 96551.3bbabbea24d431ed5070.sha.js:32
ri @ 11819.c2ee4768672e4aaff79c.sha.js:2
Ss @ 11819.c2ee4768672e4aaff79c.sha.js:2
(anonymous) @ 11819.c2ee4768672e4aaff79c.sha.js:2
S @ 11819.c2ee4768672e4aaff79c.sha.js:2
T @ 11819.c2ee4768672e4aaff79c.sha.js:2
b30920b0-c371-4649-a603-ec212a27944f:1 Uncaught (in promise) Dl {message: '6', stack: 'Error: 6\n    at new Dl (https://play.max.com/95016…x.com/95016.d85949794888f4bde783.sha.js:1:112266)', g: 0}g: 0message: "6"stack: "Error: 6\n    at new Dl (https://play.max.com/95016.d85949794888f4bde783.sha.js:1:95719)\n    at em.<anonymous> (https://play.max.com/95016.d85949794888f4bde783.sha.js:1:111788)\n    at lm (https://play.max.com/95016.d85949794888f4bde783.sha.js:1:101632)\n    at km (https://play.max.com/95016.d85949794888f4bde783.sha.js:1:101369)\n    at en (https://play.max.com/95016.d85949794888f4bde783.sha.js:1:109376)\n    at gn (https://play.max.com/95016.d85949794888f4bde783.sha.js:1:109878)\n    at n.Sb (https://play.max.com/95016.d85949794888f4bde783.sha.js:1:112289)\n    at n.fb (https://play.max.com/95016.d85949794888f4bde783.sha.js:1:112266)"[[Prototype]]: Error
Promise.then
ut @ 95016.d85949794888f4bde783.sha.js:1
rt @ 95016.d85949794888f4bde783.sha.js:1
yt @ 95016.d85949794888f4bde783.sha.js:1
getGooglePalNonce @ 7439.530f23b9b6dcf525aea2.sha.js:1
Qo._getPALNonce @ 7439.530f23b9b6dcf525aea2.sha.js:1
(anonymous) @ 7439.530f23b9b6dcf525aea2.sha.js:1
(anonymous) @ 34669.b76b14e1eecae01bf4af.sha.js:1
n._trySubscribe @ 2930.f14d5dd8aea0400e6572.sha.js:1
(anonymous) @ 2930.f14d5dd8aea0400e6572.sha.js:1
i @ 2930.f14d5dd8aea0400e6572.sha.js:1
n.subscribe @ 2930.f14d5dd8aea0400e6572.sha.js:1
(anonymous) @ 34669.b76b14e1eecae01bf4af.sha.js:1
(anonymous) @ 2930.f14d5dd8aea0400e6572.sha.js:1
(anonymous) @ 2930.f14d5dd8aea0400e6572.sha.js:1
i @ 2930.f14d5dd8aea0400e6572.sha.js:1
n.subscribe @ 2930.f14d5dd8aea0400e6572.sha.js:1
o @ 34669.b76b14e1eecae01bf4af.sha.js:1
(anonymous) @ 34669.b76b14e1eecae01bf4af.sha.js:1
n._trySubscribe @ 2930.f14d5dd8aea0400e6572.sha.js:1
(anonymous) @ 2930.f14d5dd8aea0400e6572.sha.js:1
i @ 2930.f14d5dd8aea0400e6572.sha.js:1
n.subscribe @ 2930.f14d5dd8aea0400e6572.sha.js:1
(anonymous) @ 2930.f14d5dd8aea0400e6572.sha.js:1
(anonymous) @ 2930.f14d5dd8aea0400e6572.sha.js:1
(anonymous) @ 2930.f14d5dd8aea0400e6572.sha.js:1
i @ 2930.f14d5dd8aea0400e6572.sha.js:1
n.subscribe @ 2930.f14d5dd8aea0400e6572.sha.js:1
(anonymous) @ 34669.b76b14e1eecae01bf4af.sha.js:1
(anonymous) @ 2930.f14d5dd8aea0400e6572.sha.js:1
(anonymous) @ 2930.f14d5dd8aea0400e6572.sha.js:1
i @ 2930.f14d5dd8aea0400e6572.sha.js:1
n.subscribe @ 2930.f14d5dd8aea0400e6572.sha.js:1
(anonymous) @ 34669.b76b14e1eecae01bf4af.sha.js:1
a @ 34669.b76b14e1eecae01bf4af.sha.js:1
build @ 7439.530f23b9b6dcf525aea2.sha.js:1
resolve @ chunk-play-core-app.e38d2b7665cb8b2b3aaa.sha.js:1489
(anonymous) @ 48335.44aed5a34360f853ed3b.sha.js:1
Promise.then
_load @ 48335.44aed5a34360f853ed3b.sha.js:1
(anonymous) @ 48335.44aed5a34360f853ed3b.sha.js:1
Promise.then
load @ 48335.44aed5a34360f853ed3b.sha.js:1
(anonymous) @ 96551.3bbabbea24d431ed5070.sha.js:32
ri @ 11819.c2ee4768672e4aaff79c.sha.js:2
Ss @ 11819.c2ee4768672e4aaff79c.sha.js:2
(anonymous) @ 11819.c2ee4768672e4aaff79c.sha.js:2
S @ 11819.c2ee4768672e4aaff79c.sha.js:2
T @ 11819.c2ee4768672e4aaff79c.sha.js:2
8479.594319c4ca357ee39a31.sha.js:1 It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior.
(anonymous) @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
h @ 95147.79f1f29f6fe849cc6104.sha.js:2
e._checkOptionsForSupport @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
h @ 95147.79f1f29f6fe849cc6104.sha.js:2
e._getSupport @ 8479.594319c4ca357ee39a31.sha.js:1
e.getMediaKeySupport @ 8479.594319c4ca357ee39a31.sha.js:1
t._getMediaKeySupport @ 8479.594319c4ca357ee39a31.sha.js:1
e.getMediaKeySupport @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
h @ 95147.79f1f29f6fe849cc6104.sha.js:2
e._createBuffer @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
h @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
h @ 95147.79f1f29f6fe849cc6104.sha.js:2
e.wrap @ 8479.594319c4ca357ee39a31.sha.js:1
e.load @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
s @ 95147.79f1f29f6fe849cc6104.sha.js:2
Promise.then
c @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
h @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
h @ 95147.79f1f29f6fe849cc6104.sha.js:2
e.wrap @ 8479.594319c4ca357ee39a31.sha.js:1
e._attach @ 8479.594319c4ca357ee39a31.sha.js:1
attach @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
h @ 95147.79f1f29f6fe849cc6104.sha.js:2
performAction @ 8479.594319c4ca357ee39a31.sha.js:1
handleWorkItem @ 8479.594319c4ca357ee39a31.sha.js:1
e._startWorkItem @ 8479.594319c4ca357ee39a31.sha.js:1
_handleWorkerTick @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
s @ 95147.79f1f29f6fe849cc6104.sha.js:2
Promise.then
c @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
h @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 8479.594319c4ca357ee39a31.sha.js:1
e @ 8479.594319c4ca357ee39a31.sha.js:1
t @ 8479.594319c4ca357ee39a31.sha.js:1
t._createTick @ 8479.594319c4ca357ee39a31.sha.js:1
e.tickAfter @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 8479.594319c4ca357ee39a31.sha.js:1
e.catchRejection @ 8479.594319c4ca357ee39a31.sha.js:1
e._ensureTick @ 8479.594319c4ca357ee39a31.sha.js:1
e.flush @ 8479.594319c4ca357ee39a31.sha.js:1
e._run @ 8479.594319c4ca357ee39a31.sha.js:1
e.runWithoutReturn @ 8479.594319c4ca357ee39a31.sha.js:1
e.attach @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
h @ 95147.79f1f29f6fe849cc6104.sha.js:2
e.wrap @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
h @ 95147.79f1f29f6fe849cc6104.sha.js:2
e._recoverOrRethrowError @ 8479.594319c4ca357ee39a31.sha.js:1
e.attach @ 8479.594319c4ca357ee39a31.sha.js:1
_load @ 48335.44aed5a34360f853ed3b.sha.js:1
await in _load
(anonymous) @ 48335.44aed5a34360f853ed3b.sha.js:1
await in (anonymous)
(anonymous) @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
h @ 95147.79f1f29f6fe849cc6104.sha.js:2
performAction @ 8479.594319c4ca357ee39a31.sha.js:1
handleWorkItem @ 8479.594319c4ca357ee39a31.sha.js:1
e._startWorkItem @ 8479.594319c4ca357ee39a31.sha.js:1
_handleWorkerTick @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
s @ 95147.79f1f29f6fe849cc6104.sha.js:2
Promise.then
c @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 95147.79f1f29f6fe849cc6104.sha.js:2
h @ 95147.79f1f29f6fe849cc6104.sha.js:2
(anonymous) @ 8479.594319c4ca357ee39a31.sha.js:1
e @ 8479.594319c4ca357ee39a31.sha.js:1
t @ 8479.594319c4ca357ee39a31.sha.js:1
t._createTick @ 8479.594319c4ca357ee39a31.sha.js:1
e.tickAfter @ 8479.594319c4ca357ee39a31.sha.js:1
(anonymous) @ 8479.594319c4ca357ee39a31.sha.js:1
e.catchRejection @ 8479.594319c4ca357ee39a31.sha.js:1
e._ensureTick @ 8479.594319c4ca357ee39a31.sha.js:1
e.flush @ 8479.594319c4ca357ee39a31.sha.js:1
e._run @ 8479.594319c4ca357ee39a31.sha.js:1
e.runWithoutReturn @ 8479.594319c4ca357ee39a31.sha.js:1
_queueLoadPromise @ 48335.44aed5a34360f853ed3b.sha.js:1
load @ 48335.44aed5a34360f853ed3b.sha.js:1
load @ 48335.44aed5a34360f853ed3b.sha.js:1
await in load
(anonymous) @ 48335.44aed5a34360f853ed3b.sha.js:1
Promise.then
_load @ 48335.44aed5a34360f853ed3b.sha.js:1
(anonymous) @ 48335.44aed5a34360f853ed3b.sha.js:1
Promise.then
load @ 48335.44aed5a34360f853ed3b.sha.js:1
(anonymous) @ 96551.3bbabbea24d431ed5070.sha.js:32
ri @ 11819.c2ee4768672e4aaff79c.sha.js:2
Ss @ 11819.c2ee4768672e4aaff79c.sha.js:2
(anonymous) @ 11819.c2ee4768672e4aaff79c.sha.js:2
S @ 11819.c2ee4768672e4aaff79c.sha.js:2
T @ 11819.c2ee4768672e4aaff79c.sha.js:2
chunk-braze-sdk.387f1a02e313ec77464a.sha.js:1 
            
            
           POST https://sdk.iad-01.braze.com/api/v3/data/ net::ERR_NAME_NOT_RESOLVED
Gs @ chunk-braze-sdk.387f1a02e313ec77464a.sha.js:1
p @ chunk-braze-sdk.387f1a02e313ec77464a.sha.js:1
(anonymous) @ chunk-braze-sdk.387f1a02e313ec77464a.sha.js:1
Xs @ chunk-braze-sdk.387f1a02e313ec77464a.sha.js:1
Pu @ chunk-braze-sdk.387f1a02e313ec77464a.sha.js:1
e @ chunk-braze-sdk.387f1a02e313ec77464a.sha.js:1
chunk-braze-sdk.387f1a02e313ec77464a.sha.js:1 
            
            
           POST https://sdk.iad-01.braze.com/api/v3/data/ net::ERR_NAME_NOT_RESOLVED
```

Network tab:

![Image](https://github.com/user-attachments/assets/098d9c8f-7baa-4e8c-8a10-8cb5187619e9)
