### ISSUE TITLE
Crash occurs when opening new tab on Tablet [CR127]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#39425]
### Description

Regression with 127 Chromium when opening new tab or having tabs opened. 

Only crashes on **Android Tablet**

Crash Report ID: ae7d0500-b362-320c-0000-000000000000

Crash Logs

```
2024-06-27 12:20:50.547 22211-22211/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.brave.browser_nightly, PID: 22211
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.ViewGroup.getChildCount()' on a null object reference
        at org.chromium.chrome.browser.ntp.BraveNewTabPageLayout.onMeasure(chromium-MonochromePublic.apk-canary-426906222:33)
        at android.view.View.measure(View.java:27853)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7403)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:27853)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7403)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at nH0.onMeasure(chromium-MonochromePublic.apk-canary-426906222:8)
        at android.view.View.measure(View.java:27853)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7403)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at org.chromium.chrome.browser.compositor.CompositorViewHolder.onMeasure(chromium-MonochromePublic.apk-canary-426906222:1)
        at android.view.View.measure(View.java:27853)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7403)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(chromium-MonochromePublic.apk-canary-426906222:791)
        at android.view.View.measure(View.java:27853)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7403)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(chromium-MonochromePublic.apk-canary-426906222:160)
        at android.view.View.measure(View.java:27853)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7403)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:27853)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7403)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:27853)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7403)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:27853)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7403)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1390)
        at android.view.View.measure(View.java:27853)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4882)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3461)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3767)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3151)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11068)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1321)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1329)
        at android.view.Choreographer.doCallbacks(Choreographer.java:930)
        at android.view.Choreographer.doFrame(Choreographer.java:859)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1303)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
2024-06-27 12:20:51.247 1065-5071/? E/perfmond: [PERFMOND][PERFLOG_CPUFREQ] cpuMinLock = -1, cpuMaxLock = -1, Info = CF|  -1/  -1
2024-06-27 12:20:51.259 3111-3111/? E/pageboostd: Received HALT command code 2
2024-06-27 12:20:51.261 1005-1066/? E/ANDR-PERF-UTIL: Failed to read /proc/sys/kernel/walt_low_latency_task_threshold
2024-06-27 12:20:51.261 1005-1066/? E/ANDR-PERF-OPTSHANDLER: Failed to read /proc/sys/kernel/walt_low_latency_task_threshold
```

### Steps to reproduce

1. New install
2. Open a new tab using any method
3. 

### Actual result

Crash occurs when opening tab 

https://github.com/brave/brave-browser/assets/17885425/5ff99b87-943a-4da2-9dcb-e1f4339ff117

### Expected result

No crash

### Reproduces how often

Easily reproduced

### Brave version

1.69.55 - reproducible
1.69.62 - reproducible
1.69.49 (CR126) - does not reproduce

### Device

- Brand/model: Samsung Tablet 
- Android version: 13

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by Uni-verse** [comment]
Closing as duplicate
