### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by haroonidrees** [brave/brave-browser#41254]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.70.117 Chromium: 129.0.6668.59
Operating System: Android 11

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. "Brave keeps stopping" error message continuously, even when typing this report
2. Like non-stop even when I'm not using the browser, or maybe it's in background
3. Please fix this.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/cf810100-bd5b-aa0c-0000-000000000000

**Comment by iefremov** [comment]
cc @SergeyZhukovsky

**Comment by iefremov** [comment]
@haroonidrees can you please reproduce few more times and share more crash ids? Thanks

**Comment by haroonidrees** [comment]
Hi,

Clearing cache did not fix the issue, however clearing storage /
reinstalling the brave app resolved the problem. I was getting the error
even when after killing the brave app, which was strange.

I'm not sure if it's related but recently I installed the bitwarden app few
days before the issue appeared. Although the integration between bitwarden
and brave is poor, but I tried various settings so that brave would pick up
bitwarden auto fill, like draw-over etc. I couldn't get autofill to work
but this may have been a contributing factor.

**Comment by iefremov** [comment]
thanks @haroonidrees

**Comment by haroonidrees** [comment]
Sorry, this started happening again. I've sent 10 reports using 'Send Now'
in brave://crashes.

**Comment by SergeyZhukovsky** [comment]
@haroonidrees could you please paste a few of crash ids in that issue? It would be much easier for us to filter them out from out crash reporting system in that case.

**Comment by haroonidrees** [comment]
fcdc0e00-bd5b-aa0c-0000-000000000000

02dd0e00-bd5b-aa0c-0000-000000000000

05dd0e00-bd5b-aa0c-0000-000000000000

3ade0e00-bd5b-aa0c-0000-000000000000

dcea0e00-bd5b-aa0c-0000-000000000000

**Comment by iefremov** [comment]
```
java.lang.RuntimeException: Unable to create service org.chromium.chrome.browser.autofill.BraveAutofillService: java.lang.ClassNotFoundException: Didn't find class "org.chromium.chrome.browser.autofill.BraveAutofillService" on path: DexPathList[[zip file "/data/app/~~17qsLhgYzip5kVuEdqFLDA==/com.brave.browser-HMVrEf0vWvWiH8qKk-mt_g==/base.apk"],nativeLibraryDirectories=[/data/app/~~17qsLhgYzip5kVuEdqFLDA==/com.brave.browser-HMVrEf0vWvWiH8qKk-mt_g==/lib/arm64, /data/app/~~17qsLhgYzip5kVuEdqFLDA==/com.brave.browser-HMVrEf0vWvWiH8qKk-mt_g==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4391)
	at android.app.ActivityThread.access$1900(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2112)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8010)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.chromium.chrome.browser.autofill.BraveAutofillService" on path: DexPathList[[zip file "/data/app/~~17qsLhgYzip5kVuEdqFLDA==/com.brave.browser-HMVrEf0vWvWiH8qKk-mt_g==/base.apk"],nativeLibraryDirectories=[/data/app/~~17qsLhgYzip5kVuEdqFLDA==/com.brave.browser-HMVrEf0vWvWiH8qKk-mt_g==/lib/arm64, /data/app/~~17qsLhgYzip5kVuEdqFLDA==/com.brave.browser-HMVrEf0vWvWiH8qKk-mt_g==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
	at org.chromium.chrome.browser.base.SplitCompatAppComponentFactory.instantiateService(chromium-MonochromePublic64.aab-stable-427011924:5)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4370)
	... 8 more
```

**Comment by SergeyZhukovsky** [comment]
@haroonidrees do you have Brave set as an autofill service on your Android OS settings? Could you please remove it from there as a temp workaround for now?

**Comment by LaurenWags** [comment]
Requires 1.70.124 or higher for verification 👍🏻

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 15` using the following build(s):

```
Brave | 1.70.126 Chromium: 129.0.6668.100 (Official Build) (64-bit)
--- | ---
Revision | 35f34f21e597f5f30e9e206b0354cc137df1f2a3
OS | Android 15; Build/AP41.240823.009; 35; REL
```

Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/25759#issue-2560241773 & https://github.com/brave/brave-core/pull/25759#issuecomment-2389185378, ensured that `Brave` isn't appearing as a choice for the `Autofill service` as per the following:

**`Brave not set as default browser`**

**`Example`** | **`Example`**
----------------|------------------
![Image](https://github.com/user-attachments/assets/1c7b5be5-9594-4913-a35f-3256a2bb8cee) | ![Image](https://github.com/user-attachments/assets/8e544e77-d4e2-4821-9374-02cdf5c4acf7)

**`Brave set as default browser`**

**`Example`** | **`Example`**
----------------|------------------
![Image](https://github.com/user-attachments/assets/c636e94b-c70c-4a9c-a2e9-34bfe17d9439) | ![Image](https://github.com/user-attachments/assets/410625c0-5b4f-4365-8b6a-f548856f5d5c)
