### ISSUE TITLE
Fix misaligned address read on solana decoder

### ISSUE THREAD

**Issue by cdesouza-chromium** [brave/brave-browser#41448]
### Description

ubsan report:

```
../../brave/components/brave_wallet/browser/solana_instruction_data_decoder.cc:857:24: runtime error: load of misaligned address 0x0f9c005b4002 for type 'const uint32_t' (aka 'const unsigned int'), which requires 4 byte alignment
0x0f9c005b4002: note: pointer points here
 00 00  01 00 40 00 00 00 18 00  00 00 1b 9a ff 2b 56 33  96 00 54 12 a4 b4 5e d7  8e dd 18 f6 fe c8
              ^ 
    #0 0x5b3277b6651a in brave_wallet::solana_ins_data_decoder::DecodeUint32(base::span<unsigned char const, 18446744073709551615ul, unsigned char const*>, unsigned long&) brave/components/brave_wallet/browser/solana_instruction_data_decoder.cc:857:24
    #1 0x5b3277bafa9c in brave_wallet::SolanaTxManager::DecodeMerkleTreeAuthorityAndDepth(std::__Cr::vector<unsigned char, std::__Cr::allocator<unsigned char>> const&) brave/components/brave_wallet/browser/solana_tx_manager.cc:1009:26
    #2 0x5b326af851ab in brave_wallet::SolanaTxManagerUnitTest_DecodeMerkleTreeAuthorityAndDepth_Test::TestBody() brave/components/brave_wallet/browser/solana_tx_manager_unittest.cc:2151:38
    #3 0x5b32774a42ae in testing::Test::Run() third_party/googletest/src/googletest/src/gtest.cc:2713:5
    #4 0x5b32774a5bd0 in testing::TestInfo::Run() third_party/googletest/src/googletest/src/gtest.cc:2859:11
    #5 0x5b32774a80cb in testing::TestSuite::Run() third_party/googletest/src/googletest/src/gtest.cc:3037:30
    #6 0x5b32774c0005 in testing::internal::UnitTestImpl::RunAllTests() third_party/googletest/src/googletest/src/gtest.cc:5967:44
    #7 0x5b32774bef0b in testing::UnitTest::Run() third_party/googletest/src/googletest/src/gtest.cc:5546:10
    #8 0x5b32778ed1ea in base::TestSuite::Run() base/test/test_suite.cc:421:16
    #9 0x5b327914743e in content::UnitTestTestSuite::Run() content/public/test/unittest_test_suite.cc:190:23
    #10 0x5b326c5324e9 in base::OnceCallback<int ()>::Run() && base/functional/callback.h:156:12
    #11 0x5b32778f3b00 in RunTestSuite base/test/launcher/unit_test_launcher.cc:187:38
    #12 0x5b32778f3b00 in base::(anonymous namespace)::LaunchUnitTestsInternal(base::OnceCallback<int ()>, unsigned long, int, unsigned long, bool, base::RepeatingCallback<void ()>, base::OnceCallback<void ()>) base/test/launcher/unit_test_launcher.cc:267:10
    #13 0x5b32778f370f in base::LaunchUnitTests(int, char**, base::OnceCallback<int ()>, unsigned long) base/test/launcher/unit_test_launcher.cc:332:10
    #14 0x5b327767ddc3 in main brave/test/base/run_all_unittests.cc:35:10
    #15 0x7640ece2a1c9 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #16 0x7640ece2a28a in __libc_start_main csu/../csu/libc-start.c:360:3
    #17 0x5b3269389029 in _start (/home/redacted/dev/brave-canary/src/out/Static/brave_unit_tests+0x198a4029) (BuildId: 3ccf75114deaa5fc)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../../brave/components/brave_wallet/browser/solana_instruction_data_decoder.cc:857:24 
[1/1] SolanaTxManagerUnitTest.DecodeMerkleTreeAuthorityAndDepth (CRASHED)
```

**Comment by cdesouza-chromium** [comment]
Fixed with https://github.com/brave/brave-core/pull/25855
