### ISSUE TITLE
UAF on `SidebarContainerView`'s dtor when deregistering observers

### ISSUE THREAD

**Issue by cdesouza-chromium** [brave/brave-browser#41538]
### Description

Ubsan report

```
../../base/scoped_observation_traits.h:74:13: runtime error: member call on address 0x17040109ff90 which does not point to an object of type 'SidePanelEntry'
0x17040109ff90: note: object has invalid vptr
 02 00 00 00  ef ef ef ef ef ef ef ef  ef ef ef ef ef ef ef ef  ef ef ef ef ef ef ef ef  ef ef ef ef
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
Still waiting for the following processes to finish:
	../out/Static/brave_browser_tests --disable-gpu-process-for-dx12-info-collection --gtest_also_run_disabled_tests --gtest_filter=BraveContentBrowserClientTest.CanLoadChromeURL --single-process-tests --test-launcher-jobs=1 --test-launcher-output=/tmp/scoped_dirQhjX8h/resultsRKh4Ds/test_results.xml --test-launcher-retries-left=0 --user-data-dir=/tmp/scoped_dirQhjX8h/user_data
    #0 0x58a6ad0dd99b in RemoveObserver base/scoped_observation_traits.h:74:13
    #1 0x58a6ad0dd99b in base::ScopedMultiSourceObservation<SidePanelEntry, SidePanelEntryObserver>::RemoveAllObservations() base/scoped_multi_source_observation.h:77:7
    #2 0x58a6ad0cf657 in ~ScopedMultiSourceObservation base/scoped_multi_source_observation.h:56:37
    #3 0x58a6ad0cf657 in SidebarContainerView::~SidebarContainerView() brave/browser/ui/views/sidebar/sidebar_container_view.cc:132:45
    #4 0x58a6ad0cfd1a in ~SidebarContainerView brave/browser/ui/views/sidebar/sidebar_container_view.cc:132:45
    #5 0x58a6ad0cfd1a in non-virtual thunk to SidebarContainerView::~SidebarContainerView() brave/browser/ui/views/sidebar/sidebar_container_view.cc
    #6 0x58a6b1db5101 in operator() third_party/libc++/src/include/__memory/unique_ptr.h:75:5
    #7 0x58a6b1db5101 in reset third_party/libc++/src/include/__memory/unique_ptr.h:297:7
    #8 0x58a6b1db5101 in ~unique_ptr third_party/libc++/src/include/__memory/unique_ptr.h:266:71
    #9 0x58a6b1db5101 in views::View::DoRemoveChildView(views::View*, bool, bool, views::View*) ui/views/view.cc:3083:1
    #10 0x58a6b1db55c9 in views::View::RemoveAllChildViews() ui/views/view.cc:364:5
    #11 0x58a6b0a71107 in BrowserView::~BrowserView() ../src/chrome/browser/ui/views/frame/browser_view.cc:1153:3
    #12 0x58a6acfe650d in ~BraveBrowserView brave/browser/ui/views/frame/brave_browser_view.cc:589:39
    #13 0x58a6acfe650d in non-virtual thunk to BraveBrowserView::~BraveBrowserView() brave/browser/ui/views/frame/brave_browser_view.cc
    #14 0x58a6b1db12b2 in views::View::~View() ui/views/view.cc:288:9
    #15 0x58a6b131bf47 in ~BrowserFrameViewLinux ../src/chrome/browser/ui/views/frame/browser_frame_view_linux.cc:41:47
    #16 0x58a6b131bf47 in BrowserFrameViewLinux::~BrowserFrameViewLinux() ../src/chrome/browser/ui/views/frame/browser_frame_view_linux.cc:41:47
    #17 0x58a6b1e6348f in operator() third_party/libc++/src/include/__memory/unique_ptr.h:75:5
    #18 0x58a6b1e6348f in reset third_party/libc++/src/include/__memory/unique_ptr.h:297:7
    #19 0x58a6b1e6348f in ~unique_ptr third_party/libc++/src/include/__memory/unique_ptr.h:266:71
    #20 0x58a6b1e6348f in views::NonClientView::~NonClientView() ui/views/window/non_client_view.cc:180:1
    #21 0x58a6b1e63643 in views::NonClientView::~NonClientView() ui/views/window/non_client_view.cc:176:33
    #22 0x58a6b1db5101 in operator() third_party/libc++/src/include/__memory/unique_ptr.h:75:5
    #23 0x58a6b1db5101 in reset third_party/libc++/src/include/__memory/unique_ptr.h:297:7
    #24 0x58a6b1db5101 in ~unique_ptr third_party/libc++/src/include/__memory/unique_ptr.h:266:71
    #25 0x58a6b1db5101 in views::View::DoRemoveChildView(views::View*, bool, bool, views::View*) ui/views/view.cc:3083:1
    #26 0x58a6b1db55c9 in views::View::RemoveAllChildViews() ui/views/view.cc:364:5
    #27 0x58a6b1e0bd93 in views::Widget::DestroyRootView() ../src/ui/views/widget/widget.cc:2182:15
    #28 0x58a6b1e0a750 in views::Widget::~Widget() ../src/ui/views/widget/widget.cc:264:3
    #29 0x58a6acfdc293 in BraveBrowserFrame::~BraveBrowserFrame() brave/browser/ui/views/frame/brave_browser_frame.cc:31:39
    #30 0x58a6b1ecd0a5 in operator() third_party/libc++/src/include/__memory/unique_ptr.h:75:5
    #31 0x58a6b1ecd0a5 in reset third_party/libc++/src/include/__memory/unique_ptr.h:297:7
    #32 0x58a6b1ecd0a5 in views::DesktopNativeWidgetAura::~DesktopNativeWidgetAura() ../src/ui/views/widget/desktop_aura/desktop_native_widget_aura.cc:319:34
    #33 0x58a6b0b48353 in DesktopBrowserFrameAuraLinux::~DesktopBrowserFrameAuraLinux() chrome/browser/ui/views/frame/desktop_browser_frame_aura_linux.cc:32:61
    #34 0x58a6b1ecf0ac in views::DesktopNativeWidgetAura::OnHostClosed() ../src/ui/views/widget/desktop_aura/desktop_native_widget_aura.cc:394:5
    #35 0x58a6b1f03deb in views::DesktopWindowTreeHostPlatform::OnClosed() ui/views/widget/desktop_aura/desktop_window_tree_host_platform.cc:945:32
    #36 0x58a6b1efa49b in views::DesktopWindowTreeHostPlatform::CloseNow() ui/views/widget/desktop_aura/desktop_window_tree_host_platform.cc:430:22
    #37 0x58a6b1f067ff in void base::internal::DecayedFunctorTraits<void (views::DesktopWindowTreeHostPlatform::*)(), base::WeakPtr<views::DesktopWindowTreeHostPlatform>&&>::Invoke<void (views::DesktopWindowTreeHostPlatform::*)(), base::WeakPtr<views::DesktopWindowTreeHostPlatform> const&>(void (views::DesktopWindowTreeHostPlatform::*)(), base::WeakPtr<views::DesktopWindowTreeHostPlatform> const&) base/functional/bind_internal.h:738:12
    #38 0x58a6a1555259 in base::OnceCallback<void ()>::Run() && base/functional/callback.h:156:12
    #39 0x58a6b250ac22 in base::TaskAnnotator::RunTaskImpl(base::PendingTask&) base/task/common/task_annotator.cc:202:34
    #40 0x58a6b255857d in RunTask<(lambda at ../../base/task/sequence_manager/thread_controller_with_message_pump_impl.cc:472:11)> base/task/common/task_annotator.h:90:5
    #41 0x58a6b255857d in base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*) base/task/sequence_manager/thread_controller_with_message_pump_impl.cc:470:23
    #42 0x58a6b2557272 in base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() base/task/sequence_manager/thread_controller_with_message_pump_impl.cc:332:40
    #43 0x58a6b255953a in non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() base/task/sequence_manager/thread_controller_with_message_pump_impl.cc
    #44 0x58a6b26386a0 in base::MessagePumpGlib::HandleDispatch() base/message_loop/message_pump_glib.cc:649:46
    #45 0x58a6b263abab in base::(anonymous namespace)::WorkSourceDispatch(_GSource*, int (*)(void*), void*) base/message_loop/message_pump_glib.cc:274:43
    #46 0x715edea725b4  (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x5d5b4) (BuildId: 9753724b85d60f97b5d5663181ef7f4e69a62131)
    #47 0x715edead1716  (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0xbc716) (BuildId: 9753724b85d60f97b5d5663181ef7f4e69a62131)
    #48 0x715edea71a52 in g_main_context_iteration (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x5ca52) (BuildId: 9753724b85d60f97b5d5663181ef7f4e69a62131)
    #49 0x58a6b2638bed in base::MessagePumpGlib::Run(base::MessagePump::Delegate*) base/message_loop/message_pump_glib.cc:683:30
    #50 0x58a6b255a312 in base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) base/task/sequence_manager/thread_controller_with_message_pump_impl.cc:640:12
    #51 0x58a6b24cd5a3 in base::RunLoop::Run(base::Location const&) base/run_loop.cc:133:14
    #52 0x58a6b151643b in InProcessBrowserTest::RunUntilBrowserProcessQuits() ../src/chrome/test/base/in_process_browser_test.cc:661:38
    #53 0x58a6b1518450 in InProcessBrowserTest::QuitBrowsers() ../src/chrome/test/base/in_process_browser_test.cc:915:3
    #54 0x58a6b151827e in InProcessBrowserTest::PostRunTestOnMainThread() ../src/chrome/test/base/in_process_browser_test.cc:887:3
    #55 0x58a6c2a56528 in content::BrowserTestBase::ProxyRunTestOnMainThreadLoop() content/public/test/browser_test_base.cc:966:3
    #56 0x58a6a1555259 in base::OnceCallback<void ()>::Run() && base/functional/callback.h:156:12
    #57 0x58a6a8cf7f06 in content::BrowserMainLoop::InterceptMainMessageLoopRun() ../src/content/browser/browser_main_loop.cc:1074:36
    #58 0x58a6a8cf8046 in content::BrowserMainLoop::RunMainMessageLoop() ../src/content/browser/browser_main_loop.cc:1086:7
    #59 0x58a6a8d024de in content::BrowserMainRunnerImpl::Run() content/browser/browser_main_runner_impl.cc:157:15
    #60 0x58a6a8cf0436 in content::BrowserMain(content::MainFunctionParams) content/browser/browser_main.cc:34:28
    #61 0x58a6ad64a8cd in content::RunBrowserProcessMain(content::MainFunctionParams, content::ContentMainDelegate*) content/app/content_main_runner_impl.cc:732:10
    #62 0x58a6ad64e18f in content::ContentMainRunnerImpl::RunBrowser(content::MainFunctionParams, bool) content/app/content_main_runner_impl.cc:1311:10
    #63 0x58a6ad64da99 in content::ContentMainRunnerImpl::Run() content/app/content_main_runner_impl.cc:1162:12
    #64 0x58a6ad648229 in content::RunContentProcess(content::ContentMainParams, content::ContentMainRunner*) content/app/content_main.cc:356:36
    #65 0x58a6ad648698 in content::ContentMain(content::ContentMainParams) content/app/content_main.cc:369:10
    #66 0x58a6c2a54d4f in content::BrowserTestBase::SetUp() content/public/test/browser_test_base.cc:617:3
    #67 0x58a6b1515176 in InProcessBrowserTest::SetUp() ../src/chrome/test/base/in_process_browser_test.cc:542:20
    #68 0x58a6ae947ff9 in testing::Test::Run() third_party/googletest/src/googletest/src/gtest.cc:2708:3
    #69 0x58a6ae949a00 in testing::TestInfo::Run() third_party/googletest/src/googletest/src/gtest.cc:2859:11
    #70 0x58a6ae94befb in testing::TestSuite::Run() third_party/googletest/src/googletest/src/gtest.cc:3037:30
    #71 0x58a6ae963e35 in testing::internal::UnitTestImpl::RunAllTests() third_party/googletest/src/googletest/src/gtest.cc:5967:44
    #72 0x58a6ae962d3b in testing::UnitTest::Run() third_party/googletest/src/googletest/src/gtest.cc:5546:10
    #73 0x58a6c2988e5a in base::TestSuite::Run() base/test/test_suite.cc:421:16
    #74 0x58a6b15108f9 in ChromeTestSuiteRunner::RunTestSuiteInternal(ChromeTestSuite*) ../src/chrome/test/base/chrome_test_launcher.cc:121:22
    #75 0x58a6b15109a4 in ChromeTestSuiteRunner::RunTestSuite(int, char**) ../src/chrome/test/base/chrome_test_launcher.cc:126:10
    #76 0x58a6c2ab2817 in content::LaunchTestsInternal(content::TestLauncherDelegate*, unsigned long, int, char**) content/public/test/test_launcher.cc:409:31
    #77 0x58a6c2ab2f8a in content::LaunchTests(content::TestLauncherDelegate*, unsigned long, int, char**) content/public/test/test_launcher.cc:504:10
    #78 0x58a6b15112ef in LaunchChromeTests(unsigned long, content::TestLauncherDelegate*, int, char**) ../src/chrome/test/base/chrome_test_launcher.cc:368:10
    #79 0x58a6aed3920b in main brave/test/base/browser_tests_main.cc:66:10
    #80 0x715edb62a1c9 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #81 0x715edb62a28a in __libc_start_main csu/../csu/libc-start.c:360:3
    #82 0x58a6a14f4029 in _start (/home/redacted/dev/brave-canary/src/out/Static/brave_browser_tests+0x195d1029) (BuildId: ac05ea386f3b7ab7)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../../base/scoped_observation_traits.h:74:13
```

**Comment by iefremov** [comment]
raising the priority as this is UAF

**Comment by cdesouza-chromium** [comment]
I should have mentioned this here, but I have an [upstream CL](https://chromium-review.googlesource.com/c/chromium/src/+/5924957) for this, however this CL has not been merged yet because I seem to have stumbled in some much larger problem in chromium.

[1] https://crrev.com/c/5924957

**Comment by cdesouza-chromium** [comment]
I'm gonna submit the CL as a patch to brave, and then we remove the patch when we finally the CL merged upstream.

**Comment by iefremov** [comment]
closing after discussing with @cdesouza-chromium
