### ISSUE TITLE
[Follow up to #36801] Brave crashes if `brave-ai-chat-page-content-refine` is ON

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#41662]
### Description

Follow-up to #24953.

### Steps to reproduce

1. Launch Brave
2. Open brave://flags
3. Find `brave-ai-chat-page-content-refine` and `enable` it > Relaunch Brave
4. Navigate to https://www.brianbondy.com/blog/187/cocodona-2024 > Open `Leo`
5. Ask a question like "Who was the pacer?" > *Observe*

### Actual result

Brave crashes if `brave-ai-chat-page-content-refine` is ON when asking Leo a question while on https://www.brianbondy.com/blog/187/cocodona-2024 page.

-------------------

https://github.com/user-attachments/assets/d97d49c0-c5f3-4b96-a5c2-e71392b02093

```
2024-10-15 18:46:55.206 13569-13569 ImeTracker              com.brave.browser                    I  com.brave.browser:6d46adc9: onRequestHide at ORIGIN_CLIENT reason HIDE_SOFT_INPUT fromUser false
2024-10-15 18:46:55.211 13569-13753 RemoteInpu...ectionImpl com.brave.browser                    W  requestCursorUpdates on inactive InputConnection
2024-10-15 18:46:55.215 13569-13569 InsetsController        com.brave.browser                    D  hide(ime(), fromIme=true)
2024-10-15 18:46:55.227 13569-13569 WindowOnBackDispatcher  com.brave.browser                    W  sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@248678195 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@f062361
2024-10-15 18:46:55.228 19298-19298 GoogleInpu...hodService com...gle.android.inputmethod.latin  I  GoogleInputMethodService.onStartInput():1937 onStartInput(EditorInfo{EditorInfo{packageName=com.brave.browser, inputType=0, inputTypeString=NULL, enableLearning=false, autoCorrection=false, autoComplete=false, imeOptions=12000000, privateImeOptions=null, actionName=UNSPECIFIED, actionLabel=null, initialSelStart=-1, initialSelEnd=-1, initialCapsMode=0, label=null, fieldId=0, fieldName=null, extras=null, hintText=null, hintLocales=[]}}, true)
2024-10-15 18:46:55.229  1552-2574  CoreBackPreview         system_server                        D  Window{3a2df47 u0 com.brave.browser/org.chromium.chrome.browser.brave_leo.BraveLeoActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@628c73, mPriority=0, mIsAnimationCallback=true}
2024-10-15 18:46:55.230  1552-3578  PackageConfigPersister  system_server                        W  App-specific configuration not found for packageName: com.brave.browser and userId: 0
2024-10-15 18:46:55.241 13569-13627 libc                    com.brave.browser                    W  Access denied finding property "ro.mediatek.platform"
2024-10-15 18:46:55.241 13569-13627 libc                    com.brave.browser                    W  Access denied finding property "ro.chipname"
2024-10-15 18:46:55.241 13569-13627 libc                    com.brave.browser                    W  Access denied finding property "ro.hardware.chipname"
2024-10-15 18:46:55.311 13833-13833 linker64                pid-13833                            W  type=1400 audit(0.0:1758): avc:  denied  { search } for  name="tests" dev="dm-53" ino=111 scontext=u:r:untrusted_app:s0:c115,c257,c512,c768 tcontext=u:object_r:shell_test_data_file:s0 tclass=dir permissive=0 bug=b/305600845 app=com.brave.browser
2024-10-15 18:46:55.311 13833-13833 linker64                pid-13833                            W  type=1400 audit(0.0:1759): avc:  denied  { search } for  name="tests" dev="dm-53" ino=111 scontext=u:r:untrusted_app:s0:c115,c257,c512,c768 tcontext=u:object_r:shell_test_data_file:s0 tclass=dir permissive=0 bug=b/305600845 app=com.brave.browser
2024-10-15 18:46:55.311 13833-13833 linker64                pid-13833                            W  type=1400 audit(0.0:1760): avc:  denied  { search } for  name="tests" dev="dm-53" ino=111 scontext=u:r:untrusted_app:s0:c115,c257,c512,c768 tcontext=u:object_r:shell_test_data_file:s0 tclass=dir permissive=0 bug=b/305600845 app=com.brave.browser
2024-10-15 18:46:55.311 13833-13833 linker64                pid-13833                            W  type=1400 audit(0.0:1761): avc:  denied  { search } for  name="tests" dev="dm-53" ino=111 scontext=u:r:untrusted_app:s0:c115,c257,c512,c768 tcontext=u:object_r:shell_test_data_file:s0 tclass=dir permissive=0 bug=b/305600845 app=com.brave.browser
2024-10-15 18:46:55.391 13833-13833 linker64                pid-13833                            W  type=1400 audit(0.0:1762): avc:  denied  { read } for  name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=375 scontext=u:r:untrusted_app:s0:c115,c257,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 bug=b/305600845 app=com.brave.browser
2024-10-15 18:46:55.461 13569-13627 libc                    com.brave.browser                    A  Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7370001000 in tid 13627 (ThreadPoolForeg), pid 13569 (m.brave.browser)
2024-10-15 18:46:55.572 13569-13569 ImeTracker              com.brave.browser                    I  com.brave.browser:45856477: onRequestHide at ORIGIN_CLIENT reason HIDE_SOFT_INPUT_ON_ANIMATION_STATE_CHANGED fromUser false
2024-10-15 18:46:55.573  1552-2574  ImeTracker              system_server                        I  com.brave.browser:45856477: onCancelled at PHASE_SERVER_SHOULD_HIDE
2024-10-15 18:46:55.573 13569-13569 ImeTracker              com.brave.browser                    I  com.brave.browser:6d46adc9: onHidden
2024-10-15 18:46:55.735 13842-13842 DEBUG                   pid-13842                            A  Cmdline: com.brave.browser
2024-10-15 18:46:55.735 13842-13842 DEBUG                   pid-13842                            A  pid: 13569, tid: 13627, name: ThreadPoolForeg  >>> com.brave.browser <<<
2024-10-15 18:46:55.735 13842-13842 DEBUG                   pid-13842                            A        #00 pc 0000000004dacc3c  /data/app/~~2WPHg048rvjEuIivIzMttg==/com.brave.browser-nMn4P7QT0KXxK_XLwLwA6g==/base.apk!libmonochrome_64.so (offset 0x173c000) (BuildId: 361b378ef94541f96664e52f2fd19b6caa69c5ec)
2024-10-15 18:46:55.735 13842-13842 DEBUG                   pid-13842                            A        #01 pc 0000000008270c74  /data/app/~~2WPHg048rvjEuIivIzMttg==/com.brave.browser-nMn4P7QT0KXxK_XLwLwA6g==/base.apk!libmonochrome_64.so (offset 0x173c000) (BuildId: 361b378ef94541f96664e52f2fd19b6caa69c5ec)
2024-10-15 18:46:55.735 13842-13842 DEBUG                   pid-13842                            A        #02 pc 0000000008253880  /data/app/~~2WPHg048rvjEuIivIzMttg==/com.brave.browser-nMn4P7QT0KXxK_XLwLwA6g==/base.apk!libmonochrome_64.so (offset 0x173c000) (BuildId: 361b378ef94541f96664e52f2fd19b6caa69c5ec)
2024-10-15 18:46:55.735 13842-13842 DEBUG                   pid-13842                            A        #03 pc 00000000082532e8  /data/app/~~2WPHg048rvjEuIivIzMttg==/com.brave.browser-nMn4P7QT0KXxK_XLwLwA6g==/base.apk!libmonochrome_64.so (offset 0x173c000) (BuildId: 361b378ef94541f96664e52f2fd19b6caa69c5ec)
2024-10-15 18:46:55.735 13842-13842 DEBUG                   pid-13842                            A        #04 pc 0000000008261474  /data/app/~~2WPHg048rvjEuIivIzMttg==/com.brave.browser-nMn4P7QT0KXxK_XLwLwA6g==/base.apk!libmonochrome_64.so (offset 0x173c000) (BuildId: 361b378ef94541f96664e52f2fd19b6caa69c5ec)
2024-10-15 18:46:55.735 13842-13842 DEBUG                   pid-13842                            A        #05 pc 0000000008262a04  /data/app/~~2WPHg048rvjEuIivIzMttg==/com.brave.browser-nMn4P7QT0KXxK_XLwLwA6g==/base.apk!libmonochrome_64.so (offset 0x173c000) (BuildId: 361b378ef94541f96664e52f2fd19b6caa69c5ec)
2024-10-15 18:46:55.735 13842-13842 DEBUG                   pid-13842                            A        #06 pc 00000000082623ec  /data/app/~~2WPHg048rvjEuIivIzMttg==/com.brave.browser-nMn4P7QT0KXxK_XLwLwA6g==/base.apk!libmonochrome_64.so (offset 0x173c000) (BuildId: 361b378ef94541f96664e52f2fd19b6caa69c5ec)
2024-10-15 18:46:55.735 13842-13842 DEBUG                   pid-13842                            A        #07 pc 000000000825a4b0  /data/app/~~2WPHg048rvjEuIivIzMttg==/com.brave.browser-nMn4P7QT0KXxK_XLwLwA6g==/base.apk!libmonochrome_64.so (offset 0x173c000) (BuildId: 361b378ef94541f96664e52f2fd19b6caa69c5ec)
2024-10-15 18:46:55.735 13842-13842 DEBUG                   pid-13842                            A        #08 pc 00000000087b3078  /data/app/~~2WPHg048rvjEuIivIzMttg==/com.brave.browser-nMn4P7QT0KXxK_XLwLwA6g==/base.apk!libmonochrome_64.so (offset 0x173c000) (BuildId: 361b378ef94541f96664e52f2fd19b6caa69c5ec)
2024-10-15 18:46:55.735 13842-13842 DEBUG                   pid-13842                            A        #09 pc 00000000087bb0f0  /data/app/~~2WPHg048rvjEuIivIzMttg==/com.brave.browser-nMn4P7QT0KXxK_XLwLwA6g==/base.apk!libmonochrome_64.so (offset 0x173c000) (BuildId: 361b378ef94541f96664e52f2fd19b6caa69c5ec)
2024-10-15 18:46:55.735 13842-13842 DEBUG                   pid-13842                            A        #10 pc 0000000003f7c66c  /data/app/~~2WPHg048rvjEuIivIzMttg==/com.brave.browser-nMn4P7QT0KXxK_XLwLwA6g==/base.apk!libmonochrome_64.so (offset 0x173c000) (BuildId: 361b378ef94541f96664e52f2fd19b6caa69c5ec)
2024-10-15 18:46:55.735 13842-13842 DEBUG                   pid-13842                            A        #11 pc 0000000003f7bda4  /data/app/~~2WPHg048rvjEuIivIzMttg==/com.brave.browser-nMn4P7QT0KXxK_XLwLwA6g==/base.apk!libmonochrome_64.so (offset 0x173c000) (BuildId: 361b378ef94541f96664e52f2fd19b6caa69c5ec)
2024-10-15 18:46:55.735 13842-13842 DEBUG                   pid-13842                            A        #12 pc 0000000005dfc500  /data/app/~~2WPHg048rvjEuIivIzMttg==/com.brave.browser-nMn4P7QT0KXxK_XLwLwA6g==/base.apk!libmonochrome_64.so (offset 0x173c000) (BuildId: 361b378ef94541f96664e52f2fd19b6caa69c5ec)
2024-10-15 18:46:55.735 13842-13842 DEBUG                   pid-13842                            A        #13 pc 0000000005f7ab48  /data/app/~~2WPHg048rvjEuIivIzMttg==/com.brave.browser-nMn4P7QT0KXxK_XLwLwA6g==/base.apk!libmonochrome_64.so (offset 0x173c000) (BuildId: 361b378ef94541f96664e52f2fd19b6caa69c5ec)
2024-10-15 18:46:55.735 13842-13842 DEBUG                   pid-13842                            A        #14 pc 00000000060ffe88  /data/app/~~2WPHg048rvjEuIivIzMttg==/com.brave.browser-nMn4P7QT0KXxK_XLwLwA6g==/base.apk!libmonochrome_64.so (offset 0x173c000) (BuildId: 361b378ef94541f96664e52f2fd19b6caa69c5ec)
2024-10-15 18:46:55.735 13842-13842 DEBUG                   pid-13842                            A        #15 pc 00000000075e0b30  /data/app/~~2WPHg048rvjEuIivIzMttg==/com.brave.browser-nMn4P7QT0KXxK_XLwLwA6g==/base.apk!libmonochrome_64.so (offset 0x173c000) (BuildId: 361b378ef94541f96664e52f2fd19b6caa69c5ec)
2024-10-15 18:46:55.735 13842-13842 DEBUG                   pid-13842                            A        #16 pc 00000000075e0a58  /data/app/~~2WPHg048rvjEuIivIzMttg==/com.brave.browser-nMn4P7QT0KXxK_XLwLwA6g==/base.apk!libmonochrome_64.so (offset 0x173c000) (BuildId: 361b378ef94541f96664e52f2fd19b6caa69c5ec)
2024-10-15 18:46:55.735 13842-13842 DEBUG                   pid-13842                            A        #17 pc 0000000004d64c7c  /data/app/~~2WPHg048rvjEuIivIzMttg==/com.brave.browser-nMn4P7QT0KXxK_XLwLwA6g==/base.apk!libmonochrome_64.so (offset 0x173c000) (BuildId: 361b378ef94541f96664e52f2fd19b6caa69c5ec)
2024-10-15 18:46:55.753  1552-13847 ActivityTaskManager     system_server                        W    Force finishing activity com.brave.browser/org.chromium.chrome.browser.brave_leo.BraveLeoActivity
2024-10-15 18:46:55.755  1552-13847 ActivityTaskManager     system_server                        W    Force finishing activity com.brave.browser/com.google.android.apps.chrome.Main
2024-10-15 18:46:55.812  1552-2571  ActivityManager         system_server                        I  Process com.brave.browser (pid 13569) has died: fg  TOP 
2024-10-15 18:46:55.813  1552-1635  WindowManager           system_server                        I  WIN DEATH: Window{3a2df47 u0 com.brave.browser/org.chromium.chrome.browser.brave_leo.BraveLeoActivity}
2024-10-15 18:46:55.813  1552-2575  ImeTracker              system_server                        I  com.brave.browser:b111cbfc: onRequestHide at ORIGIN_SERVER reason HIDE_REMOVE_CLIENT fromUser false
2024-10-15 18:46:55.813  1552-2575  ImeTracker              system_server                        I  com.brave.browser:b111cbfc: onCancelled at PHASE_SERVER_SHOULD_HIDE
2024-10-15 18:46:55.813  1552-1635  InputManager-JNI        system_server                        W  Input channel object '3a2df47 com.brave.browser/org.chromium.chrome.browser.brave_leo.BraveLeoActivity (client)' was disposed without first being removed with the input manager!
2024-10-15 18:46:55.813  1552-1635  WindowManager           system_server                        V  Loading animations: layout params pkg=com.brave.browser resId=0x0
2024-10-15 18:46:55.814  1552-1927  ConnectivityService     system_server                        D  releasing NetworkRequest [ REQUEST id=1196, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10371 RequestorUid: 10371 RequestorPkg: com.brave.browser UnderlyingNetworks: Null] ] (release request)
2024-10-15 18:46:55.814  1552-1927  ConnectivityService     system_server                        D  releasing NetworkRequest [ REQUEST id=1199, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10371 RequestorUid: 10371 RequestorPkg: com.brave.browser UnderlyingNetworks: Null] ] (release request)
2024-10-15 18:46:55.814  1552-1927  ConnectivityService     system_server                        D  releasing NetworkRequest [ REQUEST id=1202, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10371 RequestorUid: 10371 RequestorPkg: com.brave.browser UnderlyingNetworks: Null] ] (release request)
2024-10-15 18:46:55.815  1552-1635  WindowManager           system_server                        I  WIN DEATH: Window{dce6452 u0 com.brave.browser/com.google.android.apps.chrome.Main}
2024-10-15 18:46:55.815  1552-1635  InputManager-JNI        system_server                        W  Input channel object 'dce6452 com.brave.browser/com.google.android.apps.chrome.Main (client)' was disposed without first being removed with the input manager!
2024-10-15 18:46:55.816  1552-1635  WindowManager           system_server                        V  Loading animations: layout params pkg=com.brave.browser resId=0x1030308
2024-10-15 18:46:55.820  1552-2571  ActivityManager         system_server                        I  Killing 13722:com.brave.browser:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:1/u0a371i-8897 (adj 0): isolated not needed
2024-10-15 18:46:55.820  1552-2571  ActivityManager         system_server                        I  Killing 13601:com.brave.browser:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0/u0a371i-8898 (adj 0): isolated not needed
2024-10-15 18:46:55.846  1552-1681  WindowManager           system_server                        W  Failed to deliver inset control state change to w=Window{3a2df47 u0 com.brave.browser/org.chromium.chrome.browser.brave_leo.BraveLeoActivity EXITING} (Ask Gemini)
                                                                                                    android.os.DeadObjectException
                                                                                                    	at android.os.BinderProxy.transactNative(Native Method)
                                                                                                    	at android.os.BinderProxy.transact(BinderProxy.java:586)
                                                                                                    	at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:485)
                                                                                                    	at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:3776)
                                                                                                    	at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$3(InsetsStateController.java:376)
                                                                                                    	at com.android.server.wm.InsetsStateController.$r8$lambda$MnP7XA1MDcyrUwoj0hcoT5hTO8E(InsetsStateController.java:0)
                                                                                                    	at com.android.server.wm.InsetsStateController$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
                                                                                                    	at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:314)
                                                                                                    	at com.android.server.wm.WindowAnimator.animate(WindowAnimator.java:207)
                                                                                                    	at com.android.server.wm.WindowAnimator.lambda$new$1(WindowAnimator.java:99)
                                                                                                    	at com.android.server.wm.WindowAnimator.$r8$lambda$AS_wbK9i-bc6ocCFop7s9PnXP80(WindowAnimator.java:0)
                                                                                                    	at com.android.server.wm.WindowAnimator$$ExternalSyntheticLambda1.doFrame(R8$$SyntheticClass:0)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1404)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:941)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:85)
                                                                                                    	at com.android.server.ServiceThread.run(ServiceThread.java:46)
2024-10-15 18:46:55.859 13354-13354 Zygote                  com.brave.browser_zygote             I  Process 13722 exited cleanly (0)
2024-10-15 18:46:55.867  1552-1677  WindowManager           system_server                        V      info={id=218 t=CLOSE f=0x10 trk=0 r=[0@Point(0, 0)] c=[
                                                                                                            {WCT{RemoteToken{bf0ac28 Task{4ab6d64 #129 type=undefined}}} m=TO_FRONT f=SHOW_WALLPAPER|MOVE_TO_TOP leash=Surface(name=Task=129)/@0x46cf1a sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0},
                                                                                                            {WCT{RemoteToken{86b55a8 Task{d7013db #194 type=standard A=10371:com.brave.browser}}} m=CLOSE f=NONE leash=Surface(name=Task=194)/@0xae7fc9a sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0},
                                                                                                            {null m=TO_FRONT f=IS_WALLPAPER leash=Surface(name=WallpaperWindowToken{9a380bc token=android.os.Binder@10204af})/@0xe4e39c5 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0}
                                                                                                        ]}
2024-10-15 18:46:55.898  1552-1681  WindowManager           system_server                        W  Failed to deliver inset control state change to w=Window{3a2df47 u0 com.brave.browser/org.chromium.chrome.browser.brave_leo.BraveLeoActivity EXITING} (Ask Gemini)
                                                                                                    android.os.DeadObjectException
                                                                                                    	at android.os.BinderProxy.transactNative(Native Method)
                                                                                                    	at android.os.BinderProxy.transact(BinderProxy.java:586)
                                                                                                    	at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:485)
                                                                                                    	at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:3776)
                                                                                                    	at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$3(InsetsStateController.java:376)
                                                                                                    	at com.android.server.wm.InsetsStateController.$r8$lambda$MnP7XA1MDcyrUwoj0hcoT5hTO8E(InsetsStateController.java:0)
                                                                                                    	at com.android.server.wm.InsetsStateController$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
                                                                                                    	at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:314)
                                                                                                    	at com.android.server.wm.WindowAnimator.animate(WindowAnimator.java:207)
                                                                                                    	at com.android.server.wm.WindowAnimator.lambda$new$1(WindowAnimator.java:99)
                                                                                                    	at com.android.server.wm.WindowAnimator.$r8$lambda$AS_wbK9i-bc6ocCFop7s9PnXP80(WindowAnimator.java:0)
                                                                                                    	at com.android.server.wm.WindowAnimator$$ExternalSyntheticLambda1.doFrame(R8$$SyntheticClass:0)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1404)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:941)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:85)
                                                                                                    	at com.android.server.ServiceThread.run(ServiceThread.java:46)
2024-10-15 18:46:55.925  1552-2507  ActivityManager         system_server                        I  Process com.brave.browser:privileged_process0 (pid 13640) has died: fg  SVC 
2024-10-15 18:46:55.944 13354-13354 Zygote                  com.brave.browser_zygote             I  Process 13601 exited cleanly (0)
2024-10-15 18:46:56.471  1552-3228  WindowManager           system_server                        W  Exception thrown during dispatchAppVisibility Window{3a2df47 u0 com.brave.browser/org.chromium.chrome.browser.brave_leo.BraveLeoActivity EXITING} (Ask Gemini)
                                                                                                    android.os.DeadObjectException
                                                                                                    	at android.os.BinderProxy.transactNative(Native Method)
                                                                                                    	at android.os.BinderProxy.transact(BinderProxy.java:586)
                                                                                                    	at android.view.IWindow$Stub$Proxy.dispatchAppVisibility(IWindow.java:552)
                                                                                                    	at com.android.server.wm.WindowState.sendAppVisibilityToClients(WindowState.java:3218)
                                                                                                    	at com.android.server.wm.WindowContainer.sendAppVisibilityToClients(WindowContainer.java:1293)
                                                                                                    	at com.android.server.wm.WindowToken.setClientVisible(WindowToken.java:403)
                                                                                                    	at com.android.server.wm.ActivityRecord.setClientVisible(ActivityRecord.java:7100)
                                                                                                    	at com.android.server.wm.ActivityRecord.postApplyAnimation(ActivityRecord.java:5820)
                                                                                                    	at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:5762)
                                                                                                    	at com.android.server.wm.Transition.finishTransition(Transition.java:1257)
                                                                                                    	at com.android.server.wm.TransitionController.finishTransition(TransitionController.java:925)
                                                                                                    	at com.android.server.wm.WindowOrganizerController.finishTransition(WindowOrganizerController.java:489)
                                                                                                    	at android.window.IWindowOrganizerController$Stub.onTransact(IWindowOrganizerController.java:278)
                                                                                                    	at com.android.server.wm.WindowOrganizerController.onTransact(WindowOrganizerController.java:199)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1505)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1444)
2024-10-15 18:46:56.472  1552-3228  WindowManager           system_server                        W  Exception thrown during dispatchAppVisibility Window{dce6452 u0 com.brave.browser/com.google.android.apps.chrome.Main EXITING} (Ask Gemini)
                                                                                                    android.os.DeadObjectException
                                                                                                    	at android.os.BinderProxy.transactNative(Native Method)
                                                                                                    	at android.os.BinderProxy.transact(BinderProxy.java:586)
                                                                                                    	at android.view.IWindow$Stub$Proxy.dispatchAppVisibility(IWindow.java:552)
                                                                                                    	at com.android.server.wm.WindowState.sendAppVisibilityToClients(WindowState.java:3218)
                                                                                                    	at com.android.server.wm.WindowContainer.sendAppVisibilityToClients(WindowContainer.java:1293)
                                                                                                    	at com.android.server.wm.WindowToken.setClientVisible(WindowToken.java:403)
                                                                                                    	at com.android.server.wm.ActivityRecord.setClientVisible(ActivityRecord.java:7100)
                                                                                                    	at com.android.server.wm.ActivityRecord.postApplyAnimation(ActivityRecord.java:5820)
                                                                                                    	at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:5762)
                                                                                                    	at com.android.server.wm.Transition.finishTransition(Transition.java:1257)
                                                                                                    	at com.android.server.wm.TransitionController.finishTransition(TransitionController.java:925)
                                                                                                    	at com.android.server.wm.WindowOrganizerController.finishTransition(WindowOrganizerController.java:489)
                                                                                                    	at android.window.IWindowOrganizerController$Stub.onTransact(IWindowOrganizerController.java:278)
                                                                                                    	at com.android.server.wm.WindowOrganizerController.onTransact(WindowOrganizerController.java:199)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1505)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1444)

```

### Expected result

Brave must not crash.

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.71.112
Chromium: 130.0.6723.44 (Official Build) (64-bit) 

### Device

- Brand/model: Pixel 6, Pixel 7
- Android version: 14, 15

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @darkdh

**Comment by darkdh** [comment]
dup of https://github.com/brave/brave-browser/issues/41481
