### ISSUE TITLE
Android Webcompat reporter has empty `channel` for release build

### ISSUE THREAD

**Issue by vadimstruts** [brave/brave-browser#41719]
Android release build should have `"channel": "RELEASE"` value in the webcompat report

**Comment by kjozwiak** [comment]
The above requires `1.71.117` or higher for `1.71.x` verification 👍

**Comment by kjozwiak** [comment]
Removing from `1.71.x` as the above was reverted via https://github.com/brave/brave-core/pull/26160 due to failing the following when we were creating the `1.71.x` RC builds:

```
FAILED: gen/brave/components/version_info/android/java/org/chromium/components/version_info/BraveVersionConstants.java 
07:21:36  python3 ../../build/util/version.py --official -e BRAVE_BROWSER_VERSION=\"1.71.117\" -e BRAVE_CHROMIUM_VERSION=\"130.0.6723.58\" -e BRAVE_CHANNEL=RELEASE -o gen/brave/components/version_info/android/java/org/chromium/components/version_info/BraveVersionConstants.java ../../brave/components/version_info/android/java/org/chromium/components/version_info/BraveVersionConstants.java.version
07:21:36  Traceback (most recent call last):
07:21:36    File "/home/ubuntu/workspace/brave-browser-build-android-variant-release/src/out/android_Release_x86/../../build/util/version.py", line 293, in <module>
07:21:36      sys.exit(main(sys.argv[1:]))
07:21:36               ^^^^^^^^^^^^^^^^^^
07:21:36    File "/home/ubuntu/workspace/brave-browser-build-android-variant-release/src/out/android_Release_x86/../../build/util/version.py", line 282, in main
07:21:36      output = BuildOutput(args)
07:21:36               ^^^^^^^^^^^^^^^^^
07:21:36    File "/home/ubuntu/workspace/brave-browser-build-android-variant-release/src/out/android_Release_x86/../../build/util/version.py", line 273, in BuildOutput
07:21:36      values = GenerateValues(options, evals)
07:21:36               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
07:21:36    File "/home/ubuntu/workspace/brave-browser-build-android-variant-release/src/out/android_Release_x86/../../build/util/version.py", line 214, in GenerateValues
07:21:36      values[key] = str(eval(val, globals(), values))
07:21:36                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
07:21:36    File "<string>", line 1, in <module>
07:21:36  NameError: name 'RELEASE' is not defined
```

**Comment by kjozwiak** [comment]
The above requires `1.71.119` or higher for `1.71.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP41.240823.009 release-keys
Brave build: 1.71.120
Chromium: 130.0.6723.70 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Launch Brave
2. Go to any website > Brave Shields
3. Turn off the toggle switch
4. Report a broken site > Submit
5. Check `https://webcompat.brave.com` with Charles Proxy > *Verify*

**ACTUAL RESULTS:**
- Verified that `"channel":` shows `"RELEASE"` value for RC builds

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/40c00edc-94cf-4af6-aaaa-eddf7bb4948f) | ![2](https://github.com/user-attachments/assets/6e1948bf-355c-40ea-80b5-b6cefa1bc33b) | ![3](https://github.com/user-attachments/assets/55ab3d68-96e4-44b0-96b5-e5a078ad8b57) | ![4](https://github.com/user-attachments/assets/cce8faf2-9d4e-4547-867e-067bc9ca059a) |
