### ISSUE TITLE
Desktop - Safety check content looks empty

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#41795]
On nightly, the safety recommendations content looks empty. It seems to be the case when there's no recommendations. 
There's no invisible text or anything, it's just empty.

brave://settings/safetyCheck

![Image](https://github.com/user-attachments/assets/0eab5046-a878-468e-bf5b-289d4dde91ad)

![Image](https://github.com/user-attachments/assets/a039c901-333a-4a9f-a4ab-abd1f12f4c3c)

Version:
1.73.30 Chromium: 130.0.6723.58 (Official Build) nightly (arm64)

**Comment by rebron** [comment]
cc: @fmarier

**Comment by emerick** [comment]
@aguscruiz I see the correct message with 1.73.39, but the background looks incorrect:
![Image](https://github.com/user-attachments/assets/970a29dc-9628-4207-bf38-476e1515571e)

It seems like that may have started with https://github.com/brave/brave-browser/issues/41655.

**Comment by ShivanKaul** [comment]
I believe this issue is stale given all the tweaking we've done to this page. It looks fine now; I can't repro this bug. I'll close it out, but lmk if you run into it again @aguscruiz

**Comment by aguscruiz** [comment]
I still have this issue in the latest nightly. It looks ok on Release, but my Nightly still shows it as it is in the screenshot

**Comment by ShivanKaul** [comment]
Hmm can you print out the dev console? That's pretty unexpected cc @emerick

**Comment by emerick** [comment]
Yep, looks OK to me with the latest nightly (Version 1.76.74 Chromium: 134.0.6998.89 (Official Build) (64-bit). How about with a new profile?

**Comment by aguscruiz** [comment]
Here's what it says 


```
polymer_bundled.min.js:1 Could not find style data in module named null
St @ polymer_bundled.min.js:1
xt @ polymer_bundled.min.js:1
It @ polymer_bundled.min.js:1
r @ polymer_bundled.min.js:1
_finalizeTemplate @ polymer_bundled.min.js:1
_initializeProperties @ polymer_bundled.min.js:1
(anonymous) @ polymer_bundled.min.js:1
(anonymous) @ polymer_bundled.min.js:1
(anonymous) @ polymer_bundled.min.js:1
(anonymous) @ polymer_bundled.min.js:1
s @ polymer_bundled.min.js:1
(anonymous) @ polymer_bundled.min.js:1
SettingsSectionElement @ settings.js:4062
_stampTemplate @ polymer_bundled.min.js:1
_stampTemplate @ polymer_bundled.min.js:1
wn @ polymer_bundled.min.js:1
(anonymous) @ polymer_bundled.min.js:1
s @ polymer_bundled.min.js:1
o @ polymer_bundled.min.js:1
__createAndInsertInstance @ polymer_bundled.min.js:1
__ensureInstance @ polymer_bundled.min.js:1
__render @ polymer_bundled.min.js:1
(anonymous) @ polymer_bundled.min.js:1
(anonymous) @ polymer_bundled.min.js:1
(anonymous) @ polymer_bundled.min.js:1
shared.rollup.js:51 Uncaught (in promise) Error: Assertion failed: Unreachable code hit
    at assert (shared.rollup.js:51:55)
    at assertNotReached (shared.rollup.js:51:325)
    at getLocalizationStringForContentType (shared.rollup.js:2275:3946)
    at lazy_load.js:4909:2233
    at Array.map (<anonymous>)
    at SettingsSafetyHubUnusedSitePermissionsModuleElement.getPermissionsText_ (lazy_load.js:4909:2190)
    at lazy_load.js:4909:6047
    at Array.map (<anonymous>)
    at SettingsSafetyHubUnusedSitePermissionsModuleElement.onUnusedSitePermissionListChanged_ (lazy_load.js:4909:6014)
    at SettingsSafetyHubUnusedSitePermissionsModuleElement.connectedCallback (lazy_load.js:4909:1588)
assert @ shared.rollup.js:51
assertNotReached @ shared.rollup.js:51
getLocalizationStringForContentType @ shared.rollup.js:2275
(anonymous) @ lazy_load.js:4909
getPermissionsText_ @ lazy_load.js:4909
(anonymous) @ lazy_load.js:4909
onUnusedSitePermissionListChanged_ @ lazy_load.js:4909
connectedCallback @ lazy_load.js:4909
``` 

A new profile works ok it 😫

<img width="1644" alt="Image" src="https://github.com/user-attachments/assets/7ebf5db6-a83e-46fd-88d0-f111d58bf6e1" />

**Comment by emerick** [comment]
I wonder if something is cached or corrupt in that profile. Maybe we can have @brave/qa-team try to repro this scenario. I do think this is working now in general, though.

**Comment by LaurenWags** [comment]
Did some poking around but wasn't able to reproduce @aguscruiz issue 

```
Brave | 1.78.49 Chromium: 134.0.6998.95 (Official Build) nightly (x86_64)
-- | --
Revision | 7edbd46f3dca287cb7238eda27536c9a84a2fea2
OS | macOS Version 14.7.4 (Build 23H420)
```

<img width="1468" alt="Image" src="https://github.com/user-attachments/assets/10aaf00f-812f-4e76-8e36-b53bc15db83a" />

**Comment by emerick** [comment]
Encountered by @pes10k recently. I think the issue here is that a Brave-specific permission was revoked for a site. When this page tries to look up the informational strings associated with the Brave-specific permission, it finds nothing because we overlooked adding those strings (see, for instance, `getLocalizationStringForContentType` in `chrome/browser/resources/settings/site_settings/site_settings_util.ts`, but there are potentially other places that also need to be fixed).
