### ISSUE TITLE
(Wallet) Solana DApp message sign crashes

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#41945]
## Description 

When trying to sign a message for Solana DApps the process crashes immediately before showing the Wallet panel.

Stacktrace:

```
FATAL EXCEPTION: main
                                                                                  Process: com.brave.browser_default, PID: 29788
                                                                                  org.chromium.base.JniAndroid$UncaughtExceptionException: Native stack trace:
                                                                                  #00 pc 0x0000000000639727 /data/app/~~MA6kf92HVMvhLYZtmkZAEQ==/com.brave.browser_default-IZqNuti87njVuRKP5ctSbw==/base.apk (offset 0x55cc000)
                                                                                  #01 pc 0x00000000006261bb /data/app/~~MA6kf92HVMvhLYZtmkZAEQ==/com.brave.browser_default-IZqNuti87njVuRKP5ctSbw==/base.apk (offset 0x55cc000)
                                                                                  #02 pc 0x0000000003aa698f /data/app/~~MA6kf92HVMvhLYZtmkZAEQ==/com.brave.browser_default-IZqNuti87njVuRKP5ctSbw==/base.apk (offset 0x18ccc000)
                                                                                  #03 pc 0x00000000022daed3 /data/app/~~MA6kf92HVMvhLYZtmkZAEQ==/com.brave.browser_default-IZqNuti87njVuRKP5ctSbw==/base.apk (offset 0x18ccc000)
                                                                                  #04 pc 0x00000000000199df /data/app/~~MA6kf92HVMvhLYZtmkZAEQ==/com.brave.browser_default-IZqNuti87njVuRKP5ctSbw==/base.apk (offset 0x2627c000)
                                                                                  #05 pc 0x00000000000198b3 /data/app/~~MA6kf92HVMvhLYZtmkZAEQ==/com.brave.browser_default-IZqNuti87njVuRKP5ctSbw==/base.apk (offset 0x2627c000)
                                                                                  #06 pc 0x00000000004e9f83 /data/app/~~MA6kf92HVMvhLYZtmkZAEQ==/com.brave.browser_default-IZqNuti87njVuRKP5ctSbw==/base.apk (offset 0x55cc000)
                                                                                  #07 pc 0x000000000058eebb /data/app/~~MA6kf92HVMvhLYZtmkZAEQ==/com.brave.browser_default-IZqNuti87njVuRKP5ctSbw==/base.apk (offset 0x55cc000)
                                                                                  #08 pc 0x00000000005b5faf /data/app/~~MA6kf92HVMvhLYZtmkZAEQ==/com.brave.browser_default-IZqNuti87njVuRKP5ctSbw==/base.apk (offset 0x55cc000)
                                                                                  #09 pc 0x00000000005b5af3 /data/app/~~MA6kf92HVMvhLYZtmkZAEQ==/com.brave.browser_default-IZqNuti87njVuRKP5ctSbw==/base.apk (offset 0x55cc000)
                                                                                  #10 pc 0x000000000061d0db /data/app/~~MA6kf92HVMvhLYZtmkZAEQ==/com.brave.browser_default-IZqNuti87njVuRKP5ctSbw==/base.apk (offset 0x55cc000)
                                                                                  #11 pc 0x000000000061d047 /data/app/~~MA6kf92HVMvhLYZtmkZAEQ==/com.brave.browser_default-IZqNuti87njVuRKP5ctSbw==/base.apk (offset 0x55cc000)
                                                                                  #12 pc 0x000000000061cbbf /data/app/~~MA6kf92HVMvhLYZtmkZAEQ==/com.brave.browser_default-IZqNuti87njVuRKP5ctSbw==/base.apk (offset 0x55cc000)
                                                                                  #13 pc 0x0000000000003077 /system/lib64/libutils.so
                                                                                  #14 pc 0x000000000009f56f /system/lib64/libandroid_runtime.so
                                                                                  
                                                                                  	at org.chromium.base.JniAndroid.handleException(JniAndroid.java:89)
                                                                                  	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                  	at android.os.MessageQueue.next(MessageQueue.java:335)
                                                                                  	at android.os.Looper.loopOnce(Looper.java:161)
                                                                                  	at android.os.Looper.loop(Looper.java:288)
                                                                                  	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                  	at java.lang.reflect.Method.invoke(Native Method)
                                                                                  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                  Caused by: java.lang.AssertionError
                                                                                  	at org.chromium.chrome.browser.crypto_wallet.fragments.dapps.SignMessageFragment.updateAccount(SignMessageFragment.java:158)
                                                                                  	at org.chromium.chrome.browser.crypto_wallet.fragments.dapps.SignMessageFragment.lambda$fillSignMessageInfo$3(SignMessageFragment.java:149)
                                                                                  	at org.chromium.chrome.browser.crypto_wallet.fragments.dapps.SignMessageFragment.$r8$lambda$9Mi1gCNaOfyjE3mw4a13peofj84(Unknown Source:0)
                                                                                  	at org.chromium.chrome.browser.crypto_wallet.fragments.dapps.SignMessageFragment$$ExternalSyntheticLambda4.call(Unknown Source:4)
                                                                                  	at org.chromium.brave_wallet.mojom.BraveWalletService_Internal$BraveWalletServiceGetPendingSignMessageRequestsResponseParamsForwardToCallback.accept(BraveWalletService_Internal.java:7228)
                                                                                  	at org.chromium.mojo.bindings.RouterImpl.handleIncomingMessage(RouterImpl.java:222)
                                                                                  	at org.chromium.mojo.bindings.RouterImpl.-$$Nest$mhandleIncomingMessage(Unknown Source:0)
                                                                                  	at org.chromium.mojo.bindings.RouterImpl$HandleIncomingMessageThunk.accept(RouterImpl.java:29)
                                                                                  	at org.chromium.mojo.bindings.Connector.readAndDispatchMessage(Connector.java:194)
                                                                                  	at org.chromium.mojo.bindings.Connector.readOutstandingMessages(Connector.java:159)
                                                                                  	at org.chromium.mojo.bindings.Connector.onWatcherResult(Connector.java:137)
                                                                                  	at org.chromium.mojo.bindings.Connector.-$$Nest$monWatcherResult(Unknown Source:0)
```

### Demo

https://github.com/user-attachments/assets/c3454231-9004-41f5-944a-4efbb8459ccf

**Comment by kjozwiak** [comment]
The above requires `1.72.97` or higher for `1.72.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 15 running 1.73.86 x64 build
- Verified steps from [brave/brave-core#26280](https://github.com/brave/brave-core/pull/26280)
- Verified Warning message is shown when trying to submit `Send Transaction (mainnet)` 
- Verified confirmation dialog is shown without crashing when trying to submit `Sign Message` transaction
- Verified confirmation dialog is shown without crashing when trying to submit `Sign Transaction`
- Encountered [#41826](https://github.com/brave/brave-browser/issues/41826)

https://github.com/user-attachments/assets/0cb5437e-911f-46ce-82c4-e25e63390049
