### ISSUE TITLE
(Wallet) Solana DApp transaction sign crashes

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#41946]
## Description

When trying to sign a transaction for Solana DApps the process crashes immediately before showing the Wallet panel.

Stacktrace:

```
FATAL EXCEPTION: main
                                                                                  Process: com.brave.browser_default, PID: 30239
                                                                                  java.lang.AssertionError
                                                                                  	at org.chromium.chrome.browser.crypto_wallet.fragments.dapps.SignSolTransactionsFragment.initComponents(SignSolTransactionsFragment.java:139)
                                                                                  	at org.chromium.chrome.browser.crypto_wallet.fragments.dapps.SignSolTransactionsFragment.onCreateView(SignSolTransactionsFragment.java:133)
                                                                                  	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3119)
                                                                                  	at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java:770)
                                                                                  	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:577)
                                                                                  	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
                                                                                  	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2211)
                                                                                  	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2106)
                                                                                  	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2049)
                                                                                  	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:703)
                                                                                  	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                  	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                  	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                  	at android.os.Looper.loop(Looper.java:288)
                                                                                  	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                  	at java.lang.reflect.Method.invoke(Native Method)
                                                                                  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

## Demo

https://github.com/user-attachments/assets/d5cb2db9-2ca4-47b0-9396-62bc6420d8b9

**Comment by kjozwiak** [comment]
The above requires `1.72.97` or higher for `1.72.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 15 running 1.73.86 x64 build
- Verified steps from [brave/brave-core#26280](https://github.com/brave/brave-core/pull/26280)
- Verified Warning message is shown when trying to submit `Send Transaction (mainnet)` 
- Verified confirmation dialog is shown without crashing when trying to submit `Sign Message` transaction
- Verified confirmation dialog is shown without crashing when trying to submit `Sign Transaction`
- Encountered [#41826](https://github.com/brave/brave-browser/issues/41826)

https://github.com/user-attachments/assets/0cb5437e-911f-46ce-82c4-e25e63390049
