### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by fierytechknowhows** [brave/brave-browser#42071]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.71.121 Chromium: 130.0.6723.91
Operating System: Android 14

URL (if applicable) where crash occurred: N/A

Can you reproduce this crash? Periodically (but not every time) when I unplug either my Ugreen usb-c to 3.5mm adapter entirely or just my Apple 3.5mm Earpods from the adapter Brave crashes on my Galaxy Tab S9+.

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Unplugging Ugreen usb-c to 3.5mm adapter or just headphones from the adapter
2. 
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/50561900-d188-d80c-0000-000000000000

**Comment by iefremov** [comment]
cc @SergeyZhukovsky 
https://share.backtrace.io/api/share/Sgx26Wv4A1f5de0x29O8Mb81
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.InputDevice.isVirtual()' on a null object reference
	at ms0.a(chromium-MonochromePublic64.aab-stable-427111824:1)
	at os0.onInputDeviceChanged(chromium-MonochromePublic64.aab-stable-427111824:7)
	at android.hardware.input.InputManagerGlobal$InputDeviceListenerDelegate.handleMessage(InputManagerGlobal.java:360)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:9063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by SergeyZhukovsky** [comment]
that crash came from upstream https://issues.chromium.org/issues/374737035 and they already fixed it and going to release with chromium 131, Brave is going to have it on `1.73.x`. It's planned on November 12, 2024.
