### ISSUE TITLE
No such file or directory: '/home/bidetaggle/brave-browser/_gclient_src_ydmibz9q/.git/config.lock'

### ISSUE THREAD

**Issue by bidetaggle** [brave/brave-browser#4269]
## Description 
I want to install Brave from the sources and at the step `$ npm run init` I get this error: `FileNotFoundError: [Errno 2] No such file or directory: '/home/axel/brave-browser/_gclient_src_ydmibz9q/.git/config.lock'`

## Steps to Reproduce

   1. `git clone https://github.com/brave/brave-browser.git`
   2. `cd brave-browser`
   3. `npm install`
   4. `npm run init`

## Actual result:
```

> brave@0.66.31 init /home/axel/brave-browser
> node ./scripts/sync.js --init

git submodule sync
git submodule update --init --recursive
Submodule 'vendor/depot_tools' (https://chromium.googlesource.com/chromium/tools/depot_tools.git) registered for path 'vendor/depot_tools'
Submodule 'vendor/jinja' (git://github.com/pallets/jinja.git) registered for path 'vendor/jinja'
Cloning into '/home/axel/brave-browser/vendor/depot_tools'...
Cloning into '/home/axel/brave-browser/vendor/jinja'...
Submodule path 'vendor/depot_tools': checked out 'eb2767b2eb245bb54b1738ebb7bf4655ba390b44'
Submodule path 'vendor/jinja': checked out '209fd39b2750400d51bf571740fe5ba23008c20e'
git -C /home/axel/brave-browser/vendor/depot_tools clean -fxd
git -C /home/axel/brave-browser/vendor/depot_tools reset --hard HEAD
HEAD is now at eb2767b2 Roll recipe dependencies (trivial).
gclient sync --force --nohooks --with_branch_heads --with_tags --upstream
WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/chromium/src.git /home/axel/brave-browser/_gclient_src_ydmibz9q' in '/home/axel/brave-browser'


src (ERROR)
----------------------------------------
[0:00:01] Started.
[0:00:01] 

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/chromium/src.git /home/axel/brave-browser/_gclient_src_ydmibz9q' in '/home/axel/brave-browser'
Traceback (most recent call last):
  File "/home/axel/brave-browser/vendor/depot_tools/gclient_scm.py", line 1054, in _Clone
    print_stdout=print_stdout, stdout=stdout)
  File "/home/axel/brave-browser/vendor/depot_tools/gclient_scm.py", line 1378, in _Run
    gclient_utils.CheckCallAndFilterAndHeader(cmd, env=env, **kwargs)
  File "/home/axel/brave-browser/vendor/depot_tools/gclient_utils.py", line 344, in CheckCallAndFilterAndHeader
    return CheckCallAndFilter(args, **kwargs)
  File "/home/axel/brave-browser/vendor/depot_tools/gclient_utils.py", line 576, in CheckCallAndFilter
    stdout.write(in_byte)
  File "/home/axel/brave-browser/vendor/depot_tools/gclient_utils.py", line 366, in write
    self._wrapped.write(out, *args, **kwargs)
TypeError: string argument expected, got 'bytes'
[0:00:01] _____ removing non-empty tmp dir /home/axel/brave-browser/_gclient_src_ydmibz9q
----------------------------------------
Traceback (most recent call last):
  File "/home/axel/brave-browser/vendor/depot_tools/gclient_scm.py", line 1054, in _Clone
    print_stdout=print_stdout, stdout=stdout)
  File "/home/axel/brave-browser/vendor/depot_tools/gclient_scm.py", line 1378, in _Run
    gclient_utils.CheckCallAndFilterAndHeader(cmd, env=env, **kwargs)
  File "/home/axel/brave-browser/vendor/depot_tools/gclient_utils.py", line 344, in CheckCallAndFilterAndHeader
    return CheckCallAndFilter(args, **kwargs)
  File "/home/axel/brave-browser/vendor/depot_tools/gclient_utils.py", line 576, in CheckCallAndFilter
    stdout.write(in_byte)
  File "/home/axel/brave-browser/vendor/depot_tools/gclient_utils.py", line 366, in write
    self._wrapped.write(out, *args, **kwargs)
TypeError: string argument expected, got 'bytes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/axel/brave-browser/vendor/depot_tools/metrics.py", line 267, in print_notice_and_exit
    yield
  File "/home/axel/brave-browser/vendor/depot_tools/gclient.py", line 3155, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/axel/brave-browser/vendor/depot_tools/gclient.py", line 3141, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/home/axel/brave-browser/vendor/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/home/axel/brave-browser/vendor/depot_tools/gclient.py", line 2699, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/home/axel/brave-browser/vendor/depot_tools/gclient.py", line 1734, in RunOnDeps
    patch_refs=patch_refs, target_branches=target_branches)
  File "/home/axel/brave-browser/vendor/depot_tools/gclient_utils.py", line 894, in flush
    reraise(e[0], e[1], e[2])
  File "/home/axel/brave-browser/vendor/depot_tools/gclient_utils.py", line 72, in reraise
    raise value
  File "/home/axel/brave-browser/vendor/depot_tools/gclient_utils.py", line 971, in run
    self.item.run(*self.args, **self.kwargs)
  File "/home/axel/brave-browser/vendor/depot_tools/gclient.py", line 910, in run
    file_list)
  File "/home/axel/brave-browser/vendor/depot_tools/gclient_scm.py", line 133, in RunCommand
    return getattr(self, command)(options, args, file_list)
  File "/home/axel/brave-browser/vendor/depot_tools/gclient_scm.py", line 557, in update
    self._Clone(revision, url, options)
  File "/home/axel/brave-browser/vendor/depot_tools/gclient_scm.py", line 1064, in _Clone
    gclient_utils.rmtree(tmp_dir)
  File "/home/axel/brave-browser/vendor/depot_tools/gclient_utils.py", line 285, in rmtree
    rmtree(fullpath)
  File "/home/axel/brave-browser/vendor/depot_tools/gclient_utils.py", line 282, in rmtree
    remove(os.remove, fullpath)
  File "/home/axel/brave-browser/vendor/depot_tools/gclient_utils.py", line 273, in remove
    func(subpath)
FileNotFoundError: [Errno 2] No such file or directory: '/home/axel/brave-browser/_gclient_src_ydmibz9q/.git/config.lock'
null
null
npm ERR! code ELIFECYCLE
[...]
```

## Miscellaneous Information:
I'm on Arch Linux and I like to say it :smile:

**Comment by honeyoon** [comment]
Have you solved this issue?

**Comment by bidetaggle** [comment]
No, I tried again and this time I have `OSError: [Errno 39] Directory not empty: '/home/axel/brave-browser/_gclient_src_30_62imh/.git'`

**Comment by honeyoon** [comment]
Check out the python version! I changed the python version to 2.7. so the problem is solved.

**Comment by honeyoon** [comment]
Check out the python version! I changed the python version to 2.7. so the issue is solved.
