### ISSUE TITLE
Error while running 'npm run build' on Windows

### ISSUE THREAD

**Issue by davidfritsche17** [brave/brave-browser#4276]
I have been through all the issues found on here and other places on this subject I can find. 

## Description 
Thanks in advance for your help.

Windows 10 Build
NPM Run Install and NPM Run Install Release 

These crash each time I run them.  I'll post the debug below, but its not real helpful.  I have been able to successfully build the Debug build once.

Symptoms
The odd thing is it will die with the same error, but at different points in the build.  Sometimes only a few minutes in.  Other times hours into the build.  Example, on the CMD window, it has stopped the last 4 times in these different spots.  Notice the first example is 28524 programs into the process...many hours.:

- [28524/38802] CXX obj/chrome/chrome_initial/main_dll_loader_win.obj
- [77/9679] CXX obj/content/gpu/gpu_sources/gpu_child_thread.obj
- [55/15936] CXX obj/ui/compositor/host/host/host_context_factory_private.obj
- [540/15770] CXX obj/chrome/browser/browser/chrome_browser_main.obj
(not sure what the counts mean or why they vary from 9K to 38K?)

I thought maybe its my system, but have been monitoring resources.  plenty of disk space, 64 GB RAM and only 23 GB is used.  16 Logic processors (15 peaked at 100%).

Actual Error is: error code ELIFECYCLE
on this process: verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"

This process builds 10's of thousands of files.  And I have run it probably 50 times.  It dies in a different spot each time, but the debug log is the same:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle brave@0.66.30~prebuild: brave@0.66.30
6 info lifecycle brave@0.66.30~build: brave@0.66.30
7 verbose lifecycle brave@0.66.30~build: unsafe-perm in lifecycle true
8 verbose lifecycle brave@0.66.30~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;G:\Data\brave\brave-browser\node_modules\.bin;C:\Program Files\nodejs;C:\Python27\;c:\data\depot_tools;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\data\downloads\ffmpeg\bin;E:\Data\AppData\Roaming\Dashlane\4.7.1.28771\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components;E:\Data\AppData\Roaming\Dashlane\4.7.1.28771\ucrt; C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin;C:\Program Files\JetBrains\PyCharm 2019.1.1\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Yarn\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\dotnet\;C:\WINDOWS\System32\OpenSSH\;
9 verbose lifecycle brave@0.66.30~build: CWD: G:\Data\brave\brave-browser
10 silly lifecycle brave@0.66.30~build: Args: [ '/d /s /c', 'node ./scripts/commands.js build' ]
11 silly lifecycle brave@0.66.30~build: Returned: code: 1  signal: null
12 info lifecycle brave@0.66.30~build: Failed to exec build script
13 verbose stack Error: brave@0.66.30 build: `node ./scripts/commands.js build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid brave@0.66.30
15 verbose cwd G:\Data\brave\brave-browser
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error brave@0.66.30 build: `node ./scripts/commands.js build`
22 error Exit status 1
23 error Failed at the brave@0.66.30 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true 

## Steps to Reproduce

   1. change to Brave-Browser directory
   2. NPM run build
   3. 

## Actual result:
Build Dies

## Expected result:
Build Finishes

## Reproduces how often: 
49 out of 50 (approx)

## Brave version (brave://version info)
Building from most resent source:
git clone git@github.com:brave/brave-browser.git

## Version/Channel Information:

Have not tried any other channels.  

## Other Additional Information:

This is just a recompile of the src to make sure I have everything.

## Miscellaneous Information:
Have tried reinstalling all the prerequisites.  Some multiple times based on searches.  I have tried deleting the OUT directories and Not deleting them.  I have tried the Release build and the speed up suggestion in the Wiki:
npm run build -- Release --debug_build=true --official_build=false

My next step is to uninstall everything and start over.  I do have multiple versions of VS and Python.  However I think the path is correct for the build.

Appreciate any advice.

**Comment by davidfritsche17** [comment]
This may have been as simple as running the CMD windows as administrator.  Not sure, the build completed,
