### ISSUE TITLE
build error on Ubuntu

### ISSUE THREAD

**Issue by bog2k3** [brave/brave-browser#4660]
## Description 
Followed the wiki to configure and build brave from scratch and got an error at 
npm run build 
step

## Steps to Reproduce
   1. clone the repo
   2. install all prerequisites
   3. run npm install
   4. run npm run init
   5. run npm run build

## Actual result:
Build fails with this error:
```
ERROR in [at-loader] ./node_modules/brave-ui/src/components/buttonsIndicators/button/index.tsx:65:8 
    TS2322: Type '{ children: (Element | null)[]; text: string; size?: "small" | "large" | "medium" | "call-to-action" | undefined; type?: "default" | "accent" | "warn" | "subtle" | undefined; brand?: "brave" | "rewards" | undefined; ... 6 more ...; disabled: boolean | undefined; }' is not assignable to type 'Readonly<ThemedOuterStyledProps<Props & ClassAttributes<HTMLButtonElement> & ButtonHTMLAttributes<HTMLButtonElement>, IThemeProps>>'.
  Types of property 'type' are incompatible.
    Type '"default" | "accent" | "warn" | "subtle" | undefined' is not assignable to type 'undefined'.
      Type '"default"' is not assignable to type 'undefined'.

npm ERR! Linux 4.18.0-20-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "web-ui" "--" "--mode=development" "--output-public-path=/out/" "brave_extension=/data/maiar/brave-browser/src/brave/components/brave_extension/extension/brave_extension/braveShieldsPanel.tsx" "brave_extension_background=/data/maiar/brave-browser/src/brave/components/brave_extension/extension/brave_extension/background.ts" "content=/data/maiar/brave-browser/src/brave/components/brave_extension/extension/brave_extension/content.ts"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! brave-core@0.68.5 web-ui: `webpack --config components/webpack/webpack.config.js --progress --colors "--mode=development" "--output-public-path=/out/" "brave_extension=/data/maiar/brave-browser/src/brave/components/brave_extension/extension/brave_extension/braveShieldsPanel.tsx" "brave_extension_background=/data/maiar/brave-browser/src/brave/components/brave_extension/extension/brave_extension/background.ts" "content=/data/maiar/brave-browser/src/brave/components/brave_extension/extension/brave_extension/content.ts"`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the brave-core@0.68.5 web-ui script 'webpack --config components/webpack/webpack.config.js --progress --colors "--mode=development" "--output-public-path=/out/" "brave_extension=/data/maiar/brave-browser/src/brave/components/brave_extension/extension/brave_extension/braveShieldsPanel.tsx" "brave_extension_background=/data/maiar/brave-browser/src/brave/components/brave_extension/extension/brave_extension/background.ts" "content=/data/maiar/brave-browser/src/brave/components/brave_extension/extension/brave_extension/content.ts"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the brave-core package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config components/webpack/webpack.config.js --progress --colors "--mode=development" "--output-public-path=/out/" "brave_extension=/data/maiar/brave-browser/src/brave/components/brave_extension/extension/brave_extension/braveShieldsPanel.tsx" "brave_extension_background=/data/maiar/brave-browser/src/brave/components/brave_extension/extension/brave_extension/background.ts" "content=/data/maiar/brave-browser/src/brave/components/brave_extension/extension/brave_extension/content.ts"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs brave-core
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls brave-core
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/maiar/brave-browser/src/brave/npm-debug.log

Traceback (most recent call last):
  File "../../brave/script/transpile-web-ui.py", line 115, in <module>
    sys.exit(main())
  File "../../brave/script/transpile-web-ui.py", line 34, in main
    args.public_asset_path)
  File "../../brave/script/transpile-web-ui.py", line 95, in transpile_web_uis
    execute_stdout(args, env)
  File "/data/maiar/brave-browser/src/brave/script/lib/util.py", line 187, in execute_stdout
    execute(argv, env)
  File "/data/maiar/brave-browser/src/brave/script/lib/util.py", line 175, in execute
    raise e
subprocess.CalledProcessError: Command '['npm', 'run', 'web-ui', '--', '--mode=development', '--output-public-path=/out/', 'brave_extension=/data/maiar/brave-browser/src/brave/components/brave_extension/extension/brave_extension/braveShieldsPanel.tsx', 'brave_extension_background=/data/maiar/brave-browser/src/brave/components/brave_extension/extension/brave_extension/background.ts', 'content=/data/maiar/brave-browser/src/brave/components/brave_extension/extension/brave_extension/content.ts']' returned non-zero exit status 1
ninja: build stopped: subcommand failed.
null
null

npm ERR! Linux 4.18.0-20-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build" "--debug_build=true"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! brave@0.68.5 build: `node ./scripts/commands.js build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the brave@0.68.5 build script 'node ./scripts/commands.js build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the brave package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/commands.js build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs brave
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls brave
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/maiar/brave-browser/npm-debug.log
```

## Expected result:
Build succeedes

## Reproduces how often: 
Always

## Brave version (brave://version info)
trunk version 97a7b8af4bf3a73093bfb2beb82a4884f1f2441a

## Other Additional Information:

```
bog@bog-VirtualBox:/data/brave-browser$ npm --version
3.5.2
bog@bog-VirtualBox:/data/brave-browser$ node --version
v8.10.0
```

**Comment by bog2k3** [comment]
```
bog@bog-VirtualBox:/data/maiar/brave-browser$ cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   '--debug_build=true' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle brave@0.68.5~prebuild: brave@0.68.5
6 silly lifecycle brave@0.68.5~prebuild: no script for prebuild, continuing
7 info lifecycle brave@0.68.5~build: brave@0.68.5
8 verbose lifecycle brave@0.68.5~build: unsafe-perm in lifecycle true
9 verbose lifecycle brave@0.68.5~build: PATH: /usr/share/npm/bin/node-gyp-bin:/data/maiar/brave-browser/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle brave@0.68.5~build: CWD: /data/maiar/brave-browser
11 silly lifecycle brave@0.68.5~build: Args: [ '-c', 'node ./scripts/commands.js build' ]
12 silly lifecycle brave@0.68.5~build: Returned: code: 1  signal: null
13 info lifecycle brave@0.68.5~build: Failed to exec build script
14 verbose stack Error: brave@0.68.5 build: `node ./scripts/commands.js build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid brave@0.68.5
16 verbose cwd /data/maiar/brave-browser
17 error Linux 4.18.0-20-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "build" "--debug_build=true"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error brave@0.68.5 build: `node ./scripts/commands.js build`
22 error Exit status 1
23 error Failed at the brave@0.68.5 build script 'node ./scripts/commands.js build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the brave package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./scripts/commands.js build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs brave
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls brave
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by srirambv** [comment]
Did you install the build dependencies ? 

```
# cd to brave-browser repo root
./src/build/install-build-deps.sh
```

**Comment by bog2k3** [comment]
@srirambv yes, I did, and whenever I do, somehow /usr/bin/npm goes missing after that and I have to manually reinstall it in order to run "npm run build" again.

**Comment by srirambv** [comment]
cc: @simonhong / @iefremov  for more help on build issue

**Comment by simonhong** [comment]
@bog2k3 How about run `npm i` in `brave-browser/src/brave` and then re run `npm run build` in `brave-browser`?

**Comment by JoshuaCarter** [comment]
Just chiming in to say I have the same issue on Ubuntu 18.04 and same versions of npm and node.

Unfortunately @simonhong's suggestion didn't resolve the issue.

While we're talking about project setup, is the **huge** initial download and length build times unavoidable? Wanted to contribute but it's looking like this might be a painful project to work with.

**Comment by JoshuaCarter** [comment]
I ran the `npm run init` again and noticed this output which may or may not be problematic:

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.9
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none was installed.
```

Guessing the `fsevents` warnings aren't an issue, but less sure about `ajv-keywords`.

**Comment by bsclifton** [comment]
Looks like you're running Node 8 @bog2k3 @JoshuaCarter?  You need to be using v10 (LTS). Can you upgrade to that and give it a go?

That should also have a newer version of npm, but just in case I would try updating npm also. Let us know if that helps! 😄

**Comment by fmarier** [comment]
FYI, I am building Brave on Ubuntu 18.04 and it works fine for me. I'm using node v12.6.0 though from:

    deb https://deb.nodesource.com/node_12.x bionic main

and I also get the following after `npm install`:

    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
