### ISSUE TITLE
build on Red Hat Enterprise Linux Workstation release 7.6 (Maipo) fails

### ISSUE THREAD

**Issue by loetterle** [brave/brave-browser#4897]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/bin/npm', 'run', 'init' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'preinit', 'init', 'postinit' ]
5 info lifecycle brave@0.68.48~preinit: brave@0.68.48
6 info lifecycle brave@0.68.48~init: brave@0.68.48
7 verbose lifecycle brave@0.68.48~init: unsafe-perm in lifecycle true
8 verbose lifecycle brave@0.68.48~init: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/build/workspace/brave-browser/node_modules/.bin:/home/build/.rvm/gems/ruby-2.1.7/bin:/home/build/.rvm/gems/ruby-2.1.7@global/bin:/home/build/.rvm/rubies/ruby-2.1.7/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/var/lib/snapd/snap/bin:/home/build/.rvm/bin:/home/build/.local/bin:/home/build/bin
9 verbose lifecycle brave@0.68.48~init: CWD: /home/build/workspace/brave-browser
10 silly lifecycle brave@0.68.48~init: Args: [ '-c', 'node ./scripts/sync.js --init' ]
11 silly lifecycle brave@0.68.48~init: Returned: code: 1  signal: null
12 info lifecycle brave@0.68.48~init: Failed to exec init script
13 verbose stack Error: brave@0.68.48 init: `node ./scripts/sync.js --init`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid brave@0.68.48
15 verbose cwd /home/build/workspace/brave-browser
16 verbose Linux 3.10.0-957.21.2.el7.x86_64
17 verbose argv "/usr/bin/node" "/bin/npm" "run" "init"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error brave@0.68.48 init: `node ./scripts/sync.js --init`
22 error Exit status 1
23 error Failed at the brave@0.68.48 init script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

[build@localhost brave-browser]$ rpm -qf /bin/npm
nodejs-10.16.0-1nodesource.x86_64

**Comment by wwwutz** [comment]
Could you verify `/home/build` is located on a network file system ? I'm running into almost the same issue and to my current knowledge it is `npm` which randomly changes stdout to `O_NONBLOCK`. This and extremely long linking command lines might fill up and cut buffers. So the linking command line just isn't including the last couple of `.o` files with the result of symbols missing.

I'm still digging into this, but you might get it running by only building on a local file 'faster' system.

**Comment by bsclifton** [comment]
This issue hasn't had an update in a while - it's met the criteria for being stale. The issue is going to be closed for now. If this is still a problem, please leave a comment or re-open the issue. Thanks!
