### ISSUE TITLE
clicking on the "download arrow" doesn't save the file once the torrent is completed

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#5882]
## Description 

When attempting to download a saved file via clicking on the `download arrow` via the `SAVE FILE` column, nothing happens under `0.69.x` and you'll receive the error mentioned below.
## Steps to Reproduce

**`Test Case 1:`**

   1. launch `0.69.121 Chromium: 76.0.3809.132` 
   2. visit https://webtorrent.io/torrents/sintel.torrent and click on `Start Torrent`
   3. wait till it's 100% completed and click on the `download arrows` under the `SAVE FILE` column

**`Test Case 2:`** (found by @srirambv)

   1. launch `0.69.121 Chromium: 76.0.3809.132` 
   2. visit https://webtorrent.io/torrents/sintel.torrent and click on `Start Torrent`
   3. while the download is in progress, click a few of the `download arrows` under the `SAVE FILE` column
   4. stop the download via `Stop Torrent` and you'll receive `x` amount of save dialog modals (`x` being how many `download arrows` you clicked before stopping the torrent)

## Actual result:

Clicking on the `download arrows` once the download has been completed does nothing and displays the following error message:

```
Error in event handler: TypeError: c is not a constructor
    at _.y (chrome-extension://lgjmpdmojkpocjcopdikifhejkkjglho/extension/out/brave_webtorrent_background.bundle.js:15:578036)
    at _.a.emit (chrome-extension://lgjmpdmojkpocjcopdikifhejkkjglho/extension/out/brave_webtorrent_background.bundle.js:8:23109)
    at i.m.onIncoming (chrome-extension://lgjmpdmojkpocjcopdikifhejkkjglho/extension/out/brave_webtorrent_background.bundle.js:15:585843)
    at i.y (chrome-extension://lgjmpdmojkpocjcopdikifhejkkjglho/extension/out/brave_webtorrent_background.bundle.js:8:129833)
    at i.HEADER (chrome-extension://lgjmpdmojkpocjcopdikifhejkkjglho/extension/out/brave_webtorrent_background.bundle.js:15:62148)
    at i.execute (chrome-extension://lgjmpdmojkpocjcopdikifhejkkjglho/extension/out/brave_webtorrent_background.bundle.js:15:58950)
    at m._ (chrome-extension://lgjmpdmojkpocjcopdikifhejkkjglho/extension/out/brave_webtorrent_background.bundle.js:15:586185)
    at m.a.emit (chrome-extension://lgjmpdmojkpocjcopdikifhejkkjglho/extension/out/brave_webtorrent_background.bundle.js:8:23109)
    at w (chrome-extension://lgjmpdmojkpocjcopdikifhejkkjglho/extension/out/brave_webtorrent_background.bundle.js:15:81330)
    at _ (chrome-extension://lgjmpdmojkpocjcopdikifhejkkjglho/extension/out/brave_webtorrent_background.bundle.js:15:81145)
```

## Expected result:

Pressing the `download arrow` under the `SAVE FILE` should download the saved file.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.69.121 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No, not reproducible using 0.68.132 CR: 76.0.3809.132`
- Can you reproduce this issue with the beta channel? `Yes, reproducible using 0.69.122 CR: 76.0.3809.132`
- Can you reproduce this issue with the dev channel? `No, not reproducible using 0.70.89 CR: 76.0.3809.132`
- Can you reproduce this issue with the nightly channel? `No, not reproducible using 0.71.65 CR: 76.0.3809.132`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

Reproduced by @GeetaSarvadnya @LaurenWags and @btlechowski on Windows and macOS.

**Comment by yrliou** [comment]
Fixed by https://github.com/brave/brave-core/pull/3353

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.124 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Windows 10 OS Version 1803 (Build 17134.523)



- Verified the STR1 and STR2 mentioned in the description
![image](https://user-images.githubusercontent.com/38657976/64332306-f110f880-cff1-11e9-9a5f-60089bbc144d.png)


![image](https://user-images.githubusercontent.com/38657976/64332235-cf177600-cff1-11e9-871c-c8e780859c92.png)
