### ISSUE TITLE
Lint script fails.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#5971]
Lint step fails on CI with the following:

<pre>
09:35:45  /home/ubuntu/jenkins/workspace/ve-browser-build-pr_transfer-fee/src/brave: python /home/ubuntu/jenkins/workspace/ve-browser-build-pr_transfer-fee/scripts/lint.py --project_root=/home/ubuntu/jenkins/workspace/ve-browser-build-pr_transfer-fee/src --base_branch=origin/master
09:35:47  Traceback (most recent call last):
09:35:47    File "/home/ubuntu/jenkins/workspace/ve-browser-build-pr_transfer-fee/scripts/lint.py", line 86, in <module>
09:35:47      sys.exit(main(sys.argv[1:]))
09:35:47    File "/home/ubuntu/jenkins/workspace/ve-browser-build-pr_transfer-fee/scripts/lint.py", line 51, in main
09:35:47      cl = git_cl.Changelist(auth_config=auth_config)
09:35:47    File "/home/ubuntu/jenkins/workspace/ve-browser-build-pr_transfer-fee/vendor/depot_tools/git_cl.py", line 1092, in __init__
09:35:47      self._codereview_impl = _GerritChangelistImpl(self, **kwargs)
09:35:47  TypeError: __init__() got an unexpected keyword argument 'auth_config'
</pre>

**Comment by mkarolin** [comment]
cc: @mihaiplesa
