### ISSUE TITLE
build issue during npm run init 

### ISSUE THREAD

**Issue by yodor** [brave/brave-browser#6022]
## Description 
I'm having trouble starting the build process 

## Steps to Reproduce
1. clone the git repo
2. npm run init

## Actual result:
} catch {
^

SyntaxError: Unexpected token {
[2019-09-15T18_16_01_903Z-debug.log](https://github.com/brave/brave-browser/files/3614130/2019-09-15T18_16_01_903Z-debug.log)

## Expected result:
build to run correctly

## Miscellaneous Information:
npm run init

> brave@0.72.25 init /storage/work/local/brave-browser
> node ./scripts/sync.js --init

/storage/work/local/brave-browser/lib/gitPatcher.js:206
    } catch {
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/storage/work/local/brave-browser/scripts/sync.js:13:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brave@0.72.25 init: `node ./scripts/sync.js --init`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the brave@0.72.25 init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yodor/.npm/_logs/2019-09-15T18_16_01_903Z-debug.log

**Comment by bsclifton** [comment]
@yodor I believe you are running into this because you are running an older version of node

Can you please try installing the LTS version of Node.js?  (10.16.3 LTS). This should solve the problem 😄

**Comment by yodor** [comment]
@bsclifton Thanks :) just one more thing - reading the wiki about requirements say 

... You will need Git, Python 2.7, NodeJS >= 7.x, and npm ...

So I thought 8.12.0 is OK. Probably wiki needs update stating 10.16.3 LTS vs >7.x ?

**Comment by bsclifton** [comment]
@yodor great call - we missed updating that 😄 I just updated for each platform (macOS/Windows/Linux). Should be accurate now 😄
