### ISSUE TITLE
Lint issue

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#6434]
## Description 
During CI runs, we're seeing the following when `npm run lint` is being ran on brave-browser:
```
00:53:35  + git -C src/brave config user.name jenkins
00:53:35  + git -C src/brave config user.email no@reply.com
00:53:35  + git -C src/brave checkout -b TEMP_LINT_BRANCH_1
00:53:35  Switched to a new branch 'TEMP_LINT_BRANCH_1'
00:53:35  M	package-lock.json
00:53:35  + npm run lint -- --base=origin/0.71.x
00:53:35  
00:53:35  > brave@0.71.90 lint /home/ubuntu/jenkins/workspace/ix_private_dont_ask_again_0.71.x
00:53:35  > node ./scripts/commands.js lint "--base=origin/0.71.x"
00:53:35  
00:53:35  /home/ubuntu/jenkins/workspace/ix_private_dont_ask_again_0.71.x/src/brave: python /home/ubuntu/jenkins/workspace/ix_private_dont_ask_again_0.71.x/scripts/lint.py --project_root=/home/ubuntu/jenkins/workspace/ix_private_dont_ask_again_0.71.x/src --base_branch=origin/0.71.x
00:53:36  Traceback (most recent call last):
00:53:36    File "/home/ubuntu/jenkins/workspace/ix_private_dont_ask_again_0.71.x/scripts/lint.py", line 20, in <module>
00:53:36      import git_cl
00:53:36    File "/home/ubuntu/jenkins/workspace/ix_private_dont_ask_again_0.71.x/vendor/depot_tools/git_cl.py", line 40, in <module>
00:53:36      import auth
00:53:36    File "/home/ubuntu/jenkins/workspace/ix_private_dont_ask_again_0.71.x/vendor/depot_tools/auth.py", line 12, in <module>
00:53:36      import httplib2
00:53:36  ImportError: No module named httplib2
00:53:36  null
00:53:36  null
00:53:36  npm ERR! code ELIFECYCLE
00:53:36  npm ERR! errno 1
00:53:36  npm ERR! brave@0.71.90 lint: `node ./scripts/commands.js lint "--base=origin/0.71.x"`
00:53:36  npm ERR! Exit status 1
00:53:36  npm ERR! 
00:53:36  npm ERR! Failed at the brave@0.71.90 lint script.
00:53:36  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
00:53:36  
00:53:36  npm ERR! A complete log of this run can be found in:
00:53:36  npm ERR!     /home/ubuntu/.npm/_logs/2019-10-11T07_53_35_990Z-debug.log
```

This appears to have been introduced around the time that the Chromium 78 took place

**Comment by bsclifton** [comment]
Issue resolved - looks like it was an upstream depot_tools problem

May have been fixed with https://chromium.googlesource.com/chromium/tools/depot_tools.git/+/12265a8f7de02667caa3961b95760c0f37d743dd

**Comment by jumde** [comment]
Re-opening sincee this change re-landed: https://chromium.googlesource.com/chromium/tools/depot_tools.git/+/88d7869db09169044c1a0b2d1fbb57f11ffaee2a

Possible fix: https://github.com/brave/brave-browser/pull/6455
