### ISSUE TITLE
Following the build instructions, the `elifecycle` package does not exit.

### ISSUE THREAD

**Issue by gusbemacbe** [brave/brave-browser#6512]
## Description 
We are Arch Linux users, followed the build instructions at the wiki. When we began to run the command `npm run init`, but we received the error, indicating that `elifecycle` does not exist.

## Steps to Reproduce

   1. Follow the build instructions on Arch Linux
   2. Until the command `elifecycle`, and
   3. We received the error. 

Observe that we also tried to run the `sudo npm -g install elifecycle` and itw as the same error.

## Actual result:
Please check the attached log. 

## Expected result:
Nothing, as if `elifecycle` was available. 

## Reproduces how often: 
There is not how to reproduce good result, as the package is not available

## Brave version (brave://version info)
Latest commit from this GitHub repository

## Version/Channel Information:
Nightly

- Can you reproduce this issue with the current release?
No
- Can you reproduce this issue with the beta channel?
No
- Can you reproduce this issue with the dev channel?
Yes
- Can you reproduce this issue with the nightly channel?
Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No, it does not anything to do with the missed package.
- Does the issue resolve itself when disabling Brave Rewards?
No, it does not anything to do with the missed package.
- Is the issue reproducible on the latest version of Chrome? 
No, it does not anything to do with the missed package.

## Miscellaneous Information:
[2019-10-16T20_56_43_639Z-debug.log](https://github.com/brave/brave-browser/files/3736705/2019-10-16T20_56_43_639Z-debug.log)

**Comment by fmarier** [comment]
While we are grateful to the people who maintain third-party builds of Brave, we can't officially support them. The Arch package is one of those that isn't made by Brave, so you would probably have better luck asking about this on the Arch forums.

**Comment by fmarier** [comment]
My apologies, I misread your report. You are in fact talking about building from source on Arch Linux.

**Comment by fmarier** [comment]
I'm not sure why your build is trying to install this non-existent package.

On my local checkout (on Ubuntu 18.04), I don't have that package installed and I can build Brave just fine:

```
$ npm list | grep life
$
```

**Comment by gusbemacbe** [comment]
> My apologies, I misread your report. You are in fact talking about building from source on Arch Linux.

Correct, I was building from source. I did not build or install from AUR.

Here is the result:

```
npm list | grep life
npm ERR! extraneous: @types/chai-as-promised@0.0.31 /home/gusbemacbe/node_modules/nativescript/node_modules/@types/chai-as-promised
npm ERR! extraneous: @types/chokidar@1.6.0 /home/gusbemacbe/node_modules/nativescript/node_modules/@types/chokidar
npm ERR! extraneous: @types/color@3.0.0 /home/gusbemacbe/node_modules/nativescript/node_modules/@types/color
npm ERR! extraneous: @types/convert-source-map@1.5.1 /home/gusbemacbe/node_modules/nativescript/node_modules/@types/convert-source-map
npm ERR! extraneous: @types/glob@7.1.1 /home/gusbemacbe/node_modules/nativescript/node_modules/@types/glob
npm ERR! extraneous: @types/inquirer@0.0.43 /home/gusbemacbe/node_modules/nativescript/node_modules/@types/inquirer
npm ERR! extraneous: @types/lodash@4.14.123 /home/gusbemacbe/node_modules/nativescript/node_modules/@types/lodash
npm ERR! extraneous: @types/ora@1.3.3 /home/gusbemacbe/node_modules/nativescript/node_modules/@types/ora
npm ERR! extraneous: @types/proper-lockfile@3.0.1 /home/gusbemacbe/node_modules/nativescript/node_modules/@types/proper-lockfile
npm ERR! extraneous: @types/qr-image@3.2.0 /home/gusbemacbe/node_modules/nativescript/node_modules/@types/qr-image
npm ERR! extraneous: @types/request@0.0.45 /home/gusbemacbe/node_modules/nativescript/node_modules/@types/request
npm ERR! extraneous: @types/retry@0.12.0 /home/gusbemacbe/node_modules/nativescript/node_modules/@types/retry
npm ERR! extraneous: @types/semver@5.5.0 /home/gusbemacbe/node_modules/nativescript/node_modules/@types/semver
npm ERR! extraneous: @types/sinon@4.0.0 /home/gusbemacbe/node_modules/nativescript/node_modules/@types/sinon
npm ERR! extraneous: @types/source-map@0.5.0 /home/gusbemacbe/node_modules/nativescript/node_modules/@types/source-map
npm ERR! extraneous: @types/tar@4.0.0 /home/gusbemacbe/node_modules/nativescript/node_modules/@types/tar
npm ERR! extraneous: @types/universal-analytics@0.4.1 /home/gusbemacbe/node_modules/nativescript/node_modules/@types/universal-analytics
npm ERR! extraneous: @types/ws@4.0.1 /home/gusbemacbe/node_modules/nativescript/node_modules/@types/ws
npm ERR! extraneous: @types/xml2js@0.4.3 /home/gusbemacbe/node_modules/nativescript/node_modules/@types/xml2js
npm ERR! extraneous: @types/yargs@13.0.0 /home/gusbemacbe/node_modules/nativescript/node_modules/@types/yargs
npm ERR! extraneous: chai@4.0.2 /home/gusbemacbe/node_modules/nativescript/node_modules/chai
npm ERR! extraneous: chai-as-promised@7.0.0 /home/gusbemacbe/node_modules/nativescript/node_modules/chai-as-promised
npm ERR! extraneous: grunt@1.0.1 /home/gusbemacbe/node_modules/nativescript/node_modules/grunt
npm ERR! extraneous: grunt-contrib-clean@1.0.0 /home/gusbemacbe/node_modules/nativescript/node_modules/grunt-contrib-clean
npm ERR! extraneous: grunt-contrib-copy@1.0.0 /home/gusbemacbe/node_modules/nativescript/node_modules/grunt-contrib-copy
npm ERR! extraneous: grunt-contrib-watch@1.0.0 /home/gusbemacbe/node_modules/nativescript/node_modules/grunt-contrib-watch
npm ERR! extraneous: grunt-shell@1.3.0 /home/gusbemacbe/node_modules/nativescript/node_modules/grunt-shell
npm ERR! extraneous: grunt-template@1.0.0 /home/gusbemacbe/node_modules/nativescript/node_modules/grunt-template
npm ERR! extraneous: grunt-ts@6.0.0-beta.22 /home/gusbemacbe/node_modules/nativescript/node_modules/grunt-ts
npm ERR! extraneous: istanbul@0.4.5 /home/gusbemacbe/node_modules/nativescript/node_modules/istanbul
npm ERR! extraneous: latest-version@4.0.0 /home/gusbemacbe/node_modules/nativescript/node_modules/latest-version
npm ERR! extraneous: mocha@3.1.2 /home/gusbemacbe/node_modules/nativescript/node_modules/mocha
npm ERR! extraneous: should@7.0.2 /home/gusbemacbe/node_modules/nativescript/node_modules/should
npm ERR! extraneous: sinon@4.1.2 /home/gusbemacbe/node_modules/nativescript/node_modules/sinon
npm ERR! extraneous: source-map-support@0.5.3 /home/gusbemacbe/node_modules/nativescript/node_modules/source-map-support
npm ERR! extraneous: tslint@5.14.0 /home/gusbemacbe/node_modules/nativescript/node_modules/tslint
npm ERR! extraneous: tslint-microsoft-contrib@6.1.0 /home/gusbemacbe/node_modules/nativescript/node_modules/tslint-microsoft-contrib
npm ERR! extraneous: typescript@3.3.4000 /home/gusbemacbe/node_modules/nativescript/node_modules/typescript
```

**Comment by gusbemacbe** [comment]
And here is:

![image](https://user-images.githubusercontent.com/2257024/67607383-b22e3200-f75a-11e9-8748-55eb296c3f65.png)

**Comment by fmarier** [comment]
@antonok-edm You don't have any problems building on Arch, right?

**Comment by antonok-edm** [comment]
Only issue I have (which I believe affects all Linux distros) is https://github.com/brave/brave-browser/issues/11099.

The `npm ERR! code ELIFECYCLE` line from your log isn't referring to an npm package, it's a [more general script error](https://stackoverflow.com/questions/30744964/what-does-the-elifecycle-node-js-error-mean).

I think the real error is here:
```
Traceback (most recent call last):
  File "src/third_party/binutils/download.py", line 120, in <module>
    sys.exit(main(sys.argv[1:]))
  File "src/third_party/binutils/download.py", line 107, in main
    return FetchAndExtract(arch)
  File "src/third_party/binutils/download.py", line 72, in FetchAndExtract
    '-s', sha1file])
  File "/usr/lib64/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['download_from_google_storage', '--no_resume', '--no_auth', '--bucket', 'chromium-binutils', '-s', '/home/up/brave-browser/src/third_party/binutils/Linux_x64/binutils.tar.bz2.sha1']' returned non-zero exit status 1
```

I've never seen that before personally, but it looks like there's some issue fetching the chromium binutils package.

**Comment by antonok-edm** [comment]
One last thing to note is that on Arch, you'll need to make sure you're using `python2` rather than the default `python3`. It looks like you've probably done this, but just want to make sure.

I personally accomplish this by using a directory with a symlink called `python` that points to `/usr/bin/python2`, and adding that directory to the beginning of my `PATH` environment variable before starting a build.
