### ISSUE TITLE
Brave Shields defaults blocks login on my.1password.com

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#6561]
More details here: https://bravesoftware.slack.com/archives/C2FQMN4AD/p1571449026075800

This  seems this only happens on macOS Catalina.

```
Content Security Policies delivered via a <meta> element may not contain the report-uri directive.
Stop!
This feature is for use by web developers. Copying and pasting text here that came from someone else could give them access to your 1Password data.
b5-bb8f48df97ec31c041fc.min.js:1 crypto tests: 14.549072265625ms
b5-bb8f48df97ec31c041fc.min.js:1 Crypto init and tests are complete
jwkImport: true
rsaOaep256: true
nativeAesGcm: true
nativePbes2: true
nativeEcdsa: true
app-0c34e9547fb59f6925c6.min.js:1 Last sign out message is not available.
b5-bb8f48df97ec31c041fc.min.js:1 GET https://accounts.1password.ca/api/v1/accountcookies
b5-bb8f48df97ec31c041fc.min.js:1 GET https://accounts.1password.eu/api/v1/accountcookies
b5-bb8f48df97ec31c041fc.min.js:1 GET https://accounts.ent.1password.com/api/v1/accountcookies
b5-bb8f48df97ec31c041fc.min.js:1 GET https://accounts.1password.com/api/v1/accountcookies
b5-bb8f48df97ec31c041fc.min.js:1 GET /api/v2/auth/r.chikaki%40gmail.com/A3/VQB6YL/hyjjpbzruebzo6gjyzcqj7bqnq
b5-bb8f48df97ec31c041fc.min.js:1 POST /api/v1/device
b5-bb8f48df97ec31c041fc.min.js:1 GET /api/v2/auth/r.chikaki%40gmail.com/A3/VQB6YL/hyjjpbzruebzo6gjyzcqj7bqnq
b5-bb8f48df97ec31c041fc.min.js:1 POST /api/v1/auth
b5-bb8f48df97ec31c041fc.min.js:1 POST /api/v2/auth/verify
b5-bb8f48df97ec31c041fc.min.js:1 Loaded 267 bytes
b5-bb8f48df97ec31c041fc.min.js:1 GET /api/v1/account/keysets
b5-bb8f48df97ec31c041fc.min.js:1 Loaded 14225 bytes
b5-bb8f48df97ec31c041fc.min.js:1 PBES2g-HS256(100000): 46.967041015625ms
b5-bb8f48df97ec31c041fc.min.js:1 GET /api/v1/account?attrs=account-flags,billing,counts,invite,me,promotions,settings,tier,user-flags,groups
b5-bb8f48df97ec31c041fc.min.js:1 Unknown error Error: The request response is empty
    at _handleQwestError (b5-bb8f48df97ec31c041fc.min.js:1)
    at Array.l (vendor-4b648bcfb5e7adc3a148.min.js:65)
    at vendor-4b648bcfb5e7adc3a148.min.js:65
    at vendor-4b648bcfb5e7adc3a148.min.js:65
    at _ (vendor-4b648bcfb5e7adc3a148.min.js:65)
    at s (vendor-4b648bcfb5e7adc3a148.min.js:65)
_handleQwestError @ b5-bb8f48df97ec31c041fc.min.js:1
l @ vendor-4b648bcfb5e7adc3a148.min.js:65
(anonymous) @ vendor-4b648bcfb5e7adc3a148.min.js:65
(anonymous) @ vendor-4b648bcfb5e7adc3a148.min.js:65
_ @ vendor-4b648bcfb5e7adc3a148.min.js:65
s @ vendor-4b648bcfb5e7adc3a148.min.js:65
postMessage (async)
r @ vendor-4b648bcfb5e7adc3a148.min.js:65
f.setImmediate @ vendor-4b648bcfb5e7adc3a148.min.js:65
i @ vendor-4b648bcfb5e7adc3a148.min.js:65
u @ vendor-4b648bcfb5e7adc3a148.min.js:65
(anonymous) @ vendor-4b648bcfb5e7adc3a148.min.js:15
l @ vendor-4b648bcfb5e7adc3a148.min.js:65
(anonymous) @ vendor-4b648bcfb5e7adc3a148.min.js:65
(anonymous) @ vendor-4b648bcfb5e7adc3a148.min.js:65
_ @ vendor-4b648bcfb5e7adc3a148.min.js:65
s @ vendor-4b648bcfb5e7adc3a148.min.js:65
postMessage (async)
r @ vendor-4b648bcfb5e7adc3a148.min.js:65
f.setImmediate @ vendor-4b648bcfb5e7adc3a148.min.js:65
i @ vendor-4b648bcfb5e7adc3a148.min.js:65
u @ vendor-4b648bcfb5e7adc3a148.min.js:65
E @ vendor-4b648bcfb5e7adc3a148.min.js:15
load (async)
i.send @ vendor-4b648bcfb5e7adc3a148.min.js:15
(anonymous) @ vendor-4b648bcfb5e7adc3a148.min.js:15
(anonymous) @ vendor-4b648bcfb5e7adc3a148.min.js:15
m.map @ vendor-4b648bcfb5e7adc3a148.min.js:15
map @ vendor-4b648bcfb5e7adc3a148.min.js:15
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Promise.then (async)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
_request @ b5-bb8f48df97ec31c041fc.min.js:1
get @ b5-bb8f48df97ec31c041fc.min.js:1
D @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Promise.then (async)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Promise.then (async)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
WC @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Promise.then (async)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
JC @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Promise.then (async)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
tg @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Promise.then (async)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Promise.then (async)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Vm @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Zm @ b5-bb8f48df97ec31c041fc.min.js:1
Gm @ b5-bb8f48df97ec31c041fc.min.js:1
n.signIn @ app-0c34e9547fb59f6925c6.min.js:1
(anonymous) @ app-0c34e9547fb59f6925c6.min.js:1
ro @ vendor-4b648bcfb5e7adc3a148.min.js:56
no @ vendor-4b648bcfb5e7adc3a148.min.js:56
No @ vendor-4b648bcfb5e7adc3a148.min.js:56
qo @ vendor-4b648bcfb5e7adc3a148.min.js:56
(anonymous) @ vendor-4b648bcfb5e7adc3a148.min.js:56
t.unstable_runWithPriority @ vendor-4b648bcfb5e7adc3a148.min.js:65
As @ vendor-4b648bcfb5e7adc3a148.min.js:56
Hs @ vendor-4b648bcfb5e7adc3a148.min.js:56
Os @ vendor-4b648bcfb5e7adc3a148.min.js:56
Is @ vendor-4b648bcfb5e7adc3a148.min.js:56
Sn @ vendor-4b648bcfb5e7adc3a148.min.js:56
b5-bb8f48df97ec31c041fc.min.js:1 XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 30000, withCredentials: false, upload: XMLHttpRequestUpload, …}
b5-bb8f48df97ec31c041fc.min.js:1 [_request] Request "/api/v1/account?attrs=account-flags,billing,counts,invite,me,promotions,settings,tier,user-flags,groups" failed: LegacyServerError: Unknown error: The request response is empty
    at new t (https://app.1password.com/js/b5-bb8f48df97ec31c041fc.min.js:1:128153)
    at _handleQwestError (https://app.1password.com/js/b5-bb8f48df97ec31c041fc.min.js:1:337725)
    at Array.l (https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:140592)
    at https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:140254
    at https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:19966
    at _ (https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:20076)
    at s (https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:19439)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Promise.catch (async)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
_request @ b5-bb8f48df97ec31c041fc.min.js:1
get @ b5-bb8f48df97ec31c041fc.min.js:1
D @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Promise.then (async)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Promise.then (async)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
WC @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Promise.then (async)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
JC @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Promise.then (async)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
tg @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Promise.then (async)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Promise.then (async)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Vm @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Zm @ b5-bb8f48df97ec31c041fc.min.js:1
Gm @ b5-bb8f48df97ec31c041fc.min.js:1
n.signIn @ app-0c34e9547fb59f6925c6.min.js:1
(anonymous) @ app-0c34e9547fb59f6925c6.min.js:1
ro @ vendor-4b648bcfb5e7adc3a148.min.js:56
no @ vendor-4b648bcfb5e7adc3a148.min.js:56
No @ vendor-4b648bcfb5e7adc3a148.min.js:56
qo @ vendor-4b648bcfb5e7adc3a148.min.js:56
(anonymous) @ vendor-4b648bcfb5e7adc3a148.min.js:56
t.unstable_runWithPriority @ vendor-4b648bcfb5e7adc3a148.min.js:65
As @ vendor-4b648bcfb5e7adc3a148.min.js:56
Hs @ vendor-4b648bcfb5e7adc3a148.min.js:56
Os @ vendor-4b648bcfb5e7adc3a148.min.js:56
Is @ vendor-4b648bcfb5e7adc3a148.min.js:56
Sn @ vendor-4b648bcfb5e7adc3a148.min.js:56
b5-bb8f48df97ec31c041fc.min.js:1 [action/account#getAccountWithAttrs] LegacyServerError: Unknown error: The request response is empty
    at new t (https://app.1password.com/js/b5-bb8f48df97ec31c041fc.min.js:1:128153)
    at _handleQwestError (https://app.1password.com/js/b5-bb8f48df97ec31c041fc.min.js:1:337725)
    at Array.l (https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:140592)
    at https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:140254
    at https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:19966
    at _ (https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:20076)
    at s (https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:19439)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
L @ vendor-4b648bcfb5e7adc3a148.min.js:68
Promise.catch (async)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
WC @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Promise.then (async)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
JC @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Promise.then (async)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
tg @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Promise.then (async)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Promise.then (async)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Vm @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Zm @ b5-bb8f48df97ec31c041fc.min.js:1
Gm @ b5-bb8f48df97ec31c041fc.min.js:1
n.signIn @ app-0c34e9547fb59f6925c6.min.js:1
(anonymous) @ app-0c34e9547fb59f6925c6.min.js:1
ro @ vendor-4b648bcfb5e7adc3a148.min.js:56
no @ vendor-4b648bcfb5e7adc3a148.min.js:56
No @ vendor-4b648bcfb5e7adc3a148.min.js:56
qo @ vendor-4b648bcfb5e7adc3a148.min.js:56
(anonymous) @ vendor-4b648bcfb5e7adc3a148.min.js:56
t.unstable_runWithPriority @ vendor-4b648bcfb5e7adc3a148.min.js:65
As @ vendor-4b648bcfb5e7adc3a148.min.js:56
Hs @ vendor-4b648bcfb5e7adc3a148.min.js:56
Os @ vendor-4b648bcfb5e7adc3a148.min.js:56
Is @ vendor-4b648bcfb5e7adc3a148.min.js:56
Sn @ vendor-4b648bcfb5e7adc3a148.min.js:56
b5-bb8f48df97ec31c041fc.min.js:1 [action/account#getEntireAccount] LegacyServerError: Unknown error: The request response is empty
    at new t (https://app.1password.com/js/b5-bb8f48df97ec31c041fc.min.js:1:128153)
    at _handleQwestError (https://app.1password.com/js/b5-bb8f48df97ec31c041fc.min.js:1:337725)
    at Array.l (https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:140592)
    at https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:140254
    at https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:19966
    at _ (https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:20076)
    at s (https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:19439)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
L @ vendor-4b648bcfb5e7adc3a148.min.js:68
Promise.catch (async)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
JC @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Promise.then (async)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
tg @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Promise.then (async)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Promise.then (async)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Vm @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Zm @ b5-bb8f48df97ec31c041fc.min.js:1
Gm @ b5-bb8f48df97ec31c041fc.min.js:1
n.signIn @ app-0c34e9547fb59f6925c6.min.js:1
(anonymous) @ app-0c34e9547fb59f6925c6.min.js:1
ro @ vendor-4b648bcfb5e7adc3a148.min.js:56
no @ vendor-4b648bcfb5e7adc3a148.min.js:56
No @ vendor-4b648bcfb5e7adc3a148.min.js:56
qo @ vendor-4b648bcfb5e7adc3a148.min.js:56
(anonymous) @ vendor-4b648bcfb5e7adc3a148.min.js:56
t.unstable_runWithPriority @ vendor-4b648bcfb5e7adc3a148.min.js:65
As @ vendor-4b648bcfb5e7adc3a148.min.js:56
Hs @ vendor-4b648bcfb5e7adc3a148.min.js:56
Os @ vendor-4b648bcfb5e7adc3a148.min.js:56
Is @ vendor-4b648bcfb5e7adc3a148.min.js:56
Sn @ vendor-4b648bcfb5e7adc3a148.min.js:56
b5-bb8f48df97ec31c041fc.min.js:1 [action/auth#handleSignInSuccess] LegacyServerError: Unknown error: The request response is empty
    at new t (https://app.1password.com/js/b5-bb8f48df97ec31c041fc.min.js:1:128153)
    at _handleQwestError (https://app.1password.com/js/b5-bb8f48df97ec31c041fc.min.js:1:337725)
    at Array.l (https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:140592)
    at https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:140254
    at https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:19966
    at _ (https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:20076)
    at s (https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:19439)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
L @ vendor-4b648bcfb5e7adc3a148.min.js:68
Promise.catch (async)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
tg @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Promise.then (async)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Promise.then (async)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Vm @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Zm @ b5-bb8f48df97ec31c041fc.min.js:1
Gm @ b5-bb8f48df97ec31c041fc.min.js:1
n.signIn @ app-0c34e9547fb59f6925c6.min.js:1
(anonymous) @ app-0c34e9547fb59f6925c6.min.js:1
ro @ vendor-4b648bcfb5e7adc3a148.min.js:56
no @ vendor-4b648bcfb5e7adc3a148.min.js:56
No @ vendor-4b648bcfb5e7adc3a148.min.js:56
qo @ vendor-4b648bcfb5e7adc3a148.min.js:56
(anonymous) @ vendor-4b648bcfb5e7adc3a148.min.js:56
t.unstable_runWithPriority @ vendor-4b648bcfb5e7adc3a148.min.js:65
As @ vendor-4b648bcfb5e7adc3a148.min.js:56
Hs @ vendor-4b648bcfb5e7adc3a148.min.js:56
Os @ vendor-4b648bcfb5e7adc3a148.min.js:56
Is @ vendor-4b648bcfb5e7adc3a148.min.js:56
Sn @ vendor-4b648bcfb5e7adc3a148.min.js:56
b5-bb8f48df97ec31c041fc.min.js:1 [action/auth#signIn] LegacyServerError: Unknown error: The request response is empty
    at new t (https://app.1password.com/js/b5-bb8f48df97ec31c041fc.min.js:1:128153)
    at _handleQwestError (https://app.1password.com/js/b5-bb8f48df97ec31c041fc.min.js:1:337725)
    at Array.l (https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:140592)
    at https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:140254
    at https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:19966
    at _ (https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:20076)
    at s (https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:19439)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
L @ vendor-4b648bcfb5e7adc3a148.min.js:68
Promise.catch (async)
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Vm @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
(anonymous) @ b5-bb8f48df97ec31c041fc.min.js:1
Zm @ b5-bb8f48df97ec31c041fc.min.js:1
Gm @ b5-bb8f48df97ec31c041fc.min.js:1
n.signIn @ app-0c34e9547fb59f6925c6.min.js:1
(anonymous) @ app-0c34e9547fb59f6925c6.min.js:1
ro @ vendor-4b648bcfb5e7adc3a148.min.js:56
no @ vendor-4b648bcfb5e7adc3a148.min.js:56
No @ vendor-4b648bcfb5e7adc3a148.min.js:56
qo @ vendor-4b648bcfb5e7adc3a148.min.js:56
(anonymous) @ vendor-4b648bcfb5e7adc3a148.min.js:56
t.unstable_runWithPriority @ vendor-4b648bcfb5e7adc3a148.min.js:65
As @ vendor-4b648bcfb5e7adc3a148.min.js:56
Hs @ vendor-4b648bcfb5e7adc3a148.min.js:56
Os @ vendor-4b648bcfb5e7adc3a148.min.js:56
Is @ vendor-4b648bcfb5e7adc3a148.min.js:56
Sn @ vendor-4b648bcfb5e7adc3a148.min.js:56
app-0c34e9547fb59f6925c6.min.js:1 Sign in failed:  LegacyServerError: Unknown error: The request response is empty
    at new t (https://app.1password.com/js/b5-bb8f48df97ec31c041fc.min.js:1:128153)
    at _handleQwestError (https://app.1password.com/js/b5-bb8f48df97ec31c041fc.min.js:1:337725)
    at Array.l (https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:140592)
    at https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:140254
    at https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:19966
    at _ (https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:20076)
    at s (https://app.1password.com/js/vendor-4b648bcfb5e7adc3a148.min.js:65:19439)
```

**Comment by tomahl** [comment]
If you have "Device recognition blocked" you might wanna try to make an exeption for that site in the shield pane.

**Comment by ConvexPolygon** [comment]
There's a really simple solution. Just turn off the shields for 1password.com

**Comment by jumde** [comment]
This does not repro on `1.10.9 Chromium: 81.0.4044.122`. Closing
