### ISSUE TITLE
"chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd" errors when disabling/enabling shields

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#6828]
## Description 

When disabling/enabling shields, `chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd` will produce errors in the terminal as demonstrated in the `Actual result` section below.

## Steps to Reproduce

   1. install `0.70.122 Chromium: 78.0.3904.87` or `0.70.123 Chromium: 78.0.3904.97`
   2. launch using `--enable-logging=stderr`
   3. visit https://brave.com/ and disable/enable `Shields`

## Actual result:

```
Error
    at V (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1:62399)
    at x.n._warn (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1:57099)
    at Object.checkForgottenReturns (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1:67673)
    at x._settlePromiseFromHandler (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1:92308)
From previous event:
    at x.N [as _captureStackTrace] (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1:62039)
    at x._then (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1:87650)
    at x.then (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1:86006)
    at cosmeticFilter (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1:25457)
    at chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1:14483
    at _ (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1:12525)
    at Object.dispatch (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1:18187)
    at i (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1:132236) color: darkorange", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
```

## Expected result:

Shouldn't be seeing the above errors when disabling/enabling shields.

## Reproduces how often: 

100% reproducible when going through the above STR.

## Brave version (brave://version info)

Brave | 0.70.123 Chromium: 78.0.3904.97 (Official Build) (64-bit)
--- | ---
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @brave/legacy_qa @bsclifton @rebron @petemill @cezaraugusto

**Comment by rebron** [comment]
@kjozwiak retest in 1.2 to see if this is still an issue.

**Comment by kjozwiak** [comment]
@rebron looks like this is still happening with the following build:

Brave | 1.3.91 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | macOS Version 10.15.2 (Build 19C57)

```
[47434:775:0114/195835.314610:WARNING:CONSOLE(1)] "%cWarning: a promise was created in a handler at /mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1:44795 but was not returned from it, see http://goo.gl/rRqMUw
Error
    at V (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1:58616)
    at x.n._warn (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1:53321)
    at Object.checkForgottenReturns (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1:63880)
    at x._settlePromiseFromHandler (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1:88528)
From previous event:
    at x.N [as _captureStackTrace] (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1:58256)
    at x._then (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1:83866)
    at x.then (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1:82222)
    at shieldsPanel (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1:4428)
    at chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1:128751
    at _ (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1:126791)
    at Object.dispatch (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1:1663)
    at i (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1:136027) color: darkorange", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
```

**Comment by mariospr** [comment]
I'm seeing these kind of errors on today's build off the `master` branch (Brave 1.20.28 - based on Chromium 88.0.4315.5):
```
[2697829:2697829:1215/182658.592733:WARNING:render_widget_host_impl.cc(267)] Input request on unbound interface
[2697829:2697829:1215/182700.174136:WARNING:CONSOLE(20063)] "%cWarning: a promise was created in a handler at /mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:2390:45 but was not returned from it, see http://goo.gl/rRqMUw
    at new Promise (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:21221:10)
    at reloadTab (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1143:43)
    at chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:2390:45
From previous event:
    at shieldsPanelReducer (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:2389:18)
    at combination (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:25197:29)
    at dispatch (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:24957:22)
    at Object.dispatch (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:2020:16)
    at dispatchResponse (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:26616:32)
    at chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:25904:25 color: darkorange", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (20063)
```
Maybe worth reopening this ticket?

**Comment by mariospr** [comment]
> I'm seeing these kind of errors on today's build off the `master` branch (Brave 1.20.28 - based on Chromium 88.0.4315.5):
> 
> ```
> [2697829:2697829:1215/182658.592733:WARNING:render_widget_host_impl.cc(267)] Input request on unbound interface
> [2697829:2697829:1215/182700.174136:WARNING:CONSOLE(20063)] "%cWarning: a promise was created in a handler at /mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:2390:45 but was not returned from it, see http://goo.gl/rRqMUw
>     at new Promise (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:21221:10)
>     at reloadTab (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:1143:43)
>     at chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:2390:45
> From previous event:
>     at shieldsPanelReducer (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:2389:18)
>     at combination (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:25197:29)
>     at dispatch (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:24957:22)
>     at Object.dispatch (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:2020:16)
>     at dispatchResponse (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:26616:32)
>     at chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js:25904:25 color: darkorange", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (20063)
> ```
> 
> Maybe worth reopening this ticket?

Filed new ticket at https://github.com/brave/brave-browser/issues/13216

**Comment by philiprhoades** [comment]
Version 1.30.89 Chromium: 94.0.4606.81 (Official Build) (64-bit)

```
[39513:39513:1225/011945.339213:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 814.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[39513:39513:1225/011945.346985:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 814.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[39513:39513:1225/105821.776205:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 817.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[39513:39513:1225/105821.780606:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 817.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[39513:39513:1225/110536.412658:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 821.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[39513:39513:1225/110536.412858:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 821.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[39513:39513:1225/110536.415941:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 821.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[39513:39513:1225/110653.562712:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 823.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[39513:39513:1225/110653.563443:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 823.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[39513:39513:1225/110653.563487:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 823.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
```

As far as I know I am not doing anything with shields . . but Brave keeps locking up after a while and these errors are commonly the last in the log file when I kill Brave . .

**Comment by pb360** [comment]
I have a very similar thing happening as to @philiprhoades 

II get the following output in the terminal I am running a jupyter notebook every time i open a new tab, and do some other actions. 

It usually doesn't seem to affect performance, but i did not request this output via any commands. 

```[3728:3728:0412/145515.207967:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 272.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[3728:3728:0412/145515.789448:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 273.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[3728:3728:0412/145515.790472:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 273.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[3728:3728:0412/145516.301801:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 274.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[3728:3728:0412/145516.303560:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 274.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[3766:3773:0412/145524.762967:ERROR:ssl_client_socket_impl.cc(997)] handshake failed; returned -1, SSL error code 1, net_error -113
[3766:3773:0412/145524.804338:ERROR:ssl_client_socket_impl.cc(997)] handshake failed; returned -1, SSL error code 1, net_error -113
[3728:3728:0412/145535.573644:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 275.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[3728:3728:0412/145535.573672:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 275.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[3728:3728:0412/145535.573687:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 275.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[3728:3728:0412/145535.695173:ERROR:interface_endpoint_client.cc(659)] Message 0 rejected by interface blink.mojom.WidgetHost
[3728:3728:0412/145555.029056:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 276.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[3728:3728:0412/145555.029086:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 276.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[3728:3728:0412/145623.194165:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 286.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[3728:3728:0412/145623.194470:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 286.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[3728:3728:0412/145623.194741:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 286.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[3728:3728:0412/145734.255915:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 290.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[3728:3728:0412/145734.255944:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 290.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[3728:3728:0412/145740.991723:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 291.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
```
