### ISSUE TITLE
Reland transpiling things separately PR

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#702]
https://github.com/brave/brave-core/pull/309 was reverted due to a build problem on Windows.

Please re-land once fixed:

```
[120/12308] ACTION //brave/components/brave_rewards_ui:brave_rewards_ui(//build/toolchain/win:win_clang_x64)
FAILED: gen/brave/brave_rewards.bundle.js
C:/brave-browser/vendor/depot_tools/win_tools-2_7_6_bin/python/bin/python.exe ../../brave/script/transpile-web-ui.py --target_gen_dir=C:/brave-browser/src/out/Release/gen/brave --production

> brave-core@0.54.0 web-ui C:\brave-browser\src\brave
> webpack --config components/webpack/prod.config.js --progress --profile --colors

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "C:/brave-browser/src/out/Release/gen/brave" is not an absolute path!
   -> The output directory as **absolute path** (required).
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brave-core@0.54.0 web-ui: `webpack --config components/webpack/prod.config.js --progress --profile --colors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the brave-core@0.54.0 web-ui script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Owner\AppData\Roaming\npm-cache\_logs\2018-08-06T11_36_47_250Z-debug.log

Traceback (most recent call last):
  File "../../brave/script/transpile-web-ui.py", line 40, in <module>
    sys.exit(main())
  File "../../brave/script/transpile-web-ui.py", line 12, in main
    transpile_web_uis(args.production, args.target_gen_dir[0])
  File "../../brave/script/transpile-web-ui.py", line 37, in transpile_web_uis
    execute_stdout(args, env)
  File "C:\brave-browser\src\brave\script\lib\util.py", line 182, in execute_stdout
    execute(argv, env)
  File "C:\brave-browser\src\brave\script\lib\util.py", line 170, in execute
    raise e
subprocess.CalledProcessError: Command '['npm.cmd', 'run', 'web-ui']' returned non-zero exit status 1
[121/12308] ACTION //chrome/common/extensions/api:permission_features_json_features(//build/toolchain/win:win_clang_x64)
[122/12308] ACTION //brave/components/brave_adblock_ui:brave_adblock_ui(//build/toolchain/win:win_clang_x64)
FAILED: gen/brave/brave_adblock.bundle.js
C:/brave-browser/vendor/depot_tools/win_tools-2_7_6_bin/python/bin/python.exe ../../brave/script/transpile-web-ui.py --target_gen_dir=C:/brave-browser/src/out/Release/gen/brave --production

> brave-core@0.54.0 web-ui C:\brave-browser\src\brave
> webpack --config components/webpack/prod.config.js --progress --profile --colors

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "C:/brave-browser/src/out/Release/gen/brave" is not an absolute path!
   -> The output directory as **absolute path** (required).
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brave-core@0.54.0 web-ui: `webpack --config components/webpack/prod.config.js --progress --profile --colors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the brave-core@0.54.0 web-ui script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Owner\AppData\Roaming\npm-cache\_logs\2018-08-06T11_36_47_297Z-debug.log

Traceback (most recent call last):
  File "../../brave/script/transpile-web-ui.py", line 40, in <module>
    sys.exit(main())
  File "../../brave/script/transpile-web-ui.py", line 12, in main
    transpile_web_uis(args.production, args.target_gen_dir[0])
  File "../../brave/script/transpile-web-ui.py", line 37, in transpile_web_uis
    execute_stdout(args, env)
  File "C:\brave-browser\src\brave\script\lib\util.py", line 182, in execute_stdout
    execute(argv, env)
  File "C:\brave-browser\src\brave\script\lib\util.py", line 170, in execute
    raise e
subprocess.CalledProcessError: Command '['npm.cmd', 'run', 'web-ui']' returned non-zero exit status 1
[123/12308] ACTION //chrome/elevation_service:version_resources_action(//build/toolchain/win:win_clang_x64)
[124/12305] ACTION //chrome/common/media_router/mojo:media_controller__generate_message_ids(//build/toolchain/win:win_clang_x64)
[125/12301] ACTION //chrome/common/importer:interfaces__parser(//build/toolchain/win:win_clang_x64)
[126/12300] ACTION //chrome/services/file_util/public/mojom:mojom__generate_message_ids(//build/toolchain/win:win_clang_x64)
[127/12296] ACTION //chrome/installer/util:generate_strings(//build/toolchain/win:win_clang_x64)
[128/12296] ACTION //brave/components/brave_new_tab_ui:brave_new_tab_ui(//build/toolchain/win:win_clang_x64)
FAILED: gen/brave/brave_new_tab.bundle.js
C:/brave-browser/vendor/depot_tools/win_tools-2_7_6_bin/python/bin/python.exe ../../brave/script/transpile-web-ui.py --target_gen_dir=C:/brave-browser/src/out/Release/gen/brave --production

┌────────────────────────────────────────────────────────────┐
│                  npm update check failed                   │
│            Try running with sudo or get access             │
│            to the local update config store via            │
│ sudo chown -R $USER:$(id -gn $USER) C:\Users\Owner\.config │
└────────────────────────────────────────────────────────────┘

> brave-core@0.54.0 web-ui C:\brave-browser\src\brave
> webpack --config components/webpack/prod.config.js --progress --profile --colors

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "C:/brave-browser/src/out/Release/gen/brave" is not an absolute path!
   -> The output directory as **absolute path** (required).
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brave-core@0.54.0 web-ui: `webpack --config components/webpack/prod.config.js --progress --profile --colors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the brave-core@0.54.0 web-ui script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Owner\AppData\Roaming\npm-cache\_logs\2018-08-06T11_36_47_516Z-debug.log

Traceback (most recent call last):
  File "../../brave/script/transpile-web-ui.py", line 40, in <module>
    sys.exit(main())
  File "../../brave/script/transpile-web-ui.py", line 12, in main
    transpile_web_uis(args.production, args.target_gen_dir[0])
  File "../../brave/script/transpile-web-ui.py", line 37, in transpile_web_uis
    execute_stdout(args, env)
  File "C:\brave-browser\src\brave\script\lib\util.py", line 182, in execute_stdout
    execute(argv, env)
  File "C:\brave-browser\src\brave\script\lib\util.py", line 170, in execute
    raise e
subprocess.CalledProcessError: Command '['npm.cmd', 'run', 'web-ui']' returned non-zero exit status 1
[129/12296] ACTION //brave/components/brave_welcome_ui:brave_welcome_ui(//build/toolchain/win:win_clang_x64)
FAILED: gen/brave/brave_welcome.bundle.js
C:/brave-browser/vendor/depot_tools/win_tools-2_7_6_bin/python/bin/python.exe ../../brave/script/transpile-web-ui.py --target_gen_dir=C:/brave-browser/src/out/Release/gen/brave --production

┌────────────────────────────────────────────────────────────┐
│                  npm update check failed                   │
│            Try running with sudo or get access             │
│            to the local update config store via            │
│ sudo chown -R $USER:$(id -gn $USER) C:\Users\Owner\.config │
└────────────────────────────────────────────────────────────┘

> brave-core@0.54.0 web-ui C:\brave-browser\src\brave
> webpack --config components/webpack/prod.config.js --progress --profile --colors

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "C:/brave-browser/src/out/Release/gen/brave" is not an absolute path!
   -> The output directory as **absolute path** (required).
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brave-core@0.54.0 web-ui: `webpack --config components/webpack/prod.config.js --progress --profile --colors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the brave-core@0.54.0 web-ui script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Owner\AppData\Roaming\npm-cache\_logs\2018-08-06T11_36_47_516Z-debug.log

Traceback (most recent call last):
  File "../../brave/script/transpile-web-ui.py", line 40, in <module>
    sys.exit(main())
  File "../../brave/script/transpile-web-ui.py", line 12, in main
    transpile_web_uis(args.production, args.target_gen_dir[0])
  File "../../brave/script/transpile-web-ui.py", line 37, in transpile_web_uis
    execute_stdout(args, env)
  File "C:\brave-browser\src\brave\script\lib\util.py", line 182, in execute_stdout
    execute(argv, env)
  File "C:\brave-browser\src\brave\script\lib\util.py", line 170, in execute
    raise e
subprocess.CalledProcessError: Command '['npm.cmd', 'run', 'web-ui']' returned non-zero exit status 1
[130/12296] ACTION //chrome/browser/resources:settings_resources_grit(//build/toolchain/win:win_clang_x64)
[131/12293] CXX obj/chrome/common/non_code_constants/chrome_constants.obj

C:\brave-browser\src\out\Release>python ..\..\brave\script\redirect-cc.py ../../third_party/llvm-build/Release+Asserts/bin/clang-cl.exe /nologo /showIncludes  "-imsvc..\..\..\..\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\ATLMFC\include" "-imsvc..\..\..\..\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include" "-imsvc..\..\..\..\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-imsvc..\..\..\..\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-imsvc..\..\..\..\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-imsvc..\..\..\..\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-imsvc..\..\..\..\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" -DBRAVE_CHROMIUM_BUILD -DV8_DEPRECATION_WARNINGS -DUSE_AURA=1 -DNO_TCMALLOC -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DOFFICIAL_BUILD -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED "-DCR_CLANG_REVISION=\"337439-1\"" -D_HAS_NODISCARD -D_HAS_EXCEPTIONS=0 -D__STD_C -D_CRT_RAND_S -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_ATL_NO_OPENGL -D_WINDOWS -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DPSAPI_VERSION=1 -DWIN32 -D_SECURE_ATL -D_USING_V110_SDK71_ -DWINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP -DWIN32_LEAN_AND_MEAN -DNOMINMAX -D_UNICODE -DUNICODE -DNTDDI_VERSION=0x0A000002 -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../../brave/chromium_src -I. -I../.. -Igen /utf-8 /X -fcolor-diagnostics -fmerge-all-constants -Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -no-canonical-prefixes -fcomplete-member-pointers /Gy /FS /bigobj /d2FastFail /Zc:sizedDealloc- -fmsc-version=1911 -m64 /Brepro /W4 -Wimplicit-fallthrough -Wthread-safety /WX /wd4091 /wd4127 /wd4251 /wd4275 /wd4312 /wd4324 /wd4351 /wd4355 /wd4503 /wd4589 /wd4611 /wd4100 /wd4121 /wd4244 /wd4505 /wd4510 /wd4512 /wd4610 /wd4838 /wd4995 /wd4996 /wd4456 /wd4457 /wd4458 /wd4459 /wd4200 /wd4201 /wd4204 /wd4221 /wd4018 /wd4245 /wd4267 /wd4305 /wd4389 /wd4702 /wd4701 /wd4703 /wd4661 /wd4706 /wd4715 /wd4702 -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-address-of-packed-member -Wno-nonportable-include-path -Wno-user-defined-warnings -Wno-unused-lambda-capture -Wno-null-pointer-arithmetic -Wno-enum-compare-switch -Wno-ignored-pragma-optimize /O1 /Ob2 /Oy- /Zc:inline /Gw /Oi /Z7 -fno-standalone-debug /MT -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang enforce-in-thirdparty-webkit -Xclang -plugin-arg-find-bad-constructs -Xclang check-enum-max-value -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare /TP /wd4577 /GR- /c ../../chrome/common/chrome_constants.cc /Foobj/chrome/common/non_code_constants/chrome_constants.obj /Fd"obj/chrome/common/non_code_constants_cc.pdb"
[132/12293] ACTION //chrome/renderer:resources_grit(//build/toolchain/win:win_clang_x64)
[133/12292] ACTION //chrome/browser/resources/md_bookmarks:build(//build/toolchain/win:win_clang_x64)
[134/12292] ACTION //chrome/browser/resources/md_history:build(//build/toolchain/win:win_clang_x64)
[135/12292] ACTION //chrome/app:generated_resources_grit(//build/toolchain/win:win_clang_x64)
[136/12242] ACTION //brave/vendor/brave-extension:brave-extension(//build/toolchain/win:win_clang_x64)
ninja: build stopped: subcommand failed.
null
null
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brave@0.54.0 build: `node ./scripts/commands.js build "Release"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the brave@0.54.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Owner\AppData\Roaming\npm-cache\_logs\2018-08-06T11_36_58_177Z-debug.log

**Comment by bbondy** [comment]
Max says:
Modified `transpile-web-ui.py` line 34 to
```env["TARGET_GEN_DIR"] = os.path.abspath(target_gen_dir)```

fixes the issue. If you agree with the fix @bridiver pls go ahead and PR with that fix again and I'll merge.
