### ISSUE TITLE
gitPatcher.js:206 is giving a error when `npm run init`

### ISSUE THREAD

**Issue by AdamKearn** [brave/brave-browser#7703]
## Description 

Hi,

when trying to run `npm run init` I get the following error.
This is a fresh clone of the source (TOT).
Any help is appreciated.

-Adam.

```
$ npm install
(....other things....)
npm WARN optional Skipping failed optional dependency /jest-haste-map/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.11
root@vmi334922:~/brave-browser# npm run init

> brave@1.5.27 init /root/brave-browser
> node ./scripts/sync.js --init

Recursing through GRD to find GRDP files...
Done recursing through GRD to find GRDP files.
/root/brave-browser/lib/gitPatcher.js:206
    } catch {
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/brave-browser/scripts/sync.js:13:20)

npm ERR! Linux 4.15.0-74-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "init"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! brave@1.5.27 init: `node ./scripts/sync.js --init`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the brave@1.5.27 init script 'node ./scripts/sync.js --init'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the brave package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/sync.js --init
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs brave
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls brave
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/brave-browser/npm-debug.log
```

**Comment by AdamKearn** [comment]
Closing the issue as I found #6022 solved my problem.
Sorry guys I was being stupid and didn't think to upgrade my nodejs version...
Anyway, you live and learn.
