### ISSUE TITLE
Fix lint issue in CI pipeline

### ISSUE THREAD

**Issue by mihaiplesa** [brave/brave-browser#8127]
```
20:52:05  Recursing through GRD to find GRDP files...
20:52:05  Done recursing through GRD to find GRDP files.
20:52:05  /Users/jenkins/jenkins/workspace/wser-build-pr_uplift_4539_to_1_3/src/brave: vpython /Users/jenkins/jenkins/workspace/wser-build-pr_uplift_4539_to_1_3/scripts/lint.py --project_root=/Users/jenkins/jenkins/workspace/wser-build-pr_uplift_4539_to_1_3/src --base_branch=origin/1.3.x
20:52:05  Traceback (most recent call last):
20:52:05    File "/Users/jenkins/jenkins/workspace/wser-build-pr_uplift_4539_to_1_3/scripts/lint.py", line 84, in <module>
20:52:05      sys.exit(main(sys.argv[1:]))
20:52:05    File "/Users/jenkins/jenkins/workspace/wser-build-pr_uplift_4539_to_1_3/scripts/lint.py", line 50, in main
20:52:05      change = cl.GetChange(git_common.get_or_create_merge_base(cl.GetBranch(), options.base_branch), None)
20:52:05  TypeError: GetChange() takes exactly 2 arguments (3 given)
```

**Comment by kjozwiak** [comment]
Moving this into the `1.4.x` milestone for now. However, if we have another `1.3.x` release due to a minor CR bump, we'll need to move this into that milestone.

CCing @rebron @bsclifton as a reminder.
