### ISSUE TITLE
Intermittent test failure with ExtensionFunctionalTest.PDFJSInstalls

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#828]
```
Still waiting for the following processes to finish:
	/Users/brianbondy/projects/brave/brave-browser-c70/src/out/Debug/brave_browser_tests --disable-gpu-process-for-dx12-vulkan-info-collection --enable-logging --gtest_also_run_disabled_tests --gtest_filter=ExtensionFunctionalTest.PDFJSInstalls --single_process --test-launcher-output=/var/folders/mb/lwdrr8gj7mxdnftmyx4n98dc0000gn/T/.org.brave.Brave.development.1VFpBr/resultssB1fB3/test_results.xml --user-data-dir=/var/folders/mb/lwdrr8gj7mxdnftmyx4n98dc0000gn/T/.org.brave.Brave.development.1VFpBr/dFZeZMn --v=0
[0824/120120.551688:ERROR:kill_posix.cc(83)] Unable to terminate process group 7337: Operation not permitted (1)
[ RUN      ] ExtensionFunctionalTest.PDFJSInstalls
[7337:5123:0824/120036.602750:WARNING:notification_platform_bridge_mac.mm(510)] AlertNotificationService: XPC connection invalidated.
[7337:35843:0824/120036.939392:WARNING:extension_user_script_loader.cc(104)] Failed to get file path to js/content.bundle.js from /Users/brianbondy/projects/brave/brave-browser-c70/src/out/Debug/Brave-Browser-Development.app/Contents/Versions/70.0.55.1/Brave-Browser-Development Framework.framework/Resources/brave_extension
[7337:775:0824/120039.335985:INFO:CONSOLE(1)] "no tab id so cannot request shield data from window focus change!", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/js/background.bundle.js (1)
[7337:775:0824/120039.342880:INFO:CONSOLE(1)] "no tab id so cannot request shield data from window focus change!", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/js/background.bundle.js (1)
[7337:775:0824/120039.367918:INFO:CONSOLE(0)] "Unchecked runtime.lastError: The URL "null" is invalid.", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/background.html (0)
[7337:775:0824/120039.369591:INFO:CONSOLE(0)] "Unchecked runtime.lastError: The URL "null" is invalid.", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/background.html (0)
[7337:775:0824/120039.370797:INFO:CONSOLE(0)] "Unchecked runtime.lastError: The URL "null" is invalid.", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/background.html (0)
[7337:775:0824/120039.373100:INFO:CONSOLE(0)] "Unchecked runtime.lastError: The URL "null" is invalid.", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/background.html (0)
[7337:775:0824/120039.374977:INFO:CONSOLE(0)] "Unchecked runtime.lastError: The URL "null" is invalid.", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/background.html (0)
[7337:775:0824/120039.376377:INFO:CONSOLE(0)] "Unchecked runtime.lastError: The URL "null" is invalid.", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/background.html (0)
[7337:775:0824/120039.378259:INFO:CONSOLE(0)] "Unchecked runtime.lastError: The URL "null" is invalid.", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/background.html (0)
[7337:775:0824/120039.379657:INFO:CONSOLE(0)] "Unchecked runtime.lastError: The URL "null" is invalid.", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/background.html (0)
[7337:775:0824/120039.389589:INFO:CONSOLE(0)] "Unchecked runtime.lastError: The URL "null" is invalid.", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/background.html (0)
[7337:775:0824/120039.391279:INFO:CONSOLE(0)] "Unchecked runtime.lastError: The URL "null" is invalid.", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/background.html (0)
[7337:775:0824/120039.392831:INFO:CONSOLE(0)] "Unchecked runtime.lastError: The URL "null" is invalid.", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/background.html (0)
[7337:775:0824/120039.396195:INFO:CONSOLE(0)] "Unchecked runtime.lastError: The URL "null" is invalid.", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/background.html (0)
[7337:775:0824/120039.400811:INFO:CONSOLE(0)] "Unchecked runtime.lastError: The URL "null" is invalid.", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/background.html (0)
[7337:775:0824/120039.405265:INFO:CONSOLE(0)] "Unchecked runtime.lastError: The URL "null" is invalid.", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/background.html (0)
[7337:775:0824/120039.411623:INFO:CONSOLE(0)] "Unchecked runtime.lastError: The URL "null" is invalid.", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/background.html (0)
[7337:775:0824/120039.417040:INFO:CONSOLE(0)] "Unchecked runtime.lastError: The URL "null" is invalid.", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/background.html (0)
[7337:775:0824/120039.419900:INFO:CONSOLE(0)] "Unchecked runtime.lastError: The URL "null" is invalid.", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/background.html (0)
[7337:775:0824/120039.439840:INFO:CONSOLE(0)] "Unchecked runtime.lastError: The URL "null" is invalid.", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/background.html (0)
[7337:775:0824/120045.712247:WARNING:gaia_auth_fetcher.cc(931)] Could not reach Google Accounts servers: errno -11
[7337:775:0824/120045.881281:INFO:CONSOLE(0)] "Error handling response: TypeError: Cannot read property '127.0.0.1' of undefined
    at chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/js/background.bundle.js:1:135440", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/background.html (0)
[7337:775:0824/120047.527438:INFO:CONSOLE(94)] "Set up extension URL router.", source: chrome-extension://kpbdcmcgkedhpbcpfndimofjnefgjidd/extension-router.js (94)
[7337:14595:0824/120047.548022:WARNING:embedded_test_server.cc(238)] Request not handled. Returning 404: /favicon.ico
[7337:775:0824/120047.556257:WARNING:gaia_auth_fetcher.cc(931)] Could not reach Google Accounts servers: errno -11
[7337:775:0824/120047.666915:INFO:CONSOLE(41)] "Disabled telemetry because this is not an official build.", source: chrome-extension://kpbdcmcgkedhpbcpfndimofjnefgjidd/telemetry.js (41)
[7337:775:0824/120048.113694:INFO:CONSOLE(0)] "Error handling response: TypeError: Cannot read property '127.0.0.1' of undefined
    at chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/js/background.bundle.js:1:135440", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/background.html (0)
[7337:775:0824/120050.175571:WARNING:gaia_auth_fetcher.cc(931)] Could not reach Google Accounts servers: errno -11
[7337:775:0824/120051.086075:INFO:CONSOLE(1662)] "PDF a8200ae215b0b8d9d7168c8a1b85cb61 [1.4 Mac OS X 10.11.5 Quartz PDFContext / Preview] (PDF.js: 2.0.466)", source: chrome-extension://kpbdcmcgkedhpbcpfndimofjnefgjidd/content/web/viewer.js (1662)
[7337:775:0824/120058.117691:WARNING:gaia_auth_fetcher.cc(931)] Could not reach Google Accounts servers: errno -11
BrowserTestBase received signal: Terminated: 15. Backtrace:
0   libbase.dylib                       0x00000001241de06e base::debug::StackTrace::StackTrace(unsigned long) + 174
1   libbase.dylib                       0x00000001241de12d base::debug::StackTrace::StackTrace(unsigned long) + 29
2   libbase.dylib                       0x0000000123db679c base::debug::StackTrace::StackTrace() + 28
3   brave_browser_tests                 0x000000011336a8ce content::(anonymous namespace)::DumpStackTraceSignalHandler(int) + 622
4   libsystem_platform.dylib            0x00007fff6e618f5a _sigtramp + 26
5   libbase.dylib                       0x000000012425ce90 vtable for base::Histogram + 16
6   CoreFoundation                      0x00007fff464ce785 __CFRunLoopServiceMachPort + 341
7   CoreFoundation                      0x00007fff464cdad7 __CFRunLoopRun + 1783
8   CoreFoundation                      0x00007fff464cd153 CFRunLoopRunSpecific + 483
9   HIToolbox                           0x00007fff457b7d96 RunCurrentEventLoopInMode + 286
10  HIToolbox                           0x00007fff457b7b06 ReceiveNextEventCommon + 613
11  HIToolbox                           0x00007fff457b7884 _BlockUntilNextEventMatchingListInModeWithFilter + 64
12  AppKit                              0x00007fff43a68a73 _DPSNextEvent + 2085
13  AppKit                              0x00007fff441fee34 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
14  brave_browser_tests                 0x0000000110c2ca2a __71-[BrowserCrApplication nextEventMatchingMask:untilDate:inMode:dequeue:]_block_invoke + 106
15  libbase.dylib                       0x0000000123e3826a base::mac::CallWithEHFrame(void () block_pointer) + 10
16  brave_browser_tests                 0x0000000110c2c8c8 -[BrowserCrApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 248
17  AppKit                              0x00007fff43a5d885 -[NSApplication run] + 764
18  libbase.dylib                       0x0000000123e989fc base::MessagePumpNSApplication::DoRun(base::MessagePump::Delegate*) + 348
19  libbase.dylib                       0x0000000123e95885 base::MessagePumpCFRunLoopBase::Run(base::MessagePump::Delegate*) + 101
20  libbase.dylib                       0x0000000123e8476c base::MessageLoop::Run(bool) + 556
21  libbase.dylib                       0x0000000123f735ce base::RunLoop::Run() + 606
22  brave_browser_tests                 0x0000000113382f36 content::TitleWatcher::WaitAndGetTitle() + 38
23  brave_browser_tests                 0x0000000107fcd713 extensions::ExtensionFunctionalTest_PDFJSInstalls_Test::RunTestOnMainThread() + 1299
24  brave_browser_tests                 0x0000000113368b84 content::BrowserTestBase::ProxyRunTestOnMainThreadLoop() + 2116
25  brave_browser_tests                 0x000000011336b9cd void base::internal::FunctorTraits<void (content::BrowserTestBase::*)(), void>::Invoke<void (content::BrowserTestBase::*)(), content::BrowserTestBase*>(void (content::BrowserTestBase::*)(), content::BrowserTestBase*&&) + 125
26  brave_browser_tests                 0x000000011336b914 void base::internal::InvokeHelper<false, void>::MakeItSo<void (content::BrowserTestBase::* const&)(), content::BrowserTestBase*>(void (content::BrowserTestBase::* const&&&)(), content::BrowserTestBase*&&) + 68
27  brave_browser_tests                 0x000000011336b8a3 void base::internal::Invoker<base::internal::BindState<void (content::BrowserTestBase::*)(), base::internal::UnretainedWrapper<content::BrowserTestBase> >, void ()>::RunImpl<void (content::BrowserTestBase::* const&)(), std::__1::tuple<base::internal::UnretainedWrapper<content::BrowserTestBase> > const&, 0ul>(void (content::BrowserTestBase::* const&&&)(), std::__1::tuple<base::internal::UnretainedWrapper<content::BrowserTestBase> > const&&&, std::__1::integer_sequence<unsigned long, 0ul>) + 99
28  brave_browser_tests                 0x000000011336b7cc base::internal::Invoker<base::internal::BindState<void (content::BrowserTestBase::*)(), base::internal::UnretainedWrapper<content::BrowserTestBase> >, void ()>::Run(base::internal::BindStateBase*) + 44
29  brave_browser_tests                 0x00000001080b585d base::RepeatingCallback<void ()>::Run() const & + 61
30  brave_browser_tests                 0x0000000110c3f2e3 ChromeBrowserMainParts::PreMainMessageLoopRunImpl() + 7187
31  brave_browser_tests                 0x0000000110c3d61a ChromeBrowserMainParts::PreMainMessageLoopRun() + 250
32  libcontent.dylib                    0x000000012fcc1d41 content::BrowserMainLoop::PreMainMessageLoopRun() + 337
33  libcontent.dylib                    0x000000012fcc864d int base::internal::FunctorTraits<int (content::BrowserMainLoop::*)(), void>::Invoke<int (content::BrowserMainLoop::*)(), content::BrowserMainLoop*>(int (content::BrowserMainLoop::*)(), content::BrowserMainLoop*&&) + 125
34  libcontent.dylib                    0x000000012fcc8594 int base::internal::InvokeHelper<false, int>::MakeItSo<int (content::BrowserMainLoop::* const&)(), content::BrowserMainLoop*>(int (content::BrowserMainLoop::* const&&&)(), content::BrowserMainLoop*&&) + 68
35  libcontent.dylib                    0x000000012fcc8523 int base::internal::Invoker<base::internal::BindState<int (content::BrowserMainLoop::*)(), base::internal::UnretainedWrapper<content::BrowserMainLoop> >, int ()>::RunImpl<int (content::BrowserMainLoop::* const&)(), std::__1::tuple<base::internal::UnretainedWrapper<content::BrowserMainLoop> > const&, 0ul>(int (content::BrowserMainLoop::* const&&&)(), std::__1::tuple<base::internal::UnretainedWrapper<content::BrowserMainLoop> > const&&&, std::__1::integer_sequence<unsigned long, 0ul>) + 99
36  libcontent.dylib                    0x000000012fcc841c base::internal::Invoker<base::internal::BindState<int (content::BrowserMainLoop::*)(), base::internal::UnretainedWrapper<content::BrowserMainLoop> >, int ()>::Run(base::internal::BindStateBase*) + 44
37  libcontent.dylib                    0x00000001308d17ad base::RepeatingCallback<int ()>::Run() const & + 61
38  libcontent.dylib                    0x000000013131e7f0 content::StartupTaskRunner::RunAllTasksNow() + 528
39  libcontent.dylib                    0x000000012fcbce51 content::BrowserMainLoop::CreateStartupTasks() + 2769
40  libcontent.dylib                    0x000000012fccc3be content::BrowserMainRunnerImpl::Initialize(content::MainFunctionParams const&) + 2430
41  libcontent.dylib                    0x000000012fcb4356 content::BrowserMain(content::MainFunctionParams const&) + 550
42  libcontent.dylib                    0x0000000132d9bb55 content::RunBrowserProcessMain(content::MainFunctionParams const&, content::ContentMainDelegate*) + 309
43  libcontent.dylib                    0x0000000132d9efa2 content::ContentMainRunnerImpl::Run(bool) + 4290
44  libcontent.dylib                    0x0000000132d95c0c content::ContentServiceManagerMainDelegate::RunEmbedderProcess() + 76
45  libembedder.dylib                   0x0000000141c0a789 service_manager::Main(service_manager::MainParams const&) + 3753
46  libcontent.dylib                    0x0000000132d9b9d9 content::ContentMain(content::ContentMainParams const&) + 89
47  brave_browser_tests                 0x0000000113367fc3 content::BrowserTestBase::SetUp() + 8387
48  brave_browser_tests                 0x000000011351b830 InProcessBrowserTest::SetUp() + 3360
49  brave_browser_tests                 0x0000000107fef9be extensions::ExtensionBrowserTest::SetUp() + 238
50  brave_browser_tests                 0x0000000107fce362 extensions::ExtensionFunctionalTest::SetUp() + 34
51  brave_browser_tests                 0x000000010acfdb7e void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) + 126
52  brave_browser_tests                 0x000000010acd3882 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) + 114
53  brave_browser_tests                 0x000000010acd3764 testing::Test::Run() + 116
54  brave_browser_tests                 0x000000010acd48a0 testing::TestInfo::Run() + 224
55  brave_browser_tests                 0x000000010acd5c6f testing::TestCase::Run() + 239
56  brave_browser_tests                 0x000000010acea2d6 testing::internal::UnitTestImpl::RunAllTests() + 886
57  brave_browser_tests                 0x000000010ad00c2e bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) + 126
58  brave_browser_tests                 0x000000010ace9ee2 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) + 114
59  brave_browser_tests                 0x000000010ace9dbb testing::UnitTest::Run() + 395
60  brave_browser_tests                 0x0000000112bbb841 RUN_ALL_TESTS() + 17
61  brave_browser_tests                 0x0000000112bbaacb base::TestSuite::Run() + 363
[74/74] ExtensionFunctionalTest.PDFJSInstalls (TIMED OUT)
```

**Comment by bsclifton** [comment]
Closing as PDF.js has been removed
