### ISSUE TITLE
Update GetChange to use 3 arguments

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#8599]
```
/home/ubuntu/jenkins/workspace/uild-pr_android-channels-version/src/brave: vpython /home/ubuntu/jenkins/workspace/uild-pr_android-channels-version/scripts/lint.py --project_root=/home/ubuntu/jenkins/workspace/uild-pr_android-channels-version/src --base_branch=origin/master
13:26:49  Traceback (most recent call last):
13:26:49    File "/home/ubuntu/jenkins/workspace/uild-pr_android-channels-version/scripts/lint.py", line 84, in <module>
13:26:49      sys.exit(main(sys.argv[1:]))
13:26:49    File "/home/ubuntu/jenkins/workspace/uild-pr_android-channels-version/scripts/lint.py", line 50, in main
13:26:49      change = cl.GetChange(git_common.get_or_create_merge_base(cl.GetBranch(), options.base_branch))
13:26:49  TypeError: GetChange() takes exactly 3 arguments (2 given)
```

Change: https://chromium.googlesource.com/chromium/tools/depot_tools/+/a12175c2a7a9f79c3296068a022ac4f3051f8600%5E%21/#F0

**Comment by btlechowski** [comment]
@jumde Is this `QA/Yes` or `QA/No`?

**Comment by mihaiplesa** [comment]
@btlechowski QA/No
