### ISSUE TITLE
Issue running init

### ISSUE THREAD

**Issue by jonathanKingston** [brave/brave-browser#8708]
## Description 

Whilst running `npm run init` for the first time on a brand new Ubuntu machine, I get an bootstrap hook error

## Steps to Reproduce

   1. Clone repo
   2. npm install
   3. npm run init

## Actual result:

```
Running gclient hooks...
/home/jonathan/projects/brave-browser: gclient runhooks
Running hooks:  96% (83/86) bootstrap                                   
________ running 'vpython src/brave/script/bootstrap.py' in '/home/jonathan/projects/brave-browser'
WARN engine webtorrent@0.107.17: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
WARN engine bittorrent-tracker@9.14.4: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
npm WARN deprecated @types/storybook__addon-knobs@5.2.1: Deprecated
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! Linux 5.3.0-40-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jonathan/projects/brave-browser/src/brave/npm-debug.log

Traceback (most recent call last):
  File "src/brave/script/bootstrap.py", line 79, in <module>
    sys.exit(main())
  File "src/brave/script/bootstrap.py", line 33, in main
    update_node_modules('.')
  File "src/brave/script/bootstrap.py", line 69, in update_node_modules
    execute_stdout(args, env)
  File "/home/jonathan/projects/brave-browser/src/brave/script/lib/util.py", line 187, in execute_stdout
    execute(argv, env)
  File "/home/jonathan/projects/brave-browser/src/brave/script/lib/util.py", line 175, in execute
    raise e
subprocess.CalledProcessError: Command '['npm', 'install']' returned non-zero exit status 1
Error: Command 'vpython src/brave/script/bootstrap.py' returned non-zero exit status 1 in /home/jonathan/projects/brave-browser
Hook 'vpython src/brave/script/bootstrap.py' took 22.33 secs
null
null

npm ERR! Linux 5.3.0-40-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "init"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! brave@1.8.12 init: `node ./scripts/sync.js --init`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the brave@1.8.12 init script 'node ./scripts/sync.js --init'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the brave package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/sync.js --init
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs brave
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls brave
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jonathan/projects/brave-browser/npm-debug.log
```

## Expected result:

Success

**Comment by jonathanKingston** [comment]
Ah the install advice here suggests using apt, https://github.com/brave/brave-browser/wiki/Linux-Development-Environment it's super outdated and no longer works.

**Comment by bsclifton** [comment]
@jonathanKingston where did you install npm from? I can update the wiki

**Comment by jonathanKingston** [comment]
@bsclifton I downloaded the LTS release from https://nodejs.org/en/ and added it to my PATH environment variable and that's worked for me.
