### ISSUE TITLE
Change Brave Ads grants server end-point

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#8805]
Change Brave Ads grants server end-point in `AdsRewards::GetAdGrants()` from `GET /v2/wallet/{payment_id}/grants/ads` to `GET /v1/promotions/ads/grants/summary?paymentId={payment_id}`

**Comment by danishjalil2991** [comment]
Hello, I am interested in working on this issue. Not sure how I can assign it to myself

**Comment by danishjalil2991** [comment]
It is taking me longer than I assumed to set up the Brave Repo and get everything running. Currently I am stuck with  'npm run init' command giving me an error. I am getting the following error stack trace, seems like it is failing to apply some patches. I am running it on Mac OS and I have followed all the build guidelines. My npm version is 6.13.4 and my node version is 12.6.1. 

Done running gclient sync.
Applying patches…

Getting patch data…events.js:288
throw er; // Unhandled ‘error’ event
^

Error: spawn git EAGAIN
at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
at onErrorNT (internal/child_process.js:469:16)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted ‘error’ event on ChildProcess instance at:
at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
at onErrorNT (internal/child_process.js:469:16)
at processTicksAndRejections (internal/process/task_queues.js:84:21) {
errno: ‘EAGAIN’,
code: ‘EAGAIN’,
syscall: ‘spawn git’,
path: ‘git’,
spawnargs: [
‘apply’,
‘/Users/danishjalil/brave-browser/src/brave/patches/net-url_request-url_request_http_job.cc.patch’,
‘–numstat’,
‘-z’,
‘–ignore-space-change’,
‘–ignore-whitespace’
]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brave@1.8.33 init: node ./scripts/sync.js --init
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the brave@1.8.33 init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by tmancey** [comment]
@danishjalil2991 Apologies for the late reply, if you let me know your timezone and maybe we could have a screen share so I can help you get setup?

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.9.49 Chromium: 81.0.4044.129 (Official Build) dev (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/5232

```
[2340:12688:0430/174544.873:INFO:ads_rewards.cc(162)] GetAdGrants
[2340:12688:0430/174544.873:INFO:ads_rewards.cc(164)] GET /v1/promotions/ads/grants/summary?paymentId={payment_id}
[2340:12688:0430/174544.873:INFO:ads_rewards.cc(167)] URL Request:
[2340:12688:0430/174544.873:INFO:ads_rewards.cc(170)]   URL: https://grant.rewards.brave.com/v1/promotions/ads/grants/summary?paymentId=ac198db6-d5f4-4fcf-a729-f285c36307e7
[2340:12688:0430/174545.151:INFO:ads_rewards.cc(184)] OnGetAdGrants
[2340:12688:0430/174545.151:INFO:ads_rewards.cc(186)] URL Request Response:
[2340:12688:0430/174545.151:INFO:ads_rewards.cc(187)]   URL: https://grant.rewards.brave.com/v1/promotions/ads/grants/summary?paymentId=ac198db6-d5f4-4fcf-a729-f285c36307e7
[2340:12688:0430/174545.151:INFO:ads_rewards.cc(188)]   Response Status Code: 204
[2340:12688:0430/174545.151:INFO:ads_rewards.cc(189)]   Response: 
[2340:12688:0430/174545.151:INFO:ads_rewards.cc(190)]   Headers:
[2340:12688:0430/174545.151:INFO:ads_rewards.cc(192)]     accept-ranges: bytes
[2340:12688:0430/174545.151:INFO:ads_rewards.cc(192)]     content-type: application/json
[2340:12688:0430/174545.151:INFO:ads_rewards.cc(192)]     date: Thu, 30 Apr 2020 12:15:46 GMT
[2340:12688:0430/174545.151:INFO:ads_rewards.cc(192)]     request-id: bqlc2sgkiei1rkdcg910
[2340:12688:0430/174545.151:INFO:ads_rewards.cc(192)]     status: 204
[2340:12688:0430/174545.151:INFO:ads_rewards.cc(192)]     via: 1.1 varnish
[2340:12688:0430/174545.151:INFO:ads_rewards.cc(192)]     x-cache: MISS
[2340:12688:0430/174545.151:INFO:ads_rewards.cc(192)]     x-cache-hits: 0
[2340:12688:0430/174545.151:INFO:ads_rewards.cc(192)]     x-ratelimit-limit: 1
[2340:12688:0430/174545.151:INFO:ads_rewards.cc(192)]     x-ratelimit-remaining: 0
[2340:12688:0430/174545.151:INFO:ads_rewards.cc(192)]     x-ratelimit-reset: 1
[2340:12688:0430/174545.151:INFO:ads_rewards.cc(192)]     x-request-id: E2EuaKbuHrKZuciJ
[2340:12688:0430/174545.151:INFO:ads_rewards.cc(192)]     x-served-by: cache-sea4434-SEA
[2340:12688:0430/174545.151:INFO:ads_rewards.cc(231)] Successfully retrieved ads rewards
```
![image](https://user-images.githubusercontent.com/38657976/80710379-46af8d80-8b0c-11ea-8a1f-f21ce7965ad2.png)
