### ISSUE TITLE
run nom run init on ubuntu 16.04Error: Command 'git checkout --quiet 29324b698ccd8920bc81c71d42dadc6310f0ad0f' 

### ISSUE THREAD

**Issue by luckysunfd** [brave/brave-browser#8967]
> brave@1.8.58 init /root/brave-browser
> node ./scripts/sync.js --init

Recursing through GRD to find GRDP files...
Done recursing through GRD to find GRDP files.
Brave Browser Sync starting
Updating submodules...
/root/brave-browser: git submodule sync
Synchronizing submodule url for 'vendor/depot_tools'
Synchronizing submodule url for 'vendor/gn-project-generators'
Synchronizing submodule url for 'vendor/jinja'
/root/brave-browser: git submodule update --init --recursive
/root/brave-browser: git -C /root/brave-browser/vendor/depot_tools clean -fxd
Removing metrics.cfg
/root/brave-browser: git -C /root/brave-browser/vendor/depot_tools reset --hard HEAD
HEAD is now at c5f95c0 Roll recipe dependencies (trivial).
Done updating submodules...
Syncing Gclient (with reset)
/root/brave-browser: gclient sync --no-history --force --nohooks --with_branch_heads --with_tags --upstream
Running depot tools as root is sad.
WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.
Syncing projects:  81% (30/37) src/third_party/catapult

src/chrome/browser/resources/media_router/extension/src (ERROR)
----------------------------------------
[0:00:03] Started.
----------------------------------------
Error: Command 'git checkout --quiet 29324b698ccd8920bc81c71d42dadc6310f0ad0f' returned non-zero exit status 128 in /root/brave-browser/src/chrome/browser/resources/media_router/extension/src
fatal: reference is not a tree: 29324b698ccd8920bc81c71d42dadc6310f0ad0f

null
null
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brave@1.8.58 init: `node ./scripts/sync.js --init`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the brave@1.8.58 init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-01T16_47_30_383Z-debug.log

**Comment by luckysunfd** [comment]
npm debug log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'init' ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose run-script [ 'preinit', 'init', 'postinit' ]
5 info lifecycle brave@1.8.58~preinit: brave@1.8.58
6 info lifecycle brave@1.8.58~init: brave@1.8.58
7 verbose lifecycle brave@1.8.58~init: unsafe-perm in lifecycle true
8 verbose lifecycle brave@1.8.58~init: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/brave-browser/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle brave@1.8.58~init: CWD: /root/brave-browser
10 silly lifecycle brave@1.8.58~init: Args: [ '-c', 'node ./scripts/sync.js --init' ]
11 silly lifecycle brave@1.8.58~init: Returned: code: 1  signal: null
12 info lifecycle brave@1.8.58~init: Failed to exec init script
13 verbose stack Error: brave@1.8.58 init: `node ./scripts/sync.js --init`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid brave@1.8.58
15 verbose cwd /root/brave-browser
16 verbose Linux 4.4.0-174-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "init"
18 verbose node v12.16.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error brave@1.8.58 init: `node ./scripts/sync.js --init`
22 error Exit status 1
23 error Failed at the brave@1.8.58 init script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
~
