### ISSUE TITLE
macOS signing is broken in master

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#9650]
## Description 
Found when trying to build Nightly

I believe this was caused by https://github.com/brave/brave-core/pull/5142
cc: @AndriusA @bridiver 

```
23:09:58  [2020-05-06 01:09:57,419/INFO/commands.py:84] Running command: ['codesign', '--force', '--sign', ****, '--timestamp', '--requirements', '=designated => identifier "libspeedreader"', '/var/folders/82/bpvnl611647ghpxnbgtw99n80000gp/T/chromesign_znt9ED/Brave Browser Nightly.app/Contents/Frameworks/Brave Browser Nightly Framework.framework/Libraries/libspeedreader.dylib']
23:09:58  /var/folders/82/bpvnl611647ghpxnbgtw99n80000gp/T/chromesign_znt9ED/Brave Browser Nightly.app/Contents/Frameworks/Brave Browser Nightly Framework.framework/Libraries/libspeedreader.dylib: No such file or directory
23:09:58  Traceback (most recent call last):
23:09:58    File "/Users/jenkins/jenkins/workspace/brave-browser-build-macos-nightly/src/out/Release/Brave_Browser_Nightly_Packaging/sign_chrome.py", line 179, in <module>
23:09:58      main()
23:09:58    File "/Users/jenkins/jenkins/workspace/brave-browser-build-macos-nightly/src/out/Release/Brave_Browser_Nightly_Packaging/sign_chrome.py", line 175, in main
23:09:58      skip_brands=args.skip_brands)
23:09:58    File "/Users/jenkins/jenkins/workspace/brave-browser-build-macos-nightly/src/out/Release/Brave_Browser_Nightly_Packaging/signing/pipeline.py", line 481, in sign_all
23:09:58      signed_frameworks)
23:09:58    File "/Users/jenkins/jenkins/workspace/brave-browser-build-macos-nightly/src/out/Release/Brave_Browser_Nightly_Packaging/signing/pipeline.py", line 83, in _customize_and_sign_chrome
23:09:58      signing.sign_chrome(paths, dist_config, sign_framework=True)
23:09:58    File "/Users/jenkins/jenkins/workspace/brave-browser-build-macos-nightly/src/out/Release/Brave_Browser_Nightly_Packaging/signing/signing.py", line 265, in sign_chrome
23:09:58      sign_part(paths, config, part)
23:09:58    File "/Users/jenkins/jenkins/workspace/brave-browser-build-macos-nightly/src/out/Release/Brave_Browser_Nightly_Packaging/signing/signing.py", line 202, in sign_part
23:09:58      commands.run_command(command)
23:09:58    File "/Users/jenkins/jenkins/workspace/brave-browser-build-macos-nightly/src/out/Release/Brave_Browser_Nightly_Packaging/signing/commands.py", line 85, in run_command
23:09:58      subprocess.check_call(args, **kwargs)
23:09:58    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
23:09:58      raise CalledProcessError(retcode, cmd)
23:09:58  subprocess.CalledProcessError: Command '['codesign', '--force', '--sign', ****, '--timestamp', '--requirements', '=designated => identifier "libspeedreader"', '/var/folders/82/bpvnl611647ghpxnbgtw99n80000gp/T/chromesign_znt9ED/Brave Browser Nightly.app/Contents/Frameworks/Brave Browser Nightly Framework.framework/Libraries/libspeedreader.dylib']' returned non-zero exit status 1
23:09:58  [ERROR] ./../../brave/build/mac/sign_app.sh failed
23:09:58  ../../brave/build/mac/sign_app.sh failed with exit code 1
```

**Comment by bsclifton** [comment]
This was not a proper solution; now there is a notarization error:
https://osxapps-ssl.itunes.apple.com/itunes-assets/Enigma113/v4/de/97/55/de97553f-c82b-5755-6089-811e12036e87/developer_log.json?accessKey=1588957368_4928264668560815838_UtVjshKVg1pQZJ5JVC0zFehgkP0oPchDdffdAccr9%2BMoMi%2B%2B7lVZ6k%2FEO5tqJONG2%2Fq56s%2B%2FeDgpWDR5cUC2NzeCxaKjY4yeoIsZt5bkQPA3TuFc7n2vNwgx%2BlKLPQ8ZjhIOP8SS%2FHvmHy0b5KKsHbOnr%2FsBGaDq0exJ2f5nun4%3D

It doesn't seem that dependency was removed; it was renamed from `libspeedreader.dylib` to `libspeedreader_ffi.dylib`

**Comment by LaurenWags** [comment]
@bsclifton does this one need manual QA? If so, could you please mark `QA/Yes` and add a test plan? If not, please mark `QA/No`. Thanks!

**Comment by bsclifton** [comment]
@LaurenWags whoops- no it doesn't; tags added 😄
