### ISSUE TITLE
Brave fails to build

### ISSUE THREAD

**Issue by VladimirMikulic** [brave/brave-browser#9709]
Error:

```
> brave@1.10.44 build /home/vlado/Desktop/brave-browser
> node ./scripts/commands.js build

Recursing through GRD to find GRDP files...
Done recursing through GRD to find GRDP files.
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/vlado/Desktop/brave-browser/src/chrome/VERSION'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at checkVersionsMatch (/home/vlado/Desktop/brave-browser/lib/build.js:78:26)
    at Command.build (/home/vlado/Desktop/brave-browser/lib/build.js:91:3)
    at Command.listener (/home/vlado/Desktop/brave-browser/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:310:20)
    at Command.parseArgs (/home/vlado/Desktop/brave-browser/node_modules/commander/index.js:651:12)
    at Command.parse (/home/vlado/Desktop/brave-browser/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/home/vlado/Desktop/brave-browser/scripts/commands.js:186:4)
    at Module._compile (internal/modules/cjs/loader.js:1133:30) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/vlado/Desktop/brave-browser/src/chrome/VERSION'
}
```

I've followed the wiki instructions but it seems that it is outdated.

**Comment by bsclifton** [comment]
@VladimirMikulic looks like you were able to resolve this?

The Chromium source will get downloaded when you run `npm run init` 😄

**Comment by VladimirMikulic** [comment]
@bsclifton I wasn't but I _kinda_ know what is the problem.
My hardware is not that great so I pressed CTRL + C to cancel the git process "resolving deltas" after I had downloaded Chromium stuff with `npm run init`.

Later, I realized that might be the problem since other scripts probably run after that so yeah... my mistake. Anyway, thank you for checking this out Brian!
