### ISSUE TITLE
iOS crash when calling base::TimeFormatFriendlyDateAndTime

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#9740]
## Steps to Reproduce

   1. Launch application

## Actual result:

Application crashes on iOS
```
#0  0x000000010869347f in icu_65::DateFormat::format(double, icu_65::UnicodeString&, icu_65::FieldPosition&) const ()
#1  0x000000010869363e in icu_65::DateFormat::format(double, icu_65::UnicodeString&) const ()
#2  0x0000000108675b60 in base::TimeFormatFriendlyDateAndTime(base::Time const&) ()
#3  0x00000001085fe1b9 in confirmations::LongFormatFriendlyDateAndTime(base::Time const&, bool) ()
#4  0x00000001085fe31b in confirmations::FriendlyDateAndTime(base::Time const&, bool) ()
```
## Expected result:
Application should not crash on iOS

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by tmancey** [comment]
Closing issue as the issue was resolved as part of brave-ios
