### ISSUE TITLE
[Android] Crash on certain devices on custom tabs

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#9857]
## Description 
There is a crash on beta channel on 1.9.x related to Custom Tabs. Not sure how to describe that but certain devices crash while others don't. I had a device Samsung Galaxy S10+ that experienced that crash but only on release version. I verified everything on it while fixing in release mode.
`2020-05-19 20:33:42.558 29508-29508/? W/System.err: java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
2020-05-19 20:33:42.559 29508-29508/? W/System.err:     at x20.a(PG:62)
2020-05-19 20:33:42.559 29508-29508/? W/System.err:     at org.chromium.chrome.browser.preferences.website.BraveShieldsContentSettings.blockedEvent(PG:26)
2020-05-19 20:33:42.559 29508-29508/? W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
2020-05-19 20:33:42.559 29508-29508/? W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:336)
2020-05-19 20:33:42.559 29508-29508/? W/System.err:     at android.os.Looper.loop(Looper.java:197)
2020-05-19 20:33:42.559 29508-29508/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8016)
2020-05-19 20:33:42.559 29508-29508/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-05-19 20:33:42.559 29508-29508/? W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2020-05-19 20:33:42.559 29508-29508/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
2020-05-19 20:33:42.560 29508-29508/? A/chromium: [FATAL:jni_android.cc(249)] Please include Java exception stack in crash report`

## Steps to reproduce 

   1. Install beta 1.9.69
   2. Open custom tab via opening a link on gmail or from slack
   3. 

## Actual result 
the browser crashes

## Issue reproduces how often 
On my problem device I can replicate it every time, other devices I couldn't

## Issue happens on 
   - Current Play Store version?
   - Beta build? yes

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm.apk 1.9.74`
 - Could not reproduce the issue in 1.9.69 Android beta version, no crash when custom tabs are opened via the slack link or Gmail link
 - No crash when custom tabs are opened via the slack link or Gmail link in 1.9.74
